### ISSUE TITLE
Interface accepting input as two iterators

### ISSUE THREAD

**Issue by piotrekg2** [google/re2#100]
Hi,
is there any chance of adding an interface to the library which would accept an input as two iterators instead of a string? Such an interface would be really useful.

Thanks,
Piotr

**Comment by junyer** [comment]
`RE2::Match()` (https://github.com/google/re2/blob/master/re2/re2.h#L478-L503) takes offsets rather than iterators, but would that be sufficient for your use case?

**Comment by piotrekg2** [comment]
Unfortunately it wouldn't. I have a buffer holding a text in 4k chunks. Iterators give me an illusion of continuous sequence.

**Comment by junyer** [comment]
RE2 assumes that input strings have contiguous storage, so it cannot be used with ropes, cords et cetera. Unfortunately, `boost::regex` and `std::regex` might be your only options.

**Comment by piotrekg2** [comment]
At first glance it looks like this assumption is too restrictive. It is clear how to match against a DFA/NFA if the input is given as two forward iterators. Are patches welcome?

**Comment by junyer** [comment]
Sorry, such a change is simply not feasible. You would have to plumb the iterators all the way down to the execution engines. Everything along the way would have to become a template.

**Comment by junyer** [comment]
P.S. If you do end up trying to do this, you will need at least `BidirectionalIterator` because the DFA execution engine matches in reverse under certain circumstances.
