### ISSUE TITLE
Add backreference support

### ISSUE THREAD

**Issue by sloanlance** [google/re2#101]
The documentation shows many types of backreferences, but they're all marked as "NOT SUPPORTED".  I've only tried a couple of those, to see whether the documentation was accurate, and they didn't work.

Backreferences are an important part of regular expression use.  Please add support for them.  At the least, support the numbered backreference syntax, `\1`.

**Comment by junyer** [comment]
Sorry, RE2 cannot support backreferences without compromising its principles.

**Comment by sloanlance** [comment]
Thanks for the response.  I read a bit more about re2 and I think I have a better understanding of the project's principles.

Although re2's own substitutions don't support backreference, it's possible for an application using re2 to implement it in its own code, right?  For example, use re2 to search the input for the specified regular expression, which would return data about the matches, capture groups, etc.  The application would then use that data to make the substitutions itself, replacing references to the capture groups.

Is that a reasonable approach?

**Comment by junyer** [comment]
Ahh. I thought you meant backreferences during matching. :)

RE2 does offer some functionality for substituting `\1`, `\2` et cetera. Does `RE2::Extract()` (https://github.com/google/re2/blob/master/re2/re2.h#L399-L414) look like what you need?

**Comment by codethief** [comment]
> Sorry, RE2 cannot support backreferences without compromising its principles.

Hi @junyer, I am wondering what your thoughts are on [Becchi & Crawley's 2008 paper](https://dl.acm.org/doi/10.1145/1544012.1544037), given that it seems to propose a way to implement backreferences without backtracking. Would that be an option for re2?

**Comment by junyer** [comment]
The paper says:

> Even so, the worst-case bound in the number of pointers needed for each back-reference is $O(m^{2}N_{NFA})$, where $m$ is the length of the input text.

RE2 can't tolerate that.
