### ISSUE TITLE
x86 build fails with missing _BitScanForward64

### ISSUE THREAD

**Issue by jcurl** [google/re2#103]
Using CMake 3.6.1, version 2016-08-01, to build a VS project using the "Visual Studio 14 2015" generator which targets 32-bit. during the build with Visual Studio 2015, the following build error occurs:

Severity	Code	Description	Project	File	Line	Source	Tool
Error	C3861	'_BitScanForward64': identifier not found	re2	C:\Users\jcurl\Downloads\re2-2016-08-01\util\bitmap.h	50	Build	

On master (71d6f77ec86c3d5e6f052690c37006b9fe692db9), the build fails but the filename is bitmap256.h

Note that MSDN specifies this method is only for 64-bit machines:
https://msdn.microsoft.com/en-us/library/wfd9z0bb(v=vs.100).aspx

Intrinsic | Architecture
----- | -----
_BitScanForward | x86, IPF, x64
_BitScanForward64 | IPF, x64

The code in the header file "bitmap.h" contains at the location of the error:
```
class Bitmap256 {
...
 private:
  // Finds the least significant non-zero bit in n.
  static int FindLSBSet(uint64 n) {
...
#elif defined(_MSC_VER)
    unsigned long c;
    _BitScanForward64(&c, n);
    return static_cast<int>(c);
#else
  }
```

**Comment by junyer** [comment]
D'oh! Thanks for the report. I had overlooked that detail. :(
