### ISSUE TITLE
large input support

### ISSUE THREAD

**Issue by df2218380513f49d8a3d896fc45740e9** [google/re2#107]
It would be great if RE2 would support large input. Currently the 'int' type is used to represent offsets and lengths in lots of places which restrict the ways RE2 can be applied to inputs >2GB.

Perhaps simply templating on a 'size type' might be the way to go if there's some reason to avoid moving to 64-bit offsets/lengths?

**Comment by junyer** [comment]
Moving `StringPiece` in the direction of `std::string_view` will be a necessary first step, I think.

**Comment by junyer** [comment]
FYI, this builds cleanly on Linux, but it's entirely possible that I've overlooked something that will upset MSVC. (Ping, @DThiebaud.)
