### ISSUE TITLE
Repeated Capturing Group Pattern like "((a{0,1})+)"

### ISSUE THREAD

**Issue by qinwf** [google/re2#108]
Hi, here is the result from RE2, Python and Ruby for this pattern.

I am not sure whether this is a bug. Maybe these engines have difference rules to this kind of pattern.

```cpp
#include "re2/re2.h"
#include <stdio.h>
#include <iostream>
#include <stdlib.h> 
using namespace std;
using namespace re2;

void run_match(string pattern, string input);

int main(){

    run_match("((a{0,1})+)", "aabc");
    // matched[1]: aa, matched[2]: a

    run_match("((abc|123)+)", "abc123");
    // matched[1]: abc123, matched[2]: 123

    return 0;
}

void run_match(string pattern, string input){
    RE2 pattern1(pattern);
    StringPiece matched[3];

    pattern1.Match(input, 0, input.size(), RE2::UNANCHORED, &matched[0], 3);

    cout<< "matched[1]: " << matched[1]  << ", matched[2]: " << matched[2] <<endl;
}
```

Python

```python
import re
re.findall("((a{0,1})+)","aabc")[0] # in RE2: ('aa', 'a')
# ('aa', '') 

re.findall("((abc|123)+)","abc123")[0]
# ('abc123', '123')
```

Ruby

```ruby
/((a{0,1})+)/.match("aabc")
# => #<MatchData "aa" 1:"aa" 2:""> 

/((abc|123)+)/.match("abc123")
# => #<MatchData "abc123" 1:"abc123" 2:"123">
```

See also: [Repeating a Capturing Group vs. Capturing a Repeated Group](http://www.regular-expressions.info/captureall.html)

**Comment by junyer** [comment]
https://swtch.com/~rsc/regexp/regexp3.html#caveats documents this disagreement:

> If the regexp contains a repetition of an empty string, like `(a*)+`, then PCRE will treat the reptition sequence as ending with an empty string, while RE2 does not. Specifically, when matching `(a*)+` against `aaa`, PCRE runs the `+` twice, once to match `aaa` and a second time to match the empty string. RE2 runs the `+` only once, to match `aaa`. Because parens capture the rightmost text they matched, for PCRE `$1` will be an empty string while for RE2 `$1` will be `aaa`. The PCRE behavior could be kludged into RE2 if needed.
