### ISSUE TITLE
Documentation link is dead

### ISSUE THREAD

**Issue by bscarlet** [google/re2#11]
README points to http://code.google.com/p/re2/ for "documentation about how to install and use RE2", but that page just links back to github now.

**Comment by evertheylen** [comment]
+1

**Comment by dolzenko** [comment]
+1

**Comment by andythiv** [comment]
The same dead link is used in BigQuery's docs too:
https://cloud.google.com/bigquery/query-reference#regularexpressionfunctions

**Comment by junyer** [comment]
Fixed by e69f55cbdaa45e9fe5f8e4354146b3126ded2c11.
