### ISSUE TITLE
Warning C4309 in 32-bit MSVC compiles

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#114]
Compiling RE2 with a 32-bit MSVC compiler, the following warning occurs:

2>E:\src\re2\util/mix.h(18): warning C4309: 'static_cast' : truncation of constant value

This does not occur in 64-bit builds.

This occurs because, in a 32-bit compile, size_t is 32 bits and it is being cast from a 64-bit value.

The warning can be suppressed by changing the line:
   static const size_t kMUL = static_cast<size_t>(0xdc3eb94af8ab4c93ULL);
to:
   static const size_t kMul = (size_t)0xdc3eb94af8ab4c93ULL;

I don't know why but this suppresses the warning.

Of course we could also use a pragma to suppress the warning.

Another possibility, maybe, is to replace size_t by unsigned long long in every line in the class. I don't know if this would work or what effect it would have.

**Comment by DThiebaud** [comment]
Replacing size_t by uint64_t compiles cleanly. I'm running the tests for it.

**Comment by junyer** [comment]
`size_t` is the type that the STL uses for hash values, so we should definitely keep using it. I have no idea why `(size_t)…` suppresses the warning when `static_cast<size_t>(…)` doesn't, so I think I will simply use a pragma here.
