### ISSUE TITLE
Misleading indentation warning from util/pcre.cc

### ISSUE THREAD

**Issue by LordAro** [google/re2#118]
All the `operator()` functions in `util/pcre.cc` all trigger misleading indentation warnings in gcc 6.1 (with patch for #102 applied), from line 204 to 358. e.g:

```
util/pcre.cc:208:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
   if (&a0 == &no_more_args)  goto done; args[n++] = &a0;
   ^~
util/pcre.cc:208:41: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if (&a0 == &no_more_args)  goto done; args[n++] = &a0;
                                         ^~~~
```

That said, those functions are all rather nasty and look like they perhaps could be replaced with [something variadic](http://stackoverflow.com/a/32921291)? :)

**Comment by junyer** [comment]
We keep the PCRE wrapper code around only for the sake of the tests that compare PCRE match results with RE2 match results. It is old and crufty, but it does the needful, so I'm happy to leave it be and just address the occasional bit rot.

It seems that `-Wall` enables `-Wmisleading-indentation`, so I will try adding `#pragma GCC diagnostic ignored "-Wmisleading-indentation"` soon.
