### ISSUE TITLE
[[:word:]]

### ISSUE THREAD

**Issue by PHPDev-CA** [google/re2#119]
This likely isn't the appropriate place for this, however, I was wondering why [[:word:]] does not include apostrophe?  Contractions, possessives, plural nouns, proper names, non-English roman character words, etc. all have ' as part of a word.

**Comment by junyer** [comment]
I'm a little uncertain of the origins of `[[:word:]]` and `\w`, but they seem to mean `[0-9A-Za-z_]` because those are the "word" characters allowed in identifiers for various programming languages.

If you build RE2 with ICU, then you should be able to use `\p{Word}` instead.
