### ISSUE TITLE
Install the dll on windows

### ISSUE THREAD

**Issue by isuruf** [google/re2#123]
Right now only the `.lib` is getting installed.
Patch attached.
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3c90f5d..01bdc72 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -128,4 +128,5 @@ set(RE2_HEADERS
     )

 install(FILES ${RE2_HEADERS} DESTINATION include/re2)
-install(TARGETS re2 ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)
+install(TARGETS re2 ARCHIVE DESTINATION lib LIBRARY DESTINATION lib
+                    RUNTIME DESTINATION bin)
```

**Comment by junyer** [comment]
Thanks for the report!

Indeed, the CMake documentation states:

> For non-DLL platforms shared libraries are treated as LIBRARY targets, […] For DLL platforms the DLL part of a shared library is treated as a RUNTIME target and the corresponding import library is treated as an ARCHIVE target. All Windows-based systems including Cygwin are DLL platforms.

(Ping, @DThiebaud.)

**Comment by junyer** [comment]
The fix is in commit d2402e7d972b97e96de163c189de252a457f9698, which @gopherbot hasn't pushed yet for some reason. (It's been over an hour...)

**Comment by isuruf** [comment]
Thanks

**Comment by isuruf** [comment]
@junyer, in windows, `dll`s are placed usually on `bin`.

**Comment by junyer** [comment]
Mea culpa. I will fix that immediately.

**Comment by isuruf** [comment]
Thanks again.
