### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [google/re2#124]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [Compiler](https://github.com/google/re2/blob/7bab3dc83df6a838cc004cc7a7f51d5fe1a427d5/re2/compile.cc#L258 "Compiler class")
- [NFA](https://github.com/google/re2/blob/7bab3dc83df6a838cc004cc7a7f51d5fe1a427d5/re2/nfa.cc#L137 "NFA class")

**Comment by junyer** [comment]
Why are `Compiler` and `NFA` notable? More generally, what are the problems, risks et cetera that are currently lurking?

**Comment by elfring** [comment]
>Why are `Compiler` and `NFA` notable?

These classes are using at least two delete statements in their destructors so far.


>More generally, what are the problems, risks et cetera that are currently lurking?

* With which pointer values will [the delete operators](http://ootips.org/yonat/4dev/smart-pointers.html#WhyBugs "Article: Smart Pointers - What, Why, Which?") be eventually called in the destructor for example if one of the previous new operator calls would throw the exception “std::bad_alloc”?
* Do you care for complete clean-up of involved system resources?

**Comment by junyer** [comment]
If `std::bad_alloc` is thrown, then just let the program crash and let the operating system clean up?

**Comment by elfring** [comment]
Do you really get a desired “crash” for [a dangling pointer](https://en.wikipedia.org/wiki/Dangling_pointer "Descriptions around dangling pointers")?

**Comment by junyer** [comment]
Sorry, I should have mentioned that Google does not use exceptions. What is the answer to your question?

**Comment by elfring** [comment]
Do you switch the support for C++ exceptions off by a compilation parameter?

**Comment by junyer** [comment]
We compile with `-fno-exceptions` internally, but the open source project does not use that option.

**Comment by elfring** [comment]
Does this information mean that the open source build variants of your software can and should take care a bit more about thrown C++ exceptions?

**Comment by junyer** [comment]
Perhaps, but it is currently unclear why that might be necessary or even useful when the program is crashing.

**Comment by elfring** [comment]
How many value do you give to the implementation of destructors to perform their final actions?

**Comment by junyer** [comment]
When a ship is sinking, how much value is there in rearranging the deck chairs?

**Comment by elfring** [comment]
Should any destructor perform any action which you will find also valuable at the end?

**Comment by junyer** [comment]
Can you think of any examples?

**Comment by spektom** [comment]
One of examples could be a system that doesn't crash on "out of memory". Imagine a system that has custom memory allocator that throws bad_alloc on low memory condition. That exception is caught and handled later without the need to stop the process.
