### ISSUE TITLE
Findall like in Go

### ISSUE THREAD

**Issue by sofo23** [google/re2#125]
This is not an issue. I don't know where to ask the question. How to find all matches  in Re2 like [Go FindallString](https://golang.org/pkg/regexp/#Regexp.FindAllString)?

**Comment by junyer** [comment]
You can achieve much the same effect like this:

```
  StringPiece sp(input);
  RE2 re("(\\w+)");
  StringPiece word;
  while (RE2::FindAndConsume(&sp, re, &word)) {
    // ...
  }
```

**Comment by sofo23** [comment]
Thank for your reply.
