### ISSUE TITLE
An equivalent of TRE's reguexec (matching on arbitrary input)

### ISSUE THREAD

**Issue by cpitclaudel** [google/re2#126]
Hi all,

RE2's implementation with automata should make it particularly suitable for use on streaming data, as well as strings represented using non-contiguous chunks (ropes, piece tables, gab buffers, etc.).  

This doesn't seem to be anything in the API for this purpose at the moment.  To clarify what I have in mind, I'm looking for an equivalent of TRE's [`tre_reguexec`](http://laurikari.net/tre/documentation/reguexec/).

Given that the API takes `const StringPiece&`, could this feature be implemented by subclassing `StringPiece`?

Thanks!

**Comment by junyer** [comment]
Sorry, this is not feasible. RE2 assumes that input strings have contiguous storage. Specifically, the execution engines use pointers internally. Moreover, calling a user-specified function in order to read each input character would ruin performance. You might have some luck hacking the DFA execution engine to handle input strings in chunks, but I would suggest using Lightgrep or Hyperscan instead. Even more so if you will be matching multiple regular expressions.

**Comment by cpitclaudel** [comment]
> RE2 assumes that input strings have contiguous storage. Specifically, the execution engines use pointers internally.

I see, thanks.  In that case, how hard would it be to have partial matches in the style of pcrepartial?  I'm particularly interested in getting this to work on a gap buffer, where I'd need only the ability to split a match across two strings.

> Moreover, calling a user-specified function in order to read each input character would ruin performance.

Really? In my admittedly limited testing, Clang is pretty good at optimizing away function pointers. GCC not as much, but even then performance in `tre_reguexec` is pretty good.

> I would suggest using Lightgrep or Hyperscan instead. Even more so if you will be matching multiple regular expressions.

This sounds like overkill (but maybe my impression is mistaken?). I'm interested in (mostly) replacing Emacs' regular expression engine, so in most cases the subject strings will be reasonably short. Emacs uses a gap buffer, so I need to be able to split matches across two char buffers.

**Comment by BurntSushi** [comment]
>> Moreover, calling a user-specified function in order to read each input character would ruin performance.
>
> Really? In my admittedly limited testing, Clang is pretty good at optimizing away function pointers. GCC not as much, but even then performance in tre_reguexec is pretty good.

Optimizations like `memchr` depend on contiguous regions of memory to search.

- Andrew

**Comment by cpitclaudel** [comment]
> Optimizations like `memchr` depend on contiguous regions of memory to search.

Makes sense.  These would work in Emacs' case, since Emacs' gap buffer is really just one large chunk of memory with a single invalid region in the middle.

**Comment by mppf** [comment]
Hi @cpitclaudel - see the recent topic [Searching files directly with RE2](https://groups.google.com/forum/#!topic/re2-dev/gyZ6ukLJm30)  in the RE2 Google group. I have implemented such a thing with RE2 but as described in that thread it seems unlikely that it will be accepted into RE2.

I am curious, how did you end up solving your problem?

**Comment by cpitclaudel** [comment]
> I am curious, how did you end up solving your problem?

I didn't, unfortunately. I essentially gave up on trying to replace Emacs' regexp engine with RE2.
