### ISSUE TITLE
2016-12-01 tag missing?

### ISSUE THREAD

**Issue by tuncer** [google/re2#128]
Is there a reason why there's no `2016-12-01` git tag?

**Comment by junyer** [comment]
I didn't cut a release at the beginning of December because I was on leave that week. :)

**Comment by junyer** [comment]
I've just cut release `2017-01-01`. Happy New Year! ;)

**Comment by tuncer** [comment]
Thanks, https://github.com/tuncer/re2 v1.7.1 defaults to RE2 `2017-01-01` (if system re2 is not used).
