### ISSUE TITLE
Replace function fails for some characters

### ISSUE THREAD

**Issue by widmore** [google/re2#13]
I want to replace url in a string and following is a basic scenario to reproduce bug.

urlToReplace is a string variable and it contains following data (ignore whitespace placed just before the a tag. Otherwise github does not show example):
<  a href = "http://example.com/secure/ViewProfile.jspa?name=bug">

url variable is a string and contains following data:
http://example.com/secure/ViewProfile.jspa?name=bug

Failure occurs at this re2 function call.
bool result = re2::RE2::Replace(&urlToReplace, url, "Data to write...");

Result is false. It should be true. As far as i have seen problem is caused by ? character which exists at both urlToReplace variable and url variable.

**Comment by junyer** [comment]
`?` is the metacharacter that means zero or one, so `url` used as a regular expression will not match itself. Either pass `RE2::QuoteMeta(url)` instead of `url` or declare an `RE2::Options` object, call `set_literal(true)` on it, construct an `RE2` object with it and pass **that** instead of `url`.
