### ISSUE TITLE
Use of deprecated and system-dependent header files

### ISSUE THREAD

**Issue by H2CO3** [google/re2#130]
In many places, the code includes the C-style standard library headers, such as `<string.h>` and `<stdint.h>`. These are **deprecated** and should not be used in new code. They are superseded by their respective C++-style counterparts (for example, `<cstring>` and `<cstdint>`.) A transition from deprecated to supported headers would be strongly recommended.

Furthermore, the code unconditionally includes POSIX-specific header files ([Exhibit A](https://github.com/google/re2/blob/master/re2/re2.h#L184)) without a feature check or platform check. In that specific case, I do not see any reason why that header should be included (although I can be wrong); and even if it currently happens to be, I'm sure there is a better solution that only uses elements of the standard library.

**Comment by junyer** [comment]
`sys/types.h` seems to be the only `sys/` header that we `#include` unconditionally in a few files. I'm guessing that it was for `ushort`, `uint` and `ulong` when we still used those, so I'll see about removing them now.

**Comment by H2CO3** [comment]
Perfect, thanks!
