### ISSUE TITLE
Implicit conversions and comparison of different types

### ISSUE THREAD

**Issue by Dor1s** [google/re2#132]
Hey,

I've tried to update re2 in Chromium and got a couple of compilation errors like:

```
In file included from ../../third_party/re2/src/re2/prog.cc:8:
In file included from ../../third_party/re2/src/re2/prog.h:19:
../../third_party/re2/src/util/sparse_array.h:276:15: error: implicit conversion turns string literal into bool: 'const char [14]' to 'bool' [-Werror,-Wstring-conversion]
      assert(!"illegal index");
             ~^~~~~~~~~~~~~~~
<...>
In file included from ../../components/password_manager/core/browser/import/csv_reader.cc:5:
In file included from ../../components/password_manager/core/browser/import/csv_reader.h:13:
In file included from ../../base/strings/string_piece.h:31:
../../base/logging.h:646:26: error: comparison of integers of different signs: 'const unsigned long' and 'const int' [-Werror,-Wsign-compare]
DEFINE_CHECK_OP_IMPL(GE, >=)
~~~~~~~~~~~~~~~~~~~~~~~~~^~~
```

To see all 10 errors, could you please take a look at https://build.chromium.org/p/tryserver.chromium.mac/builders/ios-simulator-xcode-clang/builds/41339/steps/compile%20%28with%20patch%29/logs/stdio with CTRL + F "error:".

Thank you!

**Comment by junyer** [comment]
The warning (raised to an error) comes from `-Wstring-conversion`. Do you happen to know an appropriate replacement for `assert(!"…");`? (I got the idea from LLVM, funnily enough, so I'm amused that Clang considers it poor form.)

**Comment by junyer** [comment]
(Ping, @jlebar.)

**Comment by Dor1s** [comment]
@junyer I beileve that `static_cast<bool>()` resolves the issue. Maybe something like:

```cpp
#define assert_string(msg) assert(!static_cast<bool>(msg))
```

**Comment by junyer** [comment]
I was hoping for something a little easier on the eyes, but if @jlebar doesn't have any better ideas, then I will just do that. :)

**Comment by Dor1s** [comment]
Thanks a lot!

**Comment by nico** [comment]
The recommended spelling is `assert(false && "...")`.

**Comment by jlebar** [comment]
What Nico said.

**Comment by junyer** [comment]
Why didn't I think of that? Thanks, @nico and @jlebar!
