### ISSUE TITLE
Feature request: ability to get the "StringPiece* match" from RE2::Set

### ISSUE THREAD

**Issue by outcoldman** [google/re2#135]
Currently [RE2::Set::Match](https://github.com/google/re2/blob/master/re2/set.h#L45) allows you only to recognize which pattern gave you a match, but it does not actually tell you what was the match in case if you don't have anchor at the end and you are ok to receive just one match (first one or longest one).

Any issues with adding this API? Seems like [SearchDFA ](https://github.com/google/re2/blob/master/re2/set.cc#L105) have this as parameter, and comment to this function says that it should be set, see https://github.com/google/re2/blob/d8918e632f84576e3acad46d8280f4cc73fef2cd/re2/dfa.cc#L1814

**Comment by junyer** [comment]
Sorry, I don't believe that would be a good fit for `RE2::Set` insofar as it would be incongruous to support multiple patterns matching and then to introduce a feature that supports only one pattern matching.
