### ISSUE TITLE
The example in re2.h about LazyRE2 seems not work on GCC 6.2

### ISSUE THREAD

**Issue by harrywong** [google/re2#137]
I use this code:
static LazyRE2 re = { R"((\d+):(\d+))" };

But the gcc warns that
error: missing initializer for member ‘re2::LazyRE2::options_’ [-Werror=missing-field-initializers]
     static re2::LazyRE2 re2 = { R"((\d+):(\d+))" };
                                                  ^
error: missing initializer for member ‘re2::LazyRE2::barrier_against_excess_initializers_’ [-Werror=missing-field-initializers]
error: missing initializer for member ‘re2::LazyRE2::ptr_’ [-Werror=missing-field-initializers]
error: missing initializer for member ‘re2::LazyRE2::once_’ [-Werror=missing-field-initializers]

**Comment by junyer** [comment]
It appears that `-Wextra` enables `-Wmissing-field-initializers`, so I guess I will just add `#pragma GCC diagnostic ignored "-Wmissing-field-initializers"`.

**Comment by harrywong** [comment]
Sounds good to me, thanks.
