### ISSUE TITLE
a CMake option to to disable building the tests?

### ISSUE THREAD

**Issue by d** [google/re2#138]
Hi community,
Our project recently needed to use regular expression, and we jumped at the opportunity at RE2! Our project is CMake based, so we vendored `re2`, and `add_subdirectory` from our top `CMakeLists.txt` . This worked great, until we realized we've also included all `re2` tests! It would be nice if there's a way to disable the tests of `RE2` so that the library embedding scenario (am I doing this right?) would work without hassle.

If the suggestion sounds palatable, I can work on submitting a patch.

Jesse

**Comment by junyer** [comment]
From the CMake documentation:

> **Note:** CMake will generate tests only if the `enable_testing()` command has been invoked. The `CTest` module invokes the command automatically when the `BUILD_TESTING` option is `ON`.

Is it possible to set the `BUILD_TESTING` option for subprojects only?

(Ping, @dneto0.)

**Comment by d** [comment]
I don't think so. `enable_testing()` seems to a global thing, it's either on for the entire project, or it's not ...

**Comment by junyer** [comment]
http://stackoverflow.com/questions/23713650/ indicates that we are indeed out of luck. I will have to work around the problem in a similar way. :(

**Comment by junyer** [comment]
You should be able to turn off `RE2_BUILD_TESTING` in your `CMakeLists.txt` file now. :)

**Comment by dneto0** [comment]
(I was away from my keyboard.)

Looks great.  My projects do a similar thing.
I will definitely use this as well, for the same reasons as @d 
Thanks!

**Comment by junyer** [comment]
Great, thanks for confirming!
