### ISSUE TITLE
Cmake does not install re2.pc

### ISSUE THREAD

**Issue by Mice7R** [google/re2#143]
Cmake does not install (nor configure) re2.pc.
Steps to reproduce:
1. delete re2.pc (if previously instaled)
2. mkdir build
3. cd build; cmake ..
4. make install
5. pkg-config --cflags re2  # fails, No package 're2' found

Also having both Makefile and Cmake is confusing, especially when they behave differently.

**Comment by DThiebaud** [comment]
On 05/15/2017 05:36 PM, Mice7R wrote:
> Also having both Makefile and Cmake is confusing, especially when they 
> behave differently.

Isn't the usual behaviour of CMake? Or am I mistaken?

**Comment by Mice7R** [comment]
cmake creates a makefile (one that does not install re2.pc), but the repo has already one.
Also i realized that the README doesnt mention cmake at all.

**Comment by junyer** [comment]
We support CMake for the sake of users who don't have GNU make. That mostly means Visual Studio users and Xcode users, which is why we don't configure CMake to install the `.pc` file.

**Comment by chitwoodj** [comment]
K
