### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by VoteForNavalny** [google/re2#144]
Why not just rename last release to latest instead of 2017-05-01 like https://github.com/qTox/qTox/releases/latest. It's simplify automatic builds for e.g. Dockerfile.
Thank you.

**Comment by junyer** [comment]
It seems that GitHub needs the release to be "published" in order for https://github.com/google/re2/releases/latest to work. I will just have to do that via the UI whenever I push a new tag, I suppose. Thanks for the report.
