### ISSUE TITLE
restore (optional?) valgrind support

### ISSUE THREAD

**Issue by ecnalubma** [google/re2#147]
Hello,

I'd like to ask that you consider restoring the Valgrind support removed by ce6f2884. I understand that removing that support eliminates a fair amount of brittle code, but that code seemed to work. Could it perhaps be restored as a build-time option?

I ask because I'm forced to work with considerable binary blobs which Valgrind can see through but something like asan cannot.

**Comment by junyer** [comment]
Fair enough. I will make `SparseArray<>` and `SparseSet` check whether the `RE2_ON_VALGRIND` macro has been defined.
