### ISSUE TITLE
CI with different CXX and/or OS envs

### ISSUE THREAD

**Issue by tuncer** [google/re2#149]
To prevent issues like #148, we should utilize Travis-CI or GitLab-CI and test with different CXX versions and/or envs (Linux distro versions, etc.).

**Comment by junyer** [comment]
https://docs.travis-ci.com/user/languages/cpp/#C11-C%2B%2B11-(and-Beyond)-and-Toolchain-Versioning looks straightforward enough.

**Comment by junyer** [comment]
As per commits 350d61a and 8d17aba, we are now using Travis CI to test with GCC (4.8, 4.9, 5, 6, 7) and Clang (3.5, 3.6, 3.7, 3.8, 3.9, 4.0) on Linux. We were already using Kokoro to test with Visual Studio (2013) and Xcode (version unspecified) on Windows and macOS, respectively.

**Comment by junyer** [comment]
https://www.cloudbees.com/sites/default/files/2016-jenkins-world-jenkins_inside_google.pdf is a talk about Kokoro.
