### ISSUE TITLE
make fails on Cygwin 2.8.0 (gcc 5.4.0)

### ISSUE THREAD

**Issue by ButteredGroove** [google/re2#150]
Running cmake 3.6.2 via Cygwin 2.8.0(0.309/5/3), I'm getting a build error related to mutex.h:

mister_me@COMPUTER_BLUES ~/re2
$ cmake .
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mister_me/re2

mister_me@COMPUTER_BLUES ~/re2
$ make
Scanning dependencies of target testing
[  1%] Building CXX object CMakeFiles/testing.dir/re2/testing/backtrack.cc.o
[  2%] Building CXX object CMakeFiles/testing.dir/re2/testing/dump.cc.o
[  3%] Building CXX object CMakeFiles/testing.dir/re2/testing/exhaustive_tester.cc.o
[  4%] Building CXX object CMakeFiles/testing.dir/re2/testing/null_walker.cc.o
[  5%] Building CXX object CMakeFiles/testing.dir/re2/testing/regexp_generator.cc.o
[  6%] Building CXX object CMakeFiles/testing.dir/re2/testing/string_generator.cc.o
[  7%] Building CXX object CMakeFiles/testing.dir/re2/testing/tester.cc.o
[  8%] Building CXX object CMakeFiles/testing.dir/util/pcre.cc.o
[  9%] Linking CXX static library libtesting.a
[  9%] Built target testing
Scanning dependencies of target re2
[ 10%] Building CXX object CMakeFiles/re2.dir/re2/bitstate.cc.o
[ 11%] Building CXX object CMakeFiles/re2.dir/re2/compile.cc.o
[ 12%] Building CXX object CMakeFiles/re2.dir/re2/dfa.cc.o
In file included from /home/mister_me/re2/re2/dfa.cc:42:0:
/home/mister_me/re2/util/mutex.h: In constructor ‘re2::Mutex::Mutex()’:
/home/mister_me/re2/util/mutex.h:66:76: error: ‘pthread_rwlock_init’ was not declared in this scope
 Mutex::Mutex()             { SAFE_PTHREAD(pthread_rwlock_init(&mutex_, NULL)); }
                                                                            ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
/home/mister_me/re2/util/mutex.h: In destructor ‘re2::Mutex::~Mutex()’:
/home/mister_me/re2/util/mutex.h:67:73: error: ‘pthread_rwlock_destroy’ was not declared in this scope
 Mutex::~Mutex()            { SAFE_PTHREAD(pthread_rwlock_destroy(&mutex_)); }
                                                                         ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
/home/mister_me/re2/util/mutex.h: In member function ‘void re2::Mutex::Lock()’:
/home/mister_me/re2/util/mutex.h:68:72: error: ‘pthread_rwlock_wrlock’ was not declared in this scope
 void Mutex::Lock()         { SAFE_PTHREAD(pthread_rwlock_wrlock(&mutex_)); }
                                                                        ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
/home/mister_me/re2/util/mutex.h: In member function ‘void re2::Mutex::Unlock()’:
/home/mister_me/re2/util/mutex.h:69:72: error: ‘pthread_rwlock_unlock’ was not declared in this scope
 void Mutex::Unlock()       { SAFE_PTHREAD(pthread_rwlock_unlock(&mutex_)); }
                                                                        ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
/home/mister_me/re2/util/mutex.h: In member function ‘void re2::Mutex::ReaderLock()’:
/home/mister_me/re2/util/mutex.h:70:72: error: ‘pthread_rwlock_rdlock’ was not declared in this scope
 void Mutex::ReaderLock()   { SAFE_PTHREAD(pthread_rwlock_rdlock(&mutex_)); }
                                                                        ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
/home/mister_me/re2/util/mutex.h: In member function ‘void re2::Mutex::ReaderUnlock()’:
/home/mister_me/re2/util/mutex.h:71:72: error: ‘pthread_rwlock_unlock’ was not declared in this scope
 void Mutex::ReaderUnlock() { SAFE_PTHREAD(pthread_rwlock_unlock(&mutex_)); }
                                                                        ^
/home/mister_me/re2/util/mutex.h:63:10: note: in definition of macro ‘SAFE_PTHREAD’
     if ((fncall) != 0) abort(); \
          ^
make[2]: *** [CMakeFiles/re2.dir/build.make:111: CMakeFiles/re2.dir/re2/dfa.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1356: CMakeFiles/re2.dir/all] Error 2
make: *** [Makefile:139: all] Error 2_

Please see the attached file for the error message sans HTML whitespace destruction.
[re2_make_crash.txt](https://github.com/google/re2/files/1122836/re2_make_crash.txt)

I get the same error if I use the git-provided Makefile as well.

**Comment by junyer** [comment]
```
/home/mister_me/re2/util/mutex.h:66:76: error: ‘pthread_rwlock_init’ was not declared in this scope
/home/mister_me/re2/util/mutex.h:67:73: error: ‘pthread_rwlock_destroy’ was not declared in this scope
/home/mister_me/re2/util/mutex.h:68:72: error: ‘pthread_rwlock_wrlock’ was not declared in this scope
/home/mister_me/re2/util/mutex.h:69:72: error: ‘pthread_rwlock_unlock’ was not declared in this scope
/home/mister_me/re2/util/mutex.h:70:72: error: ‘pthread_rwlock_rdlock’ was not declared in this scope
/home/mister_me/re2/util/mutex.h:71:72: error: ‘pthread_rwlock_unlock’ was not declared in this scope
```

`util/mutex.h` uses the `_POSIX_READER_WRITER_LOCKS` macro to detect the availability of those functions and that is the same macro that Cygwin `pthread.h` uses to determine whether to declare those functions at all, so I don't understand how this has broken. It might be worth asking about this on the Cygwin mailing list.

**Comment by junyer** [comment]
In the meantime, are you able to dump the preprocessed source for `re2/dfa.cc`? I might be able to use that to figure out what is going on.

Using the provided `Makefile` on my Linux workstation, the command to compile is

```
g++ -c -o obj/re2/dfa.o  -std=c++11 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I.   -O3 -g -DNDEBUG re2/dfa.cc
```

and so the command to dump the preprocessed source is

```
g++ -E -dDI -o dfa.cc.dump  -std=c++11 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I.   -O3 -g -DNDEBUG re2/dfa.cc
```

Note the change from `-c -o obj/re2/dfa.o` to `-E -dDI -o dfa.cc.dump`.

**Comment by ButteredGroove** [comment]
Sure.  Please see the attached file.

[dfa.cc.dump.txt](https://github.com/google/re2/files/1125406/dfa.cc.dump.txt)

**Comment by junyer** [comment]
Looking at the dump, I see that `_POSIX_READER_WRITER_LOCKS` is defined, which is why RE2 tries to use `pthread_rwlock_init` et al., but those functions aren't declared. Until now, I had been referring to [pthread.h](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob_plain;f=newlib/libc/include/pthread.h;hb=HEAD), but the dump doesn't resemble that at all: `__PTHREAD_h` isn't defined, for starters, and the function declarations are in a very different order. Could you please attach your copy of `pthread.h`?

**Comment by ButteredGroove** [comment]
Sure.  Please see attached.
[pthread.zip](https://github.com/google/re2/files/1128636/pthread.zip)

**Comment by ButteredGroove** [comment]
Following your observation regarding the missing headers, I found this little nugget of information:
https://stackoverflow.com/questions/38139631/posix-visible-is-ruining-my-pthreading-on-cygwin

The suggestion is to replace -std=c++11 with -std=gnu++11
:water_buffalo: !!

I made that replacement to the Makefile provided by git and the regular 'make' worked.

**Comment by junyer** [comment]
That state of affairs sounds rather unfortunate. Still, I can easily handle this in CMake.

**Comment by Maxim-Mazurok** [comment]
I had the same problem with Cygwin, replacing `-std=c++11` with `-std=gnu++11` in `Makefile` helped, thanks!
