### ISSUE TITLE
Linking fails after generating bitcode files

### ISSUE THREAD

**Issue by markaduol** [google/re2#153]
I modified the makefile slightly so that I can generate an LLVM bitcode file for each source file (i.e: the files matching re2/\*.cc and util/\*.cc). I simply run the following command:

`CXX=clang++ make`

in the top-level directory

When attempting to link the individual bitcode files into a single file using the 'llvm-link' tool, an error occurs regarding invalid global references (see screenshot below).

![screenshot](https://user-images.githubusercontent.com/22771532/28374884-fa18746c-6c9d-11e7-9e72-859a80eacd7c.png)

[Here](https://raw.githubusercontent.com/markaduol/UROP/77a39ec1512c3fb97e9ad5d6437a22144a6953d2/lib/re2/Makefile) is a link to the modified version of the makefile. I added the rules

```
obj/bitcode/%.bc: %.cc $(HFILES)
	@mkdir -p $$(dirname $@)
	$(CXX) -c -o $@ -emit-llvm $(CPPFLAGS) $(RE2_CXXFLAGS) $(CXXFLAGS) -DNDEBUG $*.cc

obj/bitcode/libre2.bc: $(BCFILES)
	@mkdir -p obj/bitcode
	$(LLVM_LINK) -o obj/bitcode/libre2.bc $(LLVM_LINKFLAGS) $(BCFILES)
```

and the `BCFILES` variable.

Note that when I can successfully link some files such as `obj/bitcode/util/strutil.bc` and `obj/bitcode/util/rune.bc` into a single bitcode file, but when trying to link some files, such as `obj/bitcode/re2/parse.bc`, an error like the one shown above occurs.

These are the details of the tools that I'm using:

**llvm-link:**
LLVM (http://llvm.org/):
  LLVM version 4.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: sandybridge

**clang++**
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by junyer** [comment]
Sorry, I have no idea why those errors would occur when targeting LLVM bitcode, but it is currently unclear that RE2 is at fault here. You might want to follow up with LLVM folks in order to determine, for example, why [anygroup](https://github.com/google/re2/blob/master/re2/parse.cc#L1549) and [npos](https://github.com/google/re2/blob/master/re2/stringpiece.cc#L13) are problematic.

**Comment by markaduol** [comment]
I can confirm that the issue is to do with some LLVM-specific errors on the machine I'm using. I can confirm this because the linking works when I use a different LLVM installation in a docker container.
