### ISSUE TITLE
re2:parse_test fails ubsan

### ISSUE THREAD

**Issue by rtsai** [google/re2#155]
Software:

* bazel-0.4.5
* x86_64
* Ubuntu 16.04.3 LTS
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
* re2 tagged 2017-08-01, with 9f2263e66d0bfb7b260c6e48cc34a7b3aaa5b70c cherry-picked from master (to fix issue #154)

Using a bazelrc with:

```
build:ubsan --copt='-fsanitize=undefined'
build:ubsan --copt='-fno-sanitize-recover'
build:ubsan --linkopt='-fsanitize=undefined'
build:ubsan --linkopt='-fno-sanitize-recover'
```

Reported failure:

```
____From Testing //third_party/google/re2:parse_test:
==================== Test output for //third_party/google/re2:parse_test:
third_party/google/re2/re2/testing/parse_test.cc:229:18: runtime error: load of value 1073741824, which is not a valid value for type 'ParseFlags'
Use --strategy=TestRunner=standalone to disable sandboxing for the failing actions.
```

hex(1073741824) = 0x40000000 = 1 << 30 = re2::TestZeroFlags in parse_test.cc

Regexp::ParseFlags only seems to go up to 1 << 13

**Comment by junyer** [comment]
Thanks for the report.
