### ISSUE TITLE
install to other prefix than /usr/local

### ISSUE THREAD

**Issue by martin-uplex** [google/re2#157]
Hi,

I'd be nice to support an option for an installation prefix other than /usr/local.

Thanks
Martin

**Comment by DariuszOstolski** [comment]
When configuring build with cmake You can configure it to install headers and libraries in other directory using following command:

cmake -DCMAKE_INSTALL_PREFIX:PATH=/your/path /path/to/re2/repository

BR
Dariusz

**Comment by DariuszOstolski** [comment]
If you are using Makefile You can set prefix like that:
make prefix=/usr

BR,
Dariusz

**Comment by junyer** [comment]
Many thanks for handling this, @DariuszOstolski. :)

**Comment by martin-uplex** [comment]
> make prefix=/usr

Thank you @DariuszOstolski, this works!
