### ISSUE TITLE
"make test" fails on MacOS 10.13 

### ISSUE THREAD

**Issue by dpanshu** [google/re2#159]
Trying to install sparrowhawk. OpenFST and thrax are good to go but re2 fails in make test. Following is the error.
 
obj/so/test/charclass_test              FAIL; output in obj/so/test/charclass_test.log
obj/so/test/compile_test                FAIL; output in obj/so/test/compile_test.log
obj/so/test/filtered_re2_test           FAIL; output in obj/so/test/filtered_re2_test.log
obj/so/test/mimics_pcre_test            FAIL; output in obj/so/test/mimics_pcre_test.log
obj/so/test/parse_test                  FAIL; output in obj/so/test/parse_test.log
obj/so/test/possible_match_test         FAIL; output in obj/so/test/possible_match_test.log
obj/so/test/re2_test                    FAIL; output in obj/so/test/re2_test.log
obj/so/test/re2_arg_test                FAIL; output in obj/so/test/re2_arg_test.log
obj/so/test/regexp_test                 FAIL; output in obj/so/test/regexp_test.log
obj/so/test/required_prefix_test        FAIL; output in obj/so/test/required_prefix_test.log
obj/so/test/search_test                 FAIL; output in obj/so/test/search_test.log
obj/so/test/set_test                    FAIL; output in obj/so/test/set_test.log
obj/so/test/simplify_test               FAIL; output in obj/so/test/simplify_test.log
obj/so/test/string_generator_test       FAIL; output in obj/so/test/string_generator_test.log
TESTS FAILED.
make: *** [shared-test] Error 1

**Comment by junyer** [comment]
Could you please paste (or attach) one of those log files? I'm mostly suspicious that something changed in macOS 10.13 that affected building RE2 as a `.dylib`, but then I haven't received any complaints from Homebrew folks either...

**Comment by kylebgorman** [comment]
Hi @dpanshu, could you post one or more of the logs?

**Comment by junyer** [comment]
Ping, @dpanshu?

**Comment by dpanshu** [comment]
not sure how, but even with test fails I installed re2 and it works fine.
