### ISSUE TITLE
Matching strings that contains NULL terminator

### ISSUE THREAD

**Issue by CaledoniaProject** [google/re2#167]
I'm trying to match a paragraph that contains `\0`

The example provided in README only works with `char *`, aka `"ruby:1234"`

```
assert(RE2::FullMatch("ruby:1234", "(\\w+):(\\d+)", &s, &i));
```

Since there's nowhere to pass in a `length` parameter or a `std::string` object, how can I match a string that is not NULL terminated?

**Comment by junyer** [comment]
As per https://github.com/google/re2/blob/master/re2/stringpiece.h#L46-L56, the `StringPiece` interface allows RE2 to handle `const char*` as well as `std::string`. It sounds like you ought to construct a `StringPiece` object explicitly (i.e. with the size) and then pass that to the RE2 API.

**Comment by CaledoniaProject** [comment]
Thanks
