### ISSUE TITLE
Copy initialization of a pattern

### ISSUE THREAD

**Issue by DesWurstes** [google/re2#171]
```cpp
#include <re2/re2.h>

// or RE2 hello1 = "hello (\\w+) world";
RE2 hello1 = RE2("hello (\\w+) world");
```

```
t.c:4:38: error: 're2::RE2::RE2(const re2::RE2&)' is private within this context
 RE2 hello1 = RE2("hello (\\w+) world");
                                      ^
In file included from t.c:1:0:
/usr/local/opt/re2/include/re2/re2.h:751:3: note: declared private here
   RE2(const RE2&) = delete;
   ^~~
t.c:4:38: error: use of deleted function 're2::RE2::RE2(const re2::RE2&)'
 RE2 hello1 = RE2("hello (\\w+) world");
                                      ^
In file included from t.c:1:0:
/usr/local/opt/re2/include/re2/re2.h:751:3: note: declared here
   RE2(const RE2&) = delete;
   ^~~
```

How do I set a `RE2`? (aka copy initialization)

(@junyer ?)

**Comment by wangpeipei90** [comment]
Copy initialization should not be called in re2.
See re2/re2.h: "  RE2(const RE2&) = delete;  RE2& operator=(const RE2&) = delete;"

Why not just use RE2 initialization with strings? The RE2 object is small about 1KB. 
You can get the pattern using "const string& pattern() const { return pattern_; }"  and reconstruct a new RE2 object using "RE2(const char* pattern); RE2(const string& pattern); RE2(const StringPiece& pattern);"

**Comment by junyer** [comment]
Your example should be written like this:

```
RE2 hello1("hello (\\w+) world");
```

As @wangpeipei90 suggested, if you genuinely need to "copy" an `RE2` object for some reason, then use `.pattern()` like this:

```
RE2 hello2(hello1.pattern());
```

**Comment by DesWurstes** [comment]
It doesn't solve my problem. My actual code is
```cpp
#include <re2/re2.h>
RE2[something];
int pattern = scanf(blah blah);
std::String patterns[pattern] = scanf(blah blah);
...
...
for (int i = 0; i < pattern; i++) {
RE2[i] = patterns[i];
}
```

I need to use an array of RE2s, hence I can't do direct initialization. I don't now how many patterns there will be, and that's why I can't set a variable for each of those and put pointers of them in the array.

How can I use an array of RE2s?

**Comment by junyer** [comment]
Oh, I see. In that case, I would use a `std::vector<std::unique_ptr<RE2>>` and pass the desired size either to the constructor or to `.reserve()`. Then the loop body would look like this:

```
vec[i].reset(new RE2(patterns[i]));
```

**Comment by DesWurstes** [comment]
You guys are awesome! 👍 Thanks.
