### ISSUE TITLE
Unable to use the libre2.a while making a shared library

### ISSUE THREAD

**Issue by ashishsb95** [google/re2#172]
The error : /usr/bin/ld: /usr/local/lib/libre2.a(re2.o): relocation R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC

The Project using libre2.s is compiled with the -fPIC flag, for generating  the so file.

**Comment by junyer** [comment]
If you can't use `libre2.so`, then you could try building `libre2.a` with `-fPIC`, but it isn't generally useful to do so, IMO, so I won't be making any commits to that effect.

**Comment by ashishsb95** [comment]
USING THESE FLAGS RESOLVES IT  : RE2_CXXFLAGS?=-std=c++11 -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I. $(CCICU) $(CCPCRE)
