### ISSUE TITLE
How to build Google RE2 for Mac OS(High Sierra), did anybody try?

### ISSUE THREAD

**Issue by MrBoog** [google/re2#175]
When I use `make test`, I got this error:

```
Running dynamic binary tests.

obj/so/test/charclass_test              PASS
obj/so/test/compile_test                PASS
obj/so/test/filtered_re2_test           FAIL; output in obj/so/test/filtered_re2_test.log
obj/so/test/mimics_pcre_test            PASS
obj/so/test/parse_test                  PASS
obj/so/test/possible_match_test         FAIL; output in obj/so/test/possible_match_test.log
obj/so/test/re2_test                    FAIL; output in obj/so/test/re2_test.log
obj/so/test/re2_arg_test                FAIL; output in obj/so/test/re2_arg_test.log
obj/so/test/regexp_test                 PASS
obj/so/test/required_prefix_test        PASS
obj/so/test/search_test                 FAIL; output in obj/so/test/search_test.log
obj/so/test/set_test                    FAIL; output in obj/so/test/set_test.log
obj/so/test/simplify_test               PASS
obj/so/test/string_generator_test       PASS
TESTS FAILED.
make: *** [shared-test] Error 1
```

**Comment by junyer** [comment]
This issue is similar to https://github.com/google/re2/issues/159, but only some of the tests failed this time. Regardless, please paste (or attach) one of the log files.

**Comment by MrBoog** [comment]
for example, in this file obj/so/test/filtered_re2_test.log:

```
re2/filtered_re2.cc:45: C: 0 S:0
re2/prefilter_tree.cc:292: Compile() not called
dyld: lazy symbol binding failed: Symbol not found: __ZN3re211FilteredRE2C1Ei
  Referenced from: /Users/mac/Downloads/re2-master/obj/so/test/filtered_re2_test
  Expected in: /usr/local/lib/libre2.0.dylib

dyld: Symbol not found: __ZN3re211FilteredRE2C1Ei
  Referenced from: /Users/mac/Downloads/re2-master/obj/so/test/filtered_re2_test
  Expected in: /usr/local/lib/libre2.0.dylib

```

**Comment by junyer** [comment]
Could you please run `perl -p -i -e 's/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH/g;' /Users/mac/Downloads/re2-master/Makefile` and then try again?

(Ping, @kylebgorman.)

**Comment by MrBoog** [comment]
still the same, same errors and logs

**Comment by junyer** [comment]
Just to be clear, the problem appears to be that the dynamic linker is using `/usr/local/lib/libre2.0.dylib` instead of `…/obj/so/libre2.dylib`. If neither `LD_LIBRARY_PATH` nor `DYLD_LIBRARY_PATH` can persuade it otherwise, then I'm not sure what to try next.

BTW, where did `/usr/local/lib/libre2.0.dylib` come from? What are the symbols that it exports? (You can use `nm(1)` or `objdump(1)` to answer the latter question.)

**Comment by jbergstroem** [comment]
I had a quick look at this (since I could reproduce; albeit full fail - not partial) and I think what is going on is [system integrity protection](https://support.apple.com/en-us/HT204899). If I call the binary directly, it works fine:
```console
~/wrk/oss/re2 ±master $ LD_LIBRARY_PATH=obj/so:$(LD_LIBRARY_PATH) obj/so/test/charclass_test
zsh: command not found: LD_LIBRARY_PATH
dyld: Library not loaded: /usr/local/lib/libre2.0.dylib
  Referenced from: /Users/jbergstroem/wrk/oss/re2/obj/so/test/charclass_test
  Reason: image not found
zsh: abort      LD_LIBRARY_PATH=obj/so:$(LD_LIBRARY_PATH)
~/wrk/oss/re2 ±master $ DYLD_LIBRARY_PATH=obj/so:$(DYLD_LIBRARY_PATH) obj/so/test/charclass_test
zsh: command not found: DYLD_LIBRARY_PATH
TestCharClassBuilder.Adds
PASS
~/wrk/oss/re2 ±master $ DYLD_LIBRARY_PATH=obj/so:$(DYLD_LIBRARY_PATH) obj/so/test/charclass_test
```

Since re2 uses a wrapper to run tests (which invokes `/bin/sh`) I fear the environment passed gets stripped.

**Comment by kylebgorman** [comment]
Sorry, I don't have convenient access to a Mac anymore.

**Comment by junyer** [comment]
Thanks for the tip, @jbergstroem! This turns out to have been a problem for more than a few projects over the past couple of years. :(

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html says:

> Spawning children processes of processes restricted by System Integrity Protection, such as by launching a helper process in a bundle with `NSTask` or calling the `exec(2)` command, resets the Mach special ports of that child process. Any dynamic linker (`dyld`) environment variables, such as `DYLD_LIBRARY_PATH`, are purged when launching protected processes.

**Comment by junyer** [comment]
Am I correct in guessing that twiddling `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` from `runtests` will suffice?

**Comment by junyer** [comment]
Could someone please verify the fix? @MrBoog? @jbergstroem?

**Comment by MrBoog** [comment]
Hi, really sorry I'm not available this week... on the vacation

**Comment by junyer** [comment]
No worries. How about now? :)

**Comment by MrBoog** [comment]
Yeah, sure. ALL TESTS PASSED. 
Looks good now ;)

**Comment by junyer** [comment]
Great, thanks!
