### ISSUE TITLE
-fPIC ubuntu building double-trouble

### ISSUE THREAD

**Issue by Fihtangolz** [google/re2#178]
I try rebuild re2 because i have problem with building  served: 
make log
/usr/bin/ld: /usr/local/lib/libre2.a(re2.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libre2.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/served/CMakeFiles/served.dir/build.make:490: recipe for target 'lib/libserved.so.1.4' failed
make[2]: *** [lib/libserved.so.1.4] Error 1
CMakeFiles/Makefile2:393: recipe for target 'src/served/CMakeFiles/served.dir/all' failed
make[1]: *** [src/served/CMakeFiles/served.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
and so after make re2 i use ./compile_test
log 
TestRegexpCompileToProg.Simple
TestCompile.Latin1Ranges
TestCompile.OtherByteMapTests
TestCompile.UTF8Ranges
TestCompile.InsufficientMemory
TestCompile.Bug26705922
TestCompile.Bug35237384
PASS
What kind of god should I pray for its finally build?

**Comment by Fihtangolz** [comment]
Please add on build configure like this option(CMAKE_POSITION_INDEPENDENT_CODE "Generate position-independent code (PIC) " ON)

**Comment by junyer** [comment]
It might be reasonable to build `libre2.a` with `-fPIC` in this particular case, but I see no compelling reason to do so in general. Alternatively, could you invoke CMake with `-D BUILD_SHARED_LIBS=ON` in order to build `libre2.so`?
