### ISSUE TITLE
NFA Thread optimisation?

### ISSUE THREAD

**Issue by adrianstephens** [google/re2#182]
It seems one of the bottlenecks for the NFA implementation is the copying around of the capture boundaries, and I was wondering if that was really necessary...
Could a 'Thread' just be a single capture boundary and a (ref-counted) pointer to an earlier Thread? Most states would then refer to the same Thread, until a kInstCapture creates a new one referring to the previous.  Discarded paths along the re would kill the unnecessary Threads as refs are decremented.
I'm no RE expert; could someone who is, please correct me if there are situations where this wouldn't work?

**Comment by junyer** [comment]
Thanks for the suggestion! This was actually done in commit 881b7b8985cd1814f253da38cea0208f67b48936 just over two years ago. :)

**Comment by adrianstephens** [comment]
Ha! Actually, that wasn't quite what I meant, but it does make me think the comments about the capture copying being a bottleneck were referring to the pre-ref-counting days.
My idea was that instead of each Thread holding an array of capture boundaries, they would just hold a single boundary (with an index to identify which capture it referred to), and a ref-counted pointer to the Thread holding an earlier boundary.
I tried it out yesterday, and it passes all the tests, but only gains ~10% of the time. Should I generate a pull request?

**Comment by junyer** [comment]
Oh, right. Am I understanding correctly that you will record – separately – each execution of each `kInstCapture` instruction? Considering the input `foobarqux` and the pattern `(.)*|(..)*|(...)*`, for example, it sounds like you will produce a tree whose height is linear in the length of the input. You could splice out redundant nodes, I guess, but chasing pointers sounds worse than copying arrays.

**Comment by adrianstephens** [comment]
Yes, essentially, and yes I do have to test and skip some nodes, which I hadn't originally anticipated. So it's linear in number of captures, but then so is coping the arrays. I suppose the benefit is that Thread's don't need a separately allocated array, and the number of tests is usually only 1 or 2 compared to copying all captures.  It's certainly not a big gain.

**Comment by junyer** [comment]
In that case, I would prefer to err on the side of simplicity.
