### ISSUE TITLE
OnePass overly pessimistic

### ISSUE THREAD

**Issue by adrianstephens** [google/re2#183]
See if you like this one...
The check for a re being one-pass requires "(1) for any other Inst nip, there is at most one input-free path from ip to nip", but that precludes a number of routes through the re that seem, to my untrained eye, to still be completely deterministic (e.g. `(?:a+|b)+`). Any inconsistencies that might happen should get picked up by the kInstByteRange checks.
I've tried disabling the check for kInstNop (onepass.cc line 531) and all instructions at line 547 with no apparent unit test errors; but that's not much of a correctness proof. Does this sound legit?

**Comment by adrianstephens** [comment]
...and also:
The check for consistent actions in the same routine could be tweaked to allow for trivial loops.
e.g. ".*(?:a|b)" fails the IsOnePass test, where the equivalent (?) "[^ab]*(?:a|b)" does not. Allowing actions that index the current state to be overwritten seems like an easy fix.
i.e. onepass.cc, line 485:
if ((act & kImpossible) == kImpossible) {…}
would become:
if ((act & kImpossible) == kImpossible || act == ((nodeindex << kIndexShift) | cond)) {…}

**Comment by junyer** [comment]
`(?:a+|b)+` is not one-pass. It is equivalent to `(?:aa*|b)(?:aa*|b)*` and is ambiguous because `'a'` can be matched by `a*`, but can also move past that and be matched by `a`.

`.*(?:a|b)` is not one-pass. It is ambiguous because `'a'` can be matched by `.*`, but can also move past that and be matched by `a`. It is _**not**_ equivalent to `[^ab]*(?:a|b)`.

**Comment by adrianstephens** [comment]
Maybe a better wording would have been, things that match `(?:a+|b)+` can be found using a one-pass system, because (again, it seems to me) whichever route is picked for matching, leads to the same set of matched and unmatched results. I think.
I see that my second comment was just wrong, but what about `.*?(?:a|b)` ? The `.*?` adds one-pass entries for every case, including for a and b, but by being non-greedy it should never actually match them. That was what I was trying to address.
Perhaps both these cases would be better implemented in an optimization pass before IsOnePass is called? Do you have any opinion on that, or know if it has been tried in the past?

**Comment by junyer** [comment]
`.*?(?:a|b)` is not one-pass for the same reason that `.*(?:a|b)` is not one-pass. It is still ambiguous because the automaton still has two possibilities. The ordering of those possibilities is what changes.
