### ISSUE TITLE
How to solve the DFA out of memory error?

### ISSUE THREAD

**Issue by sty945** [google/re2#186]
hi, i have a very large regex,  about 454 patterns, this is part of regex:
```
(a|((a|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen) hundred( and ((one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen)|(twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)))?)|((twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety) (one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen))|((one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen)|(twenty|thirty|forty|fifty|sixty|seventy|eighty|ninety)))
```
when i use re2 to pattern this regex,  this is the following error that I get:
```
re2/re2.cc:650: DFA out of memory: size 18477, bytemap range 25, list count 15349
```
In order to avoid this error,i see [this issue](https://github.com/google/re2/issues/184)  increase the maximum memory to 300 megabytes and solve this problem,but i get new error:

```
/re2/re2.cc:215: pattern too large - compile failed
```
i want to know how to solve this problem? thank you very much!!

**Comment by junyer** [comment]
Please show me the part of your code that manipulates the `RE2` and `RE2::Options` objects. I suspect that there is an error there.

**Comment by sty945** [comment]
Thank you very much for your reply. 
I use the re2 C wrapper : https://github.com/marcomaggi/cre2/ ,
so `RE2::Options`  code is like this:
```
    char strPtn[200000]; 
    ifile.getline(strPtn, 200000);
    ifile.close();
    cre2_options_t* opt;
    opt = cre2_opt_new();
    cre2_opt_set_perl_classes(opt, 1); 
    cre2_opt_set_one_line(opt, 1); 
    cre2_opt_set_longest_match(opt, 1); 
    // cre2_opt_set_max_mem(opt, 300);   
    *pPtn = cre2_new(strPtn, strlen(strPtn), opt);
```
and manipulates the` RE2`  is like this:
```
int nmatch = cre2_num_capturing_groups(ptnNo);
int e = cre2_match(ptnNo, text, strlen(text), 0, strlen(text), CRE2_UNANCHORED, NULL, 0);
```

when not set `cre2_opt_set_max_mem(opt, 300);`, the following error will get when any code that manipulates the `RE2` .
```
re2/re2.cc:650: DFA out of memory: size 18477, bytemap range 25, list count 15349
```

when set `cre2_opt_set_max_mem(opt, 300);`, this error will occur:

```
/re2/re2.cc:215: pattern too large - compile failed
```

**Comment by junyer** [comment]
The `max_mem` option is in bytes, so your code is setting it to 300B. (The default is 8MiB.) Something like `300 << 20` is what you want.
