### ISSUE TITLE
Documentation link is circular

### ISSUE THREAD

**Issue by pwaller** [google/re2#19]
I just followed the documentation link from http://golang.org/pkg/regexp/, which took me to https://github.com/google/re2/, which links to itself.

Could this be changed to something more useful?

The next most obvious link is this:

https://github.com/google/re2/tree/master/doc

Which isn't immediately useful.

**Comment by junyer** [comment]
It looks like that documentation link is supposed to take you to the RE2 syntax wiki page. Judging from https://github.com/golang/go/issues/10471, it will do so as of the next Go release. :)
