### ISSUE TITLE
ABI change with new version?

### ISSUE THREAD

**Issue by mfechner** [google/re2#196]
After an upgrade from 20180901 to 20190101 I see an error with rubygem-re2 (https://github.com/mudge/re2) version 1.1.1.
I tested this all with FreeBSD.

Gitlab-ce which uses rubygem-re2 shows now the following error message:
```
2019-02-09T12:53:44.994Z 61257 TID-7yrmiht ProcessCommitWorker JID-ecb2b75aab778b5664c7180e INFO: done: 0.242 sec
2019-02-09T12:53:44.990Z 61257 TID-7yrmi71 ProcessCommitWorker JID-509cb863101c789c7ce7dbb7 INFO: done: 0.237 sec
ld-elf.so.1: /usr/local/lib/ruby/gems/2.4/gems/re2-1.1.1/lib/re2.so: Undefined symbol "_ZNK3re23RE223NumberOfCapturingGroupsEv"
```
Maybe here was something changed in the ABI?

**Comment by mfechner** [comment]
I did now a downgrade, problem is gone.
I did an upgrade again and problem does not reappear.
I will close this issue and will reopen it again, if the problem reappear.

**Comment by FireBurn** [comment]
I'm also seeing this issue and with 2019-03-01

**Comment by junyer** [comment]
Yes, the ABI would have changed here: `_ZNK3re23RE223NumberOfCapturingGroupsEv` would have disappeared due to the simplification of `RE2::NumberOfCapturingGroups()` in commit 2cf86e5ab6dcfe045a1f510c2b9a8b012a4158cd. (Hence, release `2019-01-01` was the first affected.)

**Comment by FireBurn** [comment]
I think something was being cached I ran: 

bundle exec gem uninstall re2

And reinstalling the re2 gem started working

The symbol was present in the following files:

Binary file embedded/lib/libre2.so.0.0.0 matches
Binary file embedded/lib/libre2.a matches
Binary file instance/vendor/bundle/ruby/2.5.0/gems/re2-1.1.1/lib/re2.so matches
Binary file instance/vendor/bundle/ruby/2.5.0/gems/re2-1.1.1/ext/re2/re2.so matches
Binary file instance/vendor/bundle/ruby/2.5.0/gems/re2-1.1.1/ext/re2/re2.o matches
Binary file instance/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0-static/re2-1.1.1/re2.so matches

I think it might have been the last one that caused issues
