### ISSUE TITLE
How do I get matches to ignore case

### ISSUE THREAD

**Issue by wangfenggao** [google/re2#197]
RE2 re("hello");
RE2::FullMatch(“Hello”, re) 
How do I get matches to ignore case

**Comment by junyer** [comment]
You can use `(?i)` in the pattern (https://github.com/google/re2/blob/master/re2/re2.h#L30) or unset `case_sensitive` in the options (https://github.com/google/re2/blob/master/re2/re2.h#L561-L562).

**Comment by wangfenggao** [comment]
If I do it the second way, is it reasonable to do so：
RE2::Options options;
options.set_case_sensitive(false);
RE2(pattern, options);

**Comment by junyer** [comment]
Yes, that's right. (Although the third line of code is missing the variable name.)

**Comment by wangfenggao** [comment]
you are very careful  *_*
