### ISSUE TITLE
README says go to GitHub for docs, can't find docs.

### ISSUE THREAD

**Issue by jcoffland** [google/re2#20]
The top-level README says to go to https://github.com/google/re2/ for docs but that just shows the README again.  Where are the docs?

**Comment by junyer** [comment]
We use the wiki (https://github.com/google/re2/wiki) for our documentation. :)

**Comment by jcoffland** [comment]
Why did you closed the ticket?  The problem still stands.  It's not easy to find the documentation from the README which just refers to the GitHub page.  A simple fix would be to change the link in the README to point to the wiki.

**Comment by jcoffland** [comment]
@junyer, thanks that helps a lot.

**Comment by junyer** [comment]
No worries. :)
