### ISSUE TITLE
why not support over \x80 hex value

### ISSUE THREAD

**Issue by wangfenggao** [google/re2#200]
RE2 pattern("\x80");
Error parsing invalid UTF-8

**Comment by junyer** [comment]
UTF-8 mode is the default for RE2 and, as the error indicates, `"\x80"` is invalid UTF-8.

If you wanted code point U+0080, then either `"\u0080"` or `"\\x80"` would work. Note that the former has a single backslash and will be handled by the compiler whereas the latter has a double backslash and will be handled by RE2.

If you really did mean `"\x80"`, then you need Latin-1 mode: either pass `RE2::Latin1` to the constructor or, if you are already passing an `RE2::Options` object, set the `encoding` option to `RE2::Options::EncodingLatin1`.

**Comment by wangfenggao** [comment]
thanks a lot, I am doing traffic identification now,  need to use a regex pattern  like this "\x50\x80\x00\x00\x03\x05"。 but i find \x00 not works,  does Re2 not support?

**Comment by junyer** [comment]
Please see https://stackoverflow.com/q/164168 for more information.
