### ISSUE TITLE
Export CMake target

### ISSUE THREAD

**Issue by SuperWig** [google/re2#201]
Something like this?
```diff
 install(FILES ${RE2_HEADERS} DESTINATION include/re2)
-install(TARGETS re2 ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
+install(TARGETS re2 EXPORT re2Config ARCHIVE DESTINATION lib LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
+install(EXPORT re2Config.cmake NAMESPACE re2:: DESTINATION lib/cmake/re2)
```

**Comment by junyer** [comment]
Thanks for the suggestion!

**Comment by junyer** [comment]
Please try that and let me know how it goes.

P.S. I opted not to add a namespace – `re2::re2` seemed a bit stuttery.

**Comment by SuperWig** [comment]
Isn't it best practice to use a namespace so CMake knows it's an imported target as opposed to a library so it would fail at the configure step instead of during linking?
Also creating an alias for projects using `add_subdirectory`.
```cmake
add_library(re2::re2 ALIAS re2)
```

**Comment by junyer** [comment]
> Isn't it best practice to use a namespace so CMake knows it's an imported target as opposed to a library so it would fail at the configure step instead of during linking?

Sorry, I don't understand what you mean. Can you describe the failure mode to which you are alluding?

**Comment by SuperWig** [comment]
From CMake's documentation:
"_A NAMESPACE with double-colons is specified when exporting the targets for installation. This convention of double-colons gives CMake a hint that the name is an IMPORTED target when it is used by downstreams with the target_link_libraries() command. This way, CMake can issue a diagnostic if the package providing it has not yet been found_."
 - https://cmake.org/cmake/help/v3.14/manual/cmake-packages.7.html#creating-packages

---

```cmake
target_link_libraries(MyTarget PRIVATE re2)
```
This will succeed CMake's configure step even if `re2` isn't found as it it will just amout to linking to `re2.lib` e.g.
```
fatal error LNK1104: cannot open file 're2.lib'
```
However with a namespace CMake will issue a diagnostic during configuration. e.g.
```
Target "MyTarget" links to target "re2::re2" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, or an
ALIAS target is missing?
```

**Comment by junyer** [comment]
Thanks for the detailed explanation! I will go ahead and add the namespace.

Could you just clarify your point about the alias as well?

**Comment by SuperWig** [comment]
For example, instead of having re2 outside of your project and using `find_package` you would have it part of it - like a git submodule - and use add_subdirectory
```cmake
add_executable(main main.cpp)
find_package(re2)
target_link_libraries(main PRIVATE re2::re2)
```
vs
```cmake
add_executable(main main.cpp)
add_subdirectory(third_party/re2)
target_link_libraries(main PRIVATE re2::re2)
```

**Comment by junyer** [comment]
Many thanks. :)

**Comment by SuperWig** [comment]
And to you too :)
