### ISSUE TITLE
Possible to create an OrDie version?

### ISSUE THREAD

**Issue by rosun82** [google/re2#203]
A lot of the cases we have to do

```
::RE2 re2("abc");
if (!re2.ok()) {
  LOG(FATAL) << "Failed to parse regular expression with error " << re2.error();
}
```

This is in fact quite hard if ::RE2 is created as global static variable.

Is it possible to provide an additional option, something like `dies_on_error`? The `log_errors` is not strong enough.

**Comment by junyer** [comment]
Although I'm unwilling to add any such mechanisms to RE2 itself, you could possibly do something like this?

```
const RE2* MakeRE2OrDie(const char* pattern) {
  const RE2* re = new RE2(pattern);
  CHECK(re->ok()) << …;
  return re;
}

static const RE2* const kDigitsRE = MakeRE2OrDie("\\d+");
```
