### ISSUE TITLE
Retrieving captured groups is SLOW

### ISSUE THREAD

**Issue by sergei-dyshel** [google/re2#204]
I tried to measure re2 vs PCRE performance with and without retrieving captured groups. For that matter I wrote a simple benchmark using GoogleBench, RE2 and Qt5. Qt provides `QRegularExpression` class which is wrapper for PCRE operating on UTF-16 strings.

I used regex for parsing Linux strace lines which has like 5 named capturing groups. `QRegularExpression` always saves pairs of start/end indices for all captures and AFAIU `RE2::Match()` method can be given an array of `StringPiece` objects which is essentially the same as start/end offset pair and if given zero-length array RE2 is supposed to run faster by not saving any captures.

The results of benchmark were rather disappointing. RE2 without capturing showed excellent result of 250 ns vs 1220 ns of PCRE, which is anticipated and reflects various published benchmarks on RE2 vs PCRE perf. 

But with capturing RE2 time increased to 2800 ns which is worse than PCRE and 10x worse than non-capturing RE2!

What makes RE2 so slow at capturing groups?

UPD: Tried changing pattern encoding to Latin1 and also tried changing all groups to non-capturing but without any luck.

UPD1: Making all groups non-capturing (by using `?:`) improved RE2 time from 2800 ns to 2100 ns, which is still worse than PCRE. 

Here is source of my test:
```c++
#include <QRegularExpression>
#include <boost/program_options.hpp>
#include "re2/re2.h"
#include "benchmark/benchmark.h"

namespace po = boost::program_options;

using namespace benchmark;

static const char* pattern
    = R""""(^(?:(?P<timestamp>\d{2}:\d{2}:\d{2}(?:\.\d{6})?) )?(?P<syscall>\w+)\((?P<body>.*)\)\s+=\s+(?P<rc>[-\w]+)(?: (?P<errno>\w+) \([^\)]+\))?(?: <(?P<duration>\d+\.\d+)>)?$)"""";

static const char* text
    = R""""(22:58:12.021512 access("/etc/system-fips", F_OK) = -1 ENOENT (No such file or directory) <0.000021>)"""";

static const RE2 patternRe2(pattern);
static const re2::StringPiece textRe2(text);

std::vector<re2::StringPiece> capturesRe2(patternRe2.NumberOfCapturingGroups()
                                          + 1);

static void Re2NoCaptures(benchmark::State& state)
{
    for (auto _ : state) {
        bool hasMatch = patternRe2.Match(textRe2, 0, textRe2.size(),
                                         RE2::UNANCHORED, nullptr, 0);
        if (!hasMatch)
            throw std::runtime_error("no match");
    }
}

BENCHMARK(Re2NoCaptures);

static void Re2WithCaptures(benchmark::State& state)
{
    for (auto _ : state) {
        bool hasMatch
            = patternRe2.Match(textRe2, 0, textRe2.size(), RE2::UNANCHORED,
                               &capturesRe2[0], capturesRe2.size());
        if (!hasMatch)
            throw std::runtime_error("no match");
    }
}

BENCHMARK(Re2WithCaptures);

static void Pcre(benchmark::State& state) {
    static const QRegularExpression patternPcre(pattern);
    static const QString textPcre(text);

    std::vector<QStringRef> capturesPcre(patternPcre.captureCount() + 1);

    for (auto _ : state) {
        auto match = patternPcre.match(textPcre);
        if (!match.hasMatch())
            throw std::runtime_error("no match");
        for (int i = 0; i <= patternPcre.captureCount(); ++i)
            capturesPcre[i] = (match.capturedRef(i));
    }
}

BENCHMARK(Pcre);

BENCHMARK_MAIN();
```

**Comment by junyer** [comment]
The `Re2NoCaptures` benchmark would be using the DFA execution engine, which doesn't handle capturing groups at all. The `Re2WithCaptures` benchmark would be using the BitState execution engine, I suspect, or else the NFA execution engine – and those are relatively slow because they do much more than just pointer chasing, which is what the DFA execution engine does on the fast path.

**Comment by junyer** [comment]
BTW, you might try changing the `.*` to `.*?` in order to avoid having to backtrack over more than half the input string. I would expect that to improve the PCRE timing as well.

**Comment by sergei-dyshel** [comment]
@junyer
Just curios, is that some algorithmic limitation that prevents DFA engine from saving capturing groups or is it just wasn't considered important enough to be implemented?

**Comment by junyer** [comment]
http://re2c.org/2017_trofimovich_tagged_deterministic_finite_automata_with_lookahead.pdf describes a recent technique. I'm not aware of any other DFA implementation that supports capturing groups.

**Comment by sergei-dyshel** [comment]
Thank you for clarification! I didn't think that capturing groups in DFA is such a hard problem.
