### ISSUE TITLE
How to optimize RE2 for a true or false match results?

### ISSUE THREAD

**Issue by evandrocoan** [google/re2#207]
I got this implementation https://github.com/evandrocoan/fastfilepackage/commit/abb1a694e8161399deee4506d54ae8a4d1c97064 where I use RE2 like this:
```c++
#include <iostream>
#include <re2/re2.h>

#if !defined(__unix__)
    #error Only POSIX systems are supported!
#endif

RE2* monsterregex;
RE2::Options myglobaloptions;
const char* rawregex = "(match this .* sentence)|(or this sentence)";

// myglobaloptions.set_posix_syntax(true);
monsterregex = new RE2( rawregex, myglobaloptions );

if( !monsterregex->ok() ) {
    std::cerr << "ERROR: FastFile failed to compile the rawregex with '"
            << monsterregex->error() << "'!" << std::endl;
    return;
}

ssize_t charsread;
int linebuffersize = 131072;

char* readline = (char*) malloc( linebuffersize );
FILE* cfilestream = fopen( "/mybiglogfile.txt", "r" );

while( true )
{
    if( ( charsread = getline( &readline, &linebuffersize, cfilestream ) ) != -1 )
    {
        if( RE2::PartialMatch( readline, *monsterregex ) ) {
            // do stuff
        }
    }
    else {
        // End of the file
        break;
    }
}

delete monsterregex;
```

But I am not sure this is the best implementation for my `(yes or no)` question: `Does this line has the sentence 'match this 1' or 'match this 2' or ... 'match this n'?`. Using this code above, I got `1.8` seconds to parse 250MB of text with lines around 100~200 characters of ASCII (very rarely, a random invalid UTF8 character). I already had set `myglobaloptions.set_utf8(false)` but did not have any effect on the performance time.

However, using the C Standard library `regex.h` I got only `1.4` seconds to parse the same 250MB of text. All the text is already cached into the memory by OS, so, no file io from the file system to bother us here. This is the implementation using the `regex.h` standard C library:
```c++
#include <iostream>
#include <regex.h>

#if !defined(__unix__)
    #error Only POSIX systems are supported!
#endif

regex_t monsterregex;
const char* rawregex = "(match this .* sentence)|(or this sentence)";
monsterregex = regcomp( &monsterregex, rawregex, REG_NOSUB | REG_EXTENDED );

if( monsterregex ) {
    std::cerr << "ERROR: FastFile failed to compile the rawregex '"
            << rawregex << "'!" << std::endl;
    return;
}

ssize_t charsread;
int linebuffersize = 131072;

char* readline = (char*) malloc( linebuffersize );
FILE* cfilestream = fopen( "/mybiglogfile.txt", "r" );

while( true )
{
    if( ( charsread = getline( &readline, &linebuffersize, cfilestream ) ) != -1 )
    {
        if( regexec( &monsterregex, readline, 0, NULL, 0 ) != REG_NOMATCH ) {
            // do stuff
        }
    }
    else {
        // End of the file
        break;
    }
}

regfree( &monsterregex );
```

While browsing around the code on the header file [re2/re2.h](https://github.com/google/re2/blob/master/re2/re2.h) I found this promising function called [`bool Match()`](https://github.com/google/re2/blob/0c95bcce2f1f0f071a786ca2c42384b211b8caba/re2/re2.h#L515-L520) saying stuff like `runs even faster if nsubmatch == 0`, then, wow, I wanna run that function. But sadly, `bool Match()` is a private function. Is there something similar I can use?
1. The pattern like `(group1)|(group2)|(grupn)`, should be matched anywhere on the string, for example:
	```
	this line will be matched because it has group1 near its end
	this line will not be matched because it does not has group 1 anywhere
	```
1. Some patterns inside the filtering regex may have the `.*` wildcard
1. I do not need to capture anything from the input line (i.e., capturing groups), I just need to know where the pattern is somewhere inside the line or not. This because I am just filtering out which lines are going to the next phase of the processing and which lines are not. Usually, 99% of the lines are never going to match the pattern. I did not use noncapturing groups `(?:noncapturing)` on the regexes because they are not supported by `regex.h`: https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions
1. I am confused by the use of `RE2::PartialMatch` and `RE2::FullMatch`. I used the `RE2::FullMatch` and nothing matched. Then, I used the `RE2::PartialMatch` and things starting matching. Does `RE2::FullMatch` is anchored to the start of the line? Can I set it to be UNANCHORED? I tried to figure out how to pass the `RE2::Anchor::UNANCHORED` as an option to `RE2()` Constructor, but I did not succeed.

**Comment by junyer** [comment]
`RE2::Match()` is public, so you can indeed call that and pass `RE2::UNANCHORED`. Apart from that, you can set the `never_capture` option.

Calling `RE2::PartialMatch()` is equivalent to passing `RE2::UNANCHORED` to `RE2::Match()`. Calling `RE2::FullMatch()` is equivalent to passing `RE2::ANCHOR_BOTH` to `RE2::Match()`.

**Comment by evandrocoan** [comment]
I also tested it against the https://github.com/intel/hyperscan regex library on tis commit it: https://github.com/evandrocoan/fastfilepackage/commit/8d3f14955537ef333efa2bef9759be2001287144

With it, I got `0.9` seconds to parse the same 250MB of files. For now, I will be using the Hyperscan regex library: https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/
