### ISSUE TITLE
Using libre2.so: fail with undefined reference to `re2::RE2::RE2(re2::StringPiece const&)'

### ISSUE THREAD

**Issue by Michael-Li-4C** [google/re2#208]
This looks like a very rudimentary question, but I tried to search in the history and haven't found a solution yet. Sorry if this is repeated. 

I'm trying to use libre2.so. and here is the constructors for RE2

```
#ifndef SWIG
  RE2(const char* pattern);
  RE2(const std::string& pattern);
#endif
  RE2(const StringPiece& pattern);
  RE2(const StringPiece& pattern, const Options& options);
  ~RE2();
```

So in my code, I'm using this RE2 like this,
```
        StringPiece spre2("(: *)(-*nan)");
        RE2 renan(spre2);
```
When I compile, I always get 

> re-001.cc:(.text+0x44): undefined reference to `re2::RE2::RE2(re2::StringPiece const&)'

I'm thinking I'm using the third constructor but apparently, it's not working.
I have followed the README to compile and install the libre2.so and headers properly and all the unittests have passed. Also, I'm able to use the StringPiece class without issue.
Can someone point to me any hints on why I am getting this?
Thanks in advance!

**Comment by junyer** [comment]
What does `nm -C libre2.so | grep re2::RE2::RE2` show? Assuming it shows the constructors above, please confirm that you are linking against RE2 with `-lre2`.

**Comment by Michael-Li-4C** [comment]
@junyer Thanks for your reply. Here are the results for the libre2.so

> xli@PTC-PC05L43V:~/re2/build$ nm -C /usr/local/lib/libre2.so | egrep re2::RE2::RE2
> 000000000010edf8 T re2::RE2::RE2(char const*)
> 000000000010f048 T re2::RE2::RE2(re2::StringPiece const&)
> 000000000010f15e T re2::RE2::RE2(re2::StringPiece const&, re2::RE2::Options const&)
> 000000000010ef20 T re2::RE2::RE2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
> 000000000010edf8 T re2::RE2::RE2(char const*)
> 000000000010f048 T re2::RE2::RE2(re2::StringPiece const&)
> 000000000010f15e T re2::RE2::RE2(re2::StringPiece const&, re2::RE2::Options const&)
> 000000000010ef20 T re2::RE2::RE2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
> 

It looks to have both char and StringPiece constructor. 
here are my compile flags,

> g++  -std=c++11 -I/usr/local/include -L/usr/local/lib -lre2 -I/usr/local/include  -c -o re-001.o re-001.cc

**Comment by Michael-Li-4C** [comment]
problem solved, i wasn't linking the -lre2 properly. Thanks @junyer

**Comment by junyer** [comment]
Glad to help. :)
