### ISSUE TITLE
Underscore (_) makes replace group not found

### ISSUE THREAD

**Issue by mikhailkolesnik** [google/re2#209]
https://play.golang.org/p/THIwTK5zXpW
```
package main

import (
	"fmt"
	"regexp"
)

func main() {
	r := regexp.MustCompile(`(\w+)`)
	fmt.Println(r)

	orig := "somerandomtext"
	fmt.Println(r.MatchString(orig))

	fmt.Println(r.ReplaceAllString(orig, "$1"))
	fmt.Println(r.ReplaceAllString(orig, "$1_"))
	fmt.Println(r.ReplaceAllString(orig, "$1 _"))
}
```

second output should produce `somerandomtext_` but produces nothing

**Comment by junyer** [comment]
RE2 behaves in the way that you mistakenly expected the Go `regexp` package would behave, so this isn't a bug in RE2 and, as @ianlancetaylor explained, this isn't a bug in the Go `regexp` package either.

P.S. Please help me to eradicate the myth that RE2 and the Go `regexp` package are the same thing!
