### ISSUE TITLE
Stream API (or matching across successive segments of data)?

### ISSUE THREAD

**Issue by timwoj** [google/re2#213]
I saw that RE2 has the `Consume` API for continually matching against successive segments of data, but it appears that it always starts the match at the start of each segments. Is there a way to match across the boundary between two segments?

Say for example I have the pattern `(\w+)=(\w+)` and two segments of data, one that ends with `key=` and the other that starts with `value`. I'd like to be able for the matcher to keep track that it's seen part of the match so that it can finish the match on the next segment.

Is that possible with RE2?

**Comment by junyer** [comment]
Sorry, RE2 does not support streaming. There was some discussion about this a couple of years ago on https://github.com/google/re2/issues/126 and https://github.com/google/re2/issues/127.
