### ISSUE TITLE
string_view iterator incompatibility in abseil version with MSVC

### ISSUE THREAD

**Issue by wendazhou** [google/re2#214]
Hi,

I'm currently hitting some errors trying to build the abseil version in MSVC 2019 with `/std:c++17` (pulled in when building tensorflow). Some files (e.g. [onepass.cc](https://github.com/google/re2/blob/fe859a290d4750b79712ad981bdf45a9af43ed8b/re2/onepass.cc#L252)) appear to assume that `absl::string_view::const_iterator` is implicitly convertible to `const char*`, which is true for the `absl` implementation. However, when abseil detects that the system provides a `std::string_view` implementation, it defaults to that one, and as far as I can tell there is no conversion guaranteed by the standard (and MSVC does not provide one).

Would it be possible to consider supporting `string_view` implementations which use opaque `absl::string_view::const_iterator` types? I'm happy to help.

**Comment by junyer** [comment]
Thanks for the report!

I can just replace `begin()` and `end()` with `data()` and `data()+size()`, respectively, but before I rush into doing that, I have pinged the Abseil team to ask whether anyone has any better ideas. :)

In the meantime, could you please let me know which files are broken for you? Note that you might have to pass the `--keep_going` flag to `bazel build` in order to see the full extent of the breakage.

**Comment by wendazhou** [comment]
Thanks for the quick reply!

I see errors in: `parse`, `nfa`, `bitstate`, `onepass`, `re2`, `prog` and `dfa`. I've fixed this for now by patching abseil in my build (force it to provide its own `string_view`), so I have a workaround

**Comment by junyer** [comment]
Great, thanks.

Just to be clear, I asked only because both libstdc++ and libc++ just use pointers, so I can't easily hunt down the failures myself.

**Comment by junyer** [comment]
I leaned on the indexing and cross-referencing in our internal Code Search and managed to find a few more likely failures in the testing code...

**Comment by junyer** [comment]
@wendazhou, could you please try to build `@com_googlesource_code_re2//:all`? However, please be aware that Abseil made a breaking change to their build in preparation for Bazel 1.0, I believe, so you will need to add the following to your `WORKSPACE` file in order to build at head:

```
http_archive(
    name = "rules_cc",
    strip_prefix = "rules_cc-master",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/master.zip"],
)
```

**Comment by wendazhou** [comment]
Thanks for the fix!

I can confirm it builds on head with MSVC 14.22.27905 with `/permissive-` and `/std:c++17`, *however*, only with a previous (known-good) version of `absl` (I used `43ef2148`). It seems that with the latest version of `absl` msvc gets confused about pack-expansion in the compressed tuples implementation [here](https://github.com/abseil/abseil-cpp/blob/0e7afdcbd24c7e5b7cab4e0217d8886f1525b520/absl/container/internal/compressed_tuple.h#L224) ¯\\\_(ツ)\_/¯

**Comment by junyer** [comment]
Sweet, thank you for verifying!

FWIW, https://github.com/abseil/abseil-cpp/issues/357 appears to be the bug that you observed.
