### ISSUE TITLE
Install pkgconfig files from CMake installation

### ISSUE THREAD

**Issue by metthal** [google/re2#215]
We were discussing this with Paul on gerrit [here](https://code-review.googlesource.com/c/re2/+/43990) but to sum it up.

Right now, all popular Linux distributions package re2 from GNU make build which installs pkgconfig `pc` files. However this is not an ideal situation for people who use CMake in their projects. They can't do `find_package(re2)` in their project out of the box. The usual approach then is to write your own finder that will use pkgconfig to generate CMake targets but it's much better if projects provide their own. CMake build system in RE2 already generate all the necessary files for doing just `find_package(re2)` but it does not install pkgconfig files. That way, package maintainers for Fedora, Ubuntu, Arch, ... can't really use CMake and not break existing packages which rely on pkgconfig. I have provided patch for that but Paul asked me to write this issue to start the discussion regarding this matter.

There is also another thing which is that Red Hat based distributions should have 64-bit libraries installed in /usr/lib64 but through CMake, RE2 installs itself into /usr/lib. Therefore we also need GNUInstallDirs which work just find even on Windows and macOS.

cc @SuperWig

**Comment by SuperWig** [comment]
Well regarding pkgconfig, I'm not familar with it in the slightest so can't add input to that.

However this notification reminded me that I was working on getting the CMakeLists to be target based a couple months back. 

https://github.com/SuperWig/re2/commit/79362c34912d8359e5befb372590b2f0ef8444e8

**Comment by junyer** [comment]
Thanks for filing the issue, @metthal, and thanks for responding, @SuperWig. The discussion that I anticipated hasn't eventuated, so let's move forward with the proposed change and see if someone complains later. :)

**Comment by junyer** [comment]
With GNU make, `libre2.a` and `libre2.so` are built. With CMake, `libre2.a` xor `libre2.so` is built. The difference is going to matter to package maintainers, presumably. Note also that the filename is baked into `re2Config-release.cmake`. :(

**Comment by junyer** [comment]
I don't mind keeping the `GNUInstallDirs` part of the change because handling `lib` versus `lib64` et cetera is worthwhile, but if CMake doesn't support building `libre2.a` and `libre2.so` together and installing them together, then I think I'm going to have to undo the `re2.pc` part of the change.

**Comment by metthal** [comment]
I think it would be possible to somehow do that. I'm just kinda busy last several days. I'll probably message you one more time once I resolve simultaneous installation of static and dynamic library.

**Comment by junyer** [comment]
No worries. Just reopen this issue. :)
