### ISSUE TITLE
Please change versioning convention

### ISSUE THREAD

**Issue by kloczek** [google/re2#218]
All packaging systems does not allow use '-' in version string.
Please on next release use for example "%y%m%d" format.

**Comment by junyer** [comment]
RE2 has been using the `YYYY-MM-DD` format for over four years now. If package manager XYZ uses some other format, then they will just have to convert the needful downstream. Debian is one such package manager that does that: https://packages.debian.org/bullseye/libre2-dev, for example, is currently at version `20190901+dfsg-1`, which is based on release `2019-09-01`.

**Comment by kloczek** [comment]
Look .. you started using cmake.
I just found that it has missing SONAME version.
Quite often maintainers are associating package version with SONAME version or at least main version number with SONAME version.
Other thing is is that rc2 provides rc2,pc file which **forces** to use version string without '-'. The same could be with meson build (if someone would try to add meson build framework for rc2).
BTW that rc2.pc file as Version string has "0.0.0".
You may try to insist to use non-stand version string but it will create more and more obstacles.

Everything is handle able (somehow) bout treating some packages in special way only because source tree maintainer want to stick to own style of versioning causes that some other people will be wasting time on handle those exceptions. There are many services which detects new versions/releases to automatically try to upgrade some packages and I'm not only one who is using that kind of automation.

If you want to waste time of other people by not using some de facto standards do not count that some other people will be helping you.

**Comment by kloczek** [comment]
https://en.wikipedia.org/wiki/Software_versioning

**Comment by junyer** [comment]
Sorry, I still don't understand why you can't convert from `YYYY-MM-DD` to `YYYYMMDD` downstream. If RE2 had been using the `vX.Y.Z` format, for example, would you now be demanding that the `v` be removed? (TensorFlow uses that format, BTW, so this isn't a hypothetical question.)

Also, I see that https://en.wikipedia.org/wiki/Software_versioning#Date_of_release says:

> When using dates in versioning, for instance, file names, it is common to use the ISO 8601 scheme:[13] YYYY-MM-DD, as this is easily string sorted to increasing/decreasing order. The hyphens are sometimes omitted.

**Comment by kloczek** [comment]
Current re2 cmake support does not set package version.
Try to set it to use your style and you will see that cmake will bark on you that you are trying top use '-' in version string. That string can be pout automatically into re2.pc file.

If other package will be trying to check using pkg-config availability of the re2 development resources it will be confused again because pkg-config uses doted version pattern.

If you want to use date in re3 version that is file, Issue is tooling outside re2 is even forcing to not use '-' in version strings.

Mapping in rpm versions  your versions requires additional steps like:
```
%define         longver         2019-09-01
%define         shortver        %(echo %{longver}|sed 's|-||g')

Summary:        C++ fast alternative to backtracking RE engines
Name:           re2
Version:        %{shortver}
```
The same is with deb packages.

Just look around and try to check how many any distribution packages is using your pattern.
In case of rpm based distoros NONE because rpm does not allow use '-' in version string
Just changed in my re3.spec line with Version to exactly what you are using:
```
$ rpmbuild -ba re2.spec
error: line 10: Illegal char '-' (0x2d) in: Version:	2019-09-01
```

**Comment by junyer** [comment]
I understand that the hyphens are invalid in some systems. My position remains that packaging in such systems can remove the hyphens. It is trivial to do so – as you have just demonstrated – and packaging in various systems has been doing so for years. Some systems (e.g. FreeBSD, Gentoo) even derive our releases (i.e. the Git tags) **_from_** their versions:

```
GH_TAGNAME=     ${PORTVERSION:C\|(....)(..)(..)\|\1-\2-\3\|}
```

```
# Different date format used upstream.
RE2_VER=${PV#0.}
RE2_VER=${RE2_VER//./-}
```

**Comment by kloczek** [comment]
Not "some system".
ALL currently used packaging systems.

**Comment by junyer** [comment]
Even if that were true,† the fact remains that nothing is broken, so nothing needs fixing. Of course, if something **_is_** broken, then please focus on describing the technical details of the breakage including why it can't be fixed downstream. Otherwise, this discussion has run its course.

† See https://www.debian.org/doc/debian-policy/ch-controlfields.html#version for a counterexample:

> The upstream_version may contain only alphanumerics [6] and the characters . + - ~ (full stop, plus, hyphen, tilde) and should start with a digit. If there is no debian_revision then hyphens are not allowed.
