### ISSUE TITLE
regex search: start offset of the substring

### ISSUE THREAD

**Issue by wangfenggao** [google/re2#220]
I have a text that I want to search for a substring based on the expression, and get the **start offset** of the substring, how to do?

**Comment by junyer** [comment]
`RE2::Match()` is what I typically suggest for this.

https://github.com/google/re2/blob/374ecc8d98421ac3a77b0c76eab4a8a46e27e318/re2/re2.h#L494-L520

For example,

```
  size_t startpos = 0;
  re2::StringPiece match;
  if (re.Match(text, startpos, text.size(), RE2::UNANCHORED, &match, 1)) {
    // match.data() - text.data() is the match offset.
    // match.size() is the match length.
  }
```

To obtain the next (non-overlapping) match, advance `startpos` to the end of `match` and search again, but be sure to advance `startpos` by **_at least_** one code unit – or else you will not make any progress when `match` is the empty string! (In Latin-1 mode, you can just increment `startpos`. In UTF-8 mode, you have to determine the length of the next code point and add that to `startpos`.)
