### ISSUE TITLE
Supports matching all Chinese characters

### ISSUE THREAD

**Issue by wangfenggao** [google/re2#225]
I know support  \p{Greek}， does re2 supports matching all Chinese characters（\u4E00-\u9FA5）.thanks

**Comment by junyer** [comment]
Yes, I believe that `\p{Han}` is what you want? (FYI, https://github.com/google/re2/wiki/Syntax lists all of the supported scripts.)

**Comment by wangfenggao** [comment]
thanks very much, I searched Chinese and found none, so I thought Chinese was not supported. and also i want to know how to match Japanese

**Comment by junyer** [comment]
`\p{Hiragana}` and `\p{Katakana}` are what you want...
