### ISSUE TITLE
Create releases in Github

### ISSUE THREAD

**Issue by Dargish** [google/re2#23]
Hi, we've been using re2 at double negative for some time, previously we pulled tarballs down from googlecode into our build system for each version of re2. Now that you've switched to Github though we can't pull a tarball until a release is made.

Would it be possible to have a release made sometime soon? The previous versioning system like 20150428 would be fine.

Thanks, Shane.

**Comment by junyer** [comment]
GitHub lets you download archive "snapshots" at any point. For example, https://github.com/google/re2/archive/3fcb9b7.zip gives you the repository as at 3fcb9b7877a72649ab00b301a3c5ebbfc2335a49. Would that be sufficient? If not, we can probably reinstitute releases on an ad hoc basis. :)

**Comment by Dargish** [comment]
That's nice to know. Having releases would be a bit of a more ideal solution though. It would keep the project in line with most of the projects that we use from Github. A release as well is a definite "this works and has been tested" as opposed to a commit which might not be as stable.

If you feel like making a release here, or even backporting previous releases on google code to github then we'd happily pick them up. If that's not something that you want to do right now then I'll look into using the archive like you say. Having a commit id like 3fcb9b7 as the version in our build system wouldn't be ideal though!

**Comment by junyer** [comment]
Fair enough. I'll cut a release after I've landed this next change that I'd like to get in. After that, I'll cut releases as often as seems appropriate. If you're watching the mailing list, please feel free to chime in whenever there's a fix or a feature that you're keen to pick up. :)

**Comment by Dargish** [comment]
Thanks! I'll keep an eye on new releases and add them into our system as they come out :)

**Comment by junyer** [comment]
I've cut https://github.com/google/re2/releases/tag/20150501. Enjoy!

**Comment by junyer** [comment]
The release spontaneously "unpublished" itself (i.e. reverted to draft) a couple of times for no apparent reason. :/

**Comment by Dargish** [comment]
That's odd, haven't had that problem with Github before. Goodluck figuring it out!

**Comment by junyer** [comment]
It's still happening. I've contacted GitHub Support. My apologies for the hassle. :(

**Comment by junyer** [comment]
Okay, so this is (finally!) resolved. The problem was that I kept creating the release on GitHub, which then kept getting undone by our automation that mirrors from Gerrit. ;)

I've cut https://github.com/google/re2/releases/tag/2015-05-01 and it's not going anywhere. Enjoy for really reals!

**Comment by Dargish** [comment]
Thank you! I'll put it into our system :)
