### ISSUE TITLE
How to Whitelist URLs with specific keywords?

### ISSUE THREAD

**Issue by gtg430i** [google/re2#231]
I am using Firebase to shorten link from affiliates. I need to whitelist URLs with specific keyword. That keyword would be my account ID. For example, all deep links will contain the keyword "ABCDEFGZ".

https://www.macys.com/shop/product/fantasy-flight-games-star-wars-x-wing-miniatures-game-kihraxz-fighter-expansion-pack?ID=10379715&PartnerID=LINKSHARE&cm_mmc=LINKSHARE-_-47-_-39-_-MP4739&ranMID=3184&ranEAID=Xqv79DCBYJo&ranSiteID=ABCDEFGZ-zhNFRS_B3yd3S8B_WT1_dQ&LinkshareID=Xqv79DCBYJo-zhNFRS_B3yd3S8B_WT1_dQ&m_sc=aff&PartnerID=LINKSHARE

What would be the Regex URL pattern?

**Comment by junyer** [comment]
Please contact [Firebase Support](https://firebase.google.com/support) for help with your issue.
