### ISSUE TITLE
confusing white space (\s) and word characters (\w) interpretation in Google Apps Scripts

### ISSUE THREAD

**Issue by Brt-L** [google/re2#232]
In the Wiki, RE2 syntax states:
\s	whitespace (== [\t\n\f\r ])
\w	word characters (== [0-9A-Za-z_])

... but in Google Apps Scripts, this gives different results:
  var char = String.fromCharCode(160);       // No-Break Space
  var re1 = /[\t\n\f\r 0-9A-Za-z_]/;
  var re2 = /[\s\w]/;
  var check = ( re1.test(char) == re2.test(char) ) ;
  => false

... also with:
    var char = String.fromCharCode(249);       // ù

... and many more !

The difference is not there in Google Sheets functions asRegExMatch() and Google Form validation using RegEx. So is Google Apps Script using another engine with different syntax ?
Anyway, it's confusing !

**Comment by junyer** [comment]
Just to be clear, U+00A0 (NO-BREAK SPACE) and U+00F9 (LATIN SMALL LETTER U WITH GRAVE) aren't ASCII, but in RE2, `\s` and `\w` match ASCII only.

I imagine that Google Apps Script uses the JavaScript flavour of regular expressions, but please refer to https://developers.google.com/apps-script/support if you need further help with this.

**Comment by Brt-L** [comment]
Did some more digging ...
Made an issue at http://issuetracker.google.com/issues/148664349
(so anyway RE2 working as it should ...)

**Comment by junyer** [comment]
Glad to hear. :)
