### ISSUE TITLE
[Question] How to replace GO default regexp library with google/re2

### ISSUE THREAD

**Issue by thangld322** [google/re2#233]
Hi,
I'm using Grok in GO which uses GO Regexp to parse some log text but it has a problem with performance (slower than logstash in my cases). So I want to use this library to replace GO regexp to improve Grok performance.
My problem is that I can't find the equivalent function in this library to GO regexp.
So what are the equivalent function to these functions?
[Compile](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L132)
[FindAllStringSubmatch](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L1172)
[FindStringSubmatch](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L1019)
[SubexpNames](https://github.com/golang/go/blob/master/src/regexp/regexp.go#L344)
Thanks!

**Comment by junyer** [comment]
The direct equivalent of `Compile()` is the `RE2` constructor. There are no direct equivalents of the others, alas, but one could certainly use the RE2 API to emulate them.
