### ISSUE TITLE
Unicode script extension support

### ISSUE THREAD

**Issue by jungshik** [google/re2#234]
It's often the case that ScriptExtension is a lot more useful than Script. For instance, Danda and Double Danda have script=Common because they're used by multiple Indic scripts as punctuations. 

As a result, \p{Devanagari} does not match them, but \p{scx=Devanagari} does match them. 

See 
http://www.unicode.org/reports/tr18/tr18-19.html#Script_Property .
and http://unicode.org/reports/tr24/#Script_Extensions for more details on ScriptExtension.

**Comment by junyer** [comment]
RE2 will support only Categories and Scripts for the foreseeable future. For full Unicode properties support, please build against ICU: https://github.com/google/re2/blob/6c109e908aa4006c0cd147d2397023b7b8f2705d/Makefile#L5-L8

**Comment by jungshik** [comment]
Thanks a lot for the information. Where I work, RE2 is built against ICU so that scx is supported.
