### ISSUE TITLE
ISO 15924 script codes are not recognized

### ISSUE THREAD

**Issue by jungshik** [google/re2#236]
Currently, RE2 does not recognize ISO 15924 script id (4-letter code) but only recognizes the long Unicode script name for Unicode character class - script . For instance, \p{Devanagari} works, but \p{Deva} does not. 

When the script is extracted/inferred programmatically from a locale ID using libraries like PyICU (ICU Python wrapper), it's easy to get ISO 15924 code. Getting the long Unicode script name is more involved. Therefore, it'd be nice if ISO 15924 script codes are also recognized.

**Comment by junyer** [comment]
As per https://github.com/google/re2/issues/234, please build against ICU for full Unicode properties support.
