### ISSUE TITLE
can RE2 find all regex matches

### ISSUE THREAD

**Issue by viviyoyo** [google/re2#238]
Hi , I am trying to search online, but couldn't get more information. is there any RE2 API to find all regex matches in a string similar as std::sregex_iterator in boost regex?

**Comment by junyer** [comment]
Please refer to the "SCANNING TEXT INCREMENTALLY" section of the documentation at https://github.com/google/re2/blob/master/re2/re2.h#L126-L154. Unless I have misunderstood something about `std::regex_iterator`, `RE2::FindAndConsume()` should be what you want.

**Comment by viviyoyo** [comment]
Thanks. this is what I want.  and is it possible to know that how many capture groups in each match? get each capture group id and corresponding capture offset and length?

**Comment by junyer** [comment]
> Thanks. this is what I want. and is it possible to know that how many
> capture groups in each match? 

`NumberOfCapturingGroups()` is what you want. See https://github.com/google/re2/blob/master/re2/re2.h#L482-L485.

> get each capture group id and corresponding
> capture offset and length?

You have to ask RE2 for the capturing groups explicitly. The "SCANNING TEXT INCREMENTALLY" section has an example. See also the "MATCHING WITH SUBSTRING EXTRACTION" and "USING VARIABLE NUMBER OF ARGUMENTS" sections.
