### ISSUE TITLE
multithread feature

### ISSUE THREAD

**Issue by viviyoyo** [google/re2#239]
I have large inputs. does RE2 internally have multithread feature so I can improve the performance. 
the reason I ask is because I use c++ async to manage thread launch and run re2 for many input files. each thread will run 1 file independently.  It seems performance is not bettter than I do the same for regex boost given the same machine.  
if I run 1 file for re2 and boost regex, re2 did better job than boost regex. if I scale to many files using multi-threading, somehow re2 didnt benefit from multi-threading. I can see there are as many threads as my input files.   I wonder what could be interrupt to hurt the performance.

**Comment by junyer** [comment]
You haven't given me enough details about your code, unfortunately, so I can only speculate that this is the problem:

> I can see there are as many threads as my input files.

I suggest using a thread pool with no more than `std::thread::hardware_concurrency()` threads. For your use case, the number of threads shouldn't be greater than the number of CPUs on which your process can be scheduled.

Apart from that, RE2 is thread-friendly and an `RE2` object is safe for concurrent use by multiple threads, but if you are willing to pay the RAM cost of per-thread `RE2` objects, you can avoid any possibility of contention during DFA execution.
