### ISSUE TITLE
Provide access to capturing group matching ranges.

### ISSUE THREAD

**Issue by jcoffland** [google/re2#24]
A feature that I would really like to see in re2 is the ability to extract the capturing group ranges.  I can access the content of named capturing groups matches with the functions ```NamedCapturingGroups()```, ```CapturingGroupNames()``` and ```NumberOfCapturingGroups()``` and match this with args returned by ```FullMatchN()``` but I would really like to be able to get the range of the matches.  I.e. the start and end offsets of the match with the input string.  This would be very useful for replacing capturing groups in a string.  Currently, I'd have to do multiple re2 calls to achieve this.

One way to do this with out breaking the current API would be to extend RE2:Arg by adding ```int start``` and ```int end``` variables which indicated the starting and ending offset of the match or ```-1``` for no match.

**Comment by junyer** [comment]
Do you capture into `StringPiece` objects? Given `StringPiece text` and `StringPiece argn`, the position of `argn` (i.e. within `text`) is `argn.data() - text.data()` and the length of `argn` is `argn.size()`. If nothing was captured, then `argn.data()` will be `nullptr`. Does that work for you?

FWIW, the variadic functions take `const Arg* const args[]` and I would rather not spoil that. :)

**Comment by jcoffland** [comment]
That's interesting.  I'll try it out.  Seems a bit hackish though.  It would be nice if the API support this in a more direct manner.  For example, what guarantee do I have that ```argn.data()``` and ```text.data()``` point to the same array.  I believe you that this is the case but the API does not promise this which means it could change in the future.

I don't see the advantage of ```Arg``` being passed as a constant, other than aesthetics.  Since the data the ```Arg```s are pointing to is being changed it seems more logical to me that they are not constant since they are simply pointers to non-constant data anyway.  Making them non-constant and adding ```start``` and ```end``` members would provide a non-ambiguous way to pass back the match ranges.  Obviously it's up to you though.

**Comment by junyer** [comment]
Very much like `StringRef` in LLVM and `string_view` in some future C++ standard, a `StringPiece` object is just a subrange of an underlying `string` object. This means that capturing into `StringPiece` objects is faster than capturing into `string` objects because you point into the input string instead of copying parts of it. At the lowest level, `const char*` pairs identify the submatches, but those become `StringPiece` objects in due course. As such, RE2 never even knows the offsets, but they are easily computed with `argn.begin() - text.begin()` and `argn.end() - text.begin()`. All of this also means that `argn` and `text` point into the same input string. :)

**Comment by jcoffland** [comment]
Ok, I guess that makes sense.  What happens if the original data is deallocated?  You get a dangling pointer, right?

**Comment by junyer** [comment]
You have to ensure that the underlying `string` object outlives the `StringPiece` object. This is typically not a burden even in asynchronous code, but you would want to be very certain of your object lifetimes before doing something like storing `StringPiece` objects in STL containers on the heap, for example.

**Comment by jcoffland** [comment]
An interesting idea would be to add a function to the API which returns a ```MatchResult``` object.  Internally this object would allocate the necessary ```Arg```s and gather the results.  Then you could query the ```MatchResult``` object by index or keyword and get the capture groups and be able to access their ranges.  All this could be implemented as a convenience on top of the current API.  It might work like this:

```
re2::MatchResult m = re2::ConvenientMatch("some text", "a regex");
if (m) {
  string fullMatch = m.group(0);
  string namedMatch = m.group("name");

  for (unsigned i = 1; i < m.size(); i++) {
    const re2::Group &group = m.group(i);
    std::cout << "name=" << group.name() << " value=" group.value()
      << " start=" << group.start() << " end=" << group.end() << std::endl;
  }
}
```

```re2::Group``` could be castable to ```std::string``` or ```re2::StringPiece```.  You could also add an optional ```flags``` parameter to ```re2::ConvenientMatch``` to specify full, partial or other matches.

**Comment by junyer** [comment]
That reminds me of the Python `re` API in some ways. :)

You could ask whether anyone on re2-dev@googlegroups.com would prefer to use such a wrapper?

**Comment by jcoffland** [comment]
I've used the Python API a lot.  Emailing now.

**Comment by junyer** [comment]
```
  // The provided pointer arguments can be pointers to any scalar numeric
  // type, or one of:
  //    string          (matched piece is copied to string)
  //    StringPiece     (StringPiece is mutated to point to matched piece)
  //    T               (where "bool T::ParseFrom(const char*, int)" exists)
  //    (void*)NULL     (the corresponding matched sub-pattern is not copied)
```

You could also write something that uses that third option in order to compute the offsets. Each object would have to know `text.data()` and `text.size()`, of course, but that's easily handled with one or two constructor arguments. This is probably the best way to extend the capturing group mechanism with custom logic.

**Comment by jcoffland** [comment]
@junyer, that would work but I guess I really want two things:

  1. Access to the range of the match group. (Which is already possible as pointed out above.)
  2. A way to easily deal with regex where I don't know beforehand what the match groups are.

This ticket deals with the former.
