### ISSUE TITLE
re2 parenthesis syntax 

### ISSUE THREAD

**Issue by viviyoyo** [google/re2#240]
I am doing some experiment with RE2. something weird happen. here I put a simple example below. why do we need the outer parenthesis here in regex string in order to be matched?
RE2::PartialMatch("abcde", "abc", &result)  => could't find the match
RE2::PartialMatch("abcde", "(abc)", &result)  => find the match abc

**Comment by junyer** [comment]
> RE2::PartialMatch("abcde", "abc", &result) => could't find the match

I'm not sure what you mean. Are you saying that `RE2::PartialMatch()` returns `false`? Or are you saying that `result` isn't modified? Assuming the latter, note that extra pointer arguments are for extracting capturing groups, but `abc` doesn't have capturing groups, so `result` isn't modified.

If you want the match (AKA `$0`) as opposed to the capturing groups (AKA `$1`, `$2` et cetera), you have to use `Match()` instead.

**Comment by junyer** [comment]
P.S. Could you please use the mailing list (re2-dev@googlegroups.com) for questions? Thanks!

**Comment by viviyoyo** [comment]
got it! Thanks.
