### ISSUE TITLE
Please consider change tagging convention.

### ISSUE THREAD

**Issue by kloczek** [google/re2#242]
`-` character is not allowed in version string.

**Comment by junyer** [comment]
We have had this conversation before. https://github.com/google/re2/issues/218#issuecomment-533956188 remains my position at this time.

**Comment by kloczek** [comment]
So what is the problem to be compliant wit that document?
```
The upstream_version may contain only alphanumerics [6] and the characters . + - ~ (full stop, plus, hyphen, tilde) and should start with a digit. If there is no debian_revision then hyphens are not allowed.
```

**Comment by junyer** [comment]
Are you familiar with the [Serenity Prayer](https://en.wikipedia.org/wiki/Serenity_Prayer)?

**Comment by kloczek** [comment]
No.

So what is the problem with to be compliant with docoment which you mention?

**Comment by junyer** [comment]
As I said previously, nothing is broken, so nothing needs fixing. OTOH, changing the tag format would force approximately every RE2 package maintainer to change what they are doing. That's not something that I'm willing to do.

**Comment by kloczek** [comment]
Just only FTR: still no answer.

So you want to say that is so difficult to **not** type two time `-` on tagging or change date command output format to use that one without minuses??? (because as I see that anywhere in repo is used explicite  last tagged version)

**Comment by junyer** [comment]
Are you volunteering to coordinate the change with every RE2 package maintainer? Because that's what's necessary if you really want the change to happen. If you aren't volunteering, please accept that the tag format isn't going to change.

**Comment by kloczek** [comment]
Yes I'm volunteering to delete those two caracters on every next release.

Please let me know what needs to be done to be able to tag repo next time.

**Comment by junyer** [comment]
No, you are volunteering to coordinate with every RE2 package maintainer. Which is to say, with everyone downstream. The first thing you must do is enumerate the RE2 packages and contacts for their maintainers. I suggest that you use Google Sheets to create a spreadsheet and share it with me.

**Comment by junyer** [comment]
P.S. As per https://github.com/google/re2/issues/218#issuecomment-533885452, FreeBSD and Gentoo are definitely on the list for you to get fixed.

**Comment by kloczek** [comment]
> No, you are volunteering to coordinate with every RE2 package maintainer. Which is to say, with everyone downstream. The first thing you must do is enumerate the RE2 packages and contacts for their maintainers. I suggest that you use Google Sheets to create a spreadsheet and share it with me.

So you want to say that tagging convention is part of the copyright???

**Comment by BurntSushi** [comment]
@junyer I think you are the victim of a troll here. I'd move on. :-)

**Comment by kloczek** [comment]
This kind of diversion actually is called "argumentum ad personam" or "argumentum ad hominam" 
https://en.wikipedia.org/wiki/Ad_hominem
Always it is clear sign that side of the conversarion has no any rational arguments.

You already told that it is possible to change convention if some conditions will be fullfiled. Now I'm only trying to verify is it any legal context of to be forced to ask every possible contributor/mantainer to change tagging convention. 

IMO there is no such context. Ergo: decition is only yours (as release manager) and no one else.

My proposition is to change taggin convention to release date without dots as exactly that version format is used already in all Linux distributions which I've checked (not only RH/rpm based but Debian/dpkg as well), Solaris and FreeBSD (and probably other as as well.

Please .. :)

**Comment by junyer** [comment]
The problem is that you simply don't comprehend the implications for downstream. I'm telling you to contact everyone downstream in order to make them aware of the change because it will break some of them. If you don't want to do that, then nothing will change. I don't know how I can make this any clearer for you.

**Comment by kloczek** [comment]
> to make them aware of the change because it will break some of them

What kind of things?

Sory to as again but you are not giving me ANY clues ..

**Comment by junyer** [comment]
I linked to https://github.com/google/re2/issues/218#issuecomment-533885452 already. Please pay attention.

**Comment by kloczek** [comment]
Again: there is no any clues who needs to be contacted about tagging convention change.
Seems you do not understansd as well that tagging ios completely independent from actual release string.

In github/gitlab you can do both .. rlease and tag. On making release you can use any other convention which you want.

In you will look closer on gitlab web interface you can find that that there are two tabs:
https://github.com/google/re2/releases and https://github.com/google/re2/tags

**Comment by junyer** [comment]
Yes, you get to use your favourite search engine to find all of the RE2 packages on the Internet and then contact all of the maintainers.

**Comment by kloczek** [comment]
Again: you can make releaae with your curent conventiona and tagging with new convention.

As you see all distribution are already "fixing" your convention so everyone will kiss you in n the hand to be able to switch to dowload tar bals fronm tags instead from releases.

**Comment by junyer** [comment]
So you admit that everyone has to take action? But you don't understand why you should notify them? Notifying them ahead of time is the polite thing to do. Effecting such a change after four years is bad enough. Doing so without communication and coordination is rude. Please show a little more consideration for people.

**Comment by kloczek** [comment]
Let's loomk on debian watch file which contains:
```
version=3

opts=dversionmangle=s/\+dfsg$//,repacksuffix=+dfsg,uversionmangle=s/-//g,compression=xz \
https://github.com/google/re2/releases \
.*[^n]/(?:|v|version-|version|release-|r|REL_|rel-|re2(?:_|-))(\d[^\s/]*)\.(?:tar\.xz|txz|tar\.bz2|tbz2|tar\.gz|tgz)
````
Don't you see that tagged tarbals are in not /release but in /archive directory?
If you will chang **tagging* convention nothing will be broken. Do you see that now?

I personally preffer in my packages always to dowload from /archive because some patches which after release needs to be added and they arealredy commited in git always will apply on tagged archive tarballs because maintainerd sometimes are not including in dist release tarballs all files which are patched.

Again: I'm asking to chang **tagging* convention. Not to mention that always you can add at exactly the same git hash two tags (with dashes and without).

**Comment by junyer** [comment]
If you don't want to notify the package maintainers, then I'm not going to make the change.

**Comment by kloczek** [comment]
If they have already enabled "release watch" on re2 they are already reeving notifications about new releases in which next time you can add single sentence that with next release will be changed tagging convention.

**Comment by junyer** [comment]
No, you get to contact all of the maintainers – individually – in order to advise them of the change. Because all of the maintainers – individually – are going to have to take action. If you don't want to do that work, then this conversation is over. Stop trying to squirm out of doing the right thing and just do it.

**Comment by kloczek** [comment]
Because? Please give me just any rational justification ..

So far you are refusing any argument on pure engineering background.

**Comment by junyer** [comment]
This isn't a technical problem. This is a social problem. It's clear to me that you don't know how to collaborate effectively under such circumstances and, worse yet, that you don't care to learn how. Fortunately for RE2 package maintainers, I won't be complicit in your bad open source citizenship.

**Comment by kloczek** [comment]
You just created problem.

In reality there is no any problems because we are talking about **simplification** and use convention widely used in other project. You "social problems" are creating real technical problems because package like your needs to treated as exceptions complicating some infrastructures watching for changes in source trees. That is only problem which you simple **don't want** to understand that your project is only small fraction of something way bigger and if you want to have feedback from that area you need to provide **proper and standard interface* for that kind of interactions.

**Comment by junyer** [comment]
I understand everything that you have said about the technical side of the issue. You have failed to understand anything that I have said about the social side of the issue. RE2 package maintainers must be informed ahead of time. That you disagree with this speaks volumes about you, frankly, as well as your ability to contribute helpfully to the wider community. Moreover, you are the only person who has ever complained – in nearly five years – about the hyphens, so perhaps **_you_** are the problem, not the hyphens.

**Comment by kloczek** [comment]
Yes I've alredy learned that you have no will to do anything .. even if do something will cost you only just write comment on notrmal release operation.

Thanks for understanding.

**Comment by junyer** [comment]
Enjoy the hyphens, mate.

**Comment by derzeter** [comment]
Junyer is right. memor.

**Comment by keystrike** [comment]
memor, bug reports are not for discussion. Please take it to the mailing list. :o) :P
