### ISSUE TITLE
Chromium crashing with re2 2020-03-01

### ISSUE THREAD

**Issue by foutrelis** [google/re2#243]
Chromium 80.0.3987.122 compiled against re2 2020-01-01 is crashing when running with the new version of system libre2. While bisecting, I did not observe any crashes before commit 572d6abf7f227053a4f8b83381fc4378714a2552. This looks like an ABI break, but please advise if I'm missing something.

**Comment by junyer** [comment]
I concur, it **_is_** an ABI break because inlined accessors would malfunction. Mea culpa, I didn't consider that angle partly because I was keen to address the `ReverseProg()` problem and clean up. I will send notify the mailing list (re2-dev@googlegroups.com) shortly. My deepest apologies!

**Comment by foutrelis** [comment]
Would restoring the previous member order fix this or does the removal of `mutable` still make this ABI-incompatible and thus necessitating a soname bump? It does seem to fix my Chromium crash after reordering them; previously even typing an `o` or `p` in a new tab would immediately crash with:

```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
```

As a downstream packager, having a 2020-03-02 release with restored binary compatibility would be the ideal solution. Otherwise, a soname bump and a new release would be fine as well, although it'd require rebuilds of packages linking to re2. Leaving the 2020-03-01 release with the same soname but broken ABI would be completely undesirable I think.

**Comment by junyer** [comment]
The `mutable`-related changes shouldn't affect ABI compatibility, I think, but I'm not confident about that, so +1 to the safer option of bumping the soname et cetera.

**Comment by foutrelis** [comment]
[abi-compliance-checker](https://github.com/lvc/abi-compliance-checker) seems to agree on `mutable` not causing an ABI break. It might be worth to attempt to unbreak this without a soname bump, but you're more qualified to make that decision. :)

![mutable-abi-check](https://user-images.githubusercontent.com/38810/75637352-9833bd00-5c2e-11ea-9b99-b26d1c480523.png)

**Comment by junyer** [comment]
Right, it's that effect that concerns me. The new library assumes immutability, which could have varying effects depending on the toolchain used and the optimisations enabled. I'm worried less about blatant breakage and more about subtle correctness issues, which would be hell to debug for users. If you are willing (albeit not necessarily delighted) to bump the soname, I do think that would be the better, zero-risk way to go.

**Comment by foutrelis** [comment]
Indeed, that seems like the most sensible approach. I'll keep 2020-01-01 for now in Arch Linux and wait for a new release with `SONAME=1` in the Makefile, at which point we'll rebuild the ~9 packages linking to `libre2.so.0`. (Please note that we are not supposed to change the soname downstream; it has to come from the upstream project.)

**Comment by junyer** [comment]
We have (obviously) never bumped the soname. Debian have been setting their own soname (see https://salsa.debian.org/debian/re2/-/blob/debian/debian/patches/soname.patch) for some years, for example, but it's well past time that we step up. Stand by...

**Comment by junyer** [comment]
I have tagged 2020-03-02 as well. I'm about to post to the mailing list again.

**Comment by stefanor** [comment]
If you want to get into the ABI management game, it'd make some sense to bump to the highest SONAME in use by any distribution. Then we can all be in sync, and won't have to manage the SONAME ourselves.

Fedora: 0a: https://src.fedoraproject.org/rpms/re2/blob/master/f/re2-soname.patch
Arch: 1 (as above)
SuSE: 0: https://packagehub.suse.com/packages/re2/
Debian: 5 (5 going to 6, for this change)

So, I'd suggest bumping this to 6 now. Or 7 next time around.

**Comment by junyer** [comment]
Good call. In lieu of attempting to survey distributions exhaustively, what about setting it to 10 or something? Although if Debian seems likely to have been the most meticulous about bumping the soname, then I'm fine with setting it to 6 as you suggest. :)

**Comment by foutrelis** [comment]
:+1: for 6 (preferably now, since no major distro has packaged 2020-03-xx yet).

**Comment by junyer** [comment]
Okey dokey, I'm going to proceed with setting it to 6 then.

**Comment by junyer** [comment]
Tagged 2020-03-03 and posted to the mailing list.
