### ISSUE TITLE
NumberOfCapturingGroups not working correctly

### ISSUE THREAD

**Issue by mircodezorzi** [google/re2#244]
After I updated my system the `NumberOfCapturingGroups` stopped working correctly.

**Minimal Working Example:**
```c++
#include <iostream>
#include <re2/re2.h>

int main() {
	re2::RE2 re{"(fo.)"};
	if (re.ok())
		std::cout << "ok" << std::endl;
	unsigned int n = re.NumberOfCapturingGroups();
	std::cout << n << std::endl;
}
```
**Expected output:**
```
ok
1
```
**Actual output:**
```
ok
0
```

Am I the only one experiencing this issue?

system: `Linux K501UW 5.5.5-arch1-1 #1 SMP PREEMPT Thu, 20 Feb 2020 18:23:09 +0000 x86_64 GNU/Linux`
library version: `re2-1:20200303-1`

**Comment by junyer** [comment]
I'm guessing that (a) this is related to https://github.com/google/re2/issues/243 and (b) you are using Arch, so... ahoy, @foutrelis! https://www.archlinux.org/packages/extra/x86_64/re2/ shows that `1:20200303-1` contains `libre2.so.6` as intended, so I don't know what's happening now. Have you observed any other breakage, @mircodezorzi?

**Comment by mircodezorzi** [comment]
Not as far as I could tell. Currently it's 4 AM here so I'll wait tomorrow morning and check more thoroughly.

**Comment by foutrelis** [comment]
A newly compiled program correctly outputs `ok 1` here. Only way I could get it to print `ok 0` was to first compile it against 20200101 and then run it against 20200303 by creating a `/usr/lib/libre2.so.0 ⇒ libre2.so.6` symlink which is obviously wrong on many levels.

**Comment by junyer** [comment]
Thanks for taking a look, @foutrelis! I'm much less worried now. Please follow up at your leisure, @mircodezorzi, and let us know whether something like that might have happened. Please don't feel ashamed to say so – I did much worse once upon a time with libc and a Solaris box at work! Anyway, I will leave this issue open for the moment.

**Comment by mircodezorzi** [comment]
Well... I managed to find the issue. I had an older version of `re2` installed in `/usr/local/lib`. I guess the compiler was using one version while the linker another(?). Anyways, thanks for the help!

**Comment by junyer** [comment]
Ahh. Mystery solved. Thanks for following up!
