### ISSUE TITLE
Google App Script / Non-Breaking Space

### ISSUE THREAD

**Issue by mgalibert** [google/re2#249]
I'm using Google re2 regular expressions as part of Google Apps Scripts on Google Docs.
Google re2 used to be able to search for non-breaking spaces (rather than regular spaces). Non-breaking spaces are particularly useful in some European languages as they are used before some characters such as `:` `;` `?` `!`

Now every time Google re2 hits a non-breaking space, I got the following message:
![Screenshot 2020-03-17 at 08 00 53](https://user-images.githubusercontent.com/7305438/76830405-75f09080-6825-11ea-940a-889b98f4b5af.jpg)

The code associated is:

```
function searchNonBreakingSpace(body) {
  body.replaceText(' ', 'Found!');
  return body
}
```

**Comment by junyer** [comment]
Sorry, but that error isn't from RE2 itself. Please refer to https://developers.google.com/apps-script/support if you need further help with that. In the meantime, try matching U+00A0 (NO-BREAK SPACE) by writing it as `\x{A0}`. As a JavaScript string, it would be `'\\x{A0}'`.

**Comment by mgalibert** [comment]
You are my hero, it works, thanks a lot!

**Comment by junyer** [comment]
You're welcome!

**Comment by mgalibert** [comment]
Last question if you can: thanks to your tip, I'm now able to match no-break space with `\\x{A0}`. Yet I don't know how to replace regular space with no-break space for example. I used to do:

`body.replaceText('\\s', ' ');` but it won't work if I do ` body.replaceText('\\s', '\\x{A0}');` as you can imagine… Many thanks for your help if you know how to solve this 🙏

**Comment by junyer** [comment]
Ahh. Use `'\u{A0}'` for that.

**Comment by junyer** [comment]
Note the subtle difference between the two: `'\u{A0}'` specifies a JavaScript string containing one character (i.e. U+00A0) whereas `'\\x{A0}'` specifies a JavaScript string containing six characters (i.e. `'\'` `'x'` `'{'` `'A'` `'0'` `'}'`).
