### ISSUE TITLE
Disabling long long use with RE2_HAVE_LONGLONG does not work.

### ISSUE THREAD

**Issue by SaberUK** [google/re2#25]
In 376ee9951148dadd3d258e44b03e2224a3261d34 `RE2_HAVE_LONGLONG` was introduced for disabling methods that use C++11 `long long` when using a C++03 compiler.

This patch is faulty as at the top of `re2/re2.h`  `RE2_HAVE_LONGLONG` is set to 0 if it is not already defined. This means that the `#ifdef RE2_HAVE_LONGLONG`s always evaluate to true.

**Comment by junyer** [comment]
Oops, we should have been using `#if`, not `#ifdef`.
