### ISSUE TITLE
Any plan to support (?!re)

### ISSUE THREAD

**Issue by tshasc** [google/re2#255]
This is frequently used for the scenarios that we don't want to support a particular sub-string
any plan to support it?

If no, what is the alternative method for it, thanks

(?!re) | before text not matching re (NOT SUPPORTED)

**Comment by junyer** [comment]
Yes, our plan is still to support look-around assertions as soon as someone invents a technique that works with all of the execution engines (including matching in reverse for the DFA execution engine) and is linearly bounded in time and space.

For now, a common practice is to match separate regular expressions that specify things to include versus things to exclude.
