### ISSUE TITLE
compile_test fails on 32-bit platforms

### ISSUE THREAD

**Issue by mbakke** [google/re2#256]
Hello,

Trying to build the latest re2 on i686 and armhf, I get a test failure in `obj/test/compile_test`:

```
obj/so/test/compile_test                FAIL; output in obj/so/test/compile_test.log                          
obj/dbg/test/compile_test               FAIL; output in obj/dbg/test/compile_test.log                        
obj/test/compile_test                   FAIL; output in obj/test/compile_test.log
```

compile_test.log contains only:

```
re2/testing/compile_test.cc:242: Check failed: prog == NULL
```

**Comment by junyer** [comment]
Thanks for the report! Could you please just confirm that the test fails at e93895e, but passes at 8aef3d1? If my suspicion is correct, the slight efficiency win breaks the test on 32-bit platforms.

**Comment by junyer** [comment]
Never mind, I dug around internally and found a way to reproduce the issue on `armeabi-v7a`. It seems like the test has been broken for some time – quite possibly from earlier efficiency work!
