### ISSUE TITLE
[Not an RE2 bug] Error compiling with gcc's -fconcepts.

### ISSUE THREAD

**Issue by myrrc** [google/re2#257]
Hi!
This (as mentioned in header) is not your library bug, but please take it into account.
GCC 9 and 10 with -fconcepts (-std=c++11, c++14, c++17, c++2a) refuse to compile re2 because of the following:
https://github.com/google/re2/blob/bde1ea09550a61b4a092cdf0e3ba8dca4200947a/re2/prog.cc#L484
Confirmed at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91867#3

Can be referenced at master and till commit `7cf8b88` (used by ClickHouse).

**Comment by junyer** [comment]
Interesting, thanks! Considering the circumstances, building RE2 without `-fconcepts` seems like the appropriate solution for now.
