### ISSUE TITLE
Allow to build / install only static library / shared library

### ISSUE THREAD

**Issue by Arfrever** [google/re2#258]
Some users need only e.g. shared library and are not interested in static library.
(Theoretically, but less likely, there could be users needing only static library.)

Attached simple patch allows users to run one of the following:
```
make static-lib
make DESTDIR=/some/path static-lib-install
```
```
make shared-lib
make DESTDIR=/some/path shared-lib-install
```
Behavior of less-specific `make`, `make all`, `make install` commands is unchanged.

Patch: [re2.patch.txt](https://github.com/google/re2/files/4636804/re2.patch.txt)

**Comment by junyer** [comment]
Needing to build one exclusive-or the other sounds like an interesting use case, but I'm not convinced that it has to be supported upstream. You might consider using CMake instead, I suppose, because it can only build one or the other, AFAIK, not both together.

**Comment by Arfrever** [comment]
Not building/installing of static library was requested in Gentoo: https://bugs.gentoo.org/723166.
CMake build system of re2 seems to be not actively maintained, maybe it is mainly for Windows, so it would be risky to switch re2 ebuild in Gentoo to use CMake build system.
E.g. commits f734980e70ee217cc45d3e5535b47cd2422c8f4b, d067ca501c5c2d50fd672d399a2f76019e24a671, ac65d4531798ffc9bf807d1f7c09efb0eec70480 were updating soname only in `Makefile` and not in `CMakeLists.txt`.

**Comment by Arfrever** [comment]
Gentoo is not the only distribution where static libraries are avoided.
E.g. in Fedora: https://src.fedoraproject.org/rpms/re2/blob/5e1d4bdb49006ee39ca06206c3f4a3f1f312633c/f/re2.spec#_69-70

**Comment by junyer** [comment]
The `.ebuild` will able to run `make shared` and then `make shared-install` after the next release of RE2, which is a couple of weeks away.

**Comment by junyer** [comment]
Ping, @denisarnaud and @rdieter for Fedora packaging.

**Comment by denisarnaud** [comment]
Thanks for the heads up!
