### ISSUE TITLE
Library built using CMake is ABI-incompatible with library built using custom Makefile

### ISSUE THREAD

**Issue by Arfrever** [google/re2#259]
Library built using custom Makefile has soname = `libre2.so.7`.
Library built using CMake has soname = `libre2.so`.
Different sonames imply ABI incompatibility.
`SOVERSION` needs to be set in `CMakeLists.txt`.

Additionally `libre2.symbols` (or `libre2.symbols.darwin` for Darwin) is not used when using CMake, so private symbols are exposed:
```
$ diff -u <(nm -CD --with-symbol-versions libre2.so.7_built_using_Makefile | sed -e "s/^[0-9a-f]* *//" | sort) <(nm -CD --with-symbol-versions libre2.so_built_using_CMake | sed -e "s/^[0-9a-f]* *//" | sort)
--- /dev/fd/63
+++ /dev/fd/62
@@ -1,5 +1,137 @@
+B re2::hooks::context@@Base
+D re2::perl_groups@@Base
+D re2::posix_groups@@Base
+D re2::unicode_groups@@Base
 R re2::RE2::Options::kDefaultMaxMem@@Base
 R re2::StringPiece::npos@@Base
+R re2::num_perl_groups@@Base
+R re2::num_posix_groups@@Base
+R re2::num_unicode_casefold@@Base
+R re2::num_unicode_groups@@Base
…
```

**Comment by junyer** [comment]
This seems to be a case of [the XY problem](https://en.wikipedia.org/wiki/XY_problem). In https://github.com/google/re2/issues/258, you indicated that you don't want `libre2.a`. Here, you indicated that you want ABI compatibility with `libre2.so` as built by GNU make. Would you mind explaining your ~interesting~ weird use case and why it should be supported upstream?

**Comment by Arfrever** [comment]
re2 is a library needed by other packages (e.g. Chromium and QtWebEngine). `NEEDED` entry in previously built ELF files would contain value matching `SONAME` of linked library at build time, in this case `libre2.so.7`:
```
$ readelf -d /usr/lib64/libre2.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libre2.so.7]
$ readelf -d /usr/lib64/chromium-browser/chrome | grep libre2
 0x0000000000000001 (NEEDED)             Shared library: [libre2.so.7]
$ readelf -d /usr/lib64/libQt5WebEngineCore.so | grep libre2
 0x0000000000000001 (NEEDED)             Shared library: [libre2.so.7]
```
This means that for using `/usr/lib64/chromium-browser/chrome` or `/usr/lib64/libQt5WebEngineCore.so`, a `libre2.so.7` file needs to exist.

In Gentoo, we want to use a build system most often used (=> most tested) by Linux distributions.
E.g. Arch Linux, Debian, Fedora use `Makefile` and not `CMakeLists.txt`:
- Arch Linux: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/re2
- Debian: https://salsa.debian.org/debian/re2/-/blob/debian/debian/rules
- Fedora: https://src.fedoraproject.org/rpms/re2/blob/master/f/re2.spec

**Comment by junyer** [comment]
Ahh. So you are a Linux distribution package maintainer. That information is helpful to have – and having it earlier would have prevented me from suggesting CMake because that isn't intended for Linux distributions. I will close this bug and respond to your comments on https://github.com/google/re2/issues/258.
