### ISSUE TITLE
`yarn remove <package>` results in `Error: Cannot find module './build/Release/re2'`

### ISSUE THREAD

**Issue by niftylettuce** [google/re2#261]
After running `yarn remove <package>`, `re2` errors out on app reboot with this error:

```sh
Error: Cannot find module './build/Release/re2'
```

Using latest Node LTS stable and latest `re2`.  This is probably a `node-gyp` + `yarn` issue though.

**Comment by niftylettuce** [comment]
yarn@1.22.4
node@12.16.1
re2@1.14.0

**Comment by junyer** [comment]
I'm closing this issue because it doesn't appear to have anything to do with RE2 itself whereas https://github.com/yarnpkg/yarn/issues/8167 might possibly get somewhere. It's worth noting that the Node.js wrapper comes from https://github.com/uhop/node-re2/. (Ping, @uhop.)

**Comment by niftylettuce** [comment]
Ah thanks @junyer, sorry I filed in the wrong repo.  Appreciate your quick reply on a weekend.

**Comment by uhop** [comment]
If it still fails, please file a bug at https://github.com/uhop/node-re2/issues
