### ISSUE TITLE
Full case folding

### ISSUE THREAD

**Issue by lmna** [google/re2#262]
Case-insensitive matching in RE2 uses "simple" (as opposed to "full") Unicode case-folding.

RE2 documentation does not mention this aspect. User has to write a test to find it out.

Some other regex engines can do full case-folding (for instance, [ICU](http://userguide.icu-project.org/strings/regexp#TOC-Case-Insensitive-Matching) and [regex](https://pypi.org/project/regex/)). It would be awesome if RE2 could do this too.

```
#include <re2/re2.h>
#include <gtest/gtest.h>

TEST(FullCaseFolding, FullCaseFolding)
{
	RE2::Options options;
	options.set_case_sensitive(false);

	EXPECT_TRUE(RE2::FullMatch("grüßen", RE2("GRÜSSEN", options)));
	EXPECT_TRUE(RE2::FullMatch("GRÜSSEN", RE2("grüßen", options)));
}

int main(int argc, char **argv) {
	::testing::InitGoogleTest(&argc, argv);
	return RUN_ALL_TESTS();
}
```

**Comment by junyer** [comment]
My understanding is that [normalization](https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization) should typically be performed first, which would explain why case folding in RE2 is sufficient for Google's needs. OTOH, [case mapping](https://unicode.org/faq/casemap_charprop.html#casemap) is sensitive to context and language, which is why RE2 is probably never going to support it.

**Comment by lmna** [comment]
> OTOH, [case mapping](https://unicode.org/faq/casemap_charprop.html#casemap) is sensitive to context and language, which is why RE2 is probably never going to support it.

I am talking about [case folding](ftp://ftp.unicode.org/Public/UCD/latest/ucd/CaseFolding.txt), not about case mapping. Full case folding on "grüßen" and on "GRÜSSEN" produces the same string: "grüssen".

> My understanding is that [normalization](https://en.wikipedia.org/wiki/Unicode_equivalence#Normalization) should typically be performed first, which would explain why case folding in RE2 is sufficient for Google's needs. 

Normalized "grüßen" is still "grüßen", and normalized "GRÜSSEN" is still "GRÜSSEN". How normalization would help with lack of full case-folding?

One could apply full case folding both to pattern and to text even before passing them to RE2, but that approach does not work correctly. For instance, pattern "grü.en" and text "grüßen" should match, but their full-case-folded versions ("grü.en" and "grüssen") would not.

**Comment by BurntSushi** [comment]
Yeah, I don't think normalization is really related here. The fundamental problem with full case folding is that things like `.` and character classes start needing to support matching multiple codepoints. RE2 and its ilk generally assume that such things maintain a 1-to-1 correspondence with Unicode codepoints. [UTS#18 RL2.4](http://unicode.org/reports/tr18/#Default_Loose_Matches) talks a bit about this.

I think clarifying in the docs that _simple_ case folding is used (that is, [UTS#18 RL1.5](http://unicode.org/reports/tr18/#Simple_Loose_Matches)).

ICU's regex engine and Python's `regex` package are both backtracking engines. I don't know of any finite automata oriented regex engine that implements full case folding.

**Comment by junyer** [comment]
Digging into it some more, it appears that normalization and case folding is what Google tends to do when matching, indexing et cetera. (See ZetaSQL's [`NORMALIZE_AND_CASEFOLD`](https://github.com/google/zetasql/blob/master/docs/string_functions.md#normalize_and_casefold) function, for example, which handles all four normalization forms, but `NFKC` is preferred as per [`NFKC_Casefold`](http://unicode.org/reports/tr44/#NFKC_Casefold), I believe.)

**Comment by BurntSushi** [comment]
@junyer The docs for `NORMALIZE_AND_CASEFOLD` don't specify what kind of case folding it does though. It does look like `NFKC_Casefold` does full case folding, but I actually couldn't easily confirm this from the Unicode spec.

**Comment by junyer** [comment]
https://github.com/google/zetasql/blob/master/zetasql/public/functions/string.cc#L864 is calling https://github.com/unicode-org/icu/blob/master/icu4c/source/common/unicode/unistr.h#L2790, I think, and the latter's documentation suggests that full case folding is performed.

**Comment by junyer** [comment]
Oh, and for `NFKC_Casefold`, https://github.com/unicode-org/icu/blob/master/icu4c/source/data/unidata/DerivedNormalizationProps.txt#L2970 suggests that full case folding is performed.

**Comment by BurntSushi** [comment]
@junyer Indeed. But documenting that RE2 uses simple case folding seems worth it, no?

**Comment by junyer** [comment]
Fair enough.
