### ISSUE TITLE
The `google-re2` Python package fails to install when `pybind11` is installed as a python package in virtualenv.

### ISSUE THREAD

**Issue by tamaroth** [google/re2#264]
Hi,

I've come across a slight bug, I'm not entirely sure this is the correct place.

When installing the `google-re2` package, it will fail, as expected, when there is no `pybind11` package installed. There are two options for the package to be present. First is to install it in the system, for instance via `apt install pybind11-dev` command. The second is to install it as the python package. This, however, causes a problem.

If the package is installed *globally* via `pip install pybind11`, the installation of `google-re2` package succeeds everywhere. If the package is installed inside a virtualenv instead, the installation of `google-re2` package will fail with:

```
    _re2.cc:10:10: fatal error: pybind11/pybind11.h: No such file or directory
       10 | #include <pybind11/pybind11.h>
          |          ^~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```

The problem lies in the path given as a parameter to `gcc`. The commandline for compilation is as follows:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/path/to/re2/include -Wl,-rpath=/path/to/re2/lib -fPIC -I/path/to/my/project/virtualenv/include -I/home/username/.pyenv/versions/3.8.3/include/python3.8 -c _re2.cc -o build/temp.linux-x86_64-3.8/_re2.o -fvisibility=hidden
```

The issue here, is that the include path to the local virtualenv should not be `-I/path/to/my/project/virtualenv/include` but rather `-I/path/to/my/project/virtualenv/include/site/python3.8`

**Comment by junyer** [comment]
This is the correct place for `google-re2` issues. Thanks for the report!

Looking at https://github.com/pybind/python_example/blob/master/setup.py, maybe our `setup.py` should call `pybind11.get_include()` iff the `pybind11` module can be imported? Let's see...

**Comment by junyer** [comment]
I have released version 0.0.7 to PyPI. I tested it locally, but please verify that it works for you too.

**Comment by olii** [comment]
Have you considered adding `pybind11` as a project dependency?
E.g. using the `install_requires` attribute in `setuptools` or using `extras_require` arg so one can install this with `pip install google-re2[with_pybind11]`?

**Comment by tamaroth** [comment]
Works for me as well. Thanks for blistering fast response time!

**Comment by junyer** [comment]
If our dependencies were all packages from PyPI, then I would make them `setuptools.setup()`'s problem. However, given that RE2 has to be installed some other way and that pybind11 could be installed the same way, I would prefer our users to keep typing `pip install google-re2` and our `setup.py` to be just this little bit smarter.

**Comment by junyer** [comment]
Thanks for confirming, @tamaroth. Closing this issue.
