### ISSUE TITLE
How do regex "{", "}", "]", "[[]", "[]]", "a{b}", "{c}" get interpreted?

### ISSUE THREAD

**Issue by mathieucaroff** [google/re2#267]
Apparently are valid regex:

```go
package main

import (
	"fmt"
	"regexp"
)

var regexSlice = []string{"a(b)\\1", "(?=a)", "(?<=a)", "(?!a)", "(?<!a)",
	"(", ")", "{", "}", "[", "]", "(()", "())", "[[]", "[]]",
	"?", "*", "+", "{2}", "a{b}", "{c}",
}

func main() {
	var reject = []string{}

	fmt.Print("A: ")
	for _, regexString := range regexSlice {
		_, err := regexp.Compile(regexString)
		if err != nil {
			reject = append(reject, regexString)
		} else {
			fmt.Printf("\"" + regexString + "\", ")
		}
	}

	fmt.Print("\n---\nR: ")
	for _, regexString := range reject {
		fmt.Printf(regexString + ", ")
	}

	fmt.Print("\n")

	return
}
```

```
go run .
A: "{", "}", "]", "[[]", "[]]", "a{b}", "{c}", 
---
R: a(b)\1, (?=a), (?<=a), (?!a), (?<!a), (, ), [, ((), ()), ?, *, +, {2},
```

All I could find in the [documentation of the syntax](https://github.com/google/re2/wiki/Syntax) on subject is:

> To match a metacharacter, escape it with a backslash: \+ matches a literal plus character.

My guess would be that all these regex match are all interpreted as a sequence of non-metacharaters, just matching the sequence of characters they contain. But I'm not sure why `[[]` is accepted (and `]` too), but `[` is rejected.

**Comment by junyer** [comment]
Generally speaking, RE2 aims to parse pattern strings in the same way that Perl would:

`(` doesn't fall back from trying to parse a subexpression.
`[` doesn't fall back from trying to parse a character class.
`{` **_does_** fall back from trying to parse a counted repetition – and parses as the literal character `{`.

Unexpected `)` causes an error.
Unexpected `]` parses as the literal character `]`.
Unexpected `}` parses as the literal character `}`.

`[[]` parses as the character class containing the character `[`.
`[]]` parses as the character class containing the character `]`.

**Comment by junyer** [comment]
P.S. Just to be clear, RE2 and the Go `regexp` package aren't the same thing.
