### ISSUE TITLE
Remove political banner from wiki

### ISSUE THREAD

**Issue by LoganDark** [google/re2#268]
When I open the wiki for an open-source project, the first thing I want to see is not an otherwise blank page with a giant banner on it advertising a political movement.

![GIANT](https://user-images.githubusercontent.com/4723091/87573267-8274e080-c681-11ea-81fc-b2147cb47a6f.png)

I'm personally neutral towards this movement, but the giant banner is generally just an eyesore and I don't believe this is the kind of stance an open-source project should take (political stuff on the wiki).

Could you be so kind as to remove this from the wiki as I don't have permission to edit it myself?

Ty! <3

**Comment by junyer** [comment]
In this particular case, "I don't like it" doesn't constitute a convincing argument. I suggest that you install a [userscript manager](https://en.wikipedia.org/wiki/Userscript_manager).

**Comment by LoganDark** [comment]
> I suggest that you install a userscript manager.

How is that relevant? Am I supposed to devote time to writing a userscript just to block a banner on your wiki? I chose to open an issue about it instead _and then leave_, because frankly I don't have the time to spend on such trivial matters. A wiki that took itself seriously would not install such a banner. Developers that value their own time would not waste said time with a wiki that had such a banner.

I'm not going to be able to provide to you a "convincing argument" if you can't see why a [neutral point of view](https://en.wikipedia.org/wiki/Wikipedia:Npov) is beneficial to the wiki. If you'd like to stay biased because "well nobody has proven we should do otherwise", go ahead.

**Comment by junyer** [comment]
I suggested that you install a userscript manager because doing so would empower you to solve the problem for yourself. If you don't want to see the banner, then you don't have to see the banner.

**Comment by JohnnyMarnell** [comment]
@LoganDark 
`White.Silence == VIOLENCE`
`personally_neutral != guccral`

**Comment by cancelculture** [comment]
Google is dangerous and should be dismantled. White lives matter.
