### ISSUE TITLE
lookahead and lookbehind

### ISSUE THREAD

**Issue by juancafe4** [google/re2#269]
are you planning to support lookahead and lookbehind?

**Comment by junyer** [comment]
Quoting from https://github.com/google/re2/issues/255#issuecomment-615612450:

> Yes, our plan is still to support look-around assertions as soon as someone invents a technique that works with all of the execution engines (including matching in reverse for the DFA execution engine) and is linearly bounded in time and space.

A minor breakthrough in computer science will probably be needed.

**Comment by saribricka** [comment]
Any news?

**Comment by junyer** [comment]
Sorry, the situation is unlikely to change in the foreseeable future.
