### ISSUE TITLE
Get pattern from pre-compiled re2 object.

### ISSUE THREAD

**Issue by nitindeokate99** [google/re2#27]
I have requirement where I need to get pattern(in string format) from pre-compiled object. This is needed because I create pre-compiled object in main thread. And passes the object further where I use FullMatch function to do matching. But here I need to see the pattern which I am using. Is there a way to get it?

thanks
Nitin

**Comment by junyer** [comment]
Yes, this is supported:

```
  // The string specification for this RE2.  E.g.
  //   RE2 re("ab*c?d+");
  //   re.pattern();    // "ab*c?d+"
  const string& pattern() const { return pattern_; }
```

**Comment by nitindeokate99** [comment]
Thanks a lot Junyer. this is helpful

-Nitin
