### ISSUE TITLE
Can RE2 find position of the first character of the particular sub-match?

### ISSUE THREAD

**Issue by zlianon** [google/re2#270]
something like: https://en.cppreference.com/w/cpp/regex/match_results/position

**Comment by junyer** [comment]
With [`RE2::Match()`](https://github.com/google/re2/blob/master/re2/re2.h#L513-L539), the submatches are provided as `StringPiece`s (i.e. pointer–length pairs) that reference the input string. To convert the address of the beginning of a submatch into its offset from the beginning of the input string, just subtract the address of the beginning of the input string. (For example, the offset of `$0` would be `submatch[0].data() - input.data()`.)
