### ISSUE TITLE
firestore validation rule not working

### ISSUE THREAD

**Issue by Mearman** [google/re2#273]
I'm using the re2 rules in a firestore rule string match.
The following match for a general UUID based on lengths works: `"\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\b"`
But the following expression where the 12th and 16th digits are 4 and 0-B respectively does not work `\\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89aAfF]{1}[0-9a-fA-F]{3}-[0-9a-fA-F]{12}\\b`

Any suggestions?

Any example UUID I'm trying to test is `5f21cb11-f658-48ae-B7a0-5415d7b04d20`

**Comment by junyer** [comment]
`[89aAfF]` doesn't match the hexadecimal digits `0` to `B` inclusive. `[0-9a-bA-B]` does.

**Comment by Mearman** [comment]
Hahah this is what happens when you're looking the same string for so long. it shuold have been 8, 9, A, or B.
I assume it would work if I corrected my expression to `[89aAbB]`?

**Comment by junyer** [comment]
In that case, yes, `[89aAbB]` would match what you want.
