### ISSUE TITLE
Partial match call is slower than equivalent full match call

### ISSUE THREAD

**Issue by JubilantJerry** [google/re2#275]
I am observing that using `RE2::PartialMatch` with a regex compiled on `pattern` took about 60% longer on my benchmark compared to `RE2::FullMatch` with a regex compiled on `".*(" + pattern + ").*"`. In both cases, I am calling the functions without additional arguments, and was only interested in the boolean return value. `pattern` also had no capture groups.

Is there a reason why the partial match is slower (i.e. are the semantics of my two function calls actually different)?

Is it because `RE2::PartialMatch` is internally keeping track of the location of the match even though it's not accessible from the way I called the function?

If so, would it make sense to add a special case where the location of the match is not stored if the match location is not returned in the function call (i.e. by converting it into a full match call)?

I am not sure whether the pattern itself matters, but in my case it was something like `AAAA|BBBB|CCCC|DDDD|...|ZZZZ`.

I match against many lines similar to `AAAB DDDE HHHI EEEE KKKL WWWW ...`. The full match approach takes 17 seconds and the partial match approach takes 27 seconds.

**Comment by junyer** [comment]
Please provide a code snippet that reproduces the issue. I would also recommend reading [How to Report Bugs Effectively](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

In the meantime, I can say that using `RE2::FullMatch()` with leading or trailing `.*` is an antipattern, generally speaking, and that the behaviour that you describe doesn't make any sense to me. In particular, a trailing `.*` prevents RE2 from terminating execution after matching the last byte of interest, so when the remainder of the input string is relatively large, RE2 has to do a lot more work for no benefit.

**Comment by JubilantJerry** [comment]
I wasn't sure if this is a bug or just a known quirk of the system, but from what you said it looks like this behavior is unexpected, so I will treat it as a bug then.

Here is a minimal reproduction of this behavior:
```
#include <iostream>
#include <string>
#include <vector>
#include <chrono>
#include <utility>
#include "re2/re2.h"

using namespace std;
using time_point = chrono::time_point<chrono::high_resolution_clock>;

static int time_diff_us(const time_point& start, const time_point& end) {
  return chrono::duration_cast<chrono::microseconds>(end - start).count();
}

int main() {
  vector<string> lines;
  string base = "01230A 01230B 01230C 01230D 01230E 01230F 01230G 01230H "
                "01230I 01230J 01230K 01230L 01230M 01230N 01230O 01230P "
                "01230Q 01230R 01230S 01230T 01230U 01230V 01230W 01230X "
                "01230Y 01230Z 01230a 01230b 01230c 01230d 01230e 01230f "
                "01230g 01230h 01230i 01230j 01230k 01230l 01230m 01230n "
                "01230o 01230p 01230q 01230r 01230s 01230t 01230u 01230v "
                "01230w 01230x 01230y 01230z 01231A 01231B 01231C 01231D "
                "01231E 01231F 01231G 01231H 01231I 01231J 01231K 01231L "
                "01231M 01231N 01231O 01231P 01231Q 01231R 01231S 01231T "
                "01231U 01231V 01231W 01231X 01231Y 01231Z 01231a 01231b "
                "01231c 01231d 01231e 01231f 01231g 01231h 01231i 01231j "
                "01231k 01231l 01231m 01231n 01231o 01231p 01231q 01231r "
                "01231s 01231t 01231u 01231v 01231w 01231x 01231y 01231z";
  for (int i = 0; i < 104; i++) {
    string corrupt = base;
    for (int j = 0; j < 104; j++) {
      if (j != i || i % 7 != 0) {
        corrupt[7 * j + 5] = '!';
      }
    }
    lines.push_back(corrupt);
  }

  string pattern = "01230A|01230B|01230C|01230D|01230E|01230F|01230G|01230H|"
                   "01230I|01230J|01230K|01230L|01230M|01230N|01230O|01230P|"
                   "01230Q|01230R|01230S|01230T|01230U|01230V|01230W|01230X|"
                   "01230Y|01230Z|01230a|01230b|01230c|01230d|01230e|01230f|"
                   "01230g|01230h|01230i|01230j|01230k|01230l|01230m|01230n|"
                   "01230o|01230p|01230q|01230r|01230s|01230t|01230u|01230v|"
                   "01230w|01230x|01230y|01230z|01231A|01231B|01231C|01231D|"
                   "01231E|01231F|01231G|01231H|01231I|01231J|01231K|01231L|"
                   "01231M|01231N|01231O|01231P|01231Q|01231R|01231S|01231T|"
                   "01231U|01231V|01231W|01231X|01231Y|01231Z|01231a|01231b|"
                   "01231c|01231d|01231e|01231f|01231g|01231h|01231i|01231j|"
                   "01231k|01231l|01231m|01231n|01231o|01231p|01231q|01231r|"
                   "01231s|01231t|01231u|01231v|01231w|01231x|01231y|01231z";
  time_point start, end;

  RE2 re2_partial_obj(pattern);
  RE2 re2_full_obj(".*(" + pattern + ").*");

  int re2_matches = 0;
  start = chrono::high_resolution_clock::now();
  for (int i = 0; i < 1000; i++) {
    for (const string& line: lines) {
      re2_matches += RE2::PartialMatch(line, re2_partial_obj);
    }
  }
  end = chrono::high_resolution_clock::now();
  cout << "Partial: " << re2_matches << " matches, " <<
    time_diff_us(start, end) << "us" << endl;

  re2_matches = 0;
  start = chrono::high_resolution_clock::now();
  for (int i = 0; i < 1000; i++) {
    for (const string& line: lines) {
      re2_matches += RE2::FullMatch(line, re2_full_obj);
    }
  }
  end = chrono::high_resolution_clock::now();
  cout << "Full:    " << re2_matches << " matches, " <<
       time_diff_us(start, end) << "us" << endl;

  return 0;
}
```

The output:
```
Partial: 15000 matches, 178627us
Full:    15000 matches, 124253us
```

It looks like the issue is not as clear and cut as I thought. I needed to use larger patterns and set the probability of a match to be pretty low, otherwise the partial match method did indeed perform better.

My guess is that if it weren't for the short circuiting mentioned in your reply, the partial matching approach is slower than the full matching approach.

Other information:

The system I run:
```
Macbook Pro 16 inch, 2019
Catalina 10.15.6
RAM: 16 GB
```

The processor:
```
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

Compiler information:
```
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

It is compiling with `-O3, -std=gnu++14`

**Comment by junyer** [comment]
The pattern for `RE2::PartialMatch()` factorises to `0123(?:0[A-Za-z]|1[A-Za-z])`, so RE2 uses `memchr(3)` to search for `0`, but that optimisation becomes a pessimisation when the rate of false positives is too high. The pattern for `RE2::FullMatch()` factorises similarly, but it has a leading `.*`, so RE2 can't use `memchr(3)`.
