### ISSUE TITLE
Regular expression to match a line that doesn't contain a character

### ISSUE THREAD

**Issue by AndroidNils** [google/re2#276]
My goal to write a regular expression for this cases (does not contain a `/`):
`foo/` --> ❌
`/` --> ❌
`/sdfsdf` --> ❌
`sdfsad/sdfsdf` --> ❌
`foo` --> ✅

With PCRE I would do this: `^((?!\/).)*$`. But in RE2 there is no negative lookahead (#156).

**Comment by junyer** [comment]
`^[^/]*$` would be the conventional solution.

**Comment by fhaque-wish** [comment]
Is this possible for a word i.e. does not contain word "bar"

**Comment by DesireWithin** [comment]
what shoud i do if I don't want to match a word?

**Comment by junyer** [comment]
Handling negation at the application level is typically clearer and easier. For example, consider `grep -v word` as opposed to absolutely anything else.

**Comment by miguelcb84** [comment]
I agree, but in case you cannot negate at the application level the best-effort approach would be something like

`^.*(?<!word)$`

or

`^(?!word).*$`

**Comment by rsc** [comment]
Those patterns match "every string except word". They do not match "every string that does not contain word" (grep -v word).

**Comment by junyer** [comment]
Mixing `.*` (whether implicit or explicit) with look-around assertions is fraught, generally speaking, principally because users struggle to reason about it. Even if I personally could encode my intent correctly every time, I would rather express my intent at a higher level – more clearly, more simply, possibly more efficiently – if only for the sake of future readers and maintainers.

**Comment by pkit** [comment]
@junyer I agree with the idea that library should be fast. But then all the people who introduce "use regex" functionality into their "go-based" products should always have negation too.

Unfortunately that's not even remotely the case. For example I struggle to find any `NotRegularExpression` rules in the kubernetes code while `RegularExpression` is everywhere.
