### ISSUE TITLE
CMake install missing pkg-config

### ISSUE THREAD

**Issue by SMillerDev** [google/re2#277]
When using CMake to install the library there is no pkg-config support and when using make there is no CMake support.

Would you be willing to add pkg-config to the CMake build or are these intentionally seperate?

**Comment by junyer** [comment]
This came up in https://github.com/google/re2/issues/215 and then again in https://github.com/google/re2/issues/274. In the latter case, the consensus was that gRPC should find RE2 via `pkg-config`. With recent versions of CMake, creating an imported target named `PkgConfig::RE2` automagically takes only a couple of lines! Pushing CMake users to find RE2 via `pkg-config` is the right thing to do, IMO, and I'm willing to help if that's what it takes. :)

**Comment by gyakovlev** [comment]
maybe some finds this grpc patch useful
very simple indeed
https://github.com/gentoo/gentoo/blob/f4a04a5c28a13f2d5453847701a43572c5847d8f/net-libs/grpc/files/use-pkg-config-to-find-re2.patch

**Comment by junyer** [comment]
https://github.com/grpc/grpc/commit/52299822737ef4d4418296695dc061575f10f5f3 will be in the next release of gRPC. :)
