### ISSUE TITLE
Minor leaks at initialisation

### ISSUE THREAD

**Issue by marmeladema** [google/re2#28]
Hi all,

I've noticed some minor leaks because of RE2 initialisation mechanism :

```
// static empty things for use as const references.
// To avoid global constructors, initialized on demand.
GLOBAL_MUTEX(empty_mutex);
static const string *empty_string;
static const map<string, int> *empty_named_groups;
static const map<int, string> *empty_group_names;

static void InitEmpty() {
  GLOBAL_MUTEX_LOCK(empty_mutex);
  if (empty_string == NULL) {
    empty_string = new string;
    empty_named_groups = new map<string, int>;
    empty_group_names = new map<int, string>;
  }
  GLOBAL_MUTEX_UNLOCK(empty_mutex);
}
```

Those three allocated objects are never freed, or maybe i did not find a way to do it ...
Wouldn't it be better to have those three objects in the RE2 object ? So that it can be properly freed during destructor.
I know that it would increase RE2 objects' size a little bit but imo it is worthwhile.
It would also remove the need for a global mutex here.

I can provide a patch if needed :)

**Comment by junyer** [comment]
It's true that the objects exist until program termination, but it's also true that their addresses are known – and needed – until program termination, so they aren't leaked. I'll admit that their lazy initialisation is kind of clunky, but we can't just use `std::call_once()` because that would require C++11.

**Comment by marmeladema** [comment]
Why close this "bug" ?
I know that those objects are not really leaked but it is a bit annoying when you use memory leak tools like valgrind and co.
And i don't really see the point in having global objects protected by a global mutex here but you're the maintainer :)
Putting those three little objects in the re2 object seems wrong to you ?

Thanks anyway for answering, I will eventually fork it.

**Comment by junyer** [comment]
You could generate a suppressions file for Valgrind?

For better or worse, RE2 has a lot of little tweaks like this that were measurably helpful when the code was written, so my inclination is to leave them there unless they are measurably harmful nowadays.

**Comment by junyer** [comment]
I'm going to land a fix to avoid "immortal" dynamic memory allocations.
