### ISSUE TITLE
`\pN` not working in Google Sheets

### ISSUE THREAD

**Issue by togume** [google/re2#284]
Hi there! `\p{L}+` doesn't work in Google Sheets REGEXTRACT. Is there something I'm missing?

**Comment by junyer** [comment]
Please reproduce the problem in a new, separate spreadsheet and then link to that spreadsheet here.

**Comment by togume** [comment]
@junyer sure thing: https://docs.google.com/spreadsheets/d/1rK0zYP2Xuj69qNX-sUcKtehhgb0zT8A6QoJzjsqhNS0/edit?usp=sharing

**Comment by junyer** [comment]
Thanks for doing that! I was looking into this and feeling quite baffled until I finally checked the [`REGEXEXTRACT` documentation](https://support.google.com/docs/answer/3098244), which says: "Google Sheets supports RE2 except Unicode character class matching." Sorry. :(

**Comment by togume** [comment]
:'( - I missed that, too. Thanks for getting to the bottom of this, @junyer. It's sad that neither `\w` works for international strings and `\p` doesn't either.

In case someone finds their way here, this is what worked for snagging words with international characters: `[A-Za-zÀ-ÖØ-öø-ÿ]*`
