### ISSUE TITLE
unable to install on debian 10

### ISSUE THREAD

**Issue by jefimm** [google/re2#285]
pip3 install google-re2

```
gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
# dpkg -l | grep libre2
ii  libre2-5:amd64                        20190101+dfsg-2              amd64        efficient, principled regular expression library
ii  libre2-dev:amd64                      20190101+dfsg-2              amd64        efficient, principled regular expression library, development kit
```

`pip3 install google-re2
Collecting google-re2
  Using cached google-re2-0.0.7.tar.gz (8.7 kB)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from google-re2) (1.15.0)
Building wheels for collected packages: google-re2
  Building wheel for google-re2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fhoggatd
       cwd: /tmp/pip-install-ft06pwtd/google-re2/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  copying re2.py -> build/lib.linux-x86_64-3.7
  running build_ext
  building '_re2' extension
  creating build/temp.linux-x86_64-3.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.7/dist-packages/pybind11/include -I/usr/include/python3.7m -c _re2.cc -o build/temp.linux-x86_64-3.7/_re2.o -fvisibility=hidden
  _re2.cc: In function 'std::vector<int> re2_python::RE2ProgramFanoutShim(const re2::RE2&)':
  _re2.cc:91:32: error: no matching function for call to 're2::RE2::ProgramFanout(std::vector<int>*) const'
     self.ProgramFanout(&histogram);
                                  ^
  In file included from /usr/include/re2/filtered_re2.h:27,
                   from _re2.cc:13:
  /usr/include/re2/re2.h:296:7: note: candidate: 'int re2::RE2::ProgramFanout(std::map<int, int>*) const'
     int ProgramFanout(std::map<int, int>* histogram) const;
         ^~~~~~~~~~~~~
  /usr/include/re2/re2.h:296:7: note:   no known conversion for argument 1 from 'std::vector<int>*' to 'std::map<int, int>*'
  _re2.cc: In function 'std::vector<int> re2_python::RE2ReverseProgramFanoutShim(const re2::RE2&)':
  _re2.cc:97:39: error: no matching function for call to 're2::RE2::ReverseProgramFanout(std::vector<int>*) const'
     self.ReverseProgramFanout(&histogram);
                                         ^
  In file included from /usr/include/re2/filtered_re2.h:27,
                   from _re2.cc:13:
  /usr/include/re2/re2.h:297:7: note: candidate: 'int re2::RE2::ReverseProgramFanout(std::map<int, int>*) const'
     int ReverseProgramFanout(std::map<int, int>* histogram) const;
         ^~~~~~~~~~~~~~~~~~~~
  /usr/include/re2/re2.h:297:7: note:   no known conversion for argument 1 from 'std::vector<int>*' to 'std::map<int, int>*'
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for google-re2
  Running setup.py clean for google-re2
Failed to build google-re2
Installing collected packages: google-re2
    Running setup.py install for google-re2 ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wvtx0osj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/google-re2
         cwd: /tmp/pip-install-ft06pwtd/google-re2/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    copying re2.py -> build/lib.linux-x86_64-3.7
    running build_ext
    building '_re2' extension
    creating build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.7/dist-packages/pybind11/include -I/usr/include/python3.7m -c _re2.cc -o build/temp.linux-x86_64-3.7/_re2.o -fvisibility=hidden
    _re2.cc: In function 'std::vector<int> re2_python::RE2ProgramFanoutShim(const re2::RE2&)':
    _re2.cc:91:32: error: no matching function for call to 're2::RE2::ProgramFanout(std::vector<int>*) const'
       self.ProgramFanout(&histogram);
                                    ^
    In file included from /usr/include/re2/filtered_re2.h:27,
                     from _re2.cc:13:
    /usr/include/re2/re2.h:296:7: note: candidate: 'int re2::RE2::ProgramFanout(std::map<int, int>*) const'
       int ProgramFanout(std::map<int, int>* histogram) const;
           ^~~~~~~~~~~~~
    /usr/include/re2/re2.h:296:7: note:   no known conversion for argument 1 from 'std::vector<int>*' to 'std::map<int, int>*'
    _re2.cc: In function 'std::vector<int> re2_python::RE2ReverseProgramFanoutShim(const re2::RE2&)':
    _re2.cc:97:39: error: no matching function for call to 're2::RE2::ReverseProgramFanout(std::vector<int>*) const'
       self.ReverseProgramFanout(&histogram);
                                           ^
    In file included from /usr/include/re2/filtered_re2.h:27,
                     from _re2.cc:13:
    /usr/include/re2/re2.h:297:7: note: candidate: 'int re2::RE2::ReverseProgramFanout(std::map<int, int>*) const'
       int ReverseProgramFanout(std::map<int, int>* histogram) const;
           ^~~~~~~~~~~~~~~~~~~~
    /usr/include/re2/re2.h:297:7: note:   no known conversion for argument 1 from 'std::vector<int>*' to 'std::map<int, int>*'
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ft06pwtd/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wvtx0osj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/google-re2 Check the logs for full command output.`

**Comment by junyer** [comment]
Debian 10 ("buster") ships RE2 release `2019-01-01`, unfortunately, whereas the fanout API changed in RE2 release `2020-05-01`. Pinning to `google-re2` version `0.0.5` is probably your best option for now unless you want to install a newer RE2 release manually. :(

**Comment by TimothyBramlett** [comment]
@junyer I am running into a similar error on Ubuntu 18.04.  By "install manually" do you mean to download the repo and compile it, etc.?

**Comment by junyer** [comment]
Indeed, I meant building from source (having cloned the repository or downloaded a `.zip` file) and then installing under `/usr/local` or similar.
