### ISSUE TITLE
Invalid Perl Operator

### ISSUE THREAD

**Issue by dhakrasp** [google/re2#288]
I  have successfully installed google/re2 C/C++ library and successfully installed the google-re2 python package.
I am able to compile and run simple regular expressions with re2 in Python 3.8 however for certain more complex regexes the compilation fails. 
Below is a sample of my code.
```
import re2

# works
re2.compile(r'^[\W0-9]*\w*[\W0-9]*(harry|john|sarah|liza)')

# fails
re2.compile(r'^[\W0-9]*\w*[\W0-9]*(harry|john|sarah|liza)[\s:#-]+(?!,)')

# Error thrown
# re2.error: b'invalid perl operator: (?!'
```

Is there a solution/workaround/hack for this problem?

**Comment by junyer** [comment]
RE2 doesn't support look-around assertions. For this particular case, you could try `(?:$|[^,])` as an alternative to `(?!,)`.

**Comment by junyer** [comment]
P.S. For a guide to what syntax is and isn't supported, please refer to https://github.com/google/re2/wiki/Syntax.
