### ISSUE TITLE
Match performance regression due to a change in prefix handling

### ISSUE THREAD

**Issue by zeux** [google/re2#289]
During re2 update from 2020-04 to 2020-11 I've discovered a substantial performance regression on one of the test regular expressions in my application.

Here's the regex: `(vk?)CmdDrawNoop`
In context of a MT workload that has regex matching as a bottleneck, 2020-04 version ran in 0.45 sec matching ~1.3 GB of data (over multiple threads); 2020-11 version runs in ~2.75 sec on the same data set.

I've bisected the issue to commit 75220ad07cb24ecfa20c9cebed39f1f98fb079cf. Before this commit, regex matching uses memchr to do quick scanning of the prefix - presumably looking for `v`. After this commit, the bulk of profiling samples land in re2::DFA::InlinedSearchLoop.

**Comment by junyer** [comment]
Thanks for the report! `RequiredPrefixForAccel()` doesn't "see through" capturing groups whereas the previous computation did, so that certainly explains the difference in behaviour for `(vk?)CmdDrawNoop`. I will figure out how to correct for that. :)
