### ISSUE TITLE
Windows version detection is incorrect which leads to significant perf issues in MT environment

### ISSUE THREAD

**Issue by zeux** [google/re2#290]
Change 2695ecfed0bf7f530a3646abf8803df5ef62cfc9 wrapped the usage of SRW locks in a conditional section based on WINVER.

This change results in significant performance issues in a RE2 Windows build for me. The issue is that WINVER define is defined by `windows.h` which is *not* included before the guard in `mutex.h`; thus projects that externally define WINVER can get SRW locks but by default the SRW locks end up being disabled.

My understanding is that this project doesn't accept PRs via GitHub - would it be possible to fix this? The change is rather trivial:

```
diff --git a/util/mutex.h b/util/mutex.h
index e2a8715..e6ba000 100644
--- a/util/mutex.h
+++ b/util/mutex.h
@@ -12,6 +12,7 @@
 
 #ifdef _WIN32
 // Requires Windows Vista or Windows Server 2008 at minimum.
+#include <windows.h> // defines WINVER
 #if defined(WINVER) && WINVER >= 0x0600
 #define MUTEX_IS_WIN32_SRWLOCK
 #endif
@@ -26,7 +27,6 @@
 #endif
 
 #if defined(MUTEX_IS_WIN32_SRWLOCK)
-#include <windows.h>
 typedef SRWLOCK MutexType;
 #elif defined(MUTEX_IS_PTHREAD_RWLOCK)
 #include <pthread.h>
```

**Comment by junyer** [comment]
Thanks for catching that mistake!
