### ISSUE TITLE
How do I need to whitelist a link with dynamic alphanumeric parameter at the end

### ISSUE THREAD

**Issue by vineelk8** [google/re2#291]
Hi, need to add a URL pattern in the firebase console for dynamic link generation. My requirement is while generating the short link using the [REST API](https://firebase.google.com/docs/dynamic-links/rest) method I'm adding a deep link with dynamic userID generated and attached as a query parameter at the last of the deep link.

I need to whitelist with an alphanumeric. How do I need to add a regular expression which allows alphanumeric?

**Example:**

**https://www.example.com?userId=5f7330w6b347150004351f529**

**Comment by junyer** [comment]
Please contact [Firebase Support](https://firebase.google.com/support) for help with your issue.

**Comment by vineelk8** [comment]
Hi @junyer do you have any idea on this?
