### ISSUE TITLE
re2 cannot be embedded with FetchContent into other CMake projects

### ISSUE THREAD

**Issue by eel76** [google/re2#292]
I want to embed the re2 project as a sub-project in my CMake project, i.e. do an `add_subdirectory(re2_source_directory)` first and then use the re2 targets directly in my `CMakeLists.txt`.

I do not store the re2 sources side by side in my repository but use CMake's `FetchContent` module instead.

So after
```
include(FetchContent)
FetchContent_Declare(
  re2_content
  GIT_REPOSITORY "https://github.com/google/re2.git"
  GIT_TAG "2020-11-01"
  GIT_SHALLOW TRUE
  )
FetchContent_MakeAvailable(re2_content)
```
i should be able to:
```
target_link_libraries (my_target PRIVATE re2::re2)
```
However, re2 header files are not found.

My working hotfix is to change the interface include directories of the re2 target manually:
```
target_include_directories (re2 INTERFACE $<BUILD_INTERFACE:${re2_content_SOURCE_DIR}>)
```
Then everything (including linking) works as expected, so it's only about the missing include directories.

**Comment by junyer** [comment]
Many thanks for the patch!
