### ISSUE TITLE
ImportError (python google-re2)

### ISSUE THREAD

**Issue by ultrabear** [google/re2#295]
The wheels failed to build when running pip so I compiled re2 from source and the pip wheels installed but on running the module in python it gave the following error
```
>>> import re2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/$$$/local/lib/python3.8/site-packages/re2.py", line 32, in <module>
    import _re2
ImportError: /home/$$$/.local/lib/python3.8/site-packages/_re2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3re23RE213ProgramFanoutEPSt6vectorIiSaIiEE
```
Python 3.8.5, Ubuntu 20.04 LTS

**Comment by junyer** [comment]
Ubuntu 20.04 ("focal") ships RE2 release `2020-01-01`, unfortunately, whereas the fanout API changed in RE2 release `2020-05-01`. Pinning to `google-re2` version `0.0.5` is probably your best option for now unless you want to install a newer RE2 release manually. :(
