### ISSUE TITLE
Matching decomposed forms of Korean characters?

### ISSUE THREAD

**Issue by vadim-berman** [google/re2#297]
Hello Re2 team,

We are trying to match the decomposed forms of Hangul characters. For example, when the input is **랙**, we want the re2 library to view it as **ㄹㅏㄱ**, and return _true_ when executing `FullMatch` with **.+ㄱ** as a regex. 

Is there a way to match the decomposed forms?

**Comment by junyer** [comment]
No, RE2 performs neither composition nor decomposition. Your code would have to handle those separately from matching.

**Comment by BurntSushi** [comment]
If you put your haystack in decomposed form, then your regex should work.

**Comment by vadim-berman** [comment]
@BurntSushi, thank you for your reply. Can you please elaborate?

**Comment by BurntSushi** [comment]
I'm not sure what you want me to elaborate on. If your haystack is in decomposed form, then `.` will match each of the decomposed codepoints. Why not try it?

**Comment by vadim-berman** [comment]
Oh, so you mean I need to convert it to NFD or NFKD, understood. 

It's just in C++, I'll need to find a library that decomposes the string.

**Comment by junyer** [comment]
For C++, [ICU](https://en.wikipedia.org/wiki/International_Components_for_Unicode) is likely your best bet.
