### ISSUE TITLE
Warning Case of null pointer dereference 

### ISSUE THREAD

**Issue by kashirin-alex** [google/re2#298]
_gcc (GCC) 9.3.0 at a static-linkage:_
linking-flags: 
`-Werror=null-dereference -O3 -flto -fuse-linker-plugin -ffat-lto-objects  -Wl,--whole-archive libre2.a -Wl,--no-whole-archive`
```bash
re2/re2.cc: In member function ‘DoMatch.constprop’:
re2/nfa.cc:606:47: error: null pointer dereference [-Werror=null-dereference]
  606 |       swap(nextq, runq);
      |                                               ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/local/bin/c++ returned 1 exit status
compilation terminated.
/usr/local/bin/ld: error: lto-wrapper failed
```
while rest of the Warning flags used are: 
`-Wall -Werror -Wextra -Wpedantic -Wformat -Wformat-security -Wnoexcept -Wcast-align -Wuseless-cast -Wold-style-cast -Wsuggest-override -Wnon-virtual-dtor -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wstrict-null-sentinel -Wzero-as-null-pointer-constant`

The size check seems to be not enough in the check to confront the state of both pointers  `runq` and `nextq`.
https://github.com/google/re2/blob/37fabb4dbd62218a92b62c2a380857e8bdfd236f/re2/nfa.cc#L532

https://github.com/google/re2/blob/37fabb4dbd62218a92b62c2a380857e8bdfd236f/re2/nfa.cc#L606

**Comment by junyer** [comment]
> The size check seems to be not enough in the check to confront the state of both pointers `runq` and `nextq`.

Sorry, I'm not sure what you mean. `runq` and `nextq` are pointers that are never null. But even if one or both were null, that still wouldn't matter for the purposes of `std::swap()`. So this `null-dereference` error makes no sense to me at all because these pointers are neither null nor dereferenced at line 606.

Is it possible that there's a bug in LTO that's breaking the `.constprop` version of the function? Can you reproduce this error with other versions of GCC? Are you able to dump the `.constprop` version of the function in some human-readable format?

**Comment by kashirin-alex** [comment]
The results/warnings are different with gcc (GCC) 10.2.0 (the current gcc of Archlinux)
the libre2.a was build as well (Archlinux package exclude the archive-library)
```bash
/root/s/re2/re2/regexp.cc: In member function ‘GetCharClass’:
/root/s/re2/re2/regexp.cc:921:16: warning: potential null pointer dereference [-Wnull-dereference]
  921 |   cc->nranges_ = 0;
      |                ^
/root/s/re2/re2/regexp.cc:922:20: warning: potential null pointer dereference [-Wnull-dereference]
  922 |   cc->folds_ascii_ = false;
      |                    ^
/root/s/re2/re2/regexp.cc:923:15: warning: potential null pointer dereference [-Wnull-dereference]
  923 |   cc->nrunes_ = 0;
      |               ^
/root/s/re2/re2/regexp.cc:920:15: warning: potential null pointer dereference [-Wnull-dereference]
  920 |   cc->ranges_ = reinterpret_cast<RuneRange*>(data + sizeof *cc);
      |               ^
/root/s/re2/re2/re2.cc: In member function ‘DoMatch.constprop’:
/root/s/re2/re2/nfa.cc:603:47: warning: null pointer dereference [-Wnull-dereference]
  603 |       (void)Step(runq, nextq, p < etext_ ? p[0] & 0xFF : -1, context, p);
      | 
```

It is clearly possible to notice , the `p < etext_` is  True unless `etext_` is NULL, as scope is based on ` if (p == NULL) {`

I'll try and post the actual functions used by the LTO for both builds with GCC 9.3 & 10.2 , (recommendation is welcomed on this)
and By The Way the main use case is the https://github.com/kashirin-alex/swc-db/blob/90ea1a2c680a7afd67c8b767a43898a951edb361/src/cc/include/swcdb/core/Comparators.h#L503

**Comment by junyer** [comment]
Ahh. Yes, I concur that line 603 of `nfa.cc` looks like the real culprit. I will get that code fixed.

I'm not sure why GCC is upset about lines 920–923 of `regexp.cc`, but I will improve that code as well.

**Comment by kashirin-alex** [comment]
the related to `cc->` access
Considering the struct index access is OK, It is just to change the `CharClass::New(int maxranges)` to unsigned `CharClass::New(uint32_t maxranges)` which would invalidate the input from being a negative and avoid the possibility of Zero-Byte allocation case.
https://github.com/google/re2/blob/37fabb4dbd62218a92b62c2a380857e8bdfd236f/re2/regexp.cc#L922
https://github.com/google/re2/blob/37fabb4dbd62218a92b62c2a380857e8bdfd236f/re2/regexp.cc#L924
with the change to unsigned `maxranges`, the remaining warning is the `p`:
```cpp
/root/s/re2/re2/re2.cc: In member function ‘DoMatch.constprop’:
/root/s/re2/re2/nfa.cc:603:47: warning: null pointer dereference [-Wnull-dereference]
  603 |       (void)Step(runq, nextq, p < etext_ ? p[0] & 0xFF : -1, context, p);
      |       
```

-- as to LTO, sometimes precision of it's report is just around the possibility, so far for me, there was always something to adjust over probability or even find a need for a fix.

**Comment by junyer** [comment]
Thank you very much for your great help with this!

**Comment by stefanor** [comment]
@junyer: I don't think this change required a SONAME bump, the symbol that changed wasn't part of the library's public ABI.
