### ISSUE TITLE
Unnecessary SONAME bump

### ISSUE THREAD

**Issue by stefanor** [google/re2#299]
The SONAME bump in d2f86cad1fbf75b8e524c3c257d4470d047d4456 was unnecessary, I think.

The symbol was in not one of the ones that we expose in the shared library. See `libre2.symbols` for the filtering.

We should be able to go back to SONAME=9, without any issues.

**Comment by junyer** [comment]
Thanks, great catch! `CharClass` is exposed within the Google codebase (for historical reasons) and I had neglected to think about whether it was exposed within the open source project before bumping `SONAME`. :(

**Comment by junyer** [comment]
Tagged `2021-02-02`.

**Comment by foutrelis** [comment]
Please consider skipping `10` when you need to bump it again, to avoid any confusion with `2021-02-01`.

**Comment by junyer** [comment]
I will endeavour to remember. Please yell at me if I forget. :)
