### ISSUE TITLE
Syntax page neglects several flags

### ISSUE THREAD

**Issue by doherty** [google/re2#3]
Originally reported Sep 24, 2014.

What steps will reproduce the problem?

1. Observe the list of flags supported in Perl
2. Observe the list of flags documented for RE2

What is the expected output? What do you see instead?

I expected the Perl flags to be mentioned in RE2's documentation. In particular, I was interested in /x because it is so so useful.

**Comment by junyer** [comment]
The `i`, `m` and `s` modifiers have been supported (and documented) for a long time. The `x` modifier could be supported someday, I guess, but it's arguably unnecessary in C++.
