### ISSUE TITLE
Visual Studio 2013 build fails: error C4996: 'write': The POSIX name for this item is deprecated.

### ISSUE THREAD

**Issue by ariccio** [google/re2#30]
[logging.h:59](https://github.com/google/re2/blob/master/util/logging.h#L58) generates:
```
Error	C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
```
The problem is that the line:

```
if(write(2, s.data(), n) < 0) {}  // shut up gcc
```
...uses [`write`](https://msdn.microsoft.com/en-us/library/ms235320.aspx), not [`_write`](https://msdn.microsoft.com/en-us/library/1570wh78.aspx).

**Comment by junyer** [comment]
@nico @tfarina Should I just `#define write _write` on Windows? Or would that break other builds?

**Comment by junyer** [comment]
Actually, that would break this code:

```
std::ostream& operator<<(std::ostream& o, const StringPiece& piece) {
  o.write(piece.data(), piece.size());
  return o;
}
```

I'll rephrase: Should I just call `_write` on Windows? ;)

**Comment by ariccio** [comment]
Chromium's `logging.h` actually *does* just `#define` a `_write`->`write` macro, but it `#undef _write`'s afterwards.

**Comment by junyer** [comment]
There's only one call, so I'll just `#ifdef WIN32` the line itself.

**Comment by nico** [comment]
I commented on the review but maybe you didn't see it: Could you use fwrite(stderr) instead of write(2)?

**Comment by junyer** [comment]
Sorry, I'd missed that!

> Could this just call fprintf(stderr, ...)? Is that not done because
> you want to print NULL bytes? In that case, could you call fwrite with
> stderr? If it requires these conditionals to call write, maybe this
> should just use standard c functions?

NUL bytes should not be a problem because we should be using `CEscape()` whenever we might not have printable characters.

Given that the logging code uses `std::ostringstream` already, it's tempting to use `std::cerr` as well, but then `fprintf(stderr, …);` has been used for debugging output in other places. Do you have any particular feelings about this, @rsc?

**Comment by nico** [comment]
std::cerr requires including iostream which adds static intializers, so that's no good.

**Comment by junyer** [comment]
Fair enough. I ended up opting for `fwrite` because NUL-terminating the string looked a bit naff.
