### ISSUE TITLE
undefined reference to `re2::RE2::RE2(std::string const&)`

### ISSUE THREAD

**Issue by imagineer258** [google/re2#303]
i installed re2 with apt-get install and also tried installing it from source, but in both cases when linking with cmake using : 
```
target_link_libraries(infer -Wl,--no-as-needed re2)
```
I get the below error 
```
infer.cpp:(.text+0x533): undefined reference to `re2::RE2::RE2(std::string const&)'
CMakeFiles/infer.dir/infer.cpp.o: In function `torchtext::RegexTokenizer::forward(std::string) const':
infer.cpp:(.text+0x72d): undefined reference to `re2::RE2::GlobalReplace(std::string*, re2::RE2 const&, re2::StringPiece const&)'
```
Not sure if this is an issue related to re2 or if I'm doing something wrong. Appreciate any tips on how to debug. 

Thank you very much.

**Comment by junyer** [comment]
Can you try building with `make VERBOSE=1`? What's the exact linker command that's failing?

**Comment by junyer** [comment]
Also, I'm a little dubious about the usefulness of `-Wl,--no-as-needed` there. Can you try removing it?

**Comment by imagineer258** [comment]
Thank you very much for your quick response. 

Below is the linking command when I run with `VERBOSE=1`. Running by removing  `-Wl,--no-as-needed` works in that it generates the executable correctly however its throws an `Unknown type name` error when I run the executable. 
```
/usr/bin/c++  -fPIC  -rdynamic CMakeFiles/infer.dir/infer.cpp.o  -o infer -Wl,-rpath,/home/imagineer/ML/tokenizer/libtorch/lib:/home/imagineer/ML/tokenizer/build/tokenizer:/home/imagineer/miniconda3/envs/ML_3.7/lib -Wl,--no-as-needed tokenizer/libtokenizer.so ../tokenizer/libtorch/lib/libtorch_python.so -lre2 
```

However, commenting out the two lines related to below and removing references to them in my infer.cpp file

```
infer.cpp:(.text+0x533): undefined reference to `re2::RE2::RE2(std::string const&)'
infer.cpp:(.text+0x72d): undefined reference to `re2::RE2::GlobalReplace(std::string*, re2::RE2 const&, re2::StringPiece const&)'
```
works even with `-Wl,--no-as-needed` and the executable runs correctly. So, for some reason even though there is lre2 in the link command it throws an undefined reference error.

**Comment by imagineer258** [comment]
I got the same undefined reference error even when I used pcre inplace of re2. I'm closing this because this issue is not specific to re2.

(I was able to debug with help from here : https://github.com/Linuxbrew/legacy-linuxbrew/issues/1055)

Thanks again for your attention.

**Comment by junyer** [comment]
Thanks for the link. That reminded me that you might need to ensure that everything is built with the same C++ version. (RE2 is typically built with C++11.)

Can you try adding this to your `CMakeLists.txt` file?

```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by imagineer258** [comment]
I tried the above commands but it throws a lot of errors while compiling. Maybe I'm not using the right set of packages for the above commands to work. Libtorch is one of the dependencies of my project, I was able to build and use the executable correctly after downloading the cxx11 ABI libtorch version.

Thanks again very much for your help.
