### ISSUE TITLE
How do I return the grouping using RE2?

### ISSUE THREAD

**Issue by eddynaka** [google/re2#305]
Hi,

Below a dummy regex:
```
(?i)(?P<g1>b).(?P<g2>d)
```

And, below, a dummy text:
```
abcde
```

How do I use RE2 to retrieve the groups `g1` and `g2`?

**Comment by junyer** [comment]
Here's a code fragment to get you started:

```
const int nsubmatch = re.NumberOfCapturingGroups() + 1;  // need $0
std::vector<re2::StringPiece> submatch(nsubmatch);
if (re.Match(text, 0, text.size(), RE2::UNANCHORED, submatch.data(), nsubmatch)) {
```

You can look up the `"g1"` and `"g2"` keys in the `re.NamedCapturingGroups()` map and use the values to index into `submatch`.

**Comment by eddynaka** [comment]
Thank you :)
