### ISSUE TITLE
Japanese "Chōonpu" (ー, ｰ) is not a part of Hiragana or Katakana script class names

### ISSUE THREAD

**Issue by whalderman** [google/re2#308]
Both the [Hiragana ](https://github.com/google/re2/blob/13ebb377c6ad763ca61d12dd6f88b1126bd0b911/re2/unicode_groups.cc#L5458-L5461) and [Katakana](https://github.com/google/re2/blob/13ebb377c6ad763ca61d12dd6f88b1126bd0b911/re2/unicode_groups.cc#L5535-L5543) unicode groups are missing the Japanese [Chōonpu](https://en.wikipedia.org/wiki/Ch%C5%8Donpu).

Full-width (ー) unicode decimal: 12540
Half-width (ｰ) unicode decimal: 65392

With Google recently implementing RE2 in Google Search Console to filter Queries and Pages, I noticed that neither script class name included this common mark. Considering how often it's used, along with its purpose of forming words (rather than a compound word equivalent), I expected it to be a part of both unicode groups.

Should this be added to both unicode groups? I'm curious to hear the reasoning if not.

**Comment by junyer** [comment]
U+30FC and U+FF70 are in script `Common`; matching them with hiragana or katakana depends on script extensions and so you have to write `\p{scx=Hira}` or `\p{scx=Kata}`, respectively.
