### ISSUE TITLE
ld: fatal: unrecognized option '--version-script=libre2.symbols'

### ISSUE THREAD

**Issue by DrLou** [google/re2#31]
With REBUILD_FILES=1 set:

$ make
...
g++ -shared -Wl,-soname,libre2.so.0,--version-script=libre2.symbols -pthread -o obj/so/libre2.so.0 obj/so/util/hash.o obj/so/util/rune.o obj/so/util/stringprintf.o obj/so/util/strutil.o obj/so/util/valgrind.o obj/so/re2/bitstate.o obj/so/re2/compile.o obj/so/re2/dfa.o obj/so/re2/filtered_re2.o obj/so/re2/mimics_pcre.o obj/so/re2/nfa.o obj/so/re2/onepass.o obj/so/re2/parse.o obj/so/re2/perl_groups.o obj/so/re2/prefilter.o obj/so/re2/prefilter_tree.o obj/so/re2/prog.o obj/so/re2/re2.o obj/so/re2/regexp.o obj/so/re2/set.o obj/so/re2/simplify.o obj/so/re2/stringpiece.o obj/so/re2/tostring.o obj/so/re2/unicode_casefold.o obj/so/re2/unicode_groups.o
ld: fatal: unrecognized option '--version-script=libre2.symbols'
ld: fatal: use the -z help option for usage information
collect2: error: ld returned 1 exit status
make: *** [obj/so/libre2.so] Error 1
rm re2/unicode_groups.cc re2/unicode_casefold.cc

**Comment by junyer** [comment]
Addressed in #29.
