### ISSUE TITLE
Carriage return, one of the escape characters, is being added to the pattern groups.

### ISSUE THREAD

**Issue by GokhanKUCUK61** [google/re2#311]
New line from escape characters are not being added to the pattern groups. Likewise, the carriage return is being added when it should not be added. As a result, new line and carriage return are not handled the same.
\*
there is a setting for the new line.
//   dot_nl           (false) dot matches everything including new line
void set_dot_nl(bool b)
*\
No setting for carriage return

`
std::string data {"Host: asde.com\r\n2"};
re2::RE2 pattern {"Host: (.*)\r?\n?2"};
std::string match;
re2::RE2::PartialMatch(data, pattern, &match);
`

result  match = "asde.com\r"

**Comment by junyer** [comment]
It seems to me that you should write `([^\r\n]*)` instead of `(.*)`. (`.` means `[^\n]` by default; hence the `dot_nl` option.)
