### ISSUE TITLE
How to use RE2 in a C++ entry of a regexp implementations comparison benchmark

### ISSUE THREAD

**Issue by elidoran** [google/re2#314]
I'm working on adding extra implementations to this [regexp benchmark](https://github.com/mariomka/regex-benchmark) repo. 

I noticed the [Rust entry](https://github.com/mariomka/regex-benchmark/blob/optimized/rust/src/main.rs#L8-L9) is fast because it's using an ascii mode and running on a byte array. Some of the others are in unicode mode and working on a string.

So, I wanted to add RE2 in there because it can run directly on a byte array, too. I've created (locally) a new JavaScript based entry using the npm module which wraps RE2 for node. I mimicked their current [JavaScript](https://github.com/mariomka/regex-benchmark/blob/optimized/javascript/benchmark.js) entry and simply used RE2 instead.

However, I want to add an entry with RE2 as its native C++. The section of code I need to figure out for C++ looks like this in JavaScript:

```javascript
  const regex = new RE2(pattern, 'g')
  const matches = data.match(regex)
  const count = matches.length
```

For comparison, their [current C++ entry](https://github.com/mariomka/regex-benchmark/blob/optimized/cpp/benchmark.cpp#L11-L15) looks like this for that same spot:

```c++
 const REGEX_NAMESPACE::regex re{pattern};
 unsigned count = 0;

  for (REGEX_NAMESPACE::sregex_token_iterator it{data.cbegin(), data.cend(), re}, end{}; it != end; ++it)
    count++;
```

I'm barely familiar with C++. I have the rest of what's needed working already. I have a git clone of the RE2 repo. I'm making it do a `make && make install` in the docker container. In the benchmark code I did the include for `re2/re.h`. So, far so good. 

I need the C++ equivalent of the above JavaScript code. However, I've become confused as to which is the right way to go. I looked at the Node wrapper for RE2 and see it handles the "global" mode and will return all matches in the expected ECMAScript way (an array). I also looked at RE2's `re2.h` file and its comments describing how to use it and that seems considerably different; cool, but different. 

I like the ability to have it put captured values directly into variables. That's so much better than having to pull them out of an array or the array's `groups` property. 

Anyway, it leaves me wondering how to just get an array of the matches in C++. I saw the comments about the `RE2::Args` array style ... and I decided I just don't understand C++ enough to know what I"m supposed to be doing there.

Also, I see the `CannedOptions` has a `Latin1`. That means I could do one where it's in ascii mode as well.

I think I ended up babbling a bit too much above, so, the short version is:

1. want to create a reusable instance of RE2
2. have it either grab all the matches (global mode) in one call, or, do repeated calls to count how many matches.
3. be able to configure it to ascii mode to make a better comparison against the other entries which do that.
4. have it work on an array of bytes instead of a string

So, if any of you have a minute to spend, please tell me what is likely quite obvious to any C++ coder. 

Have a great day. :)

**Comment by BurntSushi** [comment]
> I noticed the [Rust entry](https://github.com/mariomka/regex-benchmark/blob/optimized/rust/src/main.rs#L8-L9) is fast because it's using an ascii mode and running on a byte array. Some of the others are in unicode mode and working on a string.

That's not quite accurate. Have you seen this PR from me? https://github.com/mariomka/regex-benchmark/pull/21

Highlights:

* The benchmark's corpus is so small (for all benchmarks) that regex compilation is a factor here. (And indeed, regex compilation is part of the measurement.)
* Most regex engines, including RE2, make `\w` ASCII by default. Rust's regex engine makes it Unicode-aware by default. So disabling Unicode is actually bringing it more closely in line with other regex engines in the benchmark. (I have not done an exhaustive comparison with every regex engine in the benchmark, but it's certainly the case for PCRE2 for example.) So I don't think setting "ascii mode" in RE2 will do anything. RE2 lets you switch between UTF-8 and latin-1, but AIUI, it's not relevant for this particular benchmark.
* Whether it runs on strings or bytes is really immaterial for this benchmark. The Rust benchmark doesn't use bytes for perf reasons, it uses bytes for correctness reasons. If you disable Unicode mode, then it's possible for some of the regexes to match spans that don't fall on valid UTF-8 boundaries. That's a problem for Rust's `&str` type, which is guaranteed to be valid UTF-8. That's not the case for RE2's strings, so I don't think your (4) is relevant.

Disabling Unicode mode is really just about making the comparison "apples to apples." Yet, it is still considered an "optimization." Instead, the benchmark is focused on the "default configuration," regardless what that is. So it's not really the case that Rust's regex engine is fast _because_ of this. It's fast because it uses the same techniques as RE2 (lazy DFA), but does also have some literal optimizations that apply here IIRC.

I know this wasn't the meat of your question, but this particular regex benchmark seems to be the popular one at the present time, and it has a lot of flaws. It lacks analysis. It lacks comprehension. And it lacks a clear explanation of what is actually being measured.

**Comment by elidoran** [comment]
Hello @BurntSushi 

I'm curious how you managed to notice this little post of mine, and I'm glad you did.

I appreciate the gentle "That's not quite accurate" statement. What's actually true is something more like "Eli, are you out of your mind? Rust is fast because ..."

I regret writing it like that. Please excuse me. I was exhausted and after trying to figure out C++ for a while I wanted to ask for help with it so I could move on to improving that benchmark more.

So, two things, first the "Rust is fast because" part, and second the ascii/bytes options benchmark thing.

I recognize Rust is fast due to its design/implementation using a lazy DFA and optimizations such as literal optimizations; not because of ascii mode and bytes. Great work.

I meant more: I wrote new benchmark entries for Rust to show its varied performance when in modes: ascii+bytes, ascii+string, unicode+string (unicode+bytes not possible to due invalid UTF8 bytes issue), and I want to add more entries for all of the implementations to show all of the varied performance of the implementations versus both themselves in different modes and versus the other implementations, and, I'm having trouble adding in RE2 as C++ after adding one of its wrappers (Node/JS). 

I didn't want to write all that, even tho I did end up writing a too-long issue. I was hoping someone would drop a snippet of C++ code with some suggestions so I could move on.

So, my apparent "Rust is only fast in this benchmark cuz it has a config bias", is not at all what I was thinking or meant. I meant: 1. those options are helping it be its fastest self but doesn't show how it varies based on those options and we should see that and I've already done the work to add the entries to show it; 2. I want to show all the variations for all the implementations; 3. I'm trying to do that for RE2 which wasn't directly in the benchmark yet and I'm tripping over C++.

Next, You're right, the benchmark was specifically designed to include the compilation in the measurement. I think the compilation time is something which can be interesting, but, must be separated out. This is another improvement I'd like to do. After all, for me, I'd be willing to pre-build a regex via time consuming analysis for optimal performance, when that matters, even if such analysis would take a while. I can see how it could still be valuable to measure what'll happen when a new regex is thrown together at runtime and its compilation would have a significant effect.

Next, the RE2+ascii thing has two ways to look at it. Let's say you're right and it doesn't make a difference: then I want to include that benchmark entry to show that, because leaving it out leaves the possibility it does and allows viewers to look at the benchmark and think, "hey, they didn't do \<some option permutation here\> for \<one of the implementations\>". It's possible, even if unlikely for some reason, that someone, could look at proof of the non-difference and think "hmm, ya know what, I can make that faster because \<some optimization idea here\>." I understand my writing gave so many false impressions which made this perception of yours seem correct. My focus is more on create all the permutations of configurations to show the differences and then see if there's something to work on.

Next, strings/bytes being immaterial. You're right, and not. Where I'm coming from on this is it's something I've been studying lately: the difference between working on bytes and string abstractions. It keeps showing there's significant improvements to be made by working on the bytes. And serious challenges to it, such as bit endianness, byte encoding (ascii, utf8, utf16, utf32), and writing code which works on non-human-readable content (byte values) instead of visible character representations. And, in Node/JS-land it's not possible to provide a byte array as input to a regular expression. It must be a string. You're right the benchmark needs improving to really highlight the difference, and I'm working on that improvement. When I split the Rust entry into 3 entries based on bytes-or-string and ascii-or-unicode it made a difference, even in the benchmark as it is. I want to split the other implementations into multiple entries with those options as well. If an implementation doesn't perform differently for those options then maybe it would benefit things if it was shown in a benchmark. So, is my (4) relevant? Yes, in general, my goal is to show all the possibilities, and that includes showing RE2, and others, can work directly on a byte array. And, yes, in specific, because I added entries for RE2 using the Node/JS wrapper and its performance is different when given a byte array (Buffer/UInt8Array in JS) instead of a string.

Next, I agree disabling unicode is for apples to apples comparison. I want to change the whole benchmark to get as much of that as possible. 

The thing is, I also want some apples to oranges comparisons. For example, I want to see the comparison of Rust processing ascii+bytes to Rust processing utf8+string. 

For another example, I want to see how those variations line up with other implementations. Maybe some of the implementations have no difference when an option changes, or, maybe the expected performance improvement is actually the opposite of what's expected.

Next, your reply wasn't about my question but it is an understandable reaction to my poorly communicated activity and intent. And, I appreciate you taking the time to write a reply to clarify things. I hope my babble above helps as well.

Finally, you're right, the benchmark is lacking in multiple ways. That's why I felt like working on improvements. I appreciate the author of the benchmark spending the time to produce the benchmark in the first place. I'm sure it was a lot of effort and time to do. As is often the case, more time and effort can improve things.

Also, if anyone reads thru this whole thing, I thank you for spending the time to read my babble. Some times these things get rolling and the next thing I know ... I'm sure when I click "Comment" github will tell me I can't post again for a while.

**Comment by junyer** [comment]
> 1. want to create a reusable instance of RE2

See https://github.com/google/re2/blob/main/re2/re2.h#L123-L137.

> 2. have it either grab all the matches (global mode) in one call, or, do repeated calls to count how many matches.

See https://github.com/google/re2/blob/main/re2/re2.h#L139-L167. You want to be calling `RE2::FindAndConsume()` in a loop.

> 3. be able to configure it to ascii mode to make a better comparison against the other entries which do that.

"ASCII mode" and "Unicode mode" aren't really applicable. RE2 supports Latin-1 and UTF-8 encodings, but they don't affect the meanings of `\b`, `\d`, `\s`, `\w` et al.

> 4. have it work on an array of bytes instead of a string

Latin-1 versus UTF-8 matters only to the parser and the compiler; the bytecode and the execution engines are byte-oriented. (Also, at the risk of provoking the wrath of any C++ lawyercats nearby, `std::string` **_is_** an array of bytes.)

**Comment by BurntSushi** [comment]
@elidoran I'll take our conversation to email. But if you do want to ask questions about the `regex` crate in particular, I have Discussions enabled: https://github.com/rust-lang/regex/discussions
