### ISSUE TITLE
Bazel CI Broken for re2

### ISSUE THREAD

**Issue by c-parsons** [google/re2#316]
Looks broken for the last week. Last success was last Thursday, July 1.

Example Breakage: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2091#b8317341-e4d2-4ef0-b3f0-c78a4b500701

```
(02:11:03) ERROR: no such package '@rules_cc//cc': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_cc/archive/master.zip] to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/bdd99ee593796fb73f43c1c6bb42989c/external/rules_cc/temp8623117508447512888/master.zip: GET returned 404 Not Found
```

Looks like the current URL to download rules_cc no longer exists?

**Comment by c-parsons** [comment]
Hmm, scratch my theory for the root cause. It seems that I'm able to download `https://github.com/bazelbuild/rules_cc/archive/main.zip` myself with no issue.

**Comment by junyer** [comment]
https://github.com/bazelbuild/rules_cc recently migrated from `master` to `main`, which inspired me to do the same for RE2. In commit ccdbd34, I changed the branch name in our CI configuration and also fixed `rules_cc` in our `WORKSPACE` file. It seems like your CI might be stuck at commit 5aec8b5, which immediately preceded our migration. Is your CI still configured with the old branch name? (FWIW, see https://groups.google.com/g/re2-dev/c/NkMI5EkSotk/m/9ELy5N1pAAAJ for my announcement.)

**Comment by c-parsons** [comment]
Indeed it looks like the Bazel@HEAD build is stuck on commit  5aec8b5 because the last green for re2 was older than that.
The generic re2 build is still targeting the master branch, which is why the build is still red.

I'm not sure how to change our configs to fix this. @philwo

**Comment by meteorcloudy** [comment]
Fixed by correcting the CI settings:
https://buildkite.com/bazel/re2/builds/3729

**Comment by junyer** [comment]
Great, thank you!
