### ISSUE TITLE
re2 R wrapper warnings (re2R)

### ISSUE THREAD

**Issue by Mark-Nawar** [google/re2#319]
Hello , I am a google summer of code student trying to submit the re2 wrapper package in R ( [re2R](https://github.com/qinwf/re2r) ) to CRAN ( CRAN is a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R.). so it is good thing to have a package over there. However it rejects any warning in your code. 
I faced this warning( in files regexp.h and prog.h) when I was submitting the package days ago on Debian :
```
  ../inst/include/re2/regexp.h:561:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  ../inst/include/re2/regexp.h:565:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  ../inst/include/re2/regexp.h:569:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  ../inst/include/re2/regexp.h:573:12: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
```
this shall reproduce the error locally just make sure to change the directory of the project to yours: 
```bash
mark@mark-VirtualBox:~/Desktop/re2Google/re2$ g++ -fsanitize=undefined,bounds-strict -fno-omit-frame-pointer -std=gnu++11 -I"/home/mark/Desktop/re2Google/re2/" -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include -DNDEBUG -I'/home/docker/R/Rcpp/include' -I'/home/docker/R/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2 -Wall -pedantic -mtune=native  -c re2/regexp.h
```
starting GCC 8 and above ,C++11 will actually allow you to use a unnamed struct if it is defined in a named struct , Quoting from GCC documentation : ``` As permitted by ISO C11 and for compatibility with other compilers, GCC allows you to define a structure or union that contains, as fields, structures and unions without names. For example:```
```cpp
struct {
  int a;
  union {
    int b;
    float c;
  };
  int d;
} foo;
```
so I believe wrapping those unnamed structs in a named one should solve the problem! 
any ideas?

**Comment by junyer** [comment]
https://cran.r-project.org/web/packages/re2/ has existed for a couple of months. I believe that @girishji had to make various changes to the code (see https://github.com/girishji/re2) in order to bring it into compliance with CRAN's very strict policies. Although I haven't scrutinised either version of the R wrapper, abandoning the older one and collaborating on the newer one seems like the way to go.
