### ISSUE TITLE
FullMatchN crashes

### ISSUE THREAD

**Issue by zhanxw** [google/re2#32]
I encountered a crash when calling FullMatchN.
From the code below, the first and third block are OK, but the second block (below the comment) will crash. Is there a problem with my code or a bug in re2?

    #include <re2/re2.h>
    #include <iostream>

    using namespace re2;

    int main() {
      {
        std::string s;
        int i = 0;
        if (RE2::FullMatch("hello123436", "h(e)l+o([0-9]+)", &s, &i)) {
          std::cout << "1. match\n";
          std::cout << "s = " << s << "\n";
          std::cout << "i = " << i << "\n";
        }
      }

      {
        std::string s;
        int i = 0;
        RE2::Arg* args = new RE2::Arg[2];
        args[0] = &s;
        args[1] = &i;
    
        /* the line below will crash, why? */
        if (RE2::FullMatchN("hello123436", "h(e)l+o([0-9]+)", &args, 2)) {
          std::cout << "2. match\n";
          std::cout << "s = " << s << "\n";
          std::cout << "i = " << i << "\n";
        }
        delete[] args;
      }

      {

        std::string s;
        int i = 0;

        RE2::Arg arg1 = &s;
        RE2::Arg arg2 = &i;
        const RE2::Arg* args[2] = {&arg1, &arg2};

        if (RE2::FullMatchN("hello123436", "h(e)l+o([0-9]+)", args, 2)) {
          std::cout << "3. match\n";
          std::cout << "s = " << s << "\n";
          std::cout << "i = " << i << "\n";
        }
      }
    }

**Comment by zhanxw** [comment]
Still I cannot figure out why, but my tuition tells me allocating an array of RE2::Arg objects causes the problem. I tweak the code a bit, and it works now:

    // old part, will crash
    {
    std::string s;
    int i = 0;
    RE2::Arg* args = new RE2::Arg[2];
    args[0] = &s;
    args[1] = &i;
    
    /* the line below will crash, why? */
    if (RE2::FullMatchN("hello123436", "h(e)l+o([0-9]+)", &args, 2)) {
      std::cout << "2. match\n";
      std::cout << "s = " << s << "\n";
      std::cout << "i = " << i << "\n";
    }
    delete[] args;
    }
    
    // new part
      {
        std::string s;
        int i = 0;
        RE2::Arg** args = new RE2::Arg*[2];
        args[0] = new RE2::Arg;
        args[1] = new RE2::Arg;
        *(args[0]) = &s;
        *(args[1]) = &i;
        // (*args)[0] = &s;
        // (*args)[1] = &s;
    
        if (RE2::FullMatchN("hello123436", "h(e)l+o([0-9]+)", args, 2)) {
          std::cout << "2. match\n";
          std::cout << "s = " << s << "\n";
          std::cout << "i = " << i << "\n";
        }
        delete[] args;
      }

**Comment by junyer** [comment]
Indeed, the function takes an array of `RE2::Arg*`.

**Comment by zhanxw** [comment]
@junyer I am clear now. Thanks.
