### ISSUE TITLE
named capture groups don't support chinese

### ISSUE THREAD

**Issue by messense** [google/re2#321]
Python's `re` module has no issue compiling named capture groups with chinese:

```python
In [1]: import re

In [2]: re.compile(r'(?P<中文>\d+)')
Out[2]: re.compile(r'(?P<中文>\d+)', re.UNICODE)
```

re2 doesn't support it, test via pyre2

```python
In [1]: import re2

In [2]: re2.compile(r'(?P<中文>\d+)')
---------------------------------------------------------------------------
RegexError                                Traceback (most recent call last)
<ipython-input-2-67842cb6a2c6> in <module>
----> 1 re2.compile(r'(?P<中文>\d+)')

re2/compile.pxi in re2._re2.compile()

re2/compile.pxi in re2._re2._compile()

RegexError: invalid named capture group: (?P<中文>
```

rejected by `IsValidCaptureName`:
https://github.com/google/re2/blob/3a95199bcbea2f8762f899a66ea5f2e61fbd0395/re2/parse.cc#L2016-L2033

**Comment by messense** [comment]
https://github.com/python/cpython/blob/83ca46b7784b7357d82ec47b33295e09ed7380cb/Lib/sre_parse.py#L698-L703

Python 3 uses [`str.isidentifier`](https://docs.python.org/3/library/stdtypes.html#str.isidentifier) to check group name, so chinese is accepted.

**Comment by junyer** [comment]
Thanks for the report! This should be fixed shortly and then shipped with next month's release.
