### ISSUE TITLE
Reference to re2j

### ISSUE THREAD

**Issue by rivancic** [google/re2#322]
Can you point on the main README file also to the wrapper for Java besides other languages? 

I was searching for a java regex parser, I found this re2 github repository saw that there are wrappers for multiple languages and wondering that there is none for Java. Later I found out that there actually is a https://github.com/google/re2j already it was just not listed here.

Thanks

**Comment by junyer** [comment]
RE2/J is a port of the Go `regexp` package to Java, not a wrapper for RE2. Thus, it's not listed in the `README` file or on the wiki.
