### ISSUE TITLE
Re2 Error: Invalid Escape Sequence

### ISSUE THREAD

**Issue by lpan31** [google/re2#328]
Re2 gives error: *** re.error: invalid escape sequence: \—

Not able to perform special characters like **”** or **—** etc.

Where re can perform on such one.

**Comment by junyer** [comment]
Thanks for the report. I wasn't aware that the Python `re` module permits `\—`! However, I don't think there are any compelling reasons to escape any code points in the range [U+80, U+10FFFF], so I'm disinclined to permit that just for the sake of Python compatibility. Is there some code somewhere that's generating these bogus escape sequences?
