### ISSUE TITLE
Scan input string before applying regex to increase match performance

### ISSUE THREAD

**Issue by kkonevets** [google/re2#329]
If we have a pattern like `"foo bar"` and input string `"This is a bar"` than we don't even need to run regex search because we can just scan input string for `foo` and `bar` to find that `foo` is absent. So if `foo` or `bar` is absent the pattern doesn't match, fast fall.
The problem is that a pattern could be like `"(foo)*\s+(bar){1,3}"` or more complicated. And I don't know how to check whether `foo` or `bar` is an optional or mandatory substring. In the last example `foo` is optional, `bar` is mandatory, so it should be enough to check if input string contains `bar` to continue with regex search.
So speed optimization comes from a fact that string scan with something like `std::string::find()` is much cheaper then regex search. If we have thousands of regex patterns we don't need to apply each of them to input string. We can just scan input string for mandatory substrings. 
Is there a way to do this with re2?

**Comment by kkonevets** [comment]
Another example is a pattern like `(foo|bar)+` in this case we have two options:
1. Say that `foo` and `bar` are both optional and continue with regex search. This is not optimal but Ok.
2. Search for `foo` and `bar` and check if `foo` or `bar` is found in input string. This is optimal

**Comment by kkonevets** [comment]
Here is another possible optimisation. If a pattern is `(foo|bar|baz)+ blabla` and input string is `This is bar blabla` we can reduce a pattern to `(bar)+ blabla` because `foo` and `baz` not found in input string. Hence speeding up regex search by itself.

**Comment by junyer** [comment]
[`FilteredRE2`](https://github.com/google/re2/blob/main/re2/filtered_re2.h) is what you want.
