### ISSUE TITLE
Replacement substitutions for text that precedes/follows the match

### ISSUE THREAD

**Issue by tophf** [google/re2#330]
If possible, add %subj% similar to JavaScript's <code>$\`</code> and `$'` to write simpler replacements such as:

`"foo"` -> <code>"\\\`bar\\'"</code>

instead of

`"^(.*?)foo(.*)"` -> `"\\1bar\\2"`

Maybe the shorter syntax would be also faster to compile and match.

**Comment by junyer** [comment]
[`RE2::Replace()`](https://github.com/google/re2/blob/main/re2/re2.h#L444-L459) does what the first form does without the extra syntax and, yes, works more efficiently than the second form.

**Comment by tophf** [comment]
But the extra syntax allows much more than the intentionally simplified example e.g. <code>"prefix\\`bar\\'suffix"</code>, repeating, etc. which is impossible now...

**Comment by junyer** [comment]
There are at least a couple of practical issues that rule this out, I think. The first is that `RE2::Rewrite()` would need to take the input string as an additional argument **_and_** all of the submatch strings would have to be strict substrings of the input string, but getting from the current state to the desired end state would entail forcing users to migrate to the new interface for the sake of gaining a feature that they don't even want. The second is that `RE2::Replace()`, `RE2::GlobalReplace()` and `RE2::Extract()` use `RE2::Rewrite()` and would continue to do so, but the feature seems nonsensical in the context of `RE2::GlobalReplace()`.

**Comment by tophf** [comment]
I see, thanks.
