### ISSUE TITLE
Schema Carousels Error: Identical property values given, but unique values are required

### ISSUE THREAD

**Issue by JessSmithCO** [google/re2#331]
Hello Schema Pros!
I cannot for the life of me figure out this issue for my schema below (dummied out for privacy)
**Carousels**Identical property values given, but unique values are required****

Thank you in advance for the help

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "ItemList",
  "url": "https:/web.com/product/",
  "name": "name of page",
  "description": "description of page",
     "numberOfItems": "3",
 "itemListElement": [
    {
      "@type": "ListItem",
      "position": "1",
      "item":     {
 "@type": "Product",
        "brand": "xxxxx",
            "image": "https:/web.com/wp-content/uploads/2020/03/Image-1.jpg",
  "url": "https:/web.com/product/",
		"name": "product 1",
		  "description": "description of product 1",
  "offers": {
    "@type": "Offer",
     "availability": "https://schema.org/InStock",
    "price": "1.99",
    "priceCurrency": "USD"
  }}},
  {
      "@type": "ListItem",
      "position": "2",
      "item": {
        "@type": "Product",
        "brand": "xxxxx",
            "image": "https:/web.com/wp-content/uploads/2020/03/Image-2.jpg",
  "url": "https:/web.com/product/",
		"name": "product 2",
		  "description": "description of product 2",
  "offers": {
    "@type": "Offer",
     "availability": "https://schema.org/InStock",
    "price": "1.99",
    "priceCurrency": "USD"
  }}},
{
      "@type": "ListItem",
      "position": "3",
      "item": {
        "@type": "Product",
        "brand": "xxxxx",
            "image": "https:/web.com/wp-content/uploads/2020/03/Image-3.jpg",
  "url": "https:/web.com/product/",
		"name": "product 3",
		  "description": "description of product",
  "offers": {
    "@type": "Offer",
     "availability": "https://schema.org/InStock",
    "price": "1.99",
    "priceCurrency": "USD"
  }}}
  ]
}
</script>

![Screen Shot 2021-09-22 at 12 13 57 PM](https://user-images.githubusercontent.com/73302648/134398935-a63eec9b-f02d-442c-a4f6-4125d71725fb.png)

**Comment by junyer** [comment]
Sorry, I have no idea who or what directed you here, but this is the issue tracker for RE2, a regular expression engine. My best guess is that you should read https://developers.google.com/search/docs/advanced/structured-data/carousel#troubleshooting.

**Comment by JessSmithCO** [comment]
sorry about that @junyer
