### ISSUE TITLE
Considerations over warnings of -Wsuggest-attribute=pure

### ISSUE THREAD

**Issue by kashirin-alex** [google/re2#332]
The suggestions can only be seen at LTO whereas re2-library required to be built with `cmake .. -DCMAKE_CXX_FLAGS="-O3 -flto -fuse-linker-plugin -ffat-lto-objects -fPIC"` (-O3 might not be necessary) and the Program linkage is static.
I only know of GCC support the `-Wsuggest-attribute=pure` flag.

_The warnings output:_
```CPP
/root/s/re2/re2/prog.cc:1121:13: warning: function might be candidate for attribute ‘pure’ if it is known to return normally [-Wsuggest-attribute=pure]
 1121 | const void* Prog::PrefixAccel_FrontAndBack(const void* data, size_t size) {
      |             ^
/root/s/re2/re2/bitmap256.h:85:5: warning: function might be candidate for attribute ‘pure’ if it is known to return normally [-Wsuggest-attribute=pure]
   85 | int Bitmap256::FindNextSetBit(int c) const {
      |     ^
/root/s/re2/re2/compile.cc:581:6: warning: function might be candidate for attribute ‘pure’ if it is known to return normally [-Wsuggest-attribute=pure]
  581 | bool Compiler::ByteRangeEqual(int id1, int id2) {
      |      ^
/root/s/re2/re2/parse.cc:335:6: warning: function might be candidate for attribute ‘pure’ if it is known to return normally [-Wsuggest-attribute=pure]
  335 | Rune CycleFoldRune(Rune r) {
      |      ^
root/s/re2/re2/compile.cc:489:6: warning: function might be candidate for attribute ‘pure’ if it is known to return normally [-Wsuggest-attribute=pure]
  489 | bool Compiler::IsCachedRuneByteSuffix(int id) {
```

In the Program. I use pure-attribute declaration with `Type __attribute__((pure)) Function()`,
for further details, the update that made/produce the warning suggestions is https://github.com/kashirin-alex/swc-db/commit/2d35568462f9df690bafdeb99f310b8140d5f82e

Main thing that has sense(without starting to compare `const` attribute) to apply the `pure` attribute is by the https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes
> Some common examples of pure functions are strlen or memcmp. Interesting non-pure functions are functions with infinite loops or those depending on volatile memory or other system resource, that may change between consecutive calls (such as the standard C feof function in a multithreading environment).

**Comment by junyer** [comment]
I'm kind of dubious about these warnings. `Prog::PrefixAccel_FrontAndBack()` should be pure, I suppose, but GCC should flag `Prog::PrefixAccel_ShiftDFA()` as well and, regardless, "repeated invocations of the function with the same argument values" doesn't make sense for them. Similarly, common subexpression elimination doesn't make sense to me for most of the others; in the case of `CycleFoldRune()`, there's a minor opportunity, but I'm doubtful that GCC is missing it with the code as written now. Nonetheless, it's always worth considering these things, so thank you for the report. :)
