### ISSUE TITLE
warning C4389: '==' : signed/unsigned mismatch	dfa.cc	872

### ISSUE THREAD

**Issue by ariccio** [google/re2#34]
In [dfa.cc, at line 872](https://github.com/google/re2/blob/master/re2/dfa.cc#L872), MSVC produces this warning:
```
warning C4389: '==' : signed/unsigned mismatch	dfa.cc	872
```

The offending line is:

```
if ((ip->empty() & flag) == ip->empty())
```
...where `ip->empty()` returns an `EmptyOp` `enum` (defaulted to `int`), and `flag` is an `unsigned int`.

**Comment by junyer** [comment]
Could you please suggest a tweak that will satisfy MSVC? There are a couple of options here, I think, but I'm unable to test them. Thanks!
