### ISSUE TITLE
wiki got spammed

### ISSUE THREAD

**Issue by kleer001** [google/re2#342]
looks like your wiki got spammed with:
"Black Lives Matter. Support the Equal Justice Initiative."
regardless of the subject matter it's off topic

**Comment by junyer** [comment]
No, the BLM/EJI banner is intended to be there.

**Comment by spuder** [comment]
Documentation should be for documentation. Advertising banners are a distraction and takes away from the value of the wiki. 

The last thing I want to do is disagree or impose. I have no opinion on the subject matter, What I _do_ want is to ensure people get the information they need about regular expressions
.
There are some pretty big projects that link to this documentation. When a user clicks on the link expecting regex documentation, but sees something else, it's likely that the user will leave the page entirely. Or worse assume that the page has been spammed (which at-least 2 users have done now)

I humbly ask that you reconsider and separate the off-topic link from the regular express documentation in the wiki.

**Comment by junyer** [comment]
One could also argue that protests are off-topic for roads.
