### ISSUE TITLE
Add examples to the docs

### ISSUE THREAD

**Issue by fregante** [google/re2#347]
I haven't been able to find any examples on the repo. Is it possible to see some real, complete regexes that are supported? The syntax page just lists each specific character but not how to compose them, other than a handful of limited examples. What are some regular regex that _aren't_ possible?

**Comment by junyer** [comment]
It sounds like what you want is a tutorial or something similar that works through examples. I'm not aware of any material for RE2 specifically, but the Go `regexp` package supports the same syntax (except for `\C`) and https://youtu.be/nDiFzmGFjS8 looks like a nice introduction that covers the syntax only, **_not_** the API. (Thanks, @christophberger of @AppliedGo!)

**Comment by fregante** [comment]
> but the Go `regexp` package 

Yeah, I'm sure I can just google documentation, but this project is undocumented as far as I'm concerned. If ok for you…

**Comment by junyer** [comment]
RE2's documentation assumes understanding of "baseline" regular expression syntax and instead focusses on how syntactic elements are or aren't supported. The latter is what's important because "baseline" syntax doesn't really vary among regular expression engines whereas everything else varies kaleidoscopically. Any decent introductory material should familiarise you with "baseline" syntax.

**Comment by fregante** [comment]
That’s false and you’re missing the point. 

The string “https://example.com” matches that domain in RE2; That string is not valid regex. If you don’t have examples showing this, I have to figure it out from the syntax document. That’s not enough. 

The second part is that you’re telling in a GitHub issue I opened for clarification, which means it is not clear to begin with. 

A list of examples would include the aforementioned string of valid RE2 and compare it to its counterpart.

**Comment by junyer** [comment]
`https://example.com` is a valid regular expression in RE2 and every other regular expression engine. Certain programming languages might require the slashes to be escaped, I guess, but `https:\/\/example.com` should behave the same anyway.
