### ISSUE TITLE
regular expression tester like `regex101` or `regexr` for Google RE2

### ISSUE THREAD

**Issue by naveen-marthala** [google/re2#348]
This is not an issue. i am just looking for a suggesion.

I'm looking for a regular expression tester for Google RE2 regular expressions. There are a few testers out there, like [regex101](https://regex101.com/), [regexr](https://regexr.com/), that let users write and test regular-expression, but none support re2. So, I want to know how if there are any sites available that would let me write and test with re2 syntax.

**Comment by junyer** [comment]
The Go `regexp` package supports the same syntax as RE2 (except for `\C`), so I believe that [regex101.com](https://regex101.com/) should suffice for most purposes. I haven't heard of any sites that support RE2 specifically.
