### ISSUE TITLE
CMake install does not substitute or install the pkgconfig file

### ISSUE THREAD

**Issue by AdamWill** [google/re2#349]
If you do a CMake build/install of re2 on *nix, nothing substitutes `@includedir@` and `@libdir@` in `re2.pc`, or installs the file. This only happens in a `Makefile`-driven installation.

**Comment by junyer** [comment]
This has come up every so often and in varying ways, but [this comment](https://github.com/google/re2/issues/215#issuecomment-525135082) and [this comment](https://github.com/google/re2/issues/304#issuecomment-808219200) might be the most relevant to you. It still seems to me that CMake is unsuitable for packaging RE2, unfortunately, but the latter comment will hopefully help you. If there's a solution nowadays to the problem noted in the former comment, please let me know to reconsider my position. :)

**Comment by AdamWill** [comment]
Thanks. Well, I am a package maintainer (for Fedora). In Fedora at least, building and shipping static libraries is [explicitly discouraged](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_packaging_static_libraries), so that's not an issue at all.

I ran across this because our re2 maintainer switched from Makefile to CMake building and inadvertently, uh, [broke](https://bugzilla.redhat.com/show_bug.cgi?id=2038572) [the entire distribution](https://bugzilla.redhat.com/show_bug.cgi?id=2038551), so I was cleaning that up. The given reason for switching to CMake was ["I'm in the preliminary phase of adding apache ORC and apache arrow. Both build with cmake only, and both need cmake style pkg info in/usr/lib*/cmake/re2/*"](https://src.fedoraproject.org/rpms/re2/c/822dd8e86673891356199373662b5de9730ec52c?branch=rawhide). Presumably in order to switch back to Makefile building, if that's preferred, we'd need some solution for building those two things.

**Comment by AdamWill** [comment]
Oh, thanks for the reference to the `make common-install` trick. For now I just [re-created the `sed` substitution the `Makefile` does in the spec file](https://src.fedoraproject.org/rpms/re2/blob/rawhide/f/re2.spec#_63), but that might be a better solution. Do you know what the other things that don't get installed with CMake are? The phrase "everything else" implies there may be more than the pkgconfig file...

**Comment by junyer** [comment]
With `Makefile`: `static-install` installs `libre2.a`; `shared-install` installs `libre2.so`; and `common-install` installs the `.h` files and `re2.pc`.

With `CMakeLists.txt`: `install` installs `libre2.so` (when `BUILD_SHARED_LIBS` is true), the `.h` files and `re2Config.cmake`. (cb5bbb250e07e7621a5cfe3818f8141e33967f0e added `re2ConfigVersion.cmake`, but isn't in a tagged release yet.)

A while back, I helped gRPC folks (and package maintainers) by contributing [`Findre2.cmake`](https://github.com/grpc/grpc/blob/master/cmake/modules/Findre2.cmake), which attempts to find RE2 via CMake and via pkg-config. Is that an approach that would work for your use case as well?

**Comment by AdamWill** [comment]
Thanks. I guess it would, but we'd need to patch them into the apache projects downstream and ideally get them merged upstream. Since the only thing we need to 'fix' when using CMake to install re2 seems to be the pkgconfig file, I guess we'll just stick with the CMake approach for now. It seems like fixing the pkgconfig made everything that builds against it happy again.

**Comment by junyer** [comment]
I was thinking more in the sense of trying to package `Findre2.cmake` on its own, but what you have now is a simple, effective solution, so if you're happy, then I'm happy. :)
