### ISSUE TITLE
Python3 shebangs

### ISSUE THREAD

**Issue by psaiz** [google/re2#350]
There are two files in this repo that have a shebang like `#!/usr/bin/python`.  That causes issues while packaging them in an rpm. Would it be possible to put `#!/usr/bin/python3`?

```
*** ERROR: ambiguous python shebang in ./re2/make_unicode_casefold.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in ./re2/make_unicode_groups.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
```

The two files are:

https://github.com/google/re2/blob/main/re2/make_unicode_casefold.py
https://github.com/google/re2/blob/main/re2/make_unicode_groups.py

Thanks

**Comment by junyer** [comment]
Sure, no problem.
