### ISSUE TITLE
No support for Visual Studio 2022.

### ISSUE THREAD

**Issue by kubo6472** [google/re2#351]
unknown version "undefined" found at "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" rancher-sandbox/rancher-desktop#1161

**Comment by junyer** [comment]
https://github.com/rancher-sandbox/rancher-desktop/issues/1161 seems unrelated to RE2. Try filing an issue for https://github.com/nodejs/node-gyp instead?

**Comment by kubo6472** [comment]
> [rancher-sandbox/rancher-desktop#1161](https://github.com/rancher-sandbox/rancher-desktop/issues/1161) seems unrelated to RE2. Try filing an issue for https://github.com/nodejs/node-gyp instead?

I'm not the author of the linked issue. It just seemed like the same problem. Thanks for pointing me in the right direction.
