### ISSUE TITLE
-std=c++11 in the pkg-config file overrides project standard version

### ISSUE THREAD

**Issue by SadieCat** [google/re2#352]
If a project is using C++14 or newer this will override the project settings to use an older version of C++. This means you need to re-set the version back to what you were using previously after applying the re2 --cflags value.

The fix for this would be to just remove the flag from the config and let projects set it themselves.

**Comment by junyer** [comment]
Coincidentally, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003482 was filed earlier this month about the same issue. I'm about to land @stefanor's change that will remove the `-std` flag from `Makefile` and `re2.pc`; that will be released in two weeks when I tag `2022-02-01`.

**Comment by SadieCat** [comment]
Thanks!

**Comment by dotnwat** [comment]
this seems to have not yet made it into the latest release of fedora 37. any idea how to get that going?

**Comment by junyer** [comment]
https://src.fedoraproject.org/rpms/re2 indicates that [Denis Arnaud](https://src.fedoraproject.org/user/denisarnaud) upgraded Fedora 38 to the `2022-06-01` release of RE2 a couple of weeks ago, but I have no idea about their support policy for older releases of Fedora. You can file a bug about this on [bugzilla.redhat.com](https://bugzilla.redhat.com/), I suppose, and consider building your own RPM in the meantime if this is blocking your work.

**Comment by dotnwat** [comment]
thanks @junyer that's all i needed to know. since that had been merged in January but it wasn't in Fedora 37 I was concerned it might have been lost.
