### ISSUE TITLE
iOS got rejected due to legal issue (Guideline 5.0 - Legal) Syria

### ISSUE THREAD

**Issue by BlakeWuh** [google/re2#359]
We use gRPC in our app, and the gPRC-Core use re2. And our iOS app got rejected due to legal issue.
```
Guideline 5.0 - Legal


In distributing apps on the App Store, Apple must comply with U.S. laws. Under U.S. sanctions regulations, the App Store cannot host, distribute or do business with certain apps or developers connected to U.S. embargoed countries or regions. This also extends to Syria, which is currently subject to comprehensive restrictions.

We have identified that your app contains functionality that is connected to a U.S. embargoed territory. Specifically, your app includes the following link/s in the binary:

Syria
```

And I checked our app, and found there's a code 
https://github.com/google/re2/blob/885eb38accf49e2ccdd2fa6786f3590cf40a3e23/re2/unicode_groups.cc#L6086
https://github.com/google/re2/blob/885eb38accf49e2ccdd2fa6786f3590cf40a3e23/re2/unicode_groups.cc#L6402

Is there any chance I need to delete the code mentioned above to get our app approved by Apple Store?

**Comment by nzall** [comment]
Have you tried contacting Apple to appeal the rejection, stating there's naming confusion between the country Syria and the Syriac alphabet?

**Comment by BlakeWuh** [comment]
> Have you tried contacting Apple to appeal the rejection, stating there's naming confusion between the country Syria and the Syriac alphabet?

Thanks for that, we'll try to appeal with that reason. Could this issue remain open till our app get approved?

**Comment by megapro17** [comment]
> Is there any chance I need to delete the code mentioned above to get our app approved by Apple Store?

No, just don't use apple.

**Comment by ShadowJonathan** [comment]
> No, just don't use apple.

This is non-constructive feedback, unwarranted, and victim blaming.

**Comment by nzall** [comment]
> This is non-constructive feedback, unwarranted, and victim blaming.

I agree. Apple devices are still 25% of all mobile phones and over half of all tablets. It would not make good business sense to exclude such a big market share unless there is a more pressing reason than business concerns.



> This seems to be a case of the [Scunthorpe problem](https://en.wikipedia.org/wiki/Scunthorpe_problem)! I wonder whether linking against [ICU](https://github.com/unicode-org/icu) triggers that too? Regardless, I wish you the best of luck with your appeal. If need be, yes, you could just hack out support for the `Syriac` script from your copy of RE2.

I assume linking about ICU would do the same considering they also have a UBLOCK_SYRIAC in their source description. And I think that ICU might also slip up over Cuba (There are references to Cuba's timezone) and even Sudan (although only in comments, which may end up being removed in production builds).

**Comment by raszpl** [comment]
Have you tried contacting Sylvia van Os? She might have some insights you will find enlightening https://sylviavanos.nl/blog/2021/12/24/google_play_hell.html

**Comment by Keith-Cancel** [comment]
> Have you tried contacting Apple to appeal the rejection, stating there's naming confusion between the country Syria and the Syriac alphabet?



> > No, just don't use apple.
> 
> This is non-constructive feedback, unwarranted, and victim blaming.

Not the person your responded to, but if it was not for Apple's size and market penetration this would be a fine answer. Ideally, and ethically developers should not be supporting hardware designed to diminish the property rights of the owner.

**Comment by rsc** [comment]
Apple ships RE2 in iOS. See Settings > General > Legal & Regulatory > Legal Notices.
(You have to scroll a lot but they are arranged alphabetical by author and it is under "R" for "RE2 Authors".)

**Comment by rsc** [comment]
I don't know whether this is a good idea, but https://code-review.googlesource.com/c/re2/+/59750.
@BlakeWuh you can at least patch that in to your tree.

**Comment by BlakeWuh** [comment]
We remove other "Syria" strings in our app, and didn't remove the code mentioned above.And Our app got approved. Thanks a lot for the help. I'm closing this issue.
