### ISSUE TITLE
warning C4805: '|' : unsafe mix of type 're2::uint64' and type 'bool' in operation

### ISSUE THREAD

**Issue by ariccio** [google/re2#36]
[In `compile.cc`, function `Compiler::RuneByteSuffix`, at line 506](https://github.com/google/re2/blob/master/re2/compile.cc#L506), MSVC generates:

```
warning C4805: '|' : unsafe mix of type 're2::uint64' and type 'bool' in operation
```

where the offending line is:

```
uint64 key = ((uint64)next << 17) | (lo<<9) | (hi<<1) | foldcase;
```
...and `lo` is a `uint8`, `hi` is a `uint8`, `next` is an `int`, and `foldcase` is a `bool`. Is this really what you intended?

**Comment by junyer** [comment]
Would `(uint64)foldcase` be sufficient to satisfy MSVC?

**Comment by ariccio** [comment]
*probably*, but `static_cast<uint64>( foldcase )` would be better... or even `( (foldcase) ? 1ULL : 0ULL )`, which avoids casting, and might be more explicit.

I'm assuming that the behavior you're aiming for is that `foldcase` converts to `1` when `true`, and `0` when false.

I'll test and report back.

**Comment by ariccio** [comment]
Complete and total sidenote: in `util.h`. the code:

```
#if !defined(WIN32)
#include <sys/time.h>   // For gettimeofday
#endif
```
[should](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) be:
```
#if !defined(_WIN32)
#include <sys/time.h>   // For gettimeofday
#endif
```

**Comment by ariccio** [comment]
I should really open a Pull Request/issue to improve compilation on MSVC, but for now, to organize my thoughts, I'll just say that there are a lot of easily fixable `WIN32` vs `_WIN32` issues.



`static_cast<uint64>( foldcase )` fixes the warning, and so does `( (foldcase) ? 1ULL : 0ULL )`.

Related: `/analyze` says that the code `((uint64)next << 17)` is dangerous because the `(uint64)` cast happens ***after*** the shift.

**Comment by junyer** [comment]
> I'm assuming that the behavior you're aiming for is that foldcase converts
> to 1 when true, and 0 when false.

That's how the standard defines integral conversion/promotion from `bool`, I believe.

> but for now, to organize my thoughts, I'll just say that there are a
> lot of easily fixable WIN32 vs _WIN32 issues.

`WIN32` might be a Chromium-ism. Can you confirm or deny that, @nico or @tfarina? And would simply changing to `_WIN32` break anything for you?

> Related: /analyze says that the code ((uint64)next << 17) is dangerous
> because the (uint64) cast happens after the shift.

That's not how the standard defines operator precedence. Is MSVC trolling? ;)

**Comment by ariccio** [comment]
> That's how the standard defines integral conversion/promotion from bool, I believe.

Me too, but I don't like relying on such things.

> That's not how the standard defines operator precedence. Is MSVC trolling? ;)

I may have misread it? It'd make more sense if it was referring to `lo` and `hi`, which are both 8 bit unsigned integers, yet `lo` is being shifted 9 bits left! That said, if instead of `((uint64)next << 17)` it was `(static_cast<uint64>(next) << 17)`, there'd be no question :)

**Comment by ariccio** [comment]
I've manually "unrolled" the bit shifting, and can confirm that it's something weird going on with `lo` & `hi`.

All of the following produce [C6297](https://msdn.microsoft.com/en-us/library/9t02bbsx.aspx):

```
  const uint64 lo_left_nine = ( lo << 9 );
  const uint64 hi_left_one  = ( hi << 1 );
  const uint64 lo_left_nine_eight_c = ( lo << UINT8_C( 9 ) ); //to see if it's the 32-bit value of the integer literal
  const uint64 hi_left_one_eight_c  = ( hi << UINT8_C( 1 ) );
  const uint64 lo_left_nine_eight_c = ( lo << uint8( 9 ) );   //to see if it's the 32-bit value of the integer literal
  const uint64 hi_left_one_eight_c  = ( hi << uint8( 1 ) ); 
```

**Comment by junyer** [comment]
Ahh. Yes, the shifts of `lo` and `hi` definitely seem problematic now that I look at them. I'll just cast everything to `uint64` and that should take care of C4805 as well.

**Comment by nico** [comment]
@junyer No, WIN32 isn't a Chromium-ism. See the second answer in http://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c . Both WIN32 and _WIN32 should work for us, but unless there's some problem that's solved by changing this I wouldn't change it.

**Comment by junyer** [comment]
@nico Okay, thanks!
