### ISSUE TITLE
Incorrect test used for library feature availabiltiy

### ISSUE THREAD

**Issue by davemcincork** [google/re2#361]
The stringpiece.h header file tests for availabiltiy of std::string_view by testing for C++17 (__cplusplus >= 201703L). Unfortunately, this doesn't work for VS2019 in C++17 standard mode because, for compatability reasons, VS2019 always sets __cplusplus to have a value of 199711L. This can be overridden using a compiler switch but this is a fairly obscure detail that many people don't know about. And this means that people are missing out on the performance benefit of using std::string_view.

From C++11 and onwards, the correct way to test for availability of a particular library feature is to test the corresponding preprocessor feature macro. In the case of std::string_view, the macro is __cpp_lib_string_view.

**Comment by junyer** [comment]
TIL. :)

I have a fix out for review.
