### ISSUE TITLE
\z vs \Z in python

### ISSUE THREAD

**Issue by froh** [google/re2#366]
Hi,

the python module docstring known differences section [doesn't list](https://github.com/google/re2/blob/e64aa931ec6fb79f76c39db01324f227bf69adda/python/re2.py#L9)  `'\z'` in re2 vs `'\Z'` in re for a match at "end of text".

this code works:
```python
import re
import re2
re.findall("(?m)ab\d\Z", "  ab1\n  baz ab2")
re2.findall("(?m)ab\d\z", "  ab1\n  baz ab2")
```

If you flip upper and lower case `z` you get lovely invalid/bad escape exceptions.

**Comment by junyer** [comment]
The `re2` module aims to be a drop-in replacement for the `re` module at the API level, not at the syntax level. Admittedly, this syntactic incompatibility is vexing: PCRE supports `\Z` and `\z`; RE2 supports `\z`; and Python supports `\z`, but calls it `\Z`. I could rewrite `\Z` to `\z` fairly easily, I reckon, but doing so would open a can of worms that really shouldn't be opened. Would linking to https://github.com/google/re2/wiki/Syntax suffice as a reminder that RE2 doesn't support exactly the same syntax as Python? (It's widely known that backreferences and look-around assertions aren't supported, but there are more differences.)

**Comment by froh** [comment]
Hm. the syntax page doesn't spell this subtle difference yet.  So, hint  "`re2` implements only a subset of `re`" in the module docstring alone had not saved me.  I think, in addition the syntax wiki should spell out that difference between re2 and re (especially given the claim "drop in replacement").  Currently it's a _hidden_ incompatibility which bit me _after_ reading the docs.

As a side note, it made me wonder: are there more differences?  As I otherwise only use mainstream features I hope I'm good 😄.

Also, when/if you touch the syntax page, would it make sense to link to the regex descriptions of each?  The links would gently support a disclaimer, for example like so:

> re2 syntax is originally based off [PYTHON re](https://docs.python.org/3/library/re.html) and it's mostly compatible with it. UNSUPPORTED and DIFFERENT behavior is spelled out below.  The table also delineates _re2_ from some common syntax accepted by [VIM patterns](https://vimhelp.org/pattern.txt), [PERL perlre](html https://perldoc.perl.org/perlre) and [PCRE pcre2compat](https://www.pcre.org/pcre2.txt#:~:text=expressions%20(revised%20API)-,DIFFERENCES%20BETWEEN%20PCRE2%20AND%20PERL,-This%20%20document%20describes).

Not sure whether to link to pcre2compat or just pcre, though.

Makes sense?

**Comment by junyer** [comment]
RE2 aims to mimic the syntax supported by PCRE, not the syntax supported by the `re` module. OTOH, the `re2` module aims to mimic the API provided by the `re` module, but uses RE2 under the hood. Would stating that be worthwhile?

Linking to https://swtch.com/~rsc/regexp/regexp3.html#caveats might also be worthwhile, but wouldn't have helped you avoid this specific problem, so I'm less sure about it.

**Comment by froh** [comment]
Apologies Re: PCRE, somehow there was some python loving confirmation bias at work :-D

I like the pointer to the caveats.  Maybe like so?

> _re2_ syntax is a subset of [PCRE syntax](https://www.pcre.org/current/doc/html/pcre2syntax.html).  Some PCRE features are [not supported by design](https://swtch.com/~rsc/regexp/regexp3.html#caveats).  UNSUPPORTED and DIFFERENT behavior is spelled out below.  The table also delineates _re2_ from some common syntax accepted by [PYTHON re](https://docs.python.org/3/library/re.html), [VIM patterns](https://vimhelp.org/pattern.txt), and [PERL perlre](https://perldoc.perl.org/perlre).

- update the table with the \z \Z difference for python
- update the module docstring, maybe like so:

``` python
"""A drop-in replacement for the re module.

It uses RE2 under the hood, so by design some PCRE features
(e.g. backreferences, look-around assertions) are not supported.

Known differences between this API and the re module's API:

   * See https://github.com/google/re2/wiki/Syntax for
      RE2 regex syntax details and differences to python re
      (e.g. \z instead of \Z)
   * . . .
""""
```

I just skimmed the contribution guidelines --- wow. understood, yet wow (CLA, gerrit, yadda). sigh.

**Comment by junyer** [comment]
The wiki page [now](https://github.com/google/re2/wiki/Syntax/_compare/950db1a17f620f463532bd95c7993a53cd3ab295...4dde28946afad479d7d4846233cd6ac47965cb3d) links to the "Caveats" section of Russ' third article, but I'm not keen to list more dialects/flavours of regular expressions. (I don't know why Vim was ever included, honestly, and I will probably remove it someday.) Python's mistake with `\Z` ought to be documented at https://docs.python.org/3/library/re.html#index-34, but in lieu of that, mentioning it in the `re2` module docstring will have to do.

**Comment by junyer** [comment]
Done in commit 6f899d9.
