### ISSUE TITLE
How to use re2 python wrapper in bazel?

### ISSUE THREAD

**Issue by wangyufeng0615** [google/re2#367]
I have a python script that import re2. The BUILD file is 
```
py_binary(
    name = "foo",
    srcs = ["foo.py"],
    deps = [
      "@com_google_re2//python:re2",
    ],
)
```

When I build this, i got 
```
external/com_google_re2/python/_re2.cc:11:10: fatal error: pybind11/pybind11.h: No such file or directory
```

How can I set the pybind11 as dep for re2? Is there code example? I searched a lot but got no answer.

**Comment by junyer** [comment]
At the moment, building the C++ extension requires pybind11 to be installed on your system. (On Debian, for example, install the `pybind11-dev` package.)
