### ISSUE TITLE
Sadly, xkcd excerpt is not compatibly-licensed

### ISSUE THREAD

**Issue by ArloJamesBarnes** [google/re2#368]
https://github.com/google/re2/tree/main/doc

Suggestion: link to it in the documentation text instead

(via https://github.com/supertuxkart/stk-code/issues/4751)

**Comment by junyer** [comment]
Thanks for the report. I have asked our lawyercats for their advice regarding the necessary course of action here.

**Comment by junyer** [comment]
As it turns out, the image is just a remnant from when the RE2 project was hosted on Google Code (see https://web.archive.org/web/20100314093047/https://code.google.com/p/re2/, for example) and nothing actually uses it anymore, so I'm simply going to delete it.
