### ISSUE TITLE
Publish comprehensive API documentation

### ISSUE THREAD

**Issue by hickford** [google/re2#369]
I found https://github.com/google/re2/wiki/CplusplusAPI but it only describes a few functions . Is there any more comprehensive documentation published ?

The Go package has comprehensive documentation with examples at all functions https://pkg.go.dev/regexp

**Comment by hickford** [comment]
Read the header file https://github.com/google/re2/blob/main/re2/re2.h

**Comment by junyer** [comment]
The [`README`](https://github.com/google/re2/blob/main/README) file directs folks to [`re2.h`](https://github.com/google/re2/blob/main/re2/re2.h) and, indeed, that's the "source of truth" documentation. (I had actually forgotten that the [CplusplusAPI](https://github.com/google/re2/wiki/CplusplusAPI) page exists...) That seems to have sufficed for approximately everybody during my tenure as maintainer, so providing supplementary documentation isn't really planned.
