### ISSUE TITLE
Please install .pc file along with cmake files

### ISSUE THREAD

**Issue by yurivict** [google/re2#372]
Some projects (ex. or-tools) expect cmake files, and some other projects (ex. [bloaty](https://github.com/google/bloaty)) only expect .pc files.

This makes it impossible to satisfy both types of dependencies w/out installing both cmake and .pc files.

**Comment by junyer** [comment]
You can run `make common-install` to install `re2.pc` separately from invoking CMake to build and install everything else. (FWIW, Homebrew has been doing exactly this for a couple of years now.)
