### ISSUE TITLE
Fix the broken links of articles

### ISSUE THREAD

**Issue by yuki-kimoto** [google/re2#378]
I'm studying regular expression parser to write SPVM::Regex.

https://github.com/yuki-kimoto/SPVM/tree/master/lib/SPVM/Regex

SPVM is a programming language and SPVM::Regex is its regular expression library.

I'm reading articles of RE2 from Wiki.

https://github.com/google/re2/wiki

I find the links to the source codes of the re2 repository are bloken.

https://swtch.com/~rsc/regexp/regexp1.html

https://swtch.com/~rsc/regexp/regexp2.html

https://swtch.com/~rsc/regexp/regexp3.html

https://swtch.com/~rsc/regexp/regexp4.html

For examples. 

[Wrong] http://code.google.com/p/re2/source/browse/re2/parse.cc#1539

[Right] https://github.com/google/re2/tree/main/re2/parse.cc#1539

Could you fix these broken links?

**Comment by junyer** [comment]
swtch.com is @rsc's personal site. I will let him know.

**Comment by yuki-kimoto** [comment]
@junyer 

>  I will let him know.

Thank you!
