### ISSUE TITLE
Cannot compile empty set but can also not determine if set is empty.

### ISSUE THREAD

**Issue by dascandy** [google/re2#38]
Have a fix in https://github.com/dascandy/re2/commit/232c224d164fccce1f023ee7711c4d14bbdd4f6f but no idea how to get a pull request out of it. It makes the set work (and match nothing) if it's empty, and also allows you to ask if it's empty.

**Comment by junyer** [comment]
Thanks for the report and the patch! It'll be no effort to recreate the latter, obviously, and I'll want to write at least one test anyway, so don't worry about the contribution process. :)

Note that `re_` is cleared during compilation, so I'll have to think about `Empty()` a bit more. I'm not sure that it's really necessary, but I'll try to find an elegant way to handle it. (From what I've seen, people tend to have more problems with "overfilling" an `RE2::Set`!)

Looping in @rsc just in case he has any thoughts about this.

**Comment by dascandy** [comment]
Thanks for RE2 by the way - I've used it for dascandy/bob on github as the basis for a build system, and it was the fastest regular expression matcher I could find that supported submatches. I think I also have some Windows support patches - do you want those too?

**Comment by junyer** [comment]
Thank you, that's great to hear. :)

Please file a separate bug about the Windows work. Some of it might have been covered by @ariccio recently, so if you haven't pulled in the last month or so, then you might like to do that first just in case.

**Comment by junyer** [comment]
Do you have a test case that demonstrates the problem? It seems that compiling when empty does work and does match nothing: an alternation of zero expressions becomes a `kRegexpNoMatch` opcode. I'll commit the tests for the sake of improving coverage. :)

**Comment by junyer** [comment]
Please reopen if there's still an issue from your perspective!
