### ISSUE TITLE
Unreachable code in re2/compile.cc when compiled with NDEBUG

### ISSUE THREAD

**Issue by hzeller** [google/re2#384]
Compiling creates warnings about unreachable code

  * [re2/compile.cc:793](https://github.com/google/re2/blob/77797327dd2c278604155d19ff398cc304fbc031/re2/compile.cc#L793)
  * [re2/compile.cc:920](https://github.com/google/re2/blob/77797327dd2c278604155d19ff398cc304fbc031/re2/compile.cc#L920)
  * [re2/compile.cc:978](https://github.com/google/re2/blob/77797327dd2c278604155d19ff398cc304fbc031/re2/compile.cc#L978)

The `failed_ = true` code is never reached, because LOG(DFATAL) is defined as noreturn in [util/logging.h](https://github.com/google/re2/blob/77797327dd2c278604155d19ff398cc304fbc031/util/logging.h#L96).

This results in build breakages with `-Werror` and compilers that care (such as clang in address sanitizer mode). Of course, I'd rather not add `-Wno-unreachable-code`.

Could this be fixed with some annotation at the `failed_ = true` line that it is maybe unreachable ?

**Comment by junyer** [comment]
RE2 uses `LOG(DFATAL)` in numerous places, so it's puzzling that those three uses in `compile.cc` are what's causing trouble and not, for example, [the fourth use in the same file](https://github.com/google/re2/blob/77797327dd2c278604155d19ff398cc304fbc031/re2/compile.cc#L615). (It's also puzzling that this problem had never been reported until now!)

Nonetheless, the fourth use suggests that logging immediately before a `return` isn't problematic, so I can hopefully just set `failed_` **_before_** logging...

**Comment by hzeller** [comment]
Still some newly discovered instances
  * [re2/set.cc:163](https://github.com/google/re2/blob/aed1d79f1f46af3f54563d57510aade4722c5cd6/re2/set.cc#L163)
  * [re2/set.cc:130](https://github.com/google/re2/blob/aed1d79f1f46af3f54563d57510aade4722c5cd6/re2/set.cc#L130)

There might be more lurking, but this is here [my ci](https://github.com/chipsalliance/verible/runs/7696894850?check_suite_focus=true#step:7:67) currently stops

**Comment by junyer** [comment]
FWIW, ASan isn't necessary to find these; Clang with `-Wunreachable-code` is sufficient.

```
re2/parse.cc:1589:15: warning: code will never be executed [-Wunreachable-code]
  LOG(DFATAL) << "Not reached in ParseEscape.";
              ^~
re2/parse.cc:2060:5: warning: code will never be executed [-Wunreachable-code]
    status_->set_code(kRegexpInternalError);
    ^~~~~~~
2 warnings generated.

re2/prog.cc:514:16: warning: code will never be executed [-Wunreachable-code]
    LOG(ERROR) << "Using trivial bytemap.";
               ^~
re2/prog.cc:513:7: note: silence by adding parentheses to mark code as explicitly dead
  if (0) {  // For debugging, use trivial bytemap.
      ^
      /* DISABLES CODE */ ( )
1 warning generated.

re2/dfa.cc:1681:24: warning: code will never be executed [-Wunreachable-code]
      params->failed = true;
                       ^~~~
1 warning generated.

re2/prefilter.cc:535:14: warning: code will never be executed [-Wunreachable-code]
      info = EmptyString();
             ^~~~~~~~~~~
1 warning generated.

re2/set.cc:163:11: warning: code will never be executed [-Wunreachable-code]
      if (error_info != NULL)
          ^~~~~~~~~~
re2/set.cc:130:9: warning: code will never be executed [-Wunreachable-code]
    if (error_info != NULL)
        ^~~~~~~~~~
2 warnings generated.

re2/simplify.cc:435:7: warning: code will never be executed [-Wunreachable-code]
      nre->Decref();
      ^~~
re2/simplify.cc:374:7: warning: code will never be executed [-Wunreachable-code]
      nre->Decref();
      ^~~
2 warnings generated.
```

**Comment by junyer** [comment]
The odd one out there is [this](https://github.com/google/re2/blob/a23f85cae66516b22fd35ba7b8f518133e4b68c4/re2/parse.cc#L1592), which I **_think_** can just be deleted outright. At least, GCC and Clang don't get cranky about that; the CI will tell me what MSVC says.

**Comment by hzeller** [comment]
Thanks, looks like I can now compile in my CI with unreachable code warnings enabled.

**Comment by junyer** [comment]
Sweet, thanks for confirming.
