### ISSUE TITLE
Future of abseil branch?

### ISSUE THREAD

**Issue by keith** [google/re2#388]
In [Envoy](https://github.com/envoyproxy/envoy/) we depend on googletest, which used re2's abseil branch, and other projects which depend on re2's main branch. There doesn't currently seem to be any way for us to resolve these conflicts, without potentially trying to figure out how to link multiple versions of re2. Is there any plan to resolve this divergence to satisfy this use case?

For now we are blocked on updating googletest past the point at which it integrated re2 in the first place to avoid this.

**Comment by junyer** [comment]
In the long term, my plan is "just" to migrate both branches to `std::string_view`, which will reconcile the primary difference between the public APIs. In the short term, I think that I will have to resurrect `stringpiece.h` in the `abseil` branch and alias `re2::StringPiece` to `absl::string_view`. With that shim in place, you can use the `abseil` branch for Envoy code and also for its dependencies. (That would correspond to the source transformation that Google performs for its monorepo, I believe.) I'm going to hook that up for you on Monday. :)

**Comment by junyer** [comment]
I'm tentatively closing this issue as fixed, but please let me know if commit 6543c37 turns out to be insufficient.
