### ISSUE TITLE
`HAVE_PTHREAD` vs `_POSIX_THREADS`? (ongoing windows compatibility work)

### ISSUE THREAD

**Issue by ariccio** [google/re2#39]
In `mutex.h`, `re2` `#define`s `HAVE_PTHREAD` and `HAVE_RWLOCK`:

```
/*
 * A simple mutex wrapper, supporting locks and read-write locks.
 * You should assume the locks are *not* re-entrant.
 */

#ifndef RE2_UTIL_MUTEX_H_
#define RE2_UTIL_MUTEX_H_

#include <stdlib.h>

namespace re2 {

#define HAVE_PTHREAD 1
#define HAVE_RWLOCK 1
```

...without actually checking if we have `Pthreads` or not.

I think that the POSIX standard guarantees that [`_POSIX_THREADS` is defined when `Pthreads` is present](http://linux.die.net/man/7/posixoptions).

On Windows (VS2013), `Pthreads` is not present by default, and thus this breaks compilation.

Maybe `re2` should check for `_POSIX_THREADS` instead of `HAVE_PTHREAD`? (I don't have access to a unix build system at the moment)

I'm not sure about `HAVE_RWLOCK`.

Simply commenting out the two `#define`s allows compilation to proceed a bit further, until it hits the `#include <pthread.h>` in `re2.cc`.

*If* I change the `HAVE_PTHREAD` to:

```
#if defined(_POSIX_THREADS)
#define HAVE_PTHREAD 1
#endif
```

...and then guard the `#include <pthread.h>`:

```
#if defined(HAVE_PTHREAD)
#include <pthread.h>
#endif
```
...that eliminates most (maybe all) `Pthread` issues with compiling on Windows. There are, of course, other issues, but this deals with the `Pthreads` issues.

**Comment by junyer** [comment]
Thanks for the suggestion to use POSIX options. I'm putting together a change that should hopefully make life slightly better for everyone.

**Comment by ariccio** [comment]
:)
