### ISSUE TITLE
Why does RE2 support capturing groups with the same name

### ISSUE THREAD

**Issue by freekeeper** [google/re2#393]
There is such a test case in [re_test.cc](https://github.com/google/re2/blob/main/re2/testing/re2_test.cc#L1513)
```
TEST(RE2, CapturingGroupNames) {
  // Opening parentheses annotated with group IDs:
  //      12    3        45   6         7
  RE2 re("((abc)(?P<G2>)|((e+)(?P<G2>.*)(?P<G1>u+)))");
  EXPECT_TRUE(re.ok());
  const std::map<int, std::string>& have = re.CapturingGroupNames();
  std::map<int, std::string> want;
  want[3] = "G2";
  want[6] = "G2";
  want[7] = "G1";
  EXPECT_EQ(want, have);
}
```
There are two capturing groups `G2` with the same name in `RE2 re("((abc)(?P<G2>)|((e+)(?P<G2>.*)(?P<G1>u+)))")`, and successfully make `have[3] = "G2"; have[6] = "G2";`

Many regular expression libraries do not support capturing groups with the same name, such as [regex](https://github.com/rust-lang/regex).

So I would like to know why there is a [test case](https://github.com/google/re2/blob/main/re2/testing/re2_test.cc#L1513) for testing capturing groups with the same name and why RE2 supports capturing groups with the same name.

**Comment by junyer** [comment]
Perl has this behaviour:

> If multiple distinct capture groups have the same name, then `$+{NAME}` will refer to the leftmost defined group in the match.

([source](https://perldoc.perl.org/perlre#(?NAME%3Epattern)))

PCRE also has this behaviour albeit conditionally:

> By default, a name must be unique within a pattern, but it is possible to relax this constraint by setting the PCRE_DUPNAMES option at compile time. _[…]_

([source](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC16))

From brief archaeological digging, I gather that the decision to follow Perl's behaviour dates back to early 2008.

**Comment by BurntSushi** [comment]
Someone asked the inverse of this question for `rust-lang/regex` and I wrote a bit about why I chose to forbid it: https://github.com/rust-lang/regex/discussions/901
