### ISSUE TITLE
pkg-config install for cmake build

### ISSUE THREAD

**Issue by veblush** [google/re2#399]
Could you make `cmake install` install its [pkg-config](https://linux.die.net/man/1/pkg-config) package? Currently re2 installs its pkg-config package only in `make install` but not in `cmake install`. 

gRPC depends on re2 and it only supports `cmake install` (gRPC doesn't support `make install`) but it supports pkg-config for using gRPC so gRPC does install its pkg-config package when running `cmake install`. ([code](https://github.com/grpc/grpc/blob/a1dc4983564888e661755e31d24a271849b42ce9/CMakeLists.txt#L24704)) All gRPC's dependencies except re2 follow the same style (installing pkg-config in cmake install) so we can simply run `cmake install` for all dependencies and test our example build with pkg-config. ([example](https://github.com/grpc/grpc/blob/a1dc4983564888e661755e31d24a271849b42ce9/test/distrib/cpp/run_distrib_test_cmake_pkgconfig.sh#L88)) But re2 doesn't do that so it should run both `make install` and `cmake install`. This sounds a bit redundant  so it would be great to make re2 install a pkg-config file in `cmake install`.

**Comment by junyer** [comment]
Historically, I have advised folks to run `make common-install` to install `re2.pc` (i.e. separately from invoking CMake to build and install everything else), but I guess the time has come to be better. :)

**Comment by junyer** [comment]
This will be in the `2022-12-01` release.

**Comment by veblush** [comment]
@junyer Thank you for this good news!

**Comment by junyer** [comment]
FYI, commit 6f2d753 will also be in the next release.

**Comment by junyer** [comment]
I have tagged release `2022-12-01`. :)
