### ISSUE TITLE
`vsnprintf_s` in `StringAppendV`

### ISSUE THREAD

**Issue by ariccio** [google/re2#40]
In `util.h`, `vsnprintf` is `#define`d as `vsnprintf_s`:

```
#define vsnprintf vsnprintf_s
```

....and it's used twice, [both in `re2::StringAppendV`](https://github.com/google/re2/blob/master/util/stringprintf.cc#L9).

The first use:

```
  // First try with a small fixed size buffer
  char space[1024];

  // It's possible for methods that use a va_list to invalidate
  // the data in it upon use.  The fix is to make a copy
  // of the structure before using it and use that copy instead.
  va_list backup_ap;
  va_copy(backup_ap, ap);
  int result = vsnprintf(space, sizeof(space), format, backup_ap);
  va_end(backup_ap);
```
...uses a stack-allocated buffer, and thus [template parameter inference works it's magic](https://msdn.microsoft.com/en-us/library/ms175759.aspx) to [infer the size of the buffer](https://randomascii.wordpress.com/2013/04/03/stop-using-strncpy-already/).

The second use:

```
  // Repeatedly increase buffer size until it fits
  int length = sizeof(space);
  while (true) {
    if (result < 0) {
      // Older behavior: just try doubling the buffer size
      length *= 2;
    } else {
      // We need exactly "result+1" characters
      length = result+1;
    }
    char* buf = new char[length];

    // Restore the va_list before we use it again
    va_copy(backup_ap, ap);
    result = vsnprintf(buf, length, format, backup_ap);
    va_end(backup_ap);
```
...uses a dynamically allocated buffer (`char* buf = new char[length]`), and thus template parameter inference fails. MSVC generates:

```
error C2660: 'vsnprintf_s' : function does not take 4 arguments
```

The correct code looks something like:

```
result = vsnprintf(buf, length, _TRUNCATE, format, backup_ap);
```

**Comment by junyer** [comment]
You know, it's really quite tempting to ditch these "security-enhanced" functions...

**Comment by ariccio** [comment]
Insofar as `_TRUNCATE` is concerned, I totally agree. It's annoying, and seems kinda silly - is there any actual use case for it??

[Otherwise, they do actually improve things](https://randomascii.wordpress.com/2013/04/03/stop-using-strncpy-already/).  Otherwise, they are actually semi-standardized as part of the C11 standard's "Annex K", and it'd be *really nice* if GCC/LLVM actually got around to supporting them.

**Comment by huxingyi** [comment]
Hello, I compile the source on vc++ 2008, still got this error
```
Error	14	error C2660: 'vsnprintf_s' : function does not take 4 arguments
```
on this line
```c++
int result = vsnprintf(space, sizeof(space), format, backup_ap);
```

Change `#define vsnprintf vsnprintf_s` to `#define vsnprintf _vsnprintf_s` in `util/util.h` can fix this.

I checked https://msdn.microsoft.com/en-us/library/d3xd30zz.aspx, and found only `_vsnprintf_s` have the scure template overload.

**Comment by junyer** [comment]
RE2 builds cleanly with Visual Studio 2013 and Visual Studio 2015, I believe, so is it possible that Visual Studio 2008 differs from more recent versions in this regard? (Ping, @DThiebaud.)

**Comment by DThiebaud** [comment]
On 12/28/2015 5:13 AM, Paul Wankadia wrote:
>
> RE2 builds cleanly with Visual Studio 2013 and Visual Studio 2015, I 
> believe, so is it possible that Visual Studio 2008 differs from more 
> recent versions in this regard? (Ping, @DThiebaud 
> <https://github.com/DThiebaud>.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/40#issuecomment-167536396>.
>
I will build the current RE2 to verify that no problem with VS2013 or 
VS2015 has sneaked in. I have VS2008 so I will also see what I can find 
out on this.

**Comment by DThiebaud** [comment]
The current RE2 does, indeed, compile cleanly on VS2013 and VS2015. When I try to run CMAKE for VS2008 I get an error which I think is because I don't have VS2008 installed properly.

**Comment by huxingyi** [comment]
It's worth mentioning that to compile successfully on vs2008, I need do the following changes on re2:
- Download the missing stdint `https://github.com/CoDEmanX/re2win/blob/master/mswin/stdint.h` and include the folder in the project.
- Install `VC++ 2008 Feature Pack` to fix `fatal erro C1083: Cannot open include file: unordered_set`
- Define NOMINMAX macro to fix `Illegal token on right side of ::`
- Append `#define va_copy(dest, src) (dest = src)` to stdint.h(or other files)
- I just need the library, not the whole tests, so I excluded the https://github.com/google/re2/blob/master/re2/set.cc, because there is also an compile error in it.

**Comment by DThiebaud** [comment]
https://msdn.microsoft.com/en-us/library/d3xd30zz.aspx says: "vsnprintf_s,_vsnprintf_s and _vsnwprintf_s return the number of characters written, not including the terminating null, or a negative value if an output error occurs. vsnprintf_s is identical to _vsnprintf_s. vsnprintf_s is included for compliance to the ANSI standard. _vnsprintf is retained for backward compatibility."

This is in the 2008 version of this page as well as the 2015 version of this page. I don't understand why ;you get different results with vsnprintf_s as opposed to _vsnprintf_s.

**Comment by DThiebaud** [comment]
>Download the missing stdint https://github.com/CoDEmanX/re2win/blob/master/mswin/stdint.h and i>nclude the folder in the project.

How to I download this? (I don't know GIT very well.)

>Install VC++ 2008 Feature Pack to fix fatal error C1083: Cannot open include file: unordered_set
Where can I find this?

**Comment by DThiebaud** [comment]
Has anyone thought about how old a version of MSVC we want to support for RE2?

**Comment by huxingyi** [comment]
wget this link: `https://raw.githubusercontent.com/CoDEmanX/re2win/master/mswin/stdint.h`
I download `VC++ 2008 Feature Pack to fix` from here https://download.microsoft.com/download/a/c/a/acaf4f79-2210-4034-94bb-f7e15eb335f5/VC2008FeaturePack.exe 

> This is in the 2008 version of this page as well as the 2015 version of this page. I don't understand why ;you get different results with vsnprintf_s as opposed to _vsnprintf_s.

My Visual Studio 2008 Version:  Version 9.0.21022.8 RTM 

`C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include` (VC2008)
```cpp
350 _Check_return_opt_ _CRT_INSECURE_DEPRECATE(vsnprintf_s) _CRTIMP int __cdecl vsnprintf(_Out_cap_(_MaxCount) char * _DstBuf, _In_ size_t _MaxCount, _In_z_ _Printf_format_string_ const char * _Format, va_list _ArgList);
351 #if __STDC_WANT_SECURE_LIB__
352 _Check_return_opt_ _CRTIMP int __cdecl vsnprintf_s(_Out_z_cap_(_DstSize) char * _DstBuf, _In_ size_t _DstSize, _In_ size_t _MaxCount, _In_z_ _Printf_format_string_ const char * _Format, va_list _ArgList);
353 #endif

```
This one is missing `__DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_3` which presented in vc2010.

`D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdio.h` (VC2010 EXPRESS)
```cpp
354 _Check_return_opt_ _CRT_INSECURE_DEPRECATE(vsnprintf_s) _CRTIMP int __cdecl vsnprintf(_Out_cap_(_MaxCount) char * _DstBuf, _In_ size_t _MaxCount, _In_z_ _Printf_format_string_ const char * _Format, va_list _ArgList);
355 #if __STDC_WANT_SECURE_LIB__
356 _Check_return_opt_ _CRTIMP int __cdecl vsnprintf_s(_Out_z_cap_(_DstSize) char * _DstBuf, _In_ size_t _DstSize, _In_ size_t _MaxCount, _In_z_ _Printf_format_string_ const char * _Format, va_list _ArgList);
357 __DEFINE_CPP_OVERLOAD_SECURE_FUNC_0_3(int, vsnprintf_s, _Deref_post_z_ char, _Dest, _In_ size_t, _MaxCount, _In_z_ _Printf_format_string_ const char *, _Format, va_list, _Args)
358 #endif

```

**Comment by junyer** [comment]
> Has anyone thought about how old a version of MSVC we want to support for RE2?

That's a very good point. As long as we're willing to draw a line in the sand somewhere, we can then recast the question: what's the oldest version of Visual Studio that builds RE2 cleanly at (say) commit 7ae8845d4514ca7ddb5b8682d4f4cb3d3f1b16d0? 2008 won't fly, evidently, but what about 2010 and 2012? They have some support for C99 and C++11, I think, so would that address the problems with `stdint.h` and `unordered_set`?
