### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by who0sy** [google/re2#402]
1.regexRule := "(?<=^|[a-z]\-|[\s\p{Punct}&&[^\-]])([A-Z][A-Z0-9_]*-\d+)(?![^\W_])"

2.regexp2.Compile(regexRule, 0)

ERROR: unknown unicode category, script, or property '%v'
 

Help ME!

**Comment by junyer** [comment]
I think you meant to post this on [Go discussions](https://github.com/golang/go/discussions)?

**Comment by junyer** [comment]
BTW, you probably want `\pP` for the `Punctuation` category. Also, RE2 syntax (which the Go `regexp` package uses) doesn't support look-around assertions.
