### ISSUE TITLE
cmake: missing option RE2_USE_ICU

### ISSUE THREAD

**Issue by t0b3** [google/re2#407]
in cmake the option to enable `RE2_USE_ICU` is missing. 
for distro packaging it would be great to have such an option available in CMakeLists.txt :+1: 

i.e. something 
```
if(USE_ICU)
    add_definitions(-DRE2_USE_ICU)
    ... handle compiler options
    ... handle linker options
endif

**Comment by junyer** [comment]
Thanks for the suggestion! I will see if I can get that working...

**Comment by junyer** [comment]
The `find_package(ICU REQUIRED COMPONENTS uc)` part is simple enough, but I believe `re2Config.cmake.in` and `re2.pc.in` would also need to be updated... and the latter would seem to warrant refactoring and other twiddling in `Makefile` as well. I still want to get this working, but it's looking less like a quick fix and more like wrestling in the mud with CMake.

**Comment by junyer** [comment]
I **_think_** that should suffice. If you have enough time in the next few days (i.e. before the `2023-02-01` release) to test and just verify that everything is WAI and that I have neither broken something nor overlooked anything, I would greatly appreciate it!

**Comment by t0b3** [comment]
compiles fine here (gentoo with custom ebuild) both with and without RE2_USE_ICU :rocket: 
NB: would it be useful to document the cmake way in the README in order for distros to pick it up?

**Comment by junyer** [comment]
> compiles fine here (gentoo with custom ebuild) both with and without RE2_USE_ICU 🚀

Thanks for confirming!

> NB: would it be useful to document the cmake way in the README in order for distros to pick it up?

Most package maintainers will be aware by now that RE2 supports CMake as well as GNU make, I think, but I'm not opposed to expanding the documentation in order to describe the former. Is there any specific content that you want to see? (Note to self: Update the [Install](https://github.com/google/re2/wiki/Install) wiki page too.)

**Comment by t0b3** [comment]
Nothing special, just announce `cmake` works as well...
NB: Are you going to support both `cmake` and `make` at feature parity for the future? Or is it time to prefer one over the other and make according announcement?

**Comment by junyer** [comment]
RE2 will support GNU make and CMake for the foreseeable future at feature parity modulo oversights such as the optional ICU dependency. (Historically, we didn't support `re2.pc` generation with CMake, but I fixed that a couple of months ago.) Without a strong case for removing support for, say, GNU make based on a comprehensive survey of packages in the wild, there's no compelling reason for me to force package maintainers (and others installing from source) to migrate to CMake.
