### ISSUE TITLE
How did the RE2 support the zero-length asseration?

### ISSUE THREAD

**Issue by JohnHerry** [google/re2#409]
I need some help about how to use the zero-length assertion feature in the RE2 library.  In Python the regular expression can suport 
lookahead/ negtive lookahead;  lookbehind/negtive lookbehind Regular expression,  How to translate such expression string in Python into C++ RE2  regex string?

**Comment by BurntSushi** [comment]
RE2 supports limited zero length assertions like `^`, `$` and `\b`. But that's it. There is no support for arbitrary look-ahead or look-behind. If you need to translate those regexes to RE2, then it, well, depends on the regex. Sometimes it can be translated to roughly equivalent regex with some capture groups, and sometimes it might be more appropriate to split it into two regexes.

**Comment by JohnHerry** [comment]
> RE2 supports limited zero length assertions like `^`, `$` and `\b`. But that's it. There is no support for arbitrary look-ahead or look-behind. If you need to translate those regexes to RE2, then it, well, depends on the regex. Sometimes it can be translated to roughly equivalent regex with some capture groups, and sometimes it might be more appropriate to split it into two regexes.

We need some rule to match only when the target pattern is not following some string and not followed by some string.
in Python it looks like:
(?<![0-9a-zA-Z])(google|apple|intel)(?![a-zA-Z\s]);
so that it will match only one of the three word when it is complete word even if  is mixed with other characters.
so when "Lintel",  "9intel" , they do not match.  when "きintel,", "όintel." they will match.
I had tried to write the reg string as 
\b(google|apple|intel)\b
but it not work as my expection.
is there any suggestion?

**Comment by junyer** [comment]
Please provide a minimal snippet of C++ code that reproduces the failure(s).

**Comment by JohnHerry** [comment]
> Please provide a minimal snippet of C++ code that reproduces the failure(s).

std::vector<std::string> items = {
    "Apple",
    "Google",
    "戴尔（Dell）",
    "微软（MicroSoft）"
}

const int numGroups = Re2::NumberofCaptureingGroups() + 1;
auto re_str = "\\\\b(" + boost::algorithm::join(items, "|") + ")\\\\b";

auto input_text = "产品：戴尔（Dell）,价格6000；产品:Apple,价格15000；";
re2::StringPiece subMatchArr[MAX_MATCHES];
re2::StringPiece* pSubMatch = &subMatchArr[0];
std::size_t sPos=0;
std::size_t ePos = input_text.length();
const re2::StringPiece textPiece(input_text);

while(sPos < ePos) {
    bool bMatched = Re2.Match(input_text, sPos, ePos, re2::RE2::UNANCHORED, pSubMatch, numGroups );
    ....
}

**Comment by junyer** [comment]
The problem is due to too much escaping: `"\\b"` → `\b` whereas `"\\\\b"` → `\\b`; consider using C++11 raw string literals. However, note also that RE2 supports `\b` for ASCII only.

Incidentally, the snippet is rather nonsensical: `re_str` looks like the pattern string, but isn't used anywhere; `Re2` looks like the `RE2` object, but isn't instantiated anywhere; `NumberofCaptureingGroups` is a misspelling of `NumberOfCapturingGroups`. In future, please provide code that compiles and runs and, just as importantly, indicates (in the manner of a unit test) what's expected versus what's obtained.

**Comment by JohnHerry** [comment]
> The problem is due to too much escaping: `"\\b"` → `\b` whereas `"\\\\b"` → `\\b`; consider using C++11 raw string literals. However, note also that RE2 supports `\b` for ASCII only.
> 
> Incidentally, the snippet is rather nonsensical: `re_str` looks like the pattern string, but isn't used anywhere; `Re2` looks like the `RE2` object, but isn't instantiated anywhere; `NumberofCaptureingGroups` is a misspelling of `NumberOfCapturingGroups`. In future, please provide code that compiles and runs and, just as importantly, indicates (in the manner of a unit test) what's expected versus what's obtained.

"RE2 supports \b for ASCII only", that is the problem, thanks for the help. Maybe we need other regex library in our casees.

**Comment by junyer** [comment]
This is a very specific case, of course, but generally speaking, segmentation for Asian languages (e.g. Chinese, Japanese) is well beyond "use a Unicode-aware `\b`"; see https://unicode-org.github.io/icu/userguide/boundaryanalysis/#word-boundary and https://unicode-org.github.io/icu/userguide/boundaryanalysis/#dictionary-based-breakiterator, for example.
