### ISSUE TITLE
Cannot parse regular expression: invalid perl operator: (?=

### ISSUE THREAD

**Issue by jeevanjoyappa** [google/re2#413]
Hi,

We are trying to move from athena to big query and the current code is using below regular expression.regexp_replace(col1, r"(d)(?=(ddd)+(?!d))", '$1,') but we are getting error Cannot parse regular expression: invalid perl operator: (?=.As per the big query re2 document  (?= is not supported.Is there any alternate to this which we can use?

**Comment by junyer** [comment]
Indeed, look-around assertions aren't supported. Based on the fragment of code that you pasted, I'm guessing that you're trying to insert commas as group separators? BigQuery supports [`CAST(1234 AS STRING FORMAT '999,999')`](https://cloud.google.com/bigquery/docs/reference/standard-sql/format-elements#format_group_separator), for example, so a regular expression isn't needed.

**Comment by jeevanjoyappa** [comment]
Thanks for the quick response. We were trying to do 2 things.1st one was to  insert comma has group separator and the solution you gave worked.2nd one if we had something like "a(20L" it should be replaced with "$20L".we are working on this.

**Comment by junyer** [comment]
That should be straightforward, I believe, but let me know if RE2 syntax makes the implementation difficult. Also, it's worth noting that BigQuery supports [JavaScript UDFs](https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions#javascript-udf-structure), so it should be possible to implement arbitrarily complex helper functions.
