### ISSUE TITLE
Flags not parsed correctly when using latin1 encoding

### ISSUE THREAD

**Issue by anuraaga** [google/re2#419]
I am trying to use latin1 encoding to allow expressions to match against arbitrary bytes (functionality used in WAFs). Using latin1 and matching arbitrary bytes worked swell. I found that flags such as `(?sm)` do not seem to get parsed when using latin1 though. It's treated as a repetition operator and the error `missing argument to repetition operator: '?'` is raised. The issue does not happen with default utf8 encoding.

I have a failing test case in go-re2, the wasm wrapper I've shared once before. If there is a better way to share the problem than a Go unit test, let me know but I'm hoping the problem is obvious enough with this description.

https://github.com/wasilibs/go-re2/pull/36/files

**Comment by junyer** [comment]
[`internal.Compile()`](https://github.com/wasilibs/go-re2/blob/528e98641e42a6caeead02f1effff7dca0f1ed6b/internal/re2.go#L47):

```
func Compile(expr string, posix bool, longest bool, caseInsensitive bool, latin1 bool) (*Regexp, error) {
```

[`re2.Compile()`](https://github.com/wasilibs/go-re2/blob/528e98641e42a6caeead02f1effff7dca0f1ed6b/re2.go#L45-L46):

```
func Compile(expr string) (*Regexp, error) {
	return internal.Compile(expr, false, false, false, false)
```

[`experimental.CompileLatin1()`](https://github.com/wasilibs/go-re2/blob/528e98641e42a6caeead02f1effff7dca0f1ed6b/experimental/experimental.go#L13-L14):

```
func CompileLatin1(expr string) (*re2.Regexp, error) {
	return internal.Compile(expr, true, true, false, true)
```

You presumably didn't mean for `posix` and `longest` to flip to `true`...

**Comment by anuraaga** [comment]
Yikes, sorry about that! (and time to define a struct indeed...)
