### ISSUE TITLE
Add CMake option to disable install

### ISSUE THREAD

**Issue by eesaber** [google/re2#425]
For CMake `FetchContent` use case, it would be great to have an option to allow user to enable/disable install

```cmake

option(RE2_INSTALL "install Re2" ON)
```
where default is `ON` for backward compatibility.

```cmake
if(RE2_INSTALL)
  install(TARGETS re2
        EXPORT re2Targets
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  #...
endif()
```

**Comment by junyer** [comment]
Although I see that, for example, Abseil provides `ABSL_ENABLE_INSTALL` for this, https://stackoverflow.com/a/65529161 says that `add_subdirectory(… EXCLUDE_FROM_ALL)` suffices.

**Comment by eesaber** [comment]
Thanks for the solution.

> https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_populate
> Note
> Where possible, prefer to use [`FetchContent_MakeAvailable()`](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable "fetchcontent_makeavailable") instead of implementing population manually with this command.

But, the CMake Documentation recommended to use `FetchContent_MakeAvailable()` where possible. 

If you would be open to add CMake install option, I am willing to send PR to fix this

**Comment by junyer** [comment]
It seems to me like something that `FetchContent_MakeAvailable()` should support, not something that each project should have to work around with yet another option plus the logic to install or not, so please file an issue against CMake.

**Comment by jchadwick-buf** [comment]
For what it's worth, this workaround no longer works. `EXCLUDE_FROM_ALL` doesn't do the desired thing.

The solution for this in CMake is, unfortunately, that each project has to solve this problem individually, just like Abseil did with `ABSL_ENABLE_INSTALL`. Please consider re-opening the issue.
