### ISSUE TITLE
Abseil cannot be used as a submodule

### ISSUE THREAD

**Issue by s-perron** [google/re2#427]
A recent change added a dependency on Abseil. The problem we are having is that SPIR-V Tools tries to include all of the depencies by including the source files. The line below can only find Abseil as a package.

https://github.com/google/re2/blob/1e44e72d31ddc66b783a545e9d9fcaa876a146b7/CMakeLists.txt#L75

Would it be possible for this to be changed to something similar to the way Abseil includes gtest?

https://github.com/abseil/abseil-cpp/blob/d23adc1cfba78931b4aa2edb81f10a39135d2d24/CMakeLists.txt#L142

That way, I could include Abseil as a dependency for spirv-tools, and RE2 could get the targets from there.  THanks.

**Comment by junyer** [comment]
Thanks for the report! I'm wondering whether things could be a bit more automagical. What if we probe for, say, `absl::base` and then call `find_package(absl REQUIRED)` only when the target doesn't exist? That way, if the top-level project has called `add_directory(abseil-cpp)` already (possibly indirectly), that will take precedence over any copy of Abseil that might have been installed on the system. How does that sound? :)

**Comment by s-perron** [comment]
That sounds good.

**Comment by juan-lunarg** [comment]
That sounds like a good solution. We currently use that approach the Vulkan Extension Layer repo:
```
if (NOT TARGET Vulkan::Headers)
    find_package(VulkanHeaders CONFIG REQUIRED QUIET)
endif()
```

Also worth noting the Vulkan SDK and package managers in general (vcpkg/conan/apt/etc) have a much easier time building projects when they use `find_package` instead of `add_subdirectory`.

**Comment by junyer** [comment]
> That sounds like a good solution. We currently use that approach the Vulkan Extension Layer repo:

Sweet, thanks for confirming!
