### ISSUE TITLE
Issues with RE2_BUILD_TESTING=ON on windows

### ISSUE THREAD

**Issue by h-vetinari** [google/re2#429]
Hi all!

I help package re2 for conda-forge, and was running into some issues while working on [updating](https://github.com/conda-forge/re2-feedstock/pull/66) our recipe to 2023-06-01. 

Namely, we always build shared libs (we can handle the ABI impact, and then it's much saner from a distribution standpoint), but when (re-[^1])enabling `RE2_BUILD_TESTING=ON`, I run into two problems:
* `testing.lib` is not found. This is because `WINDOWS_EXPORT_ALL_SYMBOLS` is only [set](https://github.com/google/re2/blob/2023-06-01/CMakeLists.txt#L145) for the main library, not for the test artefacts. Not too hard to work around, but thought I'd mention it.
* `USEPCRE=OFF` does not seem to work, in that one test target (`regexp_benchmark.exe`) that depends on pcre still tries to build, and obviously fails when pcre is not present, details below the fold

[^1]: We ran the tests without issues for 2023-03-01, AFAICT this was switched off by default with [`ed083f5`](https://github.com/google/re2/commit/ed083f535e4bd66eef4e6c1d548eb117095916af)

<details>
<summary>error log</summary>

```
[74/74] Linking CXX executable regexp_benchmark.exe
FAILED: regexp_benchmark.exe 
cmd.exe /C "cd . && %BUILD_PREFIX%\Library\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\regexp_benchmark.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\link.exe /nologo CMakeFiles\regexp_benchmark.dir\re2\testing\regexp_benchmark.cc.obj  /out:regexp_benchmark.exe /implib:regexp_benchmark.lib /pdb:regexp_benchmark.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console  testing.lib  %PREFIX%\Library\lib\benchmark_main.lib  re2.lib  %PREFIX%\Library\lib\absl_flags.lib  %PREFIX%\Library\lib\absl_flags_internal.lib  %PREFIX%\Library\lib\absl_flags_marshalling.lib  %PREFIX%\Library\lib\absl_flags_reflection.lib  %PREFIX%\Library\lib\absl_flags_config.lib  %PREFIX%\Library\lib\absl_flags_program_name.lib  %PREFIX%\Library\lib\absl_flags_private_handle_accessor.lib  %PREFIX%\Library\lib\absl_flags_commandlineflag.lib  %PREFIX%\Library\lib\absl_flags_commandlineflag_internal.lib  %PREFIX%\Library\lib\abseil_dll.lib  %PREFIX%\Library\lib\gtest.lib  %PREFIX%\Library\lib\benchmark.lib  shlwapi.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\link.exe /nologo CMakeFiles\regexp_benchmark.dir\re2\testing\regexp_benchmark.cc.obj /out:regexp_benchmark.exe /implib:regexp_benchmark.lib /pdb:regexp_benchmark.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console testing.lib %PREFIX%\Library\lib\benchmark_main.lib re2.lib %PREFIX%\Library\lib\absl_flags.lib %PREFIX%\Library\lib\absl_flags_internal.lib %PREFIX%\Library\lib\absl_flags_marshalling.lib %PREFIX%\Library\lib\absl_flags_reflection.lib %PREFIX%\Library\lib\absl_flags_config.lib %PREFIX%\Library\lib\absl_flags_program_name.lib %PREFIX%\Library\lib\absl_flags_private_handle_accessor.lib %PREFIX%\Library\lib\absl_flags_commandlineflag.lib %PREFIX%\Library\lib\absl_flags_commandlineflag_internal.lib %PREFIX%\Library\lib\abseil_dll.lib %PREFIX%\Library\lib\gtest.lib %PREFIX%\Library\lib\benchmark.lib shlwapi.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:regexp_benchmark.exe.manifest" failed (exit code 1120) with the following output:
regexp_benchmark.cc.obj : error LNK2019: unresolved external symbol "public: static class re2::PCRE::Arg re2::PCRE::no_more_args" (?no_more_args@PCRE@re2@@2VArg@12@A) referenced in function "void __cdecl re2::ASCIIMatchPCRE(class benchmark::State &)" (?ASCIIMatchPCRE@re2@@YAXAEAVState@benchmark@@@Z)
regexp_benchmark.cc.obj : error LNK2019: unresolved external symbol "public: static struct re2::PCRE::FullMatchFunctor const re2::PCRE::FullMatch" (?FullMatch@PCRE@re2@@2UFullMatchFunctor@12@B) referenced in function "void __cdecl re2::FullMatchPCRE(class benchmark::State &,char const *)" (?FullMatchPCRE@re2@@YAXAEAVState@benchmark@@PEBD@Z)
regexp_benchmark.cc.obj : error LNK2019: unresolved external symbol "public: static struct re2::PCRE::PartialMatchFunctor const re2::PCRE::PartialMatch" (?PartialMatch@PCRE@re2@@2UPartialMatchFunctor@12@B) referenced in function "void __cdecl re2::ASCIIMatchPCRE(class benchmark::State &)" (?ASCIIMatchPCRE@re2@@YAXAEAVState@benchmark@@@Z)

regexp_benchmark.exe : fatal error LNK1120: 3 unresolved externals
```

</details>

**Comment by junyer** [comment]
Thanks for the report! While trying to fix the build recently, I switched from setting the `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` variable to setting the `WINDOWS_EXPORT_ALL_SYMBOLS` property on the `re2` target and **_not_** on the `testing` target, but given that the change didn't seem to help, I'm going to undo it and thereby solve the first problem, I hope.

The second problem is baffling, honestly, because nothing to do with the `USEPCRE` option has been touched for **_years_**. (Our CI doesn't set it, FWIW, and doesn't exhibit the problem.) Do you have any workarounds that might suggest what causes it?

**Comment by junyer** [comment]
Oh, I reckon that I understand the second problem now: `testing` is no longer forced to be a static library, which means that the three **_data_** symbols now need to be exported manually (or replaced) because CMake doesn't handle them. \*headdesk*

**Comment by h-vetinari** [comment]
> The CI is green, so you should be good to go at commit [7c5e396](https://github.com/google/re2/commit/7c5e396af825562ec8321fdbf2f1cf276b26e3ae), which I have tagged as release `2023-06-02`. :)

Thanks a lot for the quick handling, much appreciated! :)
