### ISSUE TITLE
win32 wheel builds

### ISSUE THREAD

**Issue by adityagoel4512** [google/re2#438]
Would it be possible to add support for shipping win32 wheel builds in https://github.com/google/re2/blob/main/.github/workflows/python.yml?

I'm happy to provide a PR but any Bazel pointers would be appreciated.

**Comment by junyer** [comment]
That should be pretty straightforward, I think. I'm going to make a couple of tweaks to the workflow as well.

**Comment by junyer** [comment]
Just to be clear, some bits might have rotted since November, but I wouldn't be releasing `google-re2` 1.1 before tagging the `2023-08-01` release anyway, so I have a couple more days to sort things out...

**Comment by adityagoel4512** [comment]
All good, thank you!

**Comment by junyer** [comment]
After shaving various yaks (including https://github.com/pybind/pybind11_bazel/commit/ff261d2e9190955d0830040b20ea59ab9dbe66c8), I believe that things are ready for next week...

**Comment by junyer** [comment]
See https://pypi.org/project/google-re2/#files. :)

**Comment by adityagoel4512** [comment]
Thanks again!
