### ISSUE TITLE
Interacting with NFA

### ISSUE THREAD

**Issue by remyschwab** [google/re2#440]
Hello,

I was wondering if there is an API to interact with the NFA built from the RegEx.

Thank you,
Remy

**Comment by junyer** [comment]
Sorry, RE2 doesn't provide any public, supported interfaces for accessing the `Regexp` (parsed form) or the `Prog` (compiled form) of a regular expression. If you fork or vendor RE2, you could expose those internal interfaces however you like, but you would probably be better off using something like https://github.com/katef/libfsm instead.
