### ISSUE TITLE
^+test is considered to be correct regex

### ISSUE THREAD

**Issue by ikettaneh** [google/re2#442]
Regular expressions such as `^+abc`, `$+abc`, `^*abc`, and `$*abc` are validated to be correct. Is that the intended behaviour?

For example, all the expectations below will fail.

```
  RE2 example_1("^+abc");
  EXPECT_FALSE(example_1.ok());

  RE2 example_2("$+abc");
  EXPECT_FALSE(example_2.ok());
  
  RE2 example_3("$*abc");
  EXPECT_FALSE(example_3.ok());
  
  RE2 example_4("$*abc");
  EXPECT_FALSE(example_4.ok());
```

**Comment by junyer** [comment]
Yes, it's WAI, but its meaningfulness varies depending on the quantifier.

FWIW, Perl carps about `^*`, `^+` and `^?` in different ways:

```
$ perl -Wlpe 'print if /^*abc/;'
^* matches null string many times in regex; marked by <-- HERE in m/^* <-- HERE abc/ at -e line 1.
^D
$ perl -Wlpe 'print if /^+abc/;'
^+ matches null string many times in regex; marked by <-- HERE in m/^+ <-- HERE abc/ at -e line 1.
Quantifier unexpected on zero-length expression in regex m/^+abc/ at -e line 1.
^D
$ perl -Wlpe 'print if /^?abc/;'
^D
$ 
```

OTOH, Python raises `re.error: nothing to repeat at position 1` in each case.

**Comment by BurntSushi** [comment]
And note that even for regex engines that emit errors, you can usually do things like `(?:^)*` to squash the errors with a semantically equivalent regex.

**Comment by junyer** [comment]
Indeed, Python doesn't raise for `(?:^)*`, `(?:^)+` and `(?:^)?`. Funnily enough, Perl still carps. :)
