### ISSUE TITLE
GCC does not recognize '-Wl' option while make testinstall in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by chaebkimm** [google/re2#443]
In [Makefile:21-23](https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L21-L23) '-Wl' is removed in LDABSL because it causes GCC error in Ubuntu 22.04.
https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L21-L23

Removal of '-Wl' could be applied to [Makefile:361](https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L361), [371](https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L371) to suppress g++ error when make testinstall in ubuntu 22.04.
https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L361
https://github.com/google/re2/blob/73031bbc08cb3e3200497be4a50e37d6f3acc1d0/Makefile#L371

**Comment by junyer** [comment]
Thanks for the report! Will do. :)
