### ISSUE TITLE
undefined reference issue with simple hello example

### ISSUE THREAD

**Issue by th3r0b0t** [google/re2#444]
Good day,
I'm trying to use re2 with a simple c++ application as below:
```cpp
#include <iostream>
#include <re2/re2.h>

int main()
{
    absl::string_view x = "shad";
    re2::RE2 re("h.*o");
    const  re2::RE2::Arg* const args = new re2::RE2::Arg();
    int n;
    std::cout << re2::RE2::FullMatchN(x, re,
                                      reinterpret_cast<const RE2::Arg *const *>(args), n);
    return 0;
}
```
```cpp
#include <iostream>
#include <re2/re2.h>

int main()
{
    std::cout << re2::RE2::FullMatch("hello", "h.*o");
    return 0;
}
```
Neither of above code works! Both throwing this linker error:
```sh
/usr/bin/ld: /tmp/ccGSs3Xk.o: in function `main':
main.cpp:(.text+0x99): undefined reference to `re2::RE2::FullMatchN(std::basic_string_view<char, std::char_traits<char> >, re2::RE2 const&, re2::RE2::Arg const* const*, int)'
collect2: error: ld returned 1 exit status
```
Complied with this command:
```sh
g++ main.cpp -L/usr/lib -lre2
```
I installed **`Abseil`** and **`re2`** like this:
```sh
sudo apt install libabsl-dev
sudo apt install libre2-dev
```
Running on Ubuntu 23.04  

----------
I've also tried to build re2 by myself as instructed in quickStart, However it failed as I mentioned full problem here in StackOverflow:
https://stackoverflow.com/questions/77035742/how-to-install-and-add-google-re2-to-a-c-application

It worth mentioning that my final goal is to add `re2` to my CMake application.
I'm not fully understood how I'm supposed to add `Abseil` dependency for `re2`? Should I build from source and `make install` them both? Should `Abseil` and `re2` both resides in a sub-directory of my project each; Or maybe, `Abseil` inside a sub-directory of `re2`?
Thanks in advance

**Comment by junyer** [comment]
Ubuntu 23.04 has `libre2-dev` version `20230201-1`, I think, which predates the Abseil dependency by some months, so you should use `re2::StringPiece`, not `absl::string_view`/`std::string_view`.

To use the bleeding-edge versions of Abseil and RE2 with CMake, you should build and install Abseil **_and RE2_** with CMake. In that case, `find_package(re2 REQUIRED)` and the `re2::re2` target should Just Work™.

**Comment by th3r0b0t** [comment]
> Ubuntu 23.04 has `libre2-dev` version `20230201-1`, I think, which predates the Abseil dependency by some months, so you should use `re2::StringPiece`, not `absl::string_view`/`std::string_view`.
> 
> To use the bleeding-edge versions of Abseil and RE2 with CMake, you should build and install Abseil **_and RE2_** with CMake. In that case, `find_package(re2 REQUIRED)` and the `re2::re2` target should Just Work™.

Please advise me through this if possible:
I just `git clone` the Abseil Github repo and put it under `project/abseil-cpp/` then `git clone` the re2 and place it inside `project/re2/`.
Now if in the root directory's `CmakeList.txt` (i.e. `project/`)  I put `find_package(re2 REQUIRED)` and `target_link_libraries(project re2::re2)` it'll be enough?
I'm sorry for such newbie question, I'm new to CMake

**Comment by th3r0b0t** [comment]
I'll try it rn and close the issue/report any problem when it's done.
My greatest regards for such instant answer.

**Comment by th3r0b0t** [comment]
> https://abseil.io/docs/cpp/quickstart-cmake walks through using a subdirectory and `add_subdirectory(abseil-cpp)`. OTOH, https://abseil.io/docs/cpp/tools/cmake-installs walks through installing and using `find_package(absl REQUIRED)`. I prefer the latter, personally, but the former is okay too. Once you get Abseil working, getting RE2 working will be a very similar process.

I have no word to thank you! Being as humble to teach me with with patience and also answering in no time.
I got it up and running following the latter solution; However I think for newbies to CMake system like me, It'll be a great help if you write this solution somewhere in Install section of wiki or else.
I'll be happy to submit it if you think it'll help.

**Comment by junyer** [comment]
Glad to help! Sure, I can poke some details into the [Install](https://github.com/google/re2/wiki/Install) page about this. :)
