### ISSUE TITLE
Lockless re2

### ISSUE THREAD

**Issue by rschu1ze** [google/re2#446]
Hi,
we ([ClickHouse](https://github.com/ClickHouse/ClickHouse)) used to use a variant of re2 where internal locking was patched out (in an admittedly hacky way). Details of the source-to-source transformation from re2 to "re2_st", i.e. "single-threaded", can be found here:
- https://github.com/ClickHouse/ClickHouse/blob/23.5/contrib/re2-cmake/CMakeLists.txt
- https://github.com/ClickHouse/ClickHouse/blob/23.5/contrib/re2-cmake/re2_transform.cmake

The underlying idea was that the calling program already takes care that pattern compilation and evaluation are properly synchronized, i.e. single-threaded or protected by mutexes etc. The re2-to-re2_st transformation broke for us when re2 moved from its own locking to abseil locking.

I believe the situation that higher layers provide synchronization is rather common. Therefore, would it be possible to relax the locking in re2, either as a runtime-option (e.g. via some flag during pattern compilation) or at build time (e.g. via some build system option)?

**Comment by junyer** [comment]
Sorry, this isn't something that I'm keen to support upstream. Having said that, if the reader–writer mutex in the `DFA` class is the primary target here, there **_is_** a way that you can swap in another mechanism somewhat more conveniently:

https://github.com/google/re2/blob/09de536bb7c77c2e0869a001f012d49560f56cbe/re2/dfa.cc#L168-L169

Within Google, we simply do something like this:

```
#if defined(…)
#include …
#endif

…

  // Make it easier to swap in a scalable reader-writer mutex.
#if defined(…)
  using CacheMutex = …;
#else
  using CacheMutex = absl::Mutex;
#endif
```

**Comment by rschu1ze** [comment]
Thanks, I'll try that!
