### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by gozdal** [google/re2#454]
Would it be possible to build wheels for Python package https://pypi.org/project/google-re2/ for Python 3.12? It seems that building `re2` is challenging, especially for Windows, pre-built wheels for Python 3.12 would be great.

**Comment by junyer** [comment]
In theory, it's simply a matter of adding `'3.12'` to `matrix.ver` in the GitHub Actions workflow. In practice, it's also a matter of waiting for GitHub Actions to support Python 3.12 across Linux, macOS and Windows, which should be quite soon, I think.

**Comment by gozdal** [comment]
It seems that there is a 3.12.0 release in https://github.com/actions/python-versions/releases/tag/3.12.0-6381888192
Not sure if this is enough though?

**Comment by junyer** [comment]
I was looking at [this](https://github.com/actions/runner-images/issues/8626#issuecomment-1776883352) comment posted yesterday.

**Comment by junyer** [comment]
Well, I kept tripping over technical debt in the GitHub Actions workflow, but I **_think_** Python 3.12 is ready to roll, so I'm going to try to publish wheels tonight.

**Comment by junyer** [comment]
`google_re2-1.1-3-cp312-cp312-win_amd64.whl` and `google_re2-1.1-3-cp312-cp312-win32.whl` have been published to PyPI as per https://pypi.org/project/google-re2/#files. Enjoy. :)

**Comment by gozdal** [comment]
Thanks!
