### ISSUE TITLE
Memory leak issue observed in RE2 

### ISSUE THREAD

**Issue by vinaygund** [google/re2#457]
Here is the callstack from SOAK run done over the period of 4 days , 
this particular callstack where there is call to functions from RE2 is allocation memory but deallocation is not happening. 

can anyone please help me with this, how can I resolve this memory leak issue ?

// Each log entry has the following syntax:                                 
//                                                                          
// + BYTES_DELTA (NEW_BYTES - OLD_BYTES) NEW_COUNT allocs BackTrace TRACEID 
// + COUNT_DELTA (NEW_COUNT - OLD_COUNT) BackTrace TRACEID allocations      
//     ... stack trace ...                                                  
//                                                                          
// where:                                                                   
//                                                                          
//     BYTES_DELTA - increase in bytes between before and after log         
//     NEW_BYTES - bytes in after log                                       
//     OLD_BYTES - bytes in before log                                      
//     COUNT_DELTA - increase in allocations between before and after log   
//     NEW_COUNT - number of allocations in after log                       
//     OLD_COUNT - number of allocations in before log                      
//     TRACEID - decimal index of the stack trace in the trace database     
//         (can be used to search for allocation instances in the original  
//         UMDH logs).                                                      
//                                                                          

+  635096 ( 635096 -      0)    743 allocs	BackTraceAE73
+     743 (    743 -      0)	BackTraceAE73	allocations

	ntdll!RtlAllocateHeap+4146
	ntdll!RtlAllocateHeap+72C
	XYZ!**_malloc_base**+44 (minkernel\crts\ucrt\src\appcrt\heap\malloc_base.cpp, 34)
	XYZ!**operator new**+1F (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp, 35)
	XYZ!**re2::DFA::CachedState**+FE (c:\jenkins\workspace\ABC\Thirdparty\re2\dfa.cc, 755)
	XYZ!**re2::DFA::WorkqToCachedState**+2E2 (c:\jenkins\workspace\ABC\Thirdparty\re2\dfa.cc, 716)
	XYZ!**re2::DFA::RunStateOnByte**+392 (c:\jenkins\workspace\ABC\Thirdparty\re2\dfa.cc, 1084)
	XYZ!**re2::DFA::InlinedSearchLoop<0,0,1>**+16D (c:\jenkins\workspace\ABC\Thirdparty\re2\dfa.cc, 1400)
	XYZ!**re2::Prog::SearchDFA**+1B5 (c:\jenkins\workspace\ABC\Thirdparty\re2\dfa.cc, 1865)
	XYZ!**re2::RE2::Set::Match**+112 (c:\jenkins\workspace\ABC\Thirdparty\re2\set.cc, 144)
	XYZ!**Re2SetHandle::MatchSet**+9E (c:\jenkins\workspace\ABC\Thirdparty\re2\re2_helper.cpp, 125)
	
	
	
	Regards Vinay.

**Comment by junyer** [comment]
Without knowing anything about `Re2SetHandle` or even what a "SOAK run" is, I can only speculate that the `RE2::Set` object isn't destructed. (`RE2::Set` uses the DFA execution engine, which caches DFA states, so that's why the stack trace looks as it does.) In order for me to provide **_any_** specific guidance, you will need to disclose more context and, ideally, pertinent code.

**Comment by vinaygund** [comment]
> Without knowing anything about `Re2SetHandle` or even what a "SOAK run" is, I can only speculate that the `RE2::Set` object isn't destructed. (`RE2::Set` uses the DFA execution engine, which caches DFA states, so that's why the stack trace looks as it does.) In order for me to provide **_any_** specific guidance, you will need to disclose more context and, ideally, pertinent code.

Hi @junyer 

The term "SOAK " is a testing run performed over a period of few days, where the application is continuously subjected to testing conditions. The provided call stack and information about memory allocations suggest that there may be a memory leak issue in the tested software, where memory is being allocated but not properly deallocated over time.

this is Re2SetHandle class 

class Re2SetHandle
{
public:
    Re2SetHandle(const bool caseSensitive, const bool fullMatch);
    Re2SetHandle() = delete;
    bool AddPatternToSet(const char* const pattern);
    bool CompileSet();
    bool MatchSet(const char* const testString,
        const int** const ppMatchingIndices,
        size_t* const     pMatchingIndexCount);
    const std::string& GetErrorMessage() const { return m_lastErrorMessage; } 
    ~Re2SetHandle();
private:
    **std::unique_ptr<re2::RE2::Set> m_Re2Set;**
    std::vector<int> m_matchingIndices;
    std::string      m_lastErrorMessage;
};


and this is "XYZ!Re2SetHandle::MatchSet+9E (c:\jenkins\workspace\ABC\Thirdparty\re2\re2_helper.cpp, 125)"

bool Re2SetHandle::MatchSet(
    const char* const testString,
    const int** const ppMatchingIndices,
    size_t* const     pMatchingIndexCount)
{
    auto success{ true };

    try
    {
        m_lastErrorMessage.clear();

        if (!testString || !ppMatchingIndices || !pMatchingIndexCount)
        {
            throw std::invalid_argument{ "Invalid argument(s)." };
        }

        *ppMatchingIndices = nullptr;
        *pMatchingIndexCount = 0;

        m_matchingIndices.clear();

        if (m_Re2Set->Match(testString, &m_matchingIndices))      //line 125
        {
            *ppMatchingIndices = m_matchingIndices.data();
            *pMatchingIndexCount = m_matchingIndices.size();
        }
        else
        {
            success = false;
        }
    }
    catch (const std::exception& ex)
    {
        m_lastErrorMessage = ex.what();
        success = false;
    }

    return success;
}

and        "line number 125 :- if (m_Re2Set->Match(testString, &m_matchingIndices))"

this is the relevant code from my project  , after this all the functions from RE2 are called where memory deallocation is not happening.

your previous reply was helpful , please have a look at this.
I will be waiting for your response, Thank you.

**Comment by junyer** [comment]
The use of `std::unique_ptr<re2::RE2::Set>` is all well and good, but now the question is whether the `Re2SetHandle` object is destructed. The second stack trace shows a memory allocation that occurs during compilation, which is expected. There's still no indication that there's a memory leak in RE2 itself. The allocations will indeed have corresponding deallocations iff the calling code completes and the object "hierarchy" is cleaned up correctly.
