### ISSUE TITLE
Data race condition in void DFA::RWLocker::LockForWriting() 

### ISSUE THREAD

**Issue by vinaygund** [google/re2#464]
Hi , in my project I use Coverity tool {Coverity is a static analysis tool used for identifying software security vulnerabilities, quality defects, and code maintenance issues in source code.}

in dfa.cc file line 1132.

![image](https://github.com/google/re2/assets/145984632/5cb1e816-3c8e-46d4-bc39-21ac960d82ae)

-------------------------------------------------------------------

this is the code and warning reported by coverity in above snapshot ,

 
1130// This function is marked as NO_THREAD_SAFETY_ANALYSIS because
1131// the annotations don't support lock upgrade.
1132void DFA::RWLocker::LockForWriting() NO_THREAD_SAFETY_ANALYSIS {
    	
CID 155380 (#1 of 1): Data race condition (MISSING_LOCK)
1. missing_lock: Accessing this->writing_ without holding lock re2::Mutex.mutex_. Elsewhere, re2::DFA::RWLocker.writing_ is written to with Mutex.mutex_ held 1 out of 1 times (1 of these accesses strongly imply that it is necessary).
1133  if (!writing_) {
1134    mu_->ReaderUnlock();
    	A1. lock_acquire: Example 1: Calling WriterLock acquires lock re2::Mutex.mutex_. [[hide details](http://watcoverity2.mcafee.int/eventId=42605752-1&modelId=42605752-0&fileInstanceId=161945198&filePath=%2FThirdparty%2Fre2%2Futil%2Fmutex.h&fileStart=54&fileEnd=54)]
1135    mu_->WriterLock();
[/Thirdparty/re2/util/mutex.h](http://watcoverity2.mcafee.int/fileInstanceId=/161945198&defectInstanceId=/42605752&modelId=/42605752-0)
53  inline void ReaderUnlock(); // Release a read share of this Mutex
  	A1. lock: Lock locks this->mutex_.
54  inline void WriterLock() { Lock(); }     // Acquire an exclusive lock
55  inline void WriterUnlock() { Unlock(); } // Release a lock from WriterLock()
    	A2. example_access: Example 1 (cont.): re2::DFA::RWLocker.writing_ is written to with lock re2::Mutex.mutex_ held.
1136    writing_ = true;
1137  }
1138}
1139

please provide your feedback.

Regards vinay

**Comment by junyer** [comment]
This is a false positive. I'm guessing that Coverity doesn't recognise `NO_THREAD_SAFETY_ANALYSIS`.

**Comment by junyer** [comment]
Oh, hang on. You are using an older version of RE2 that predates the Abseil dependency. `NO_THREAD_SAFETY_ANALYSIS` was a no-op, which is presumably why the false positive arose. Nowadays, `ABSL_NO_THREAD_SAFETY_ANALYSIS` is used and Coverity should hopefully recognise that.
