### ISSUE TITLE
What is the 'sam' command used in doc scripts?

### ISSUE THREAD

**Issue by dolmen** [google/re2#466]
The scripts in the [doc](https://github.com/google/re2/tree/main/doc) directory use a `sam` command that looks like `sed`. Where does it comes from?

**Comment by dolmen** [comment]
I've just submitted [CL 62250](https://code-review.googlesource.com/c/re2/+/62250), but I've not been able to run the script because of this issue.

**Comment by junyer** [comment]
That would be https://en.wikipedia.org/wiki/Sam_(text_editor). If it helps, I install the [`9base`](https://packages.debian.org/trixie/9base) package temporarily whenever it happens to be necessary for me to run one of those scripts.

P.S. Thanks for the patch!
