### ISSUE TITLE
Fail on negative lookbehind regex compilation

### ISSUE THREAD

**Issue by rafalszeflerrtb** [google/re2#468]
re2, when used in versions 2023-11-01 and 2023-09-01 fails on negative lookbehind compilation. I'm using pyre2 lib compiled directly, with directly compiled re2 from sources. Machine: Macbook Pro M2, MacOS Ventura 13.3. Then I see:

```
>>> import re2
>>> re2.compile(r"(?<!t)\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "compile.pxi", line 6, in re2.compile
  File "compile.pxi", line 93, in re2._compile
re.error: invalid named capture group: (?<!t)\n
```

It seems that the lib interprets the pattern as capture group, while it should be interpreted as negative lookbehind.

This is under Python 3.10, as I said, with pyre2 library. I see the same behaviour with fb-re2 and associated google-re2 library.

Note that all 3 libs work correctly when compiled with re2 in older version, e.g. 2023-08-01.

Note 2: I didn't test it, but it is likely it fails with positive lookbehind `(?<=` as well.

**Comment by junyer** [comment]
It almost certainly changed due to commit 6148386f0c8f03da1ab0bf982a4dbe080b4ea7bc, which was in the `2023-09-01` release. However, given that RE2 doesn't support look-around assertions, is the desire here simply to correct the error message?

**Comment by rafalszeflerrtb** [comment]
@junyer it seems to work for me in. In version 2023-08-01:

```
>>> import re2
>>> p = re2.compile(r'(?<!t)\n')
>>> p.match('\n') is not None
True
>>> p.match(t\n') is not None
False
```
Am I missing something?

**Comment by rafalszeflerrtb** [comment]
@junyer oh, wow, really? Am I completely wrong that I saw it work?

**Comment by junyer** [comment]
Digging quickly, I believe [this](https://github.com/andreasvc/pyre2/blob/76cdec765244a8ff24f2e3088af1d3b0b6faba22/src/compile.pxi#L88-L93) triggers now (i.e. the error code is no longer `ErrorBadPerlOp`) whereas the previous behaviour must have been to fall back to the `re` module, which does support look-around assertions.

I'm keen to correct the error message, but bearing in mind the holidays, I anticipate the fix will be in the `2024-02-01` release.

**Comment by rtb-zla-karma** [comment]
I used `re` as fallback? This can be quite useful. Maybe the right solution is to raise proper warning by default about unsupported feature and also informing that it can fallback to `re` when some parameter(?), env var(?) is set.

**Comment by junyer** [comment]
`pyre2` is a completely separate project. `google-re2` doesn't fall back to the `re` module.
