### ISSUE TITLE
configure some PREFIX or special CONFIG something

### ISSUE THREAD

**Issue by jefby** [google/re2#47]
Hi , the default linux application usage is like ./configure --prefix=xxxx && make && make install , and now i want to compute the --prefix location  via some commands in outer wrapper Makefile, do you know how to configure it (use some configure file),thanks very much!

**Comment by junyer** [comment]
The RE2 `Makefile` contains this line:

```
prefix=/usr/local
```

You can override that value by doing something like this in your `Makefile`:

```
        $(MAKE) -e prefix=$(YOURPREFIX) install
```

Will that suffice for your purposes?

**Comment by jefby** [comment]
@junyer Yes, it can work.Thanks very much.
