### ISSUE TITLE
Non-greedy qualifier doesn't work with end-anchor

### ISSUE THREAD

**Issue by b-pass** [google/re2#479]
Regex: `\A.*x(.*?)y\z`
Input: "aaaxbbby xccccy"
Expected: `res[1]` should be "cccc"
Actual: `res[1]` is "bbby xcccc"

Simple driver program:
```c++
#include <re2/re2.h>
#include <iostream>
int main()
{
        re2::RE2 rx(R"(\A.*x(.*?)y\z)");
        absl::string_view d = "aaaxbbby xccccy";
        constexpr int nres = 2;
        absl::string_view res[nres];
        if (!rx.Match(d, 0, d.size(), re2::RE2::UNANCHORED, res, nres)) {
                std::cout << "No match\n";
        }
        else {
                std::cout << "Match:\n";
                for (int i = 0; i < nres; ++i)
                        std::cout << (i+1) << "=(" << res[i].size() << ")=" << res[i] << std::endl;
        }
        return 0;
}
```

I have figured out that changing [line 750 of re2.cc](https://github.com/google/re2/blob/dbf15a205c5b28fe7e8c43df2e036bbf47c9cb57/re2/re2.cc#L750) fixes this problem:
```diff
         if (!prog->SearchDFA(subtext, text, Prog::kAnchored,
-                             Prog::kLongestMatch, matchp, &dfa_failed, NULL)) {
+                             kind, matchp, &dfa_failed, NULL)) {
```

But I am not sure if that would break something else...?

**Comment by BurntSushi** [comment]
The actual result you report is correct.

**Comment by b-pass** [comment]
Hmm, ok, what about for the pattern `\A.*x(.*?)y\z`?  That one also exhibits the same behavior, but I think should have a the shorter match in the capture group because it is non-greedy.

**Comment by BurntSushi** [comment]
Greediness (or not) does not override prioritizing finding the **leftmost** match.

**Comment by b-pass** [comment]
Ah, ok, leftmost.  That makes sense. But for re2, that seems counter to the setting the "longest_match" option to false (the default) for these patterns. 

Since re2 is working backwards, this is not the first match (the shorter one), it is the longest and leftmost match.

If you're wondering why I care, it's because there is no `RE2::ANCHOR_END` and so using `\z` is the closest that one can get to that behavior.

**Comment by b-pass** [comment]
I've updated the original post with the slightly modified regex.  Leftmost or not, all other engines I could easily try (all of the ones on regex101.com) return the shorter match for this group.

**Comment by junyer** [comment]
Here's your code snippet after some minor tweaking because I thought that I would be adding it to `re2_test.cc` imminently:

```
TEST(RE2, Issue479) {
  absl::string_view s = "aaaxbbby xccccy";
  RE2 re(R"(\A.*x(.*?)y\z)");
  constexpr int nsubmatch = 2;
  absl::string_view submatch[nsubmatch];
  ASSERT_TRUE(re.Match(s, 0, s.size(), RE2::UNANCHORED, submatch, nsubmatch));
  auto log_submatch = [&](int i) {
    LOG(INFO) << "$" << i
              << " at (" << (submatch[i].data() - s.data())
              << "," << (submatch[i].data() + submatch[i].size() - s.data())
              << ") is \"" << submatch[i] << "\"";
  };
  for (int i = 0; i < nsubmatch; i++)
    log_submatch(i);
}
```

Here's the output, which disagrees with what you observed:

```
[ RUN      ] RE2.Issue479
re2/testing/re2_test.cc:1687: $0 at (0,15) is "aaaxbbby xccccy"
re2/testing/re2_test.cc:1687: $1 at (10,14) is "cccc"
[       OK ] RE2.Issue479 (0 ms)
```

I also tried adding your test case to `search_test.cc` in order to cross-check with different execution engines – even against PCRE itself! – and still couldn't reproduce what you observed.

I guess it might help to disclose what version of RE2 you are using and whether it has any local modifications. Otherwise, I'm probably not going to be able to assist further.
