### ISSUE TITLE
Success but unsuppressable stderr message when compiling an empty `re2.Filter`

### ISSUE THREAD

**Issue by masklinn** [google/re2#485]
```python
>>> import re2
>>> f = re2.Filter()
>>> f.Compile()
re2/filtered_re2.cc:74: Compile called before Add.
```
The message is emitted by `FilteredRE2::Compile`: https://github.com/google/re2/blob/108914d28a79243d4300e7e651cd0a0d5883ca0f/re2/filtered_re2.cc#L73-L76 and there doesn't seem to be any hook to suppress it e.g. it does not call `Options::log_errors`

But that does not return any sort of error signal. It also does not return any sort of failure signal, so while `Filter.Compile` checks for compilation error: https://github.com/google/re2/blob/108914d28a79243d4300e7e651cd0a0d5883ca0f/python/re2.py#L564-L566 that can only come from `Set::Compile`: https://github.com/google/re2/blob/108914d28a79243d4300e7e651cd0a0d5883ca0f/python/_re2.cc#L204-L219

And `Set` is perfectly happy with having no entries, so `Compile` succeeds.

**Comment by junyer** [comment]
Given https://github.com/ua-parser/uap-python/pull/200, would it suffice to remove [this](https://github.com/google/re2/blob/db46d1e11eee1ad501e8e08411747468d1d6a87e/re2/filtered_re2.cc#L74) line? (FWIW, that would be analogous to [this](https://github.com/google/re2/blob/db46d1e11eee1ad501e8e08411747468d1d6a87e/re2/prefilter_tree.cc#L58-L61) kludge.) If you **_do_** want `Filter` to raise when `_patterns` is empty, that would be fine as well. Just let me know which approach you desire.

**Comment by masklinn** [comment]
> Given [ua-parser/uap-python#200](https://github.com/ua-parser/uap-python/pull/200), would it suffice to remove [this](https://github.com/google/re2/blob/db46d1e11eee1ad501e8e08411747468d1d6a87e/re2/filtered_re2.cc#L74) line? (FWIW, that would be analogous to [this](https://github.com/google/re2/blob/db46d1e11eee1ad501e8e08411747468d1d6a87e/re2/prefilter_tree.cc#L58-L61) kludge.) If you **_do_** want `Filter` to raise when `_patterns` is empty, that would be fine as well. Just let me know which approach you desire.

As you have noticed I've already worked around it, so it's really up to what you prefer. I would think an empty list of patterns being legal would be simpler for the caller to handle (especially in a dynamically typed language).

I was thinking maybe `Options` could be used for that as it is a few lines above, but it would require adding an options parameter to either `Compile` or `FilteredRE2` itself so I can understand that being undesirable.

Might still be a good idea though, as other such logs (such as compiling twice) have the same issue, unless you start adding redundant guards to the python code but that seems like a pain.

**Comment by junyer** [comment]
Fair enough. I will just remove that line for now. :)
