### ISSUE TITLE
please release a new pypi version

### ISSUE THREAD

**Issue by trim21** [google/re2#486]
![image](https://github.com/google/re2/assets/13553903/ae8ba73a-dec5-4b21-88c6-eae62a0317f0)

**Comment by junyer** [comment]
The release of version 1.1 was indeed in August last year, but the release of version 1.1 **_build number 6_** was... about an hour ago... as per https://pypi.org/project/google-re2/#files. Should we bump versions (and stop using build numbers) even just for the mundane rebuilds?

**Comment by trim21** [comment]
I'm think use date as version number is not a bad idea.

**Comment by junyer** [comment]
Having meditated on it a little more, I'm going to bring `.YYYYMMDD` suffixes back, but still keep build numbers around (typically set to `1`) just in case rebuilds are ever needed for some reason. The next release is at least a month away, so I will come back to this issue then. :)

**Comment by trim21** [comment]
works for me

**Comment by junyer** [comment]
Just to be clear, the next release is still three weeks away. ;)

**Comment by junyer** [comment]
https://pypi.org/project/google-re2/1.1.20240501/#files has the latest release. :)
