### ISSUE TITLE
How to install  google_re2-1.1-2 by pip ?

### ISSUE THREAD

**Issue by broholens** [google/re2#489]
Hi, bro! 
The latest release version is google_re2-1.1-6 now, however i want to install google_re2-1.1-2 by pip.

I tried `pip install google-re2===1.1-2`, but it doesn't work.

Is there any way to install?

Thank you!

**Comment by broholens** [comment]
By the way, i tried `pip install https://files.pythonhosted.org/packages/c3/b9/2032ab65bc5535bccbee0ed5af0345e66d49a6ba051cbbe9cb940cffda02/google_re2-1.1-2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl`, and it works. 

But i still wonder if there's a way to not specify a URL to pip...

**Comment by junyer** [comment]
Sorry, I don't think specifying a build number to `pip install` is supported. :(

Coincidentally, we will be moving away from build numbers as per issue https://github.com/google/re2/issues/486.

**Comment by junyer** [comment]
P.S. What's the reason why you want that particular build number? O_o

**Comment by broholens** [comment]
We need to keep google-re2  build number version same so that after pip install at different time the `_re2.cpython-310-x86_64-linux-gnu.so` has no difference

**Comment by junyer** [comment]
https://pypi.org/project/google-re2/1.1.20240501/#files has the latest release. :)

**Comment by AlekseiSaff** [comment]
it seems that release can't be built on CentOS 7

**Comment by junyer** [comment]
Indeed, we had to drop `manylinux2014` from the build matrix back in commit https://github.com/google/re2/commit/f56cbe21b72dcddc91f84139b7434cc09b7fdf99. (And now CentOS 7 will be EOL in ~1.5 months.)
