### ISSUE TITLE
Getting a double free or corruption error when using re2 with an invalid regex

### ISSUE THREAD

**Issue by PrajwalKrishna** [google/re2#491]
I have a single UT which tries to build a non-supported regex via RE2, and checks if RE2 was successfully compiled.
```
TEST(RuleMatcher, Prajwal) {
  RE2 a = RE2("(a+)\\1");
  ASSERT_FALSE(a->ok());
}
```

Expectation - This test should run successfully without any crashes.

Output -
On running the test, it crashes and prints `double free or corruption (out)` error

Version - I am currently using an older version of RE2 - `"2021-02-01"` due to legacy bazel in my setup. 

P.S. I tried searching for issues but couldn't find any open/closed issue for the same.

**Comment by junyer** [comment]
`RE2` objects aren't copyable, so I'm not sure why that even compiles. `RE2 a("(a+)\\1");` should be okay though.

**Comment by PrajwalKrishna** [comment]
```
TEST(RuleMatcher, Prajwal) {
  RE2 a("(a+)\\1");
  ASSERT_FALSE(a.ok());
}
```

I don't think this is the issue, recreated the issue with the above modified code as well

**Comment by junyer** [comment]
I haven't been able to reproduce this failure – not even under sanitisers (ASan, MSan, TSan, UBSan). If you can provide sufficient details to reproduce this failure, I can reopen this issue. Otherwise, it's unclear that there's anything more for me to investigate here with regard to RE2 itself.

**Comment by PrajwalKrishna** [comment]
@junyer just confirming that you are using the version of RE2 mentioned `"2021-02-01"`

**Comment by junyer** [comment]
No, I haven't been – and won't be – debugging a version of RE2 from three years ago. Particularly without compelling evidence of a bug.

**Comment by PrajwalKrishna** [comment]
Was able to debug this finally, putting it here in case any one else comes here.

There was no bug in RE2. We had a `LogMessage` class in global namespace in our project, this was clashing with `LogMessage` class defined by RE2 https://github.com/google/re2/blob/b84e3ff189980a33d4a0c6fa1201aa0b3b8bab4a/util/logging.h#L57-L59 in global namespace, and that was causing the above error.

**Comment by junyer** [comment]
Thanks for letting me know and, indeed, for noting this for posterity. The `LogMessage` class can be moved into the `re2` namespace, but in the not too distant future, RE2 will be able to replace the legacy code with Abseil logging, which should avoid this biting anybody else.
