### ISSUE TITLE
Capture variables from successful combination of submatches

### ISSUE THREAD

**Issue by Declan-ARM** [google/re2#493]
Hi there,

Hopefully not a silly question, but is there a way to capture the variables of a successful combination of sub-matches?

For example, if I use the following made-up SPIR-V:
```cpp
    %end = OpVariable %_ptr_Function_int Function
     %15 = OpLoad %int %n
     %16 = OpLoad %int %n
           OpStore %end %16
```
...the following checks will return `false`...
```cpp
const std::string check = R"(
    CHECK:    [[END:%\w+]] = OpVariable
    CHECK: [[LOADED:%\w+]] = OpLoad %int %n
    CHECK:                   OpStore [[END]] [[LOADED]]
)";
```
...despite `OpStore %end %16` being a possibility.

Is there a better syntactical way to capture all possible versions of `LOADED` and return success if a match is found (instead of stopping after the first match)?

**Comment by junyer** [comment]
This is... LLVM's [FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html), yeah? Doesn't that use LLVM's regular expression engine implementation?

**Comment by junyer** [comment]
Ahh. Yeah, this would be something for that project to consider supporting. It's conceivable that they could collect the multiple values of `LOADED` and `|` those values together. It's also conceivable that they could adopt a backtracking approach. It's **_not_** possible to solve the problem with a trickier regular expression.

**Comment by junyer** [comment]
You're welcome. Good luck! :)
