### ISSUE TITLE
Allow using absl logging.

### ISSUE THREAD

**Issue by bcsgh** [google/re2#494]
It would be nice to either replace RE2's "Simplified version of Google's logging" with ABSL logging or provide an option to switch to that.

More than half the uses of `util/logging.h` are in files that already depend on ABSL which has had a full copy of glog for nearly two years. The only feature that RE2's logging seems to implement that I'm not seeing in ABSL is `VLOG`. It looks like a full switch over would be almost trivial, assuming the version dependency is allowable.

**Comment by junyer** [comment]
Thanks for the nudge. I had indeed been wanting to switch to Abseil logging for quite some time, but hadn't found the motivation to deal with the fact that Ubuntu (as used in our CI workflows) ships very old versions of Abseil. ;)

**Comment by bcsgh** [comment]
I could make an argument that CI shouldn't depend on the version of anything shipped on the host. ... That said, I'll try to not jostle your elbow while your doing that thin I asked for. ;0)

**Comment by junyer** [comment]
My life would probably be a lot simpler if RE2 could get away with supporting Bazel **_only_**, but...
