### ISSUE TITLE
pip unable to install latest version google-re2==1.1.20240501

### ISSUE THREAD

**Issue by ksrakesh6** [google/re2#495]
ERROR: Command errored out with exit status 1:
   command: /home/mydatabox/airflow-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f5mkuest
       cwd: /tmp/pip-install-wex44zw2/google-re2/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for google-re2
  Running setup.py clean for google-re2
Failed to build google-re2
Installing collected packages: google-re2
  Attempting uninstall: google-re2
    Found existing installation: google-re2 1.1
    Uninstalling google-re2-1.1:
      Successfully uninstalled google-re2-1.1
    Running setup.py install for google-re2 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/mydatabox/airflow-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5976ec49/install-record.txt --single-version-externally-managed --compile --install-headers /home/mydatabox/airflow-env/include/site/python3.8/google-re2
         cwd: /tmp/pip-install-wex44zw2/google-re2/
    Complete output (24 lines):
    running install
    /home/mydatabox/airflow-env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-38
    copying re2.py -> build/lib.linux-x86_64-cpython-38
    running build_ext
    building '_re2' extension
    creating build/temp.linux-x86_64-cpython-38
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/mydatabox/airflow-env/include -I/usr/include/python3.8 -c _re2.cc -o build/temp.linux-x86_64-cpython-38/_re2.o -fvisibility=hidden
    error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
    ----------------------------------------
  Rolling back uninstall of google-re2
  Moving to /home/mydatabox/airflow-env/lib/python3.8/site-packages/__pycache__/re2.cpython-38.pyc
   from /tmp/pip-uninstall-67_ycakx/re2.cpython-38.pyc
  Moving to /home/mydatabox/airflow-env/lib/python3.8/site-packages/_re2.cpython-38-x86_64-linux-gnu.so
   from /tmp/pip-uninstall-30fmxu63/_re2.cpython-38-x86_64-linux-gnu.so
  Moving to /home/mydatabox/airflow-env/lib/python3.8/site-packages/google_re2-1.1.dist-info/
   from /home/mydatabox/airflow-env/lib/python3.8/site-packages/~oogle_re2-1.1.dist-info
  Moving to /home/mydatabox/airflow-env/lib/python3.8/site-packages/re2.py
   from /tmp/pip-uninstall-30fmxu63/re2.py
ERROR: Command errored out with exit status 1: /home/mydatabox/airflow-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wex44zw2/google-re2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5976ec49/install-record.txt --single-version-externally-managed --compile --install-headers /home/mydatabox/airflow-env/include/site/python3.8/google-re2 Check the logs for full command output.

**Comment by cosmicexplorer** [comment]
What `pip` command line was executed to produce this output? I believe this is much more likely to be a `pip` bug than anything `re2` itself can do, but I can't immediately reproduce the behavior. Was this from pypi? What platform was this running on / why was pip unable to use the binary wheel?

**Comment by ksrakesh6** [comment]
I am running it  on WSL .pip is able to install all  other packages than  this one. re installed wsl  in latest image of ubuntu and its working .issue was with Ubuntu 20
