### ISSUE TITLE
Switch to ABSL-Check made compiler stumble over signed comparison issues in `CHECK()` calls

### ISSUE THREAD

**Issue by hzeller** [google/re2#499]
Using Current [`2024-06-01`](https://github.com/google/re2/releases/tag/2024-06-01), I get all kinds of warnings like the following when compiled with sign-compare warnings on (which is default with the usual `-Wall -Wextra`), failing a build with `--cxxopt=-Werror` enabled.

```
In file included from external/abseil-cpp~20240116.2/absl/base/macros.h:36,
                 from external/abseil-cpp~20240116.2/absl/base/internal/raw_logging.h:28,
                 from external/abseil-cpp~20240116.2/absl/base/internal/low_level_scheduling.h:21,
                 from external/abseil-cpp~20240116.2/absl/base/call_once.h:35,
                 from external/re2~2024-06-01/re2/prog.h:19,
                 from external/re2~2024-06-01/re2/prog.cc:8:
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h: In instantiation of 'constexpr std::string* absl::lts_20240116::log_internal::Check_EQImpl(const T1&, const T2&, const char*) [with T1 = unsigned int; T2 = int; std::string = std::__cxx11::basic_string<char>]':
external/re2~2024-06-01/re2/prog.cc:40:3:   required from here
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h:361:43: error: comparison of integer expressions of different signedness: 'const unsigned int' and 'const int' [-Werror=sign-compare]
  361 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_EQ, ==)
external/abseil-cpp~20240116.2/absl/base/optimization.h:179:58: note: in definition of macro 'ABSL_PREDICT_TRUE'
  179 | #define ABSL_PREDICT_TRUE(x) (__builtin_expect(false || (x), true))
      |                                                          ^
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h:361:1: note: in expansion of macro 'ABSL_LOG_INTERNAL_CHECK_OP_IMPL'
  361 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_EQ, ==)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h: In instantiation of 'constexpr std::string* absl::lts_20240116::log_internal::Check_GEImpl(const T1&, const T2&, const char*) [with T1 = long unsigned int; T2 = int; std::string = std::__cxx11::basic_string<char>]':
external/re2~2024-06-01/re2/prog.cc:1138:3:   required from here
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h:365:43: error: comparison of integer expressions of different signedness: 'const long unsigned int' and 'const int' [-Werror=sign-compare]
  365 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_GE, >=)
external/abseil-cpp~20240116.2/absl/base/optimization.h:179:58: note: in definition of macro 'ABSL_PREDICT_TRUE'
  179 | #define ABSL_PREDICT_TRUE(x) (__builtin_expect(false || (x), true))
      |                                                          ^
external/abseil-cpp~20240116.2/absl/log/internal/check_op.h:365:1: note: in expansion of macro 'ABSL_LOG_INTERNAL_CHECK_OP_IMPL'
  365 | ABSL_LOG_INTERNAL_CHECK_OP_IMPL(Check_GE, >=)
```

This happens in one of my personal projects using re2. To reproduce:

```bash
git clone https://github.com/hzeller/bant
cd bant
sed -i 's/2024-05-01/2024-06-01/' MODULE.bazel  # change Re2 version
bazel test --cxxopt=-Werror --keep_going ...
```

I suspect the change from `CHECK*` to `ABSL_CHECK_*` messed things up a bit due to signed comparison issues with it
(This is probably hitting b/246413374 ).

In Verible, I worked around the signed CHECK issues like this https://github.com/chipsalliance/verible/commit/c9391aedbecbeacd5e046fe9d38c34afacc3ee75 when switching to ABSL logging. Something like this might be an intermediate solutiion, but hopefully we convince the absl maintainers to not need such workarounds in the future.

**Comment by junyer** [comment]
Clang 18 and GCC 14 both show `warning: comparison …` 18 times in CI logs, FWIW, so I can hopefully "just" twiddle these checks instead of waiting for some kind of fix in Abseil logging.

**Comment by junyer** [comment]
Okay, that looks like all of the `-Wsign-compare` warnings. Interestingly, CI logs show a couple of other warnings...

Clang 18:

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: warning: 'get_temporary_buffer<std::pair<unsigned long, int>>' is deprecated [-Wdeprecated-declarations]
```

This seems to be due to using `std::stable_sort()`? #lol #lmao

GCC 14:

```
./re2/bitmap256.h:36:26: warning: array subscript 4 is above array bounds of ‘const uint64_t [4]’ {aka ‘const long unsigned int [4]’} [-Warray-bounds=]
```

This seems to be a false positive. Vexingly, a false positive despite various checks that byte values are in the range [0, 255]. 🤷

**Comment by hzeller** [comment]
Cool, thanks for the quick fix.

If there weren't these false positives, the CI could be run with `--cxxopt=-Werror`. Maybe with `--cxxopt=-Wno-deprecated-declarations` ?

The gcc14 triggering might be, because condition is tested with `DCHECK()` (which is not aborting but continues after LOG(ERROR)), not `CHECK()` ?

What happens if you add 
`if (c < 0 || c > 255) return false;` ?

**Comment by hzeller** [comment]
(off-topic) Speaking of CI, the clang-based compilations seem to repeat the same compile flags many times over https://github.com/google/re2/actions/runs/9599364439/job/26472915655#step:5:9

**Comment by junyer** [comment]
> The gcc14 triggering might be, because condition is tested with `DCHECK()` (which is not aborting but continues after LOG(ERROR)), not `CHECK()` ?

According to the CI logs, the warning shows up only for the build that **_doesn't_** pass `-DNDEBUG`, so... "🤷" remains my position on it for now.

> (off-topic) Speaking of CI, the clang-based compilations seem to repeat the same compile flags many times over https://github.com/google/re2/actions/runs/9599364439/job/26472915655#step:5:9

I'm fairly certain that it has **_something_** to do with `pkg-config … --cflags`, but I'm absolutely baffled as to how it could happen in the first place and, moreover, why it would differ between Clang and GCC.
