### ISSUE TITLE
Bug in util/util.h and -maybe- in Android.mk  

### ISSUE THREAD

**Issue by cdottori** [google/re2#50]
Hi there, 

I've discovered a problem when trying to build re2 for M-Dessert, where stlport is not used any more. 
In particular, re2 doesn't build because of the following lines in util.h:

```
#if defined(ANDROID)

#if defined(_STLPORT_VERSION)
#include <unordered_set>      // using stlport
#else
#include <tr1/unordered_set>  // using gnustl
#endif
using std::tr1::unordered_set;
 
#elif defined(__GNUC__) && !defined(USE_CXX0X)

#include <tr1/unordered_set>
using std::tr1::unordered_set;

#else

#include <unordered_set>
using std::unordered_set;

#endif
```

And because of this directive in Android.mk
LOCAL_SDK_VERSION := 14.

The fix "seems to be" the following: 
```
#if defined(ANDROID) 

#if defined(_STLPORT_VERSION) || defined(_USING_LIBCXX)
#include <unordered_set>      // using stlport
using std::unordered_set;
#else
#include <tr1/unordered_set>  // using gnustl
using std::tr1::unordered_set;
#endif
 
#elif defined(__GNUC__) && !defined(USE_CXX0X)

#include <tr1/unordered_set>
using std::tr1::unordered_set;

#else

#include <unordered_set>
using std::unordered_set;

#endif
```

And there is the need to comment "LOCAL_SDK_VERSION := 14" in the makefile. 

Please elaborate. 
C

**Comment by junyer** [comment]
Thanks for the report, but this repository has neither `Android.mk` nor the logic in `util/util.h` that you showed. Are you working with the https://android.googlesource.com/platform/external/regex-re2/ repository? I'll ping danalbert@google.com for you, but that's as much as I'm able to help. :)

**Comment by DanAlbert** [comment]
The version of re2 in Android is only built using the NDK, and using gnustl. `_USING_LIBCXX` should be irrelevant here.

**Comment by cdottori** [comment]
Many thanks anyway. I'll follow up with Dan then.

Cheers,
Chiara

**Comment by cdottori** [comment]
Hi Dan,

thanks for your answer. To give you some context, I work in Intel and I've
discovered via "git blame" that the buggy changes to util.h have been done
by Intel folks -> I'll follow up with them then. :-)


Cheers and have a great day.

Chiara

**Comment by cdottori** [comment]
All wrong. It was google folks.

agutkin@google.com
pszczepaniak@google.com
idh@google.com

I'll follow up with them.

Br,
Chiara
