### ISSUE TITLE
`setup.py` no longer works with source from PyPI

### ISSUE THREAD

**Issue by xylar** [google/re2#500]
Modifications made in [2024-07-01](https://github.com/google/re2/tree/2024-07-01) to `python/setup.py` are no longer compatible with the source code uploaded to PyPI (https://files.pythonhosted.org/packages/b9/7c/6a44a14375496d0931ce349b580686ed3ed15bf0c62d77ae1a3a57fab110/google_re2-1.1.20240701.tar.gz)

This results in:
```
  Running command python setup.py egg_info
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/home/conda/feedstock_root/build_artifacts/google-re2_1719767281588/work/setup.py", line 111, in <module>
      os.makedirs(PACKAGE)
    File "/home/conda/feedstock_root/build_artifacts/google-re2_1719767281588/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/os.py", line 225, in makedirs
      mkdir(name, mode)
  FileExistsError: [Errno 17] File exists: 're2'
  error: subprocess-exited-with-error
```
because the processing that `setup.py` is trying to do has already been done for the source code on PyPI.  Presumably, a process is needed to detect this and skip these modifications if they have already been made.

See the conda-forge build for more details:
https://github.com/conda-forge/google-re2-feedstock/pull/14
Specifically the Azure-Pipelines output:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=966161&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7

**Comment by junyer** [comment]
Yikes! Thanks for the report!

**Comment by junyer** [comment]
I have a fix out for review. I should be able to cut release `2024-07-02` tomorrow night.

**Comment by xylar** [comment]
@junyer, thanks so much for responding so quickly!

**Comment by junyer** [comment]
You're welcome. :)

**Comment by junyer** [comment]
Keeping this issue open until the release is cut...

**Comment by junyer** [comment]
Okay, release `2024-07-02` has been cut and, more to the point, published to PyPI. :)

**Comment by xylar** [comment]
Wonderful, thank you, @junyer!
