### ISSUE TITLE
RE2 fails to compile under MSVC 2015 due to sprintf

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#51]
Util.h, around line 68, redefines sprintf to sprintf_s:

#ifdef _WIN32

#define snprintf _snprintf_s
#define sprintf sprintf_s

However, sprintf_s has different parameters. The call to sprintf in strutil.cc at line 42 causes a compile error:
          sprintf(dest + used, "\\%03o", c);

C2664	'int sprintf_s(char *const ,const size_t,const char *const ,...)': cannot convert argument 2 from 'const char [6]' to 'const size_t'	re2	c:\src\re2\util\strutil.cc	41

Some possible ways to correct this are:
1. Do not redefine sprintf.  Build MSVC project with macro _CRT_SECURE_NO_DEPRECATE  defined.

2. Do not redefine sprintf. Use something like:
#ifdef _WIN32
                 sprintf_s(dest + used, 5, "\\%03o", c);
#else 
                 sprintf(dest + used, "\\%03o", c);
#endif

**Comment by junyer** [comment]
There was a similar issue with `vsnprintf_s` a couple of months ago. I will fix this in much the same way and also switch to `_snprintf_s`.

**Comment by DThiebaud** [comment]
With this fix, RE2 now builds cleanly for me using MSVC 2013. It requires macro definitions NOMINMAX and COMPILER_MSVC.  I can't test the build because the test doesn't build.

**Comment by junyer** [comment]
Thanks, that's great news!

As of d9cc8e580e4ff2b38e7417b07f3d0215787a4619, CMake should see those macros defined:

```
if(WIN32)
  add_definitions(-DUNICODE -D_UNICODE -DSTRICT -DNOMINMAX)
  # Used in a couple of places.
  add_definitions(-DCOMPILER_MSVC)
…
```

It should also allow the tests to be built easily.
