### ISSUE TITLE
threadwin.cc gets compiler errors in MSVC 2013

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#53]
If I compile threadwin.cc in MSVC2013 I get a compiler error in thread.h: 
  e:\src\re2\util/thread.h(8): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

If I put ifdef's around the include of pthread.h, I get no errors in thread.h but I get errors in compiling threadwin.cc

in thread.h:
#ifndef _WIN32
#include <pthread.h>
#endif

>e:\src\re2\util/thread.h(22): error C2146: syntax error : missing ';' before identifier 'pid_'
1>e:\src\re2\util/thread.h(22): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>e:\src\re2\util\threadwin.cc(11): error C2065: 'pid_' : undeclared identifier
1>e:\src\re2\util\threadwin.cc(27): error C2065: 'pid_' : undeclared identifier
1>e:\src\re2\util\threadwin.cc(31): error C2065: 'pid_' : undeclared identifier
1>e:\src\re2\util\threadwin.cc(32): error C2065: 'pid_' : undeclared identifier
1>e:\src\re2\util\threadwin.cc(39): error C2065: 'pid_' : undeclared identifier
1>e:\src\re2\util\threadwin.cc(41): error C2065: 'pid_' : undeclared identifier

If I change this line in thread.h:
  pthread_t pid_;
to:
#ifdef _WIN32
  HANDLE pid_;
#else
  pthread_t pid_;
#endif  

then threadwin.cc compiles with no errors.

This is all with source-code cloned from the code-review repository as of about 9:30 PM on Monday, September18, with project files build with CMAKE.

**Comment by DThiebaud** [comment]
Oops--in thread.h, the "#ifdef WIN32" is actuarlly #ifdef _WIN32

**Comment by junyer** [comment]
Ouch. Thanks for the report!

**Comment by DThiebaud** [comment]
I still get the same problem:

2>  threadwin.cc
2>e:\src\re2\util/thread.h(25): error C2146: syntax error : missing ';' before identifier 'pid_'
2>e:\src\re2\util/thread.h(25): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>e:\src\re2\util\threadwin.cc(9): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(17): error C2143: syntax error : missing ';' before '__cdecl'
2>e:\src\re2\util\threadwin.cc(17): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>e:\src\re2\util\threadwin.cc(25): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(25): error C3861: 'CreateThread': identifier not found
2>e:\src\re2\util\threadwin.cc(28): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(28): error C3861: 'CloseHandle': identifier not found
2>e:\src\re2\util\threadwin.cc(29): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(36): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(37): error C2065: 'pid_' : undeclared identifier
2>e:\src\re2\util\threadwin.cc(37): error C3861: 'WaitForSingleObject': identifier not found

**Comment by DThiebaud** [comment]
This is with source cloned from "git clone https://code.googlesource.com/re2" as of 1:30 AM EDT on October 2.

**Comment by DThiebaud** [comment]
As before, if I reverse the order of the lines "#include <util/util.h>" and "#include <util/thread.h> in threadwin.cc, then threadwin.cc compiles cleanly.

**Comment by junyer** [comment]
I wonder whether this could be caused by the definition of `WIN32_LEAN_AND_MEAN` in `util/mutex.h`, which is included by `util/util.h`. However, since nothing in `util/thread.h` needs anything in or via `util/util.h`, simply including it first seems like the straightforward solution.
