### ISSUE TITLE
Compiling benchmark.cc in MSVC 2013 gets compile errors.

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#55]
Compiling benchmark.cc in MSVC 2013 gets compile errors.
1>------ Build started: Project: benchmark, Configuration: Release x64 ------
1>  benchmark.cc
1>E:\src\re2\util\benchmark.cc(29): error C2079: 'tv' uses undefined struct 'nsec::timeval'
1>E:\src\re2\util\benchmark.cc(30): error C3861: 'gettimeofday': identifier not found
1>E:\src\re2\util\benchmark.cc(32): error C2228: left of '.tv_sec' must have class/struct/union
1>          type is 'int'
1>E:\src\re2\util\benchmark.cc(32): error C2228: left of '.tv_usec' must have class/struct/union
1>          type is 'int'
1>E:\src\re2\util\benchmark.cc(115): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data
1>E:\src\re2\util\benchmark.cc(117): warning C4244: '=' : conversion from 'double' to 'int', possible loss of data

struct timeval and gettimeofday are not defined in MSVC

The following code compiles cleanly and I think it is correct (untested):

static int64 nsec() {
#if defined(_MSC_VER)
   LARGE_INTEGER freq, val;
   QueryPerformanceFrequency(&freq);
   QueryPerformanceCounter(&val);
   return (1000*(double)val.QuadPart) / (double)freq.QuadPart;
#elif defined(__APPLE__) || defined(_WIN32) 
	struct timeval tv;
	if(gettimeofday(&tv, 0) < 0)
		return -1;
	return (int64)tv.tv_sec*1000*1000*1000 + tv.tv_usec*1000;
#else
	struct timespec tp;
	if(clock_gettime(CLOCK_REALTIME, &tp) < 0)
		return -1;
	return (int64)tp.tv_sec*1000*1000*1000 + tp.tv_nsec;
#endif
}

**Comment by junyer** [comment]
Windows doesn't have `gettimeofday(2)`, it seems, so I don't know why we were trying to use it. :)

Thanks for the suggested patch, but I've found an emulation of `clock_gettime(2)` for Windows that I can reuse.

**Comment by junyer** [comment]
Even better, https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408.aspx has an example as well as lots of documentation.
