### ISSUE TITLE
threadwin.cc does not recognize HANDLE in thread.h

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#57]
This causes a compile error on syntax. 

The cure for this is the same as we encountered before: define thread.h before, instead of after, test.h. With this change, threadwin.cc compiles without error.

In fact, with this change and other recent changes Paul has submitted, RE2 and the entire test suite compile cleanly for me in MSVC 2013 64-bit.

**Comment by junyer** [comment]
f7a87691544aa9dcd8703f8c11f78a2985287b8b fixed this a few days ago. Has a subsequent commit broken things again somehow?

**Comment by junyer** [comment]
Ahh. I think you meant `dfa_test.cc`?

**Comment by DThiebaud** [comment]
Yes, I meant dfa_test.cc  Sorry for the mistake.

**Comment by junyer** [comment]
No worries. :)

**Comment by tfarina** [comment]
Shouldn't we fix the cause rather than workaround it? In Chromium we sort headers alphabetically, hence I got surprised when saw this change.

**Comment by junyer** [comment]
I don't know for sure that `WIN32_LEAN_AND_MEAN` is the problem. I also don't know very much about Windows and don't have a Windows machine on which to test these changes before committing them. :(

**Comment by DThiebaud** [comment]
On 10/13/2015 12:03 AM, Paul Wankadia wrote:
>
> I don't know for sure that |WIN32_LEAN_AND_MEAN| is the problem. I 
> also don't know very much about Windows and don't have a Windows 
> machine on which to test these changes before committing them. :(
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/57#issuecomment-147593096>.
>
If we could figure out what caused the problem, we would fix it. I tried 
and WIN_LEAN_AND_MEAN did not seem be the cause. Whatever is causing it 
seems to be rather weird.

**Comment by junyer** [comment]
I suspect that we should include specific header files instead of relying on `windows.h` for everything. I could probably work out which ones by reading MSDN, but (again) would have no means of testing the change before committing it.

**Comment by DThiebaud** [comment]
On 10/13/2015 1:09 AM, Paul Wankadia wrote:
>
> I suspect that we should include specific header files instead of 
> relying on |windows.h| for everything. I could probably work out which 
> ones by reading MSDN, but (again) would have no means of testing the 
> change before committing it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/57#issuecomment-147602472>.
>
possibly, but it can get tricky figuring out which headers rely on which 
other readers. The entire build only takes about 5 minutes.

PS: with the last change, a full build (of all projects) was success in 
MSVC 2013 64-bit.

**Comment by DThiebaud** [comment]
On 10/13/2015 1:09 AM, Paul Wankadia wrote:
>
> I suspect that we should include specific header files instead of 
> relying on |windows.h| for everything. I could probably work out which 
> ones by reading MSDN, but (again) would have no means of testing the 
> change before committing it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/57#issuecomment-147602472>.
>
I'm always happy to run Windows tests, but note I will be on vacation 
the next two weeks.

**Comment by junyer** [comment]
> PS: with the last change, a full build (of all projects) was success in
> MSVC 2013 64-bit.

If I'm not mistaken, that means we're good for builds, tests and benchmarks! :)

> I'm always happy to run Windows tests, but note I will be on vacation
> the next two weeks.

Thanks, Dick. I'll have to look into "continuous integration" solutions eventually, I think, but now that we've reached this milestone, ad hoc testing is probably sufficient.

**Comment by DThiebaud** [comment]
On 10/13/2015 2:05 AM, Paul Wankadia wrote:
>
>     PS: with the last change, a full build (of all projects) was
>     success in
>     MSVC 2013 64-bit.
>
> If I'm not mistaken, that means we're good for builds, tests and 
> benchmarks! :)
>
>     I'm always happy to run Windows tests, but note I will be on vacation
>     the next two weeks.
>
> Thanks, Dick. I'll have to look into "continuous integration" 
> solutions eventually, I think, but now that we've reached this 
> milestone, ad hoc testing is probably sufficient.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/57#issuecomment-147614825>.
>
I ran all the tests and regexp_benchmark for re2 built with MSVC 2013 
64-bit. All were successful.

**Comment by junyer** [comment]
> I ran all the tests and regexp_benchmark for re2 built with MSVC 2013
> 64-bit. All were successful.

Fantastic, thanks for the confirmation.
