### ISSUE TITLE
Building with USEPCRE in MSCV 2013 gives link errors: entry point pcre_free multiply defined.

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#58]
Compiling the "test" project with USEPCRE defined, in MSVC 2013, I get warning messages that entry point pcre_free is defined in different programs:

1>tester.obj : warning LNK4006: pcre_free already defined in pcre.obj; second definition ignored
1>exhaustive_tester.obj : warning LNK4006: pcre_free already defined in pcre.obj; second definition ignored
1>  test.vcxproj -> E:\src\re2\bin\Debug\test.lib

If I try to build any program that uses test.lib with USEPCRE defined, I get similar messages but they are errors, not warnings, and the link fails:

1>------ Build started: Project: exhaustive_test, Configuration: Debug x64 ------
1>test.lib(tester.obj) : error LNK2005: pcre_free already defined in test.lib(exhaustive_tester.obj)
1>test.lib(pcre.obj) : error LNK2005: pcre_free already defined in test.lib(exhaustive_tester.obj)
1>pcre.lib(pcre_globals.obj) : error LNK2005: pcre_free already defined in test.lib(exhaustive_tester.obj)
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>E:\src\re2\bin\Debug\exhaustive_test.exe : fatal error LNK1169: one or more multiply defined symbols found

(Since PCRE is not native to Windows, I downloaded PCRE version 8.37, built it, and put pcre.lib and pcre.h in the default lib and include directories).

I have no idea how this could happen. It looks as if tester.obj and exhaustive_tester.obj contain definitions of pcre_free, but looking at them, I don't see how they could. I am quite mystified.

Does this even matter? Do we need to be able the run the re2 tests with PCRE when building with MSVC?

**Comment by junyer** [comment]
`pcre_free` is the only symbol mentioned in the errors? That's quite bizarre. Due to my lack of Windows experience, I don't even know where to suggest looking first. (Ping, @ariccio!)

However, PCRE is used for comparison only: submatches in tests, speed in benchmarks. I would like to see this problem fixed, of course, but I wouldn't lose too much sleep over it. :)

**Comment by DThiebaud** [comment]
Yes, pcre_free is the only symbol mentioned in the errors. I agree, it's quite bizarre. As far as I can see, pcre.c in the source code for pcre is the only place where pcre_free is defined.

**Comment by DThiebaud** [comment]
I think I've found the cause of this. In <pcre.h> from pcre 8.37, the entry points for pcre are defined as:

PCRE_EXP_DECL void *(*pcre_malloc)(size_t);
void  (*pcre_free)(void *);
PCRE_EXP_DECL void *(*pcre_stack_malloc)(size_t);
PCRE_EXP_DECL void  (*pcre_stack_free)(void *);
etc.
PCRE_EXP_DECL gets expanded to "extern "c"".  

Multiple programs in RE2 directly or indirectly include "util/pcre.h" which includes <pcre.h>. and thus define pcre_free. Without an "extern" declaration, the MSVC linker doesn't like this. 

I consider this a bug in pcre 8.37; pcre_free should be defined with PCRE_EXP_DECL, same as the other PCRE entry points. If I make this correction and rebuild pcre.lib, the programs using pcre link okay in RE2.

We have an easy workaround.  Do not include <pcre.h> in "util/pcre.h". Instead, include it in pcre.cpp, which is the only program that calls the pcre C functions.

Should I try committing the source code changes for this? Or should I show the diffs here and let one of the experienced developers on this project put the change in?

**Comment by DThiebaud** [comment]
Should have said, do not include <pcre.h> in "util/pcre.h". Instead, include <pcre.h> in pcre.cpp since it's the only program that calls the PCRE C functions.

**Comment by junyer** [comment]
FWIW, version 8.31 seems not to have this bug:

```
$ grep '\<pcre_free\>' /usr/include/pcre.h
PCRE_EXP_DECL void  (*pcre_free)(void *);
PCRE_EXP_DECL void  pcre_free(void *);
$ 
```

As always, thanks for digging into this! I'll implement your solution.

**Comment by DThiebaud** [comment]
Version 8.35 does not have that bug either. I'll see if I can find where to report this bug to the PCRE project.

**Comment by DThiebaud** [comment]
Does anyone know if there's a way to set the define for USEPCRE in the solution so it is applied to all 25 projects?

How difficult would it be to add this as an option in CMAKE?

**Comment by junyer** [comment]
It appears that a forward declaration of the `pcre` type is effectively impossible:

```
struct real_pcre;                 /* declaration; the definition is private  */
typedef struct real_pcre pcre;
```

As such, I don't think that working around the bug is feasible after all. :(

**Comment by junyer** [comment]
> Version 8.35 does not have that bug either. I'll see if I can find where to report this bug to the PCRE project.

FWIW, http://vcs.pcre.org/pcre/code/trunk/pcre.h.in?revision=1454&view=markup#l511 seems fine.

**Comment by junyer** [comment]
> How difficult would it be to add this as an option in CMAKE?

That should be easy enough.

**Comment by DThiebaud** [comment]
Paul, you are right.  The pcre.h header must be included in util/pcre.h  I have the feeling that, with enough work, we could make it so that it doesn't need to be included, but this would be major work and source code change (assuming it's possible at all). It's not worth this for what is a PCRE bug that is easily corrected and has been fixed in their latest code. I'm closing this issue as satisfied.

**Comment by junyer** [comment]
If you pull 5eb0bdaf6197bb1d5cb88c3d0c7a3f5a0ee6db6c, you can run CMake with `-DUSEPCRE=y` and then MSVC should hopefully do the right thing. (I tested it both ways on Linux, at least, and it worked as intended.)

**Comment by junyer** [comment]
6d917e6623556351f0df507a8ca66aec83115cf1 is very slightly tidier.

**Comment by DThiebaud** [comment]
I have to apologize to you. It appears that earlier, while, trying to resolve compile errors related to PCRE (since resolved), I experimentally removed the PCRE_EXP_DECL from pcre_free in the code for PCRE. There is no bug in PCRE, this was my mistake. I hope you haven't spent too much time on this bug.

with -DUSEPCRE=y, pcre and all test programs build successfully. I will run all the tests and let you know the results.

Could USEPCRE be added to the options shown in pcre_gui?

**Comment by junyer** [comment]
No time was wasted, so no worries there. :)

> Could USEPCRE be added to the options shown in pcre_gui?

Sorry, I'm not sure what pcre_gui is?

**Comment by DThiebaud** [comment]
On 10/09/2015 10:16 PM, Paul Wankadia wrote:
>
> Sorry, I'm not sure what pcre_gui is?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/58#issuecomment-147022903>.
>
I meant cmake_gui. This is a graphical shell for cmake on Windows and 
linux. It gives a list of all the options for a cmake project and lets 
you set them in the gui. Under the current re2 pull, the gui does not 
show the "USEPCRE" option. However, the gui lets you add the "USEPCRE" 
option and then correctly generates the build code for whether the 
option is selected or not. I suspect but don't know that making the gui 
show the option without the user adding the option would be a simple change.

**Comment by junyer** [comment]
Ahh. Sure, I'll look into it shortly.

**Comment by junyer** [comment]
d10ed8f2303f6c7303f5472736e2f535249b0a75 added the option.
