### ISSUE TITLE
make testinstall fails on osx 10.9 mavericks (probably Yosemite too)

### ISSUE THREAD

**Issue by josecanciani** [google/re2#6]
What steps will reproduce the problem?

1) run install steps as per wiki
2) in last step, make testinstall, it fails.

What is the expected output? What do you see instead?

Expected: to work :)
Actual result:

$ sudo make testinstall
cp testinstall.cc obj
(cd obj && c++ -I/usr/local/include -L/usr/local/lib testinstall.cc -lre2 -pthread -o testinstall)
Undefined symbols for architecture x86_64:
  "re2::FilteredRE2::FirstMatch(re2::StringPiece const&, std::__1::vector<int, std::__1::allocator<int> > const&) const", referenced from:
      _main in testinstall-025vi1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [testinstall] Error 1

What version of the product are you using? On what operating system?
Last from source. OS is mavericks (10.9.2)

Thanks!

**Comment by suejb** [comment]
Any fix for this yet? I am experiencing the same issue on Yosemite.

**Comment by bjornbugge** [comment]
I had the same problem.  It was fixed by adding __ZNK3re211FilteredRE2* to libre2.symbols.darwin, as mentioned in the thread https://code.google.com/p/re2/issues/detail?id=59

**Comment by junyer** [comment]
Since 59d96121fea1bab268b5969b2a7344f0bdfdaeb0, `libre2.symbols.darwin` lists `__ZN3re211FilteredRE2*` and `__ZNK3re211FilteredRE210AllMatches*`, but not `__ZNK3re211FilteredRE2*`. Does it need to be readded?

**Comment by CodyMorris** [comment]
Junyer, looks like re-adding __ZNK3re211FilteredRE2 lets me run ```make testinstall``` successfully, but then breaks ```make test```

'''obj/so/test/filtered_re2_test           FAIL;'''

**Comment by junyer** [comment]
D'oh! What's in `obj/so/test/filtered_re2_test.log`?

**Comment by junyer** [comment]
I'm pretty sure that I fixed this today with e7411ab1a03298449a958e65863a09325ec6d911.
