### ISSUE TITLE
VC++ warning on odd code

### ISSUE THREAD

**Issue by junyer** [google/re2#61]
Reported by @randomascii on re2-dev:

> VC++ gives this warning when compiling all of re2:
> 
>     re2\testing\regexp_benchmark.cc(141): warning C4804: '%' : unsafe use of type 'bool' in operation
> 
> The line of code in question is this:
> 
>     if (!rand()%30)
> 
> Due to the high precedence of '!' the "% 30" is effectively ignored so the frequency of '\n' characters is much lower (1/RAND_MAX instead of 1/30) than intended. Not a serious problem, but perhaps worth fixing? I can upload a patch if that is what is wanted.
> 
> There are some other warnings about integer truncation but I'm assuming those are all intentional. This is with VC++ 2013.

**Comment by junyer** [comment]
@rsc, do you happen to remember why `MakeText()` inserts `\n` at all? Almost none of the benchmarks allow `.` to match `\n`.

Also, I wonder if this is related to #59 in some way. At least, that might explain the mysterious match failure after ~100KiB. (Ping, @DThiebaud.)

**Comment by junyer** [comment]
For posterity, `\n` characters were indeed the problem.

Conclusive debugging evidence courtesy of @DThiebaud:

```
@105098: (0000000001688BE0)65538,65539,65540,65542,65543,65545,65546,65548,65549,65551,65552,65554,65555,65557,65558,65559,65561 flag=0
@105099: (0000000001688BE0)65538,65539,65540,65542,65543,65545,65546,65548,65549,65551,65552,65554,65555,65557,65558,65559,65561 flag=0
@105100: (0000000001688BE0)65538,65539,65540,65542,65543,65545,65546,65548,65549,65551,65552,65554,65555,65557,65558,65559,65561 flag=0
@105101: (0000000001688BE0)65538,65539,65540,65542,65543,65545,65546,65548,65549,65551,65552,65554,65555,65557,65558,65559,65561 flag=0
65538,65539,65540,65542,65543,65545,65546,65548,65549,65551,65552,65554,65555,65557,65558,65559,65561 on 10[0x1] ->  [0]
WorkqToCachedState  [0x1] -> DeadState
E:\src\re2\re2\testing\regexp_benchmark.cc:899: Check failed: (prog->SearchDFA(text, 0, anchor, Prog::kFirstMatch, 0, &failed, 0)) == (expect_match)
```

**Comment by ariccio** [comment]
Eeww. I'm surprised that I didn't notice this way back when I first built re2 with /analyze
