### ISSUE TITLE
Compile errors in atomicop.h in MSVC 2013

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#62]
In atomicop.h the compiler does not recognize "LONG" or "::InterlockedExchange".
These should be replaced by "long"and "InterlockedExchange".

Around line 82, the lines:

// Windows
inline void WriteMemoryBarrier() {
  LONG x;
  ::InterlockedExchange(&x, 0);
}

should be replaced by:

// Windows
inline void WriteMemoryBarrier() {
  long x;
  InterlockedExchange(&x, 0);
}

**Comment by junyer** [comment]
21621d9ac9fb0ee441b88767737891a89e70c96d was my attempt to fix that. `LONG` is supposed to work. :(

Fortunately, @randomascii has a change pending (https://code-review.googlesource.com/3590) that should solve this and also improve performance dramatically.

**Comment by DThiebaud** [comment]
On 10/14/2015 12:10 AM, Paul Wankadia wrote:
>
> 21621d9 
> <https://github.com/google/re2/commit/21621d9ac9fb0ee441b88767737891a89e70c96d> 
> was my attempt to fix that. |LONG| is supposed to work. :(
>
> Fortunately, @randomascii <https://github.com/randomascii> has a 
> change pending (https://code-review.googlesource.com/3590) that should 
> solve this and also improve performance dramatically.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/62#issuecomment-147929948>.
>

Looking at change set 2 of this, it will still use "LONG" and 
"::InterlockedExchange" for MSVC compiling for a target that is not x86 
or x64. I don't know and can't test if MSVC not for these will accept 
these words. For MSVC x86 or x64, the code with the change set will 
compile okay.

I'm not sure its worth making a change for code we don't know if it's 
wrong and can't test if it is. Should I close issue 62 (or do you want to?)

**Comment by DThiebaud** [comment]
I have not tested this, but it looks like the function name should be "InterlockedExchange" for MSVC 32-bit and "InterlockedExchange64" for MSVC 64-bin.  There are standard MSVC defines for 64 bit: _M_X64 and _WIN64.

**Comment by DThiebaud** [comment]
I was wrong about "InterlockedExchange32". Per https://msdn.microsoft.com/en-us/library/3b2e7499.aspx, "long" is 32 bits in 64-bit windows.

**Comment by junyer** [comment]
> I'm not sure its worth making a change for code we don't know if it's
> wrong and can't test if it is. Should I close issue 62 (or do you want to?)

Let's leave this issue open until the commit lands. I'll be happy as long as x86 and x64 are fine, but I'd certainly like to hear from anyone using ARM.

**Comment by DThiebaud** [comment]
I meant "wrong about 'InterlockedExchange64'".

**Comment by randomascii** [comment]
The code compiles fine on Windows now. Since LONG is fixed size on Windows (always 32-bit, they don't dare ever change it) for x86, x64, and ARM it should be fine forevermore.

I don't have an ARM machine handy but I could probably compile it for ARM, I think, although I'm confident that InterlockedExchange and LONG won't be issues.

**Comment by DThiebaud** [comment]
The code in a clone of re2 done at about 1:00 does compile cleanly and recognize "LONG" and "::interlocked_interchange". This is very odd to me, because one or two days ago it didn't for me. (both times using MSVC 2013 with project files from CMAKE.

For Windows 64 bits, is atomicop.h supposed to use the the following code?

: #elif defined(__x86_64__)

// 64-bit implementations of memory barrier can be simpler, because
// "sfence" is guaranteed to exist.
static inline void WriteMemoryBarrier() {
  __asm__ __volatile__("sfence" : : : "memory");
}

For me it is not: Running in debug with a breakpoint set, it stops at ::InterlockedInterchanged in the lines:

#elif defined(__windows__) || defined(_WIN32)

#include <windows.h>

// Windows
inline void WriteMemoryBarrier() {
  LONG x;
  ::InterlockedExchange(&x, 0);
}

Is the the desired behavior?

**Comment by junyer** [comment]
Yes, `__x86_64__` is a GNUism, I believe, and that definition of `WriteMemoryBarrier()` uses GNU inline assembly, so it would be a build-breaking bug if MSVC actually tried to compile it. :)

**Comment by DThiebaud** [comment]
Since atomicop.h with the latest changes does compile cleanly, I am closing this issue.

**Comment by DThiebaud** [comment]
Paul, you are right. Hacking atomicop.h so that windows uses the lines under __x86_64__,, the inline assemply does indeed break the compile.
