### ISSUE TITLE
continuous fuzzing for re2

### ISSUE THREAD

**Issue by kcc** [google/re2#64]
Let's fuzz re2 to make it even more reliable!
I've set up a [public fuzzing bot for re2](https://github.com/google/libfuzzer-bot/tree/master/re2).
Right now it uses libFuzzer and AddressSanitizer, and tests a *very* simple [target function](https://github.com/google/libfuzzer-bot/blob/master/re2/re2_fuzzer.cc).

This bug will be tracking the process of improving and extending this fuzzer.
Bugs found by this process (if any) will be reported separately.

**Comment by kcc** [comment]
@junyer , there are 3 instances of LOG(INFO) that the fuzzer finds very quickly:
```
re2/re2/dfa.cc:    LOG(INFO) << StringPrintf("DFA out of memory: prog size %d mem %lld",
re2/re2/dfa.cc:    LOG(INFO) << StringPrintf("DFA out of memory: prog size %d mem %lld",
re2/re2/dfa.cc:    LOG(INFO) << "DFA memory cache could be too small: "
```
Since this is an actual I/O, the fuzzing becomes very slow and verbose.
Is it possible to hide this logging under a flag?
Maybe RE2::Options::set_log_info(false), or somrthing?

**Comment by kcc** [comment]
The [target function](https://github.com/google/libfuzzer-bot/blob/master/re2/re2_fuzzer.cc) currently resides in the libfuzzer-bot git. 
Would you like to have it in the re2 git instead? 
W'll need to make a few changes in it before it becomes stable.

**Comment by junyer** [comment]
> Since this is an actual I/O, the fuzzing becomes very slow and verbose.
> Is it possible to hide this logging under a flag?
> Maybe RE2::Options::set_log_info(false), or something?

I'm not sure that an option – with all of the requisite plumbing – is worthwhile. Unless @rsc vetoes the change, I'd prefer to emulate the `--minloglevel` flag, which seems like the simple and general solution.

**Comment by kcc** [comment]
-minloglevel will work fine if there is a way to set it from within the process (i.e. not from command line)

**Comment by junyer** [comment]
Yes, you can simply assign to `FLAGS_minloglevel`.

**Comment by junyer** [comment]
> The target function currently resides in the libfuzzer-bot git. 
> Would you like to have it in the re2 git instead? 

Thanks, but I'm doubtful that moving it here would actually benefit either project. :)

**Comment by kcc** [comment]
>> Thanks, but I'm doubtful that moving it here would actually benefit either project. :)

The reason I suggested this is because I will not be fuzzing re2 indefinitely.
The bot itself is planned to be running forever, and so if the target function is in your hands 
you can modify it to change what the bot is actually testing. 

Anyway. 
The bot is up and running, I've also extended the target function. 
The bot shows the current coverage info (the list of file locations of functions *not* covered).
E.g. from http://104.197.8.28/pass-2015-11-02-19-54-52.log :
```
    ...
    22	re2/compile.cc:1098:0
    23	re2/compile.cc:1104:0
    24	re2/compile.cc:1146:0
    25	re2/dfa.cc:502:0
    26	re2/dfa.cc:518:0
    ...
```

May I ask you to look at the [target function](https://github.com/google/libfuzzer-bot/blob/master/re2/re2_fuzzer.cc) and at the recent coverage report to see if
some obvious big chunk of functionality is missing (not covered)?

**Comment by junyer** [comment]
Looking at `re2/re2.cc`:

```
    74	re2/re2.cc:275:0
```

This is `RE2::ProgramFanout()`, which you are not (yet?) using this time around.

```
    77	re2/re2.cc:354:0
    78	re2/re2.cc:434:0
```

Exercising `RE2::Extract()` will also exercise `RE2::MaxSubmatch()`.

```
    79	re2/re2.cc:485:0
    80	re2/re2.cc:926:0
```

It might be worth exercising `RE2::PossibleMatchRange()` and `RE2::CheckRewriteString()`.

```
    81	re2/re2.cc:964:0
```

This and onwards are the argument parsers. Complete coverage of just the integral types would require exercising the cross product of types and bases.

**Comment by junyer** [comment]
Almost all of the output for `re2/parse.cc` is surprising to me. For example,

```
    46	re2/parse.cc:171:0
    47	re2/parse.cc:179:0
```

These are the `ParseState` constructor and destructor – RE2 cannot parse a regular expression without creating and destroying one of those objects!

**Comment by junyer** [comment]
```
     1	re2/bitstate.cc:84:0
     2	re2/bitstate.cc:87:0
```

**Comment by junyer** [comment]
```
     1	re2/bitstate.cc:84:0
     2	re2/bitstate.cc:87:0
```

These are the `BitState` constructor and destructor.

**Comment by junyer** [comment]
There are similar oddities for other files such as `re2/dfa.cc`, but apart from that, the coverage of the compiler and the execution engines LGTM.

**Comment by junyer** [comment]
Is it possible that inlining could be causing this radar clutter?

**Comment by kcc** [comment]
@junyer yes, inlining is guilty in this imprecise coverage data. 
I've temporary switched the bot to O1, which is 2x slower, but does not suffer from inlining. 
Mind having one more quick look, e.g. http://104.197.8.28/pass-2015-11-04-16-32-05.log?
This time there are fewer uncovered functions and only two from re2/parse.cc

**Comment by junyer** [comment]
LGTM. You might consider fuzzing `RE2::Set` and `FilteredRE2` if you are extremely keen, but the utility functions that I mentioned previously are more important, I think.

**Comment by junyer** [comment]
As discussed privately, I will accept the fuzzer into this repository with no fuzzing integration as such.

> Just say put into the documentation something like "this is a fuzz target for fuzzers like libFuzzer and AFL. Our build system only ensures that the target function builds and runs on a fixed set of inputs. To do the actual fuzzing refer to documentation for libFuzzer [1] and AFL [2]"
> [1] llvm.org/docs/LibFuzzer.html
> [2] lcamtuf.coredump.cx/afl/
