### ISSUE TITLE
Eliminate compiler warnings for MSVC

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#65]
I have changes, mostly using static_cast, to eliminate all compiler warnings for MSVC. What do I do to upload them? I am only somewhat familiar with GIT.

**Comment by junyer** [comment]
Cool, thanks!

You should be able to generate a patch by executing `git diff` with standard output redirected to a file. Then you can just attach the file to this issue. I'll work through the changes. :)

**Comment by DThiebaud** [comment]
Replying to code reviews:

If I put in any reformatting changes, it was a mistake on my part, and I apologize.

Experimenting, almost all the warnings come from assigning a size_t to an int. Almost all of the warnings can be eliminated without casts, by changing the associated int fields to size_t or ptrdiff_t, in ways that appear to be correct. 2 or 3 cases seem to correctly require a cast.
If anyone is interested, I can send them the diff of my experiments, which compile without errors but which I haven't checked for correctness or tested.

Do the whitespace conventions for this project follow the Google coding conventions?

Some functions defined in re2.h may more naturally take size_t rather than int arguments, but do we want to change them?

**Comment by junyer** [comment]
> Do the whitespace conventions for this project follow the Google coding conventions?

Yes, indents are two spaces and tabs should not be used. (Having said that, I'm aware that there are oddball files like `util/benchmark.cc` as well as lines here and there that use or at least contain tabs.)

> Some functions defined in re2.h may more naturally take size_t rather than int arguments, but do we want to change them?

The answer is a resounding "maybe" – I'll have to consider each case very carefully and try to anticipate problems.

**Comment by junyer** [comment]
Just a few more files to go. :)

BTW, have you tried building with https://github.com/google/re2/blob/master/util/util.h#L73-L74 removed? If not, could you please try it and let me know whether they are hiding another slew of warnings? Thanks!

**Comment by DThiebaud** [comment]
On 11/30/2015 11:42 PM, Paul Wankadia wrote:
>
> Just a few more files to go. :)
>
> BTW, have you tried building with 
> https://github.com/google/re2/blob/master/util/util.h#L73-L74 removed? 
> If not, could you please try it and let me know whether they are 
> hiding another slew of warnings? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/65#issuecomment-160851441>.
>
This increases the number of warnings from 43 to 97. :(

**Comment by DThiebaud** [comment]
On 11/30/2015 11:42 PM, Paul Wankadia wrote:
>
> Just a few more files to go. :)
>
> BTW, have you tried building with 
> https://github.com/google/re2/blob/master/util/util.h#L73-L74 removed? 
> If not, could you please try it and let me know whether they are 
> hiding another slew of warnings? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/65#issuecomment-160851441>.
>

To get rid of warning c4800, coercing an int to bool does not get rid of 
the error. In other words if you have:

int i;
bool b;
b = i;

changing "b = i" to "b = (bool)i" does not get rid of the warning. To 
get rid of the warning, you need to change "b = i" to "b = (i!=0)"

Would you like me to send you a list of where warning c4800 is generated?

**Comment by junyer** [comment]
> Would you like me to send you a list of where warning c4800 is generated?

Thanks!

(For anyone else reading this, the list was provided via private mail.)

**Comment by junyer** [comment]
I believe that's everything, but I'll wait for you to confirm before I close this issue. Thanks! :)

**Comment by DThiebaud** [comment]
On 12/6/2015 1:18 AM, Paul Wankadia wrote:
>
> I believe that's everything, but I'll wait for you to confirm before I 
> close this issue. Thanks! :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/65#issuecomment-162276600>.
>
There is still one warning left:

*Warning    C4244    '=': conversion from 're2::int64' to 'int', 
possible loss of data    benchmark E:\src\re2\util\benchmark.cc    129
*

**Comment by DThiebaud** [comment]
Re2 and all the tests now build under MSVC 15 with no warnings and no errors.

**Comment by junyer** [comment]
Once again, a milestone reached because of your contributions! Thank you very much. :)

**Comment by DThiebaud** [comment]
On 12/6/2015 9:22 PM, Paul Wankadia wrote:
>
> Once again, a milestone reached because of your contributions! Thank 
> you very much. :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/65#issuecomment-162390498>.
>
Thank you! I am currently running all the tests--I am confident they 
will all pass. I will let you know when they finish.

**Comment by DThiebaud** [comment]
All tests were passed for RE2 built with MSVC 2015.

**Comment by junyer** [comment]
Great, thank you. :)
