### ISSUE TITLE
Wrong Match

### ISSUE THREAD

**Issue by marijnfs** [google/re2#67]
I'm calling Match directly on a string with pattern: "[^\S]+" , so at least one character should match.
It happily returns true and the match has a length of 0. 
Is this a known error for this version?
libre2 version: 20150701+dfsg-2

I call it using:
reg.Match(input, index, input.size(), RE2::ANCHOR_START, &matches[0], 1)

**Comment by junyer** [comment]
Could you please provide a full example that reproduces the bug? Thanks!

**Comment by marijnfs** [comment]
Hi,

I have found an error in my code, due to an uninitialized string a
constructor it probably got a random string to parse. So problem is
solved!

-Marijn
