### ISSUE TITLE
Certain regexes are very slow in re2-2015-11-01

### ISSUE THREAD

**Issue by sklochkov** [google/re2#71]
While using the latest release of re2 (2015-11-01), I've encountered an issue, that certain regexes are extremely slow (4-5 times slower than using python 2.7 builtin re module!)

I've produced an isolated case that reproduces the issue.

Test data is generated like that (it's meant to resemble a certain log format that I was using when I've encountered the issue):
```bash
for i in {0..9999999} ; do echo "${i} 2015-12-22:00:00:26 fooooo:baaaaaar acme.example.com : AAA ${i} FOO 43 4 baz=110 : OK NOREPLY : ms=3" >> /dev/shm/test.log ; done
```
This is a sample re2 program. It runs for 2 minutes 50 seconds on a Xeon E5520 CPU.

```c++
#include <fstream>
#include <string>
#include <re2/re2.h>
#include <stdio.h>

int main(int argc, char **argv) {
	re2::RE2 re(".*?AAA\\s+(\\d+)\\s+(FOO|BAR).*");
	std::ifstream infile("/dev/shm/test.log");
	std::string line;
	std::string bat, domain;
	int i;
	while (std::getline(infile, line)) {
		if (re2::RE2::FullMatch(line, re, &bat, &domain)) {
			i++;
		}
	}
	infile.close();
	printf("%d\n", i);
	return 0;
}
```
And this is a python script that completes the same task in 30 seconds:
```python
import re
TEST_RE = re.compile(""".*?AAA\s+(\d+)\s+(FOO|BAR).*""")
res = 0
f = open("/dev/shm/test.log", 'r')
for line in f:
        m = TEST_RE.match(line)
        if m:
                res += 1
f.close()
print res
```
Any suggestions will be appreciated.

**Comment by sklochkov** [comment]
In case it will help, this is the callgrind output for re2 processing first 10000 lines of the aforementioned test file.

https://yadi.sk/d/wA1hI09omQKLi

**Comment by junyer** [comment]
According to the benchmarks that I just ran, a partial match with `AAA\s+(\d+)\s+(FOO|BAR)` will be roughly three times faster than a full match with `.*?AAA\s+(\d+)\s+(FOO|BAR).*`:

```
BM_Issue71_FullMatch     2000000               536 ns/op         195.54 MB/s
BM_Issue71_PartialMatch 10000000               184 ns/op         569.38 MB/s
```

However, your time works out to 17µs/op. Some of that will be due to the overhead of file I/O, but I'm not sure how much. Also, could you please just confirm that you compiled with at least `-O2` if not `-O3`?

**Comment by sklochkov** [comment]
Hello Junyer,

libre2.so was compiled with -O2.

I've tried to use partial match, and in that cases it takes re2 only 8 seconds to complete the test.

**Comment by junyer** [comment]
> I've tried to use partial match, and in that cases it takes re2 only 8 seconds to complete the test.

Assuming everything else remained the same, that works out to 800 ns/op, which sounds a lot more reasonable. Unfortunately, I still have no explanation for your previous time. :(

**Comment by junyer** [comment]
Ahh. I had overlooked that your code was asking for two submatches. I reran the benchmarks and the speed of the full match is indeed consistent with your observed time:

```
BM_Issue71_FullMatch      100000             17928 ns/op           6.19 MB/s
BM_Issue71_PartialMatch  5000000               528 ns/op         209.92 MB/s
```

For the full match, RE2 uses the BitState execution engine. For the partial match, RE2 uses the DFA execution engine (forwards and backwards!) and then the OnePass execution engine. The latter might sound like more work, but RE2 is free to use `memchr(3)` to look for the first `A`, which is much faster than processing one byte at a time for the `.*?`.
