### ISSUE TITLE
RE2 doesn't support invisible character matching.

### ISSUE THREAD

**Issue by iaadoa** [google/re2#72]
I need to match a pattern with invincible character in it.  For example, "\xA8\xA9\xAA".  I tried following testing codes:

```C
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <re2/re2.h>

int main() {
    char text[4];
    RE2 re("\\xA8\\xA9\\xAA");
    assert(re.ok());
    text[0] = 0xA8;
    text[1] = 0xA9;
    text[2] = 0xAA;
    text[3] = 0;
    assert (RE2::FullMatch(text, re));

    return 0;
}
```

And got following result:
```
Assertion failed: (RE2::FullMatch(text, re)), function main, file test_re.cc, line 14.
Abort trap: 6
```

But if I input visible character vector like "\\x3a\\3b\\3c", matching is success.

**Comment by junyer** [comment]
RE2 defaults to UTF-8, so you will want to use Latin-1 instead:

```
    RE2 re("\xA8\xA9\xAA", RE2::Latin1);
```

That should allow you to match arbitrary bytes.

**Comment by iaadoa** [comment]
That works!  Thank you very much.

**Comment by junyer** [comment]
Great, thanks for confirming.
