### ISSUE TITLE
Installing re2 on centos7

### ISSUE THREAD

**Issue by matthewferguson694** [google/re2#73]
Hi Guys,

I am trying to install re2 on a centos7 vm, and I am having some trouble solving these dependencies:

/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc

Any help would be great! :)

thanks!

**Comment by junyer** [comment]
Ouch! Are you able to build anything else? (Is RE2 the only thing that fails to build?)

**Comment by matthewferguson694** [comment]
Hmm, that is a good question, I have not tried to build anything else.

I installed executed: yum install -y glibc-static libstdc++-static

and then tried again:

[root@roller re2]# make testinstall
cp testinstall.cc obj
(cd obj && g++ -I/usr/local/include -L/usr/local/lib testinstall.cc -lre2 -pthread -static -o testinstall)
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): In function `sem_open':
(.text+0x682b): warning: the use of `mktemp' is dangerous, better use `mkstemp'
obj/testinstall
PASS
(cd obj && g++ -I/usr/local/include -L/usr/local/lib testinstall.cc -lre2 -pthread -o testinstall)
LD_LIBRARY_PATH=/usr/local/lib obj/testinstall
PASS

So that looks a lot better!

**Comment by junyer** [comment]
Ahh. Very good. :)
