### ISSUE TITLE
Building with MinGW

### ISSUE THREAD

**Issue by Ratstail91** [google/re2#76]
I feel stupid asking this, but how the hell do you build this with MinGW? make doesn't work, and the makefile doesn't seem to have the answer.

**Comment by junyer** [comment]
CMake supports MinGW and MSYS, I believe, so please try using it to generate the appropriate files for your system.

**Comment by Ratstail91** [comment]
I've been struggling all day with this repo, and nothing has come of it. Is a simple Regex parser so much to ask?

**Comment by junyer** [comment]
Did you try using CMake?

**Comment by Ratstail91** [comment]
Yes, and it still didn't work.

**Comment by junyer** [comment]
Please read [How to Report Bugs Effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) by Simon Tatham.

**Comment by DThiebaud** [comment]
Regex2 gets compile errors for me for mingw using the make file generated by Cmake:

E:\src\re2\bin>make
[  1%] Building CXX object CMakeFiles/benchmark.dir/re2/testing/backtrack.cc.obj
In file included from c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/atomic:38:0,
                 from E:/src/re2/util/util.h:33,
                 from E:\src\re2\re2\testing\backtrack.cc:26:
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
In file included from c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/atomic:41:0,
                 from E:/src/re2/util/util.h:33,
                 from E:\src\re2\re2\testing\backtrack.cc:26:
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:63:3: error: 'constexpr' does not name a type
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:63:3: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:71:41: error: expected initializer before 'noexcept'
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:75:41: error: expected initializer before 'noexcept'
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:81:30: error: expected initializer before 'noexcept'
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:129:25: error: 'char16_t' was not declared in this scope
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:129:33: error: template argument 1 is invalid
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:129:64: error: invalid type in declaration before ';' token
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:132:25: error: 'char32_t' was not declared in this scope
c:\gnat\2013\bin\../lib/gcc/i686-pc-mingw32/4.7.4/../../../../include/c++/4.7.4/bits/atomic_base.h:132:33: error: template argument 1 is invalid
c

and on and on for hundreds of errors. Apparently some source files are using c++11 features, but the option for them is not being turned on. If anyone wants the full printfile of the compile I can send it to them. It looks like  cmakelists.txt needs somethings added to generate compile option -stdc=c++11 if mingw is being used.

Cmake version: 3.4.0
make version: GNU Make 4.1 Built for x86_64-w64-mingw32
g++.exe version: g++ (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 4.9.2

**Comment by DThiebaud** [comment]
I think it would be worth re-opening this topic.

**Comment by junyer** [comment]
Ahh. Yes, C++11 has been required since cd505f4597d4022902b25bd036de29478e22d481. Unfortunately, I had not considered MinGW at the time. I will look into tweaking `CMakeLists.txt` accordingly.

Thank you for investigating!

**Comment by DThiebaud** [comment]
Further testing shows: in the makefiles generated by Cmake for mingw on windows, and for gcc on linux, the option "-std=c++" is not passed to the compiled, and the compile gets hundreds of errors for this. Note that this happens on gcc on linux as well as mingw on windows. 

If I manually add this option to CMAKE_C++_FLAGS in the GUI, then re2 builds cleanly on both gcc. mingw gets a compile error in re2test.cc because it can't find include file <include sys/mman.h>.  This is a separate issue. I'll check if there's an error in my setup before logging a new issue.

Tomarrow I'm test that re2 still compiles ok on MSVC.

**Comment by DThiebaud** [comment]
Gopherbot's commit does not correct the problem for me--I get the same results as before.

**Comment by junyer** [comment]
Maybe it should use `add_compile_options` rather than `add_definitions` even though the latter works for me with CMake 2.8.12.2. I will try that instead.

BTW, if you want to compare, here is an example of what `grep(1)` turns up with 11250b391d7815eca0fda3b5364fe895d01df308:

```
./CMakeFiles/re2.dir/flags.make:CXX_FLAGS = -I/home/junyer/re2    -std=c++11 -pthread
```

**Comment by junyer** [comment]
Please try with 366f9203d0900f15f6214c92b554fc1de0305ae4 on Linux.

I will try to figure out what the other MinGW issue might be.

**Comment by DThiebaud** [comment]
That didn't seem to work either. I'm tired and could be making errors. I'll retest in the morning.

**Comment by junyer** [comment]
No worries. As always, your assistance is very much appreciated!

I have committed 5e8da740f306a407e20a21aab8c491d2b0214603, which should hopefully address the other MinGW issue.

**Comment by DThiebaud** [comment]
In Cmake, WIN32 is true for Mingw. We want to set "-std=c++11" for both gcc in linux and Mingw in Windows, but not for MSVC. The following works for me:


if (NOT MSVC)
  add_definitions(-std=c++11)
endif()
if(WIN32)
  add_definitions(-DUNICODE -D_UNICODE -DSTRICT -DNOMINMAX)
  set(THREADING threadwin)
else()
  add_definitions(-pthread)
  set(THREADING thread)
  list(APPEND EXTRA_TARGET_LINK_LIBRARIES -pthread)
endif()

Also, the fix for not finding <sys/mman.h> worked for me.

I'll retest everything in the morning.

**Comment by junyer** [comment]
Good catch. `WIN32` does indeed mean the target, not the compiler.

**Comment by junyer** [comment]
Okay, 72276a1197043d4359863463fa59fd701d732ae0 looks for GCC/Clang, so that should hopefully cover Cygwin as well as MinGW.

**Comment by DThiebaud** [comment]
With the latest patch, re2 builds correctly for MSVC and mingw on Windows and GCC on Linux using the make files generated by CMake. Thanks to those who contributed on this.

**Comment by DThiebaud** [comment]
CMake does not have an option to create a make file for Cygwin. However, RE2 compile cleanly under Cygwin using the make file in the top directory of re2. (Since the aim of Cygwin is to replicate a Unix environment, this is probably to be expected, but I thought I'd try. It worked.

**Comment by junyer** [comment]
The `cmake(1)` manual page seems to suggest that Cygwin is supported, but if it Just Works™ with the RE2 `Makefile` anyway, then that's even better.

Thank you very much for diagnosing the problems and also for confirming the fixes!
