### ISSUE TITLE
Add to README: node.js wrapper for RE2

### ISSUE THREAD

**Issue by uhop** [google/re2#77]
I wrote a node.js wrapper (JavaScript) before this repository went public. It is available under the BSD license. `node-re2` is used in several production projects in IT. It may be worthwhile to add it to the README in the list of well-known publicly available wrappers.

The repository can be found here:

https://github.com/uhop/node-re2

The NPM package is here:

https://www.npmjs.com/package/re2

**Comment by junyer** [comment]
It's been linked since 81aad9ad217fe95de693e2253e7fd510f649e9f2. :)

**Comment by uhop** [comment]
Heh, I didn't update the repository since then. Totally my fault, sorry.
