### ISSUE TITLE
Documentation does not explain replace syntax

### ISSUE THREAD

**Issue by SomnaW** [google/re2#78]
I had to dig through various forums to discover that $1 is the correct syntax to use the first numbered capturing group instead of \1. I still have no idea what the syntax is for using a named capturing group.

**Comment by junyer** [comment]
`\1` is correct for RE2.

`$1` sounds like the Go `regexp` package. Please refer to https://golang.org/pkg/regexp/#Regexp.Expand for the relevant documentation.
