### ISSUE TITLE
Compile errors in prog.cc lines 117, 119 using MSVC 2013

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#79]
Building the latest re2 using MSVC 2013, I get the following compile errors:

Error	1	error C2451: conditional expression of type 'std::atomic<re2::DFA *>' is illegal	E:\src\re2\re2\prog.cc	117	1	re2
	22	IntelliSense: more than one conversion function from "std::atomic<re2::DFA *>" to a built-in type applies:
            function "std::atomic<_Ty *>::operator _Ty *() const [with _Ty=re2::DFA]"
            function "std::_Atomic_address::operator void *() const"	e:\src\re2\re2\prog.cc	117	9	re2

Error	2	error C2451: conditional expression of type 'std::atomic<re2::DFA *>' is illegal	E:\src\re2\re2\prog.cc	119	1	re2
	23	IntelliSense: more than one conversion function from "std::atomic<re2::DFA *>" to a built-in type applies:
            function "std::atomic<_Ty *>::operator _Ty *() const [with _Ty=re2::DFA]"
            function "std::_Atomic_address::operator void *() const"	e:\src\re2\re2\prog.cc	119	9	re2

**Comment by DThiebaud** [comment]
Changing lines 117-120 to the following (by adding "(void *)" ) makes re2 build cleanly in MSVC 2013, though I don't know if this is what is wanted or not:

    if ((void *)dfa_first_)
      delete_dfa_(dfa_first_);
    if ((void *)dfa_longest_)
      delete_dfa_(dfa_longest_);

**Comment by junyer** [comment]
Thanks for the report! I think I can tidy up the code slightly while I'm here. :)

**Comment by DThiebaud** [comment]
This worked; it compiles with no errors in it.

But I do get two warnings in lines 1586-1589 of re2test.cc:

Warning	1	warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data	E:\src\re2\re2\testing\re2_test.cc	1586	1	re2_test
Warning	2	warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data	E:\src\re2\re2\testing\re2_test.cc	1589	1	re2_test

The lines are:

 CHECK(re.Match(s, 0, s.size(), RE2::UNANCHORED, &m, 1));
  CHECK_EQ(m, s) << " (UNANCHORED) got m='" << m << "', want '" << s << "'";

  CHECK(re.Match(s, 0, s.size(), RE2::ANCHOR_BOTH, &m, 1));
  CHECK_EQ(m, s) << " (ANCHOR_BOTH) got m='" << m << "', want '" << s << "'";

Is it worth resolving these warnings?

**Comment by junyer** [comment]
Yes, certainly. I will commit a fix shortly.

**Comment by junyer** [comment]
Fixed in ce40fd612a0f9df3b7227a35f840238563f7a110. Thanks for letting me know!

**Comment by DThiebaud** [comment]
This doesn't really belong here but I need to put it somewhere.

Results of building RE2 with different versions of MSVC:

2015: works
2013: works
2012: fails because function va_copy is not supported by this version of MSVC
2010: fails because include file <atomic> is not supported by this version of MSVC

Do we want to update the wiki to say that MSVC 213 or later is required?

Do we want to update the

**Comment by junyer** [comment]
I think you've just answered your question from https://github.com/google/re2/issues/40#issuecomment-167711516. I'll update the documentation now. :)

**Comment by DThiebaud** [comment]
If we #define va_copy(ab) (a) = (b),
re2 will compile cleanly in MSVC 2012 (tested) and should (though I haven't tested it) work correctly. Is it worth adding a define like this, to be executed for MSVC 2012 only, to the code? Personally, I don't think so but what does anyone else think?

**Comment by junyer** [comment]
I would prefer not to ship that hack as part of RE2. ;)
