### ISSUE TITLE
Build fails under MSVC 2015

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#82]
The current build fails under MSVC 2015. If built with static library, the compile runs ok, but every test program exits in 0 seconds with return code 1. If built with dll, the compile fails because re2.lib is not generated for re2.dll. This may be because the dll is not exporting any symbols.

I'm going on vacation tomorrow and I may not have a chance to research this for two weeks.

I suspect but have not tested that this is released to recent changes for generating an .so file under linux. How, in GIT, do I pull the code from before these changes?

**Comment by DThiebaud** [comment]
I'll look at the GIT documentation and figure out what I need to know. I will test various versions and see which change produced the problem with MSVC. I'll have to do this after vacation.

**Comment by junyer** [comment]
> The current build fails under MSVC 2015. If built with static library, the compile runs ok, but every test program exits in 0 seconds with return code 1. If built with dll, the compile fails because re2.lib is not generated for re2.dll. This may be because the dll is not exporting any symbols.

Ouch! We know from your past experiments that MSVC won't build a .dll correctly without additional work, but it's very concerning that something else has broken.

> I suspect but have not tested that this is released to recent changes for generating an .so file under linux. How, in GIT, do I pull the code from before these changes?

I'm not sure which change(s) you mean, but `git checkout <commit>` should do the needful.

**Comment by DThiebaud** [comment]
On 3/14/2016 9:27 PM, Paul Wankadia wrote:
>
>     The current build fails under MSVC 2015. If built with static
>     library, the compile runs ok, but every test program exits in 0
>     seconds with return code 1. If built with dll, the compile fails
>     because re2.lib is not generated for re2.dll. This may be because
>     the dll is not exporting any symbols.
>
> Ouch! We know from your past experiments that MSVC won't build a .dll 
> correctly without additional work, but it's very concerning that 
> something else has broken.
>
>     I suspect but have not tested that this is released to recent
>     changes for generating an .so file under linux. How, in GIT, do I
>     pull the code from before these changes?
>
> I'm not sure which change(s) you mean, but |git checkout <commit>| 
> should do the needful.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/re2/issues/82#issuecomment-196620172
>
Did we decide to not do anything about building a DLL in MSVC, unless 
someone needs it? I seem to recall I experimented with the necessary 
changes and saved them but we did not commit them. So not building a dll 
is not an issue. However, the problem I had with the static build still 
holds (all test programs immediately exit with status code 1). I should 
be able to run one of these under debugger and see what is going on.

**Comment by junyer** [comment]
> Did we decide to not do anything about building a DLL in MSVC, unless
> someone needs it? I seem to recall I experimented with the necessary
> changes and saved them but we did not commit them. So not building a dll
> is not an issue. 

Yes, that's correct.

> However, the problem I had with the static build still
> holds (all test programs immediately exit with status code 1). I should
> be able to run one of these under debugger and see what is going on.

Thank you very much. I'll await further details.

**Comment by DThiebaud** [comment]
On 3/14/2016 10:12 PM, Paul Wankadia wrote:
>
>     Did we decide to not do anything about building a DLL in MSVC, unless
>     someone needs it? I seem to recall I experimented with the necessary
>     changes and saved them but we did not commit them. So not building
>     a dll
>     is not an issue.
>
> Yes, that's correct.
>
>     However, the problem I had with the static build still
>     holds (all test programs immediately exit with status code 1). I
>     should
>     be able to run one of these under debugger and see what is going on.
>
> Thank you very much. I'll await further details.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/google/re2/issues/82#issuecomment-196631185
>
The error is not in re2 but in my python test script. Something changed 
between python 2 and python 3. The issue can be closed.

**Comment by junyer** [comment]
Ahh. Thanks for letting me know. Enjoy your vacation! :)
