### ISSUE TITLE
Mach IP address

### ISSUE THREAD

**Issue by cmesquita** [google/re2#83]
Hi All -
Does anyone able to provide an example to match a IP ADDRESS using RE2?

I need match something like : 172.12.0.2 

tks in advance

**Comment by junyer** [comment]
`\d+\.\d+\.\d+\.\d+` is good enough in most cases.

**Comment by jcac100** [comment]
Does anyone have success implementing an RE2 regular expression that can catch ALL IPv4 addresses, private, public, and in-between?
