### ISSUE TITLE
Have Cmake put out error for building MSVC for DLL?

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#84]
DLLs built from MSVC are not supported by RE2. Could Cmake put out an error message if a person tries to build a dynamic lib (DLL) using MSVC? Also, could it put out an error message if a version of MSVC prior to 2013 is requested?

**Comment by junyer** [comment]
> DLLs built from MSVC are not supported by RE2. Could Cmake put out an error message if a person tries to build a dynamic lib (DLL) using MSVC? 

I'll find out how to do this.

> Also, could it put out an error message if a version of MSVC prior to 2013 is requested?

d36f207ec3663340c3111627d13d3359b73b9208 should have made it require Visual Studio 2013 or later.

**Comment by junyer** [comment]
Cool, it looks like `BUILD_SHARED_LIBS` is what we want.

**Comment by junyer** [comment]
I would have found that sooner if I had looked at our `CMakeLists.txt` file instead of the `cmake(1)` manual page. ;)
