### ISSUE TITLE
Error in re2_test when compiled under windows for MinGW

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#85]
I compiled RE2 for MinGW under Windows, using the Make file created by CMake. The compiles all ran fine. When I executed the test programs, all ran correctly except for re2_test. After 45 minutes, it aborted with return code 3.

I'm not familiar with the debugger for MinGW. I'll try to learn enough to use it and see where the error is occurring and what the error is.

**Comment by DThiebaud** [comment]
The program writes the following to stderr:
RE2.FullMatchIgnoredArg
RE2.FullMatchTypedNullArg
RE2.NULTerminated
RE2.FullMatchTypeTests
RE2.FloatingPointFullMatchTypes
e:/src/re2/re2/testing/re2_test.cc:885: Check failed: (v) == (6700000000081920.1f)6.6999997e+015 != 6.7000003e+015

**Comment by junyer** [comment]
This looks like the problem that was reported in https://github.com/google/re2/issues/2.

**Comment by junyer** [comment]
https://github.com/google/re2/blob/master/re2/testing/re2_test.cc#L870-L886 shows that @rsc wrote this test case very carefully and very deliberately. It's quite intriguing that it fails on Cygwin and MinGW.

**Comment by DThiebaud** [comment]
On 3/30/2016 10:43 PM, Paul Wankadia wrote:
>
> https://github.com/google/re2/blob/master/re2/testing/re2_test.cc#L870-L886 
> shows that @rsc <https://github.com/rsc> wrote this test case very 
> carefully and very deliberately. It's quite intriguing that it fails 
> on Cygwin and MinGW.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/85#issuecomment-203739268>
>
I didn't test it on Cygwin.

**Comment by junyer** [comment]
Oh, I was alluding to the other report, which said "on a Cygwin64 environment". :)

**Comment by DThiebaud** [comment]
On 3/30/2016 10:43 PM, Paul Wankadia wrote:
>
> https://github.com/google/re2/blob/master/re2/testing/re2_test.cc#L870-L886 
> shows that @rsc <https://github.com/rsc> wrote this test case very 
> carefully and very deliberately. It's quite intriguing that it fails 
> on Cygwin and MinGW.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/85#issuecomment-203739268>
>
Testing:
    mingw 64 bits gcc version 5.3: error
    cygwin 64 bits gcc version 5.3: error
    cygwin 32 bits gcc version 5.3: error
    MSVC 15 64 bits: no error
    MSVC 15 32 bits: no error
(same error in all cases)

**Comment by junyer** [comment]
http://www.polarhome.com/service/man/?qf=strtod&tf=2&of=Cygwin&sf=3 suggests that `strtof(3)` is broken on Cygwin! And I'm guessing that MinGW inherited that behaviour.

**Comment by DThiebaud** [comment]
On 04/01/2016 12:11 AM, Paul Wankadia wrote:
>
> http://www.polarhome.com/service/man/?qf=strtod&tf=2&of=Cygwin&sf=3 
> suggests that |strtof(3)| is broken on Cygwin! And I'm guessing that 
> MinGW inherited that behaviour.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/85#issuecomment-204240892>
>
Paul, where on the page does it suggest this? I don't see it.

**Comment by junyer** [comment]
This hints at trouble:

> `strtof` is identical to `strtod` except for its return type.

This is the clincher:

> However, `strtof` is currently subject to double rounding errors.

**Comment by DThiebaud** [comment]
On 03/31/2016 12:43 AM, Paul Wankadia wrote:
>
> Oh, I was alluding to the other report, which said "on a Cygwin64 
> environment". :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/85#issuecomment-203749947>
>
Is there any chance of producing a work-around for this compiler error? 
Is there any interest in doing so?

**Comment by junyer** [comment]
From what I can tell, this problem exists because their standard library implements `strtof(3)` by calling `strtod(3)` and then casting the result from `double` to `float`. It's not something that we can work around without providing a bona fide implementation of `strtof(3)`. However, it's also not something that will ever matter to most people. For now, I will be satisfied as long as Cygwin and MinGW users can run the RE2 tests without failures caused by hitting this edge case.
