### ISSUE TITLE
Cygwin build fails using native make file (succeeds using Cmake make file)

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#86]
If I try to build RE2 using Cygwin (under windows), it fails with a message "can't file -lre". This is using RE2's native make file. If I build using a make file generated by CMake, it succeeds. (Must run CMake under Cygwin, not native in Windows.)

I don't know if this is an issue or not but I thought I would report it.

The following is the last few lines from "make test":

g++ -c -o obj/re2/testing/string_generator_test.o  -std=c++11 -O3 -g -pthread   -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -I.     -DNDEBUG re2/testing/string_generator_test.cc
g++ -o obj/test/string_generator_test obj/re2/testing/string_generator_test.o obj/util/pcre.o obj/util/random.o obj/util/thread.o obj/re2/testing/backtrack.o obj/re2/testing/dump.o obj/re2/testing/exhaustive_tester.o obj/re2/testing/null_walker.o obj/re2/testing/regexp_generator.o obj/re2/testing/string_generator.o obj/re2/testing/tester.o  obj/util/test.o obj/libre2.a -pthread
g++ -o obj/so/test/charclass_test obj/re2/testing/charclass_test.o obj/util/pcre.o obj/util/random.o obj/util/thread.o obj/re2/testing/backtrack.o obj/re2/testing/dump.o obj/re2/testing/exhaustive_tester.o obj/re2/testing/null_walker.o obj/re2/testing/regexp_generator.o obj/re2/testing/string_generator.o obj/re2/testing/tester.o  obj/util/test.o -Lobj/so -lre2 obj/libre2.a -pthread
/usr/lib/gcc/x86_64-pc-cygwin/5.3.0/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lre2
collect2: error: ld returned 1 exit status
Makefile:209: recipe for target 'obj/so/test/charclass_test' failed
make: *** [obj/so/test/charclass_test] Error 1

I can post the whole file if desired.

**Comment by junyer** [comment]
I suspect that Cygwin is looking for `libre2.dll` rather than `libre2.so`. We could work around that, I bet, but if I'm reading https://cygwin.com/cygwin-ug-net/dll.html correctly, even Cygwin can't avoid the pain required in order to build a DLL properly. (See the part about building as an export library.)

**Comment by junyer** [comment]
I updated https://github.com/google/re2/wiki/Install: "Bazel and CMake are also supported. The latter enables generation of Visual Studio and Xcode projects as well as Cygwin, MinGW and MSYS makefiles." Is there anything else that you think we should do to guide Cygwin users in the direction of CMake?

**Comment by DThiebaud** [comment]
On 4/4/2016 2:15 AM, Paul Wankadia wrote:
>
> I updated https://github.com/google/re2/wiki/Install: "Bazel and CMake 
> are also supported. The latter enables generation of Visual Studio and 
> Xcode projects as well as Cygwin, MinGW and MSYS makefiles." Is there 
> anything else that you think we should do to guide Cygwin users in the 
> direction of CMake?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/google/re2/issues/86#issuecomment-205150233>
>
It generates lire2.a not libre2.dll or .so.  I don't know if what you 
said is the problem or not. However, I agree that since the Cmake file 
works, we could close the issue.

I think we should add a sentence that, for Cygwin, CMake must be run 
from the Cygwin command line not the Windows command line. It took me a 
while to recognize this.

I wonder if this is all moot? I suspect that no one other than me is 
trying to use RE2 with Cygwin.

**Comment by junyer** [comment]
> I think we should add a sentence that, for Cygwin, CMake must be run
> from the Cygwin command line not the Windows command line. It took me a
> while to recognize this.

Thanks for reminding me about that. I added a note as well:

_Cygwin users: You must run CMake from the Cygwin command line, not the Windows command line._

> I wonder if this is all moot? I suspect that no one other than me is
> trying to use RE2 with Cygwin.

We might not find out whenever it helps someone, but there is certainly no harm in documenting whatever we learn. :)
