### ISSUE TITLE
Warning errors converting size_t to int in prog.cc compiled with MSVC

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#89]
prog.cc
3>E:\src\re2\re2\prog.cc(380): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
3>E:\src\re2\re2\prog.cc(385): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
3>E:\src\re2\re2\prog.cc(415): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
3>E:\src\re2\re2\prog.cc(506): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
3>E:\src\re2\re2\prog.cc(507): warning C4267: '=': conversion from 'size_t' to 're2::uint32', possible loss of data
3>

**Comment by DThiebaud** [comment]
The version of RE2 used was cloned at about 6 PM Eastern time on May 1.

**Comment by DThiebaud** [comment]
For anyone not in the United States, that would be about 10 PM on May 1 in GMT.

**Comment by junyer** [comment]
Oops, mea culpa. Thanks for the report!
