### ISSUE TITLE
Question: Obtaining matches

### ISSUE THREAD

**Issue by IngwiePhoenix** [google/re2#9]
Hey.

I have not found any other place where to ask questions - so if this is not the right one, i'd be happy if you could point me into the right direction where to ask.

Currently I am working on replacing a RegExp extension within a scripting language ( https://github.com/unitpoint/objectscript ) that was formerly based off pcrelib with re2. So I downloaded, test-compiled and ran all the tests that re2 had - and I had no issues at all, OS X 10.10.

But now I want to write the actual C++ wrapper but got a little bit stuck:

```c++
  static bool FullMatchN(const StringPiece& text, const RE2& re,
                         const Arg* const args[], int argc);
  static const VariadicFunction2<
      bool, const StringPiece&, const RE2&, Arg, RE2::FullMatchN> FullMatch;
```

I see that there is `const Arg* const args[]`. But I see no conversion operator within the `Arg` class to the parsed type...or at least, no way to convert the matches.

What I would like to do would be something like this:

```c++
{type} matches = RE2::fullMtchN(string, RegExp, &args, &argc);
for(int i=0; i<argc; i++) {
    // Add value to a return array to the script language.
    // Get the type within args[i] and add the correct value type.
}
```

I am not familiar with Python or any other language for which a re2 wrapper exists, so I have a lot of difficulties understanding how they work.

All that I want to do for now is to place in a content string and a regular expression and return the results in an array.

How would I go about this?

Kind regards,
Ingwie

**Comment by junyer** [comment]
If you just want the submatches as strings, I'd suggest using `RE2::Match()` instead of fiddling around with `RE2::Arg` objects.

Please send mail to re2-dev@googlegroups.com if you have further questions. There are many people subscribed to the mailing list, but very few who triage the GitHub issues.
