### ISSUE TITLE
Named Groups not working in Google Apps Script

### ISSUE THREAD

**Issue by bobsquito** [google/re2#92]
Hi,

I am not sure if this is the right or wrong place to be posting this, but I am trying to used named groups in Google Apps Script but they just don't seem to work. The documentation in Google Apps Script points to the wiki on here, and that documentation states that it should work.

```
function regexTest() {
  var text = 'my number is 01234567';
  var regex = /(?P<num>\d+)/;
  var result = regex.exec(text);
  Logger.log(result.num);
}
```

Instead I get the error:
SyntaxError: Invalid quantifier ?.

Sorry if this isn't the right place to be posting this but thanks for any help

**Comment by junyer** [comment]
Sorry, I can't seem to find that documentation that mentions RE2. Could you please let me know which page(s) you were reading? I was under the impression that Apps Script spoke the JavaScript dialect of regular expressions, but I can follow up with the team during the week. Thanks!

**Comment by junyer** [comment]
Note to self: Check https://code.google.com/p/google-apps-script-issues/issues/detail?id=6002 for updates.

**Comment by junyer** [comment]
Ping, @bobsquito!

Could you please let me know which page(s) you were reading? Thanks!

**Comment by bobsquito** [comment]
@junyer I haven't been able to find it again, I came across it when I was trying to find out what google apps script was using. I'm pretty sure I didn't just dream it...

**Comment by junyer** [comment]
Fair enough. If you do happen to find it again at some point, please let me know so that I can ask the team to correct it.
