### ISSUE TITLE
Illumos build - libre2.symbols - symbol referencing errors

### ISSUE THREAD

**Issue by DrLou** [google/re2#93]
Paul,

Trying to revisit this now, against a fresh pull. Only mod is REBUILD_TABLES=1...

Attempt is to specifically force use of the Illumos linker, with gcc 4.9:

```
$ /usr/bin/ld --version 
ld: Software Generation Utilities - Solaris Link Editors: 5.11-1.1753 (illumos)
$ gcc --version              
gcc (GCC) 4.9.3

$ make distclean
$ make LD_ALTEXEC=/usr/bin/ld

...
g++ -shared -Wl,-soname,libre2.so.0,-M,libre2.symbols -pthread    -o obj/so/libre2.so.0 obj/so/util/hash.o obj/so/util/logging.o obj/so/util/rune.o obj/so/util/stringprintf.o obj/so/util/strutil.o obj/so/util/valgrind.o obj/so/re2/bitstate.o obj/so/re2/compile.o obj/so/re2/dfa.o obj/so/re2/filtered_re2.o obj/so/re2/mimics_pcre.o obj/so/re2/nfa.o obj/so/re2/onepass.o obj/so/re2/parse.o obj/so/re2/perl_groups.o obj/so/re2/prefilter.o obj/so/re2/prefilter_tree.o obj/so/re2/prog.o obj/so/re2/re2.o obj/so/re2/regexp.o obj/so/re2/set.o obj/so/re2/simplify.o obj/so/re2/stringpiece.o obj/so/re2/tostring.o obj/so/re2/unicode_casefold.o obj/so/re2/unicode_groups.o
Undefined                       first referenced
 symbol                             in file
_ZNK3re211FilteredRE2*              libre2.symbols
_ZNK3re211StringPiece*              libre2.symbols
...
ld: warning: symbol referencing errors
ln -sf libre2.so.0 obj/so/libre2.so
```
( apologies for inactivity; original (driving) project had to be temporarily dropped, partly due to inability to build re2 (!) )

**Comment by junyer** [comment]
Could you please use `nm(1)` to list the symbols in `libre2.a` and then attach a file here containing the output? I suspect that the symbols are different – if we are lucky, it could just be a matter of adding or removing a leading underscore. Thanks!

**Comment by DrLou** [comment]
nm output attached here. Thanks for your attention to this.

[nm symbol output.txt](https://github.com/google/re2/files/276386/nm.symbol.output.txt)

**Comment by junyer** [comment]
Both globs mentioned in your original comment match symbols.

`filtered_re2.o` contains:

```
00001a50 T _ZNK3re211FilteredRE210AllMatchesERKNS_11StringPieceERKSt6vectorIiSaIiEEPS6_
00000b50 T _ZNK3re211FilteredRE210FirstMatchERKNS_11StringPieceERKSt6vectorIiSaIiEE
00000240 T _ZNK3re211FilteredRE213AllPotentialsERKSt6vectorIiSaIiEEPS3_
000001d0 T _ZNK3re211FilteredRE214SlowFirstMatchERKNS_11StringPieceE
```

`stringpiece.o` contains:

```
000000a0 T _ZNK3re211StringPiece12CopyToStringEPSs
000000c0 T _ZNK3re211StringPiece14AppendToStringEPSs
000000e0 T _ZNK3re211StringPiece4copyEPcjj
000006a0 T _ZNK3re211StringPiece4findEcj
000003c0 T _ZNK3re211StringPiece4findERKS0_j
000007d0 T _ZNK3re211StringPiece5rfindEcj
00000840 T _ZNK3re211StringPiece5rfindERKS0_j
00000810 T _ZNK3re211StringPiece6substrEjj
00000110 T _ZNK3re211StringPiece8containsES0_
```

Was every glob in `libre2.symbols` listed?

**Comment by junyer** [comment]
https://docs.oracle.com/cd/E23824_01/html/819-0690/gjpky.html#gdzmc notes: "To ensure interface definition stability, no wildcard expansion is provided for defining symbol names." A few paragraphs above, it describes `*` in terms of auto-reduction and auto-elimination only.

Could you please remove `,-M,libre2.symbols` from the `MAKE_SHARED_LIBRARY` command in `Makefile` and then try again? In particular, please verify that `make install` and `make testinstall` work as expected. If they do, then I will commit that change. Thanks.

**Comment by DrLou** [comment]
Removing use of the symbols map is ringing a bell for some reason... Hard to remember at the distance of about a year! My notes are pretty good, but apparently not complete. 

Will try. 

Lou 

----- Original Message -----

**Comment by junyer** [comment]
Great, thanks for confirming. We will just have to export all of the symbols by default, I suppose.
