### ISSUE TITLE
Compile error in re2.h under MSVC

### ISSUE THREAD

**Issue by DThiebaud** [google/re2#98]
Compiling the latest version gives the following error in re2.h in MSVC:

>E:\src\re2\re2/re2.h(345): error C2466: cannot allocate an array of constant size 0
>  E:\src\re2\re2/re2.h(363): note: see reference to function template instantiation 'bool re2::RE2::Apply<bool(__cdecl *)(const re2::StringPiece &,const re2::RE2 &,const re2::RE2::Arg *const [],int),re2::StringPiece,>(F,SP,const re2::RE2 &)' being compiled
>          with
>          [
>              F=bool (__cdecl *)(const re2::StringPiece &,const re2::RE2 &,const re2::RE2::Arg *const [],int),
>              SP=re2::StringPiece
>          ]
>  E:\src\re2\util\benchmark.cc(158): note: see reference to function template instantiation 'bool re2::RE2::PartialMatch<>(const re2::StringPiece &,const re2::RE2 &)' being compiled
2>

**Comment by zeux** [comment]
There are two ways to solve this:

```
diff --git a/re2/re2.h b/re2/re2.h
index 56fde7f..645ad5a 100644
--- a/re2/re2.h
+++ b/re2/re2.h
@@ -342,7 +342,7 @@ class RE2 {
  private:
   template <typename F, typename SP, typename... A>
   static inline bool Apply(F f, SP sp, const RE2& re, const A&... a) {
-    const Arg* const args[] = {&a...};
+    const Arg* const args[] = {&a..., NULL};
     const int argc = sizeof...(a);
     return f(sp, re, args, argc);
   }
```
or
```
diff --git a/re2/re2.h b/re2/re2.h
index 56fde7f..7087c40 100644
--- a/re2/re2.h
+++ b/re2/re2.h
@@ -346,6 +346,10 @@ class RE2 {
     const int argc = sizeof...(a);
     return f(sp, re, args, argc);
   }
+  template <typename F, typename SP>
+  static inline bool Apply(F f, SP sp, const RE2& re) {
+    return f(sp, re, NULL, 0);
+  }
 
  public:
   // In order to allow FullMatch() et al. to be called with a varying number
```

Both work in MSVC 2015 (update 2).

**Comment by junyer** [comment]
Thanks for the report and for the suggestions! I really should have kept the zero-argument overload even though GCC and Clang didn't complain without it.

**Comment by DThiebaud** [comment]
I can confirm that, with the last commit, RE2 compiles successfully with MSVC 2015 and all tests work correctly.

**Comment by junyer** [comment]
Great, thank you for confirming the fix!
